In [24]:
import pandas as pd
import  numpy as np
import random
from keras.models import Sequential
from keras.layers import Dense
from keras.initializers import HeNormal
from sklearn.model_selection import train_test_split
from keras import backend as K
from keras.layers import Layer
# from sklearn.preprocessing import TargetEncoder
import category_encoders as ce
import os
import glob
from sklearn.preprocessing import MinMaxScaler

# For all users

###  Preparing data of 7 users

In [2]:
# data0=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\AAE0190.csv',index_col=0)
# data0['user_name']='AAE0190.csv'
# # data0

# data1=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\JAV0361.csv',index_col=0)
# data1['user_name']='JAV0361.csv'
# data1

# data2=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\GJT0386.csv',index_col=0)
# data2['user_name']='GJT0386.csv'
# data2


# data4=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\CKB0427.csv',index_col=0)
# data4['user_name']='CKB0427.csv'
# data4

# data5=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\AQD0820.csv',index_col=0)
# data5['user_name']='AQD0820.csv'
# data5

# data6=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\ARD0509.csv',index_col=0)
# data6['user_name']='ARD0509.csv'
# data6

# data7=pd.read_csv(r'C:\Users\TLS\Desktop\r4.2\user_files\AAL0706.csv',index_col=0)
# data7['user_name']='AAL0706.csv'
# data7

# data=pd.concat([data0,data1,data2,data4,data5,data6,data7])

# data=data.sample(frac=1)

In [3]:
# data.to_csv('shuffled7users.csv')

### read merged data

In [4]:
# data=pd.read_csv('shuffled7users.csv')

# data.describe()

# data

In [5]:
# plt.figure(figsize=(16,10))
# sns.heatmap(data.corr(),  annot=True, annot_kws={"size": 14})
# sns.set_style('white')
# plt.xticks(fontsize=14)
# plt.yticks(fontsize=14)
# plt.show()

#### train test split

In [6]:
# Y=data['user_name']
# Y

#### Encoding y into ordinal

In [7]:
# y=Y.to_numpy().reshape(-1,1)

# oe=ce.OneHotEncoder()
# oe.fit(y)
# y_enc=oe.transform(y)
# y_enc

# y=pd. DataFrame(y_enc)

# type(y)
# # y.dtypes
# y
# x=oe.get_feature_names()

# # y.describe()
# y.columns=['AQD0820.csv' ,'ARD0509.csv', 'AAL0706.csv', 'AAE0190.csv', 'GJT0386.csv','CKB0427.csv' ,'JAV0361.csv']
# y

In [8]:
# data['target']=y
# data=data.drop(['Connect','Disconnect'],axis=1)
# data

In [9]:
# y

In [10]:
# X=data.iloc[:,1:4]
# y.dtypes

In [11]:
# X_train,X_test,Y_train,Y_test=train_test_split(X, y, test_size=0.3, random_state=1)

# X_train
# Y_train,Y_test

In [12]:
# X_train

## Model

In [13]:
# model=Sequential()
# model.add(Dense(6, kernel_initializer= 'uniform', activation = 'relu', input_dim = 3))

In [14]:
# model.add(Dense(6,kernel_initializer='uniform',activation='relu'))

In [15]:
# model.add(Dense(6,kernel_initializer='uniform',activation='relu'))
# model.add(Dense(5,kernel_initializer='uniform',activation='relu'))
# model.add(Dense(4,kernel_initializer='uniform',activation='relu'))

In [16]:
# model.add(Dense(7,kernel_initializer='uniform',activation='softmax'))

In [17]:
# model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [18]:
# model.fit(X_train, Y_train, epochs = 50)

In [19]:
# model.predict( [[4.0,0.0,5.0]])

# for all users

#### Merge Data of all users

In [20]:
# for i in all_users:
#     d=pd.read_csv(i)
#     for j in d.columns:
#         if j=='Logon_x':
#             print(i)
#             break
#     print(i)

In [5]:
# print(os.listdir(os.getcwd()))
# print(os.listdir())
path=r'C:\Users\TLS\Desktop\FYDP_updated\user_files'
all_users=glob.glob(os.path.join(path + "\*.csv"),recursive = True)
all_users.remove(r'C:\Users\TLS\Desktop\FYDP_updated\user_files\MOH0273.csv')
all_users.remove(r'C:\Users\TLS\Desktop\FYDP_updated\user_files\NWK0215.csv')

all_users
data=pd.DataFrame()
for user in all_users:
    name=os.path.basename(user).strip('.csv')
    aux=pd.read_csv(user)
    aux['user_name']=name
    data=pd.concat([aux,data],axis=0)
    print("aux",aux)
#     print(merge)
data=data.sample(frac=1)
data.to_csv('concatenated_users.csv')
data

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      2.0       3.0       1      1        0
1    01-04-2010       6.0      4.0       4.0       1      1        0
2    01-04-2011       1.0      8.0       5.0       1      1        0
3    01-05-2010       6.0      4.0       3.0       1      1        0
4    01-05-2011       6.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0      10.0       1      1        0
342  12-28-2010       5.0      1.0       8.0       1      1        0
343  12-29-2010       5.0      4.0       5.0       1      1        0
344  12-30-2010       2.0      1.0      11.0       1      1        0
345  03-22-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AAE0190
1             0   AAE0190
2             0   AAE0190
3             0   AAE0190
4             0   AAE0190
..          ...       ...
341           0   AAE0190
342           0   AAE0190
343           0   AAE0190
344           0   AAE0190
345           0   AAE0190

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      0.0       1.0       1      1      0.0
1    01-05-2010       2.0      0.0       1.0       1      1      2.0
2    01-06-2010       1.0      0.0       1.0       1      1      1.0
3    01-07-2010       0.0      0.0       3.0       1      1      2.0
4    01-08-2010       0.0      0.0       3.0       1      1      4.0
..          ...       ...      ...       ...     ...    ...      ...
159  08-20-2010       0.0      1.0       2.0       1      1      5.0
160  08-23-2010       1.0      1.0       1.0       1      1      1.0
161  08-24-2010       1.0      1.0       1.0       1      1      1.0
162  03-17-2010       0.0      0.0       0.0       1      1      2.0
163  08-05-2010       0.0      0.0       0.0       1      1      8.0

     Disconnect user_name
0           0.0   AAF0535
1           2.0   AAF0535
2           1.0   AAF0535
3           2.0   AAF0535
4           4.0   AAF0535
..          ...       ...
159         5.0   AAF0535
160         1.0   AAF0535
161         1.0   AAF0535
162         2.0   AAF0535
163         8.0   AAF0535

[164 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      1.0       2.0       1      1        0
3    01-05-2010       5.0      1.0       3.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      1        0
342  12-27-2010       6.0      0.0       3.0       1      1        0
343  12-28-2010       4.0      0.0       5.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       6.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   AAF0791
1             0   AAF0791
2             0   AAF0791
3             0   AAF0791
4             0   AAF0791
..          ...       ...
341           0   AAF0791
342           0   AAF0791
343           0   AAF0791
344           0   AAF0791
345           0   AAF0791

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-29-2010       0.0      0.0       0.0       1      1        0
342  06-29-2010       0.0      0.0       0.0       1      1        0
343  07-30-2010       0.0      0.0       0.0       1      1        0
344  10-04-2010       0.0      0.0       0.0       1      1        0
345  11-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AAL0706
1             0   AAL0706
2             0   AAL0706
3             0   AAL0706
4             0   AAL0706
..          ...       ...
341           0   AAL0706
342           0   AAL0706
343           0   AAL0706
344           0   AAL0706
345           0   AAL0706

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       3.0       1      1      0.0
1    01-05-2010       1.0      0.0       2.0       1      1      0.0
2    01-06-2010       1.0      0.0       2.0       1      1      0.0
3    01-07-2010       2.0      0.0       1.0       1      1      0.0
4    01-08-2010       0.0      0.0       3.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
220  11-12-2010       3.0      0.0       0.0       1      1      0.0
221  11-15-2010       0.0      0.0       3.0       1      1      0.0
222  11-16-2010       0.0      0.0       3.0       1      1      0.0
223  11-17-2010       1.0      1.0       1.0       1      1      0.0
224  10-23-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           0.0   AAM0658
1           0.0   AAM0658
2           0.0   AAM0658
3           0.0   AAM0658
4           0.0   AAM0658
..          ...       ...
220         0.0   AAM0658
221         0.0   AAM0658
222         0.0   AAM0658
223         0.0   AAM0658
224         1.0   AAM0658

[225 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-04-2011       0.0      0.0       0.0       1      1        0
342  05-11-2011       0.0      0.0       0.0       1      1        0
343  05-12-2011       0.0      0.0       0.0       1      1        0
344  06-18-2010       0.0      0.0       0.0       1      1        0
345  11-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AAN0823
1             0   AAN0823
2             0   AAN0823
3             0   AAN0823
4             0   AAN0823
..          ...       ...
341           0   AAN0823
342           0   AAN0823
343           0   AAN0823
344           0   AAN0823
345           0   AAN0823

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       2.0      1.0       0.0       1      2        0
1   01-05-2010       1.0      0.0       2.0       1      2        0
2   01-06-2010       0.0      0.0       3.0       1      2        0
3   01-07-2010       1.0      0.0       2.0       1      2        0
4   01-08-2010       1.0      0.0       2.0       1      2        0
5   01-11-2010       1.0      0.0       2.0       1      2        0
6   01-12-2010       0.0      0.0       2.0       1      2        0
7   01-13-2010       1.0      0.0       1.0       1      2        0
8   01-14-2010       1.0      0.0       2.0       1      1        0
9   01-15-2010       1.0      0.0       1.0       1      2        0
10  01-18-2010       0.0      0.0       3.0       1      2        0
11  01-19-2010       0.0      0.0       3.0       1      2        0
12  01-20-2010       0.0      0.0       3.0       1      2        0
13  01-21-2010       2.0      0.0       1.0       1      2        0
14  01-22-2010       0.0      0.0       3.0       1      2        0
15  01-25-2010       0.0      0.0       3.0       1      2        0
16  01-26-2010       1.0      0.0       2.0       1      2        0
17  01-27-2010       2.0      0.0       1.0       1      1        0
18  01-28-2010       0.0      0.0       3.0       1      1        0
19  01-29-2010       2.0      0.0       1.0       1      2        0
20  02-01-2010       0.0      0.0       2.0       1      1        0
21  02-02-2010       0.0      1.0       2.0       1      2        0
22  02-03-2010       2.0      0.0       1.0       1      2        0
23  02-04-2010       1.0      0.0       2.0       1      2        0
24  02-05-2010       0.0      0.0       3.0       1      2        0
25  02-08-2010       2.0      0.0       1.0       1      1        0
26  02-09-2010       2.0      0.0       1.0       1      2        0
27  02-10-2010       1.0      0.0       2.0       1      2        0
28  02-11-2010       1.0      0.0       2.0       1      1        0
29  02-12-2010       1.0      0.0       2.0       1      2        0
30  02-15-2010       3.0      0.0       0.0       1      1        0
31  02-16-2010       1.0      0.0       2.0       1      2        0
32  02-17-2010       2.0      0.0       1.0       1      2        0
33  02-18-2010       1.0      1.0       1.0       1      2        0
34  02-19-2010       0.0      0.0       2.0       1      2        0
35  02-22-2010       1.0      0.0       2.0       1      2        0
36  02-23-2010       1.0      0.0       2.0       1      1        0
37  02-24-2010       1.0      0.0       2.0       1      2        0
38  02-25-2010       1.0      0.0       2.0       1      2        0
39  02-26-2010       0.0      1.0       2.0       1      2        0
40  03-01-2010       2.0      0.0       1.0       1      1        0
41  03-02-2010       0.0      0.0       3.0       1      2        0
42  03-03-2010       1.0      1.0       1.0       1      2        0
43  03-04-2010       0.0      0.0       3.0       1      1        0
44  03-05-2010       2.0      0.0       1.0       1      2        0
45  03-08-2010       0.0      0.0       3.0       1      1        0
46  03-09-2010       0.0      0.0       3.0       1      1        0
47  03-10-2010       3.0      0.0       0.0       1      1        0
48  03-11-2010       2.0      0.0       1.0       1      2        0
49  03-12-2010       1.0      0.0       2.0       1      1        0

    Disconnect user_name
0            0   AAS0442
1            0   AAS0442
2            0   AAS0442
3            0   AAS0442
4            0   AAS0442
5            0   AAS0442
6            0   AAS0442
7            0   AAS0442
8            0   AAS0442
9            0   AAS0442
10           0   AAS0442
11           0   AAS0442
12           0   AAS0442
13           0   AAS0442
14           0   AAS0442
15           0   AAS0442
16           0   AAS0442
17           0   AAS0442
18           0   AAS0442
19           0   AAS0442
20           0   AAS0442
21           0   AAS0442
22           0   AAS0442
23           0   AAS0442
24           0   AAS0442
25           0   AAS0442
26           0   AAS0442
27           0   AAS0442
28           0   AAS0442
29           0   AAS0442
30           0   AAS0442
31           0   AAS0442
32           0   AAS0442
33           0   AAS0442
34           0   AAS0442
35           0   AAS0442
36           0   AAS0442
37           0   AAS0442
38           0   AAS0442
39           0   AAS0442
40           0   AAS0442
41           0   AAS0442
42           0   AAS0442
43           0   AAS0442
44           0   AAS0442
45           0   AAS0442
46           0   AAS0442
47           0   AAS0442
48           0   AAS0442
49           0   AAS0442

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-03-2011       0.0      0.0       0.0       1      1        0
342  06-22-2010       0.0      0.0       0.0       1      1        0
343  07-19-2010       0.0      0.0       0.0       1      1        0
344  08-02-2010       0.0      0.0       0.0       1      1        0
345  09-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AAV0450
1             0   AAV0450
2             0   AAV0450
3             0   AAV0450
4             0   AAV0450
..          ...       ...
341           0   AAV0450
342           0   AAV0450
343           0   AAV0450
344           0   AAV0450
345           0   AAV0450

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       3.0      0.0       0.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-08-2011       0.0      0.0       0.0       1      1        0
342  04-13-2010       0.0      0.0       0.0       1      1        0
343  08-26-2010       0.0      0.0       0.0       1      1        0
344  09-07-2010       0.0      0.0       0.0       1      1        0
345  11-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AAW0353
1             0   AAW0353
2             0   AAW0353
3             0   AAW0353
4             0   AAW0353
..          ...       ...
341           0   AAW0353
342           0   AAW0353
343           0   AAW0353
344           0   AAW0353
345           0   AAW0353

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      2.0      10.0       1      2      2.0
1    01-04-2010      10.0      0.0       4.0       1      2      2.0
2    01-05-2010       8.0      0.0       7.0       1      2      2.0
3    01-06-2010       8.0      1.0       6.0       1      2      1.0
4    01-07-2010       3.0      0.0      12.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
291  12-22-2010       2.0      0.0      13.0       1      2      3.0
292  12-23-2010       4.0      0.0      11.0       1      2      2.0
293  12-24-2010       8.0      2.0       5.0       1      2      5.0
294  06-17-2010       0.0      0.0       0.0       1      2      1.0
295  06-22-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           2.0   ABC0174
1           2.0   ABC0174
2           2.0   ABC0174
3           1.0   ABC0174
4           1.0   ABC0174
..          ...       ...
291         3.0   ABC0174
292         2.0   ABC0174
293         5.0   ABC0174
294         1.0   ABC0174
295         1.0   ABC0174

[296 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      2        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       5.0      0.0       3.0       1      2        0
4    01-05-2011       4.0      1.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      1.0       7.0       1      2        0
342  12-29-2010       3.0      0.0       6.0       1      2        0
343  12-30-2010       3.0      0.0       6.0       1      2        0
344  10-05-2010       0.0      0.0       0.0       1      2        0
345  12-13-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   ABC0253
1             0   ABC0253
2             0   ABC0253
3             0   ABC0253
4             0   ABC0253
..          ...       ...
341           0   ABC0253
342           0   ABC0253
343           0   ABC0253
344           0   ABC0253
345           0   ABC0253

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       3.0      0.0       0.0       1      1        0
4    01-05-2011       3.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  02-03-2010       0.0      0.0       0.0       1      1        0
343  02-25-2010       0.0      0.0       0.0       1      1        0
344  03-05-2010       0.0      0.0       0.0       1      1        0
345  07-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ABH0663
1             0   ABH0663
2             0   ABH0663
3             0   ABH0663
4             0   ABH0663
..          ...       ...
341           0   ABH0663
342           0   ABH0663
343           0   ABH0663
344           0   ABH0663
345           0   ABH0663

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      2        0
2    01-04-2011       0.0      1.0       0.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-17-2011       0.0      0.0       0.0       2      2        0
342  02-05-2010       0.0      0.0       0.0       2      3        0
343  04-20-2010       0.0      0.0       0.0       1      2        0
344  04-28-2011       0.0      0.0       0.0       1      2        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ABM0845
1             0   ABM0845
2             0   ABM0845
3             0   ABM0845
4             0   ABM0845
..          ...       ...
341           0   ABM0845
342           0   ABM0845
343           0   ABM0845
344           0   ABM0845
345           0   ABM0845

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      2        0
2    01-04-2011       7.0      1.0       1.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      2        0
342  12-27-2010       7.0      0.0       2.0       1      2        0
343  12-28-2010       2.0      1.0       6.0       1      2        0
344  12-29-2010       4.0      1.0       4.0       1      2        0
345  12-30-2010       1.0      0.0       8.0       1      2        0

     Disconnect user_name
0             0   ABN0239
1             0   ABN0239
2             0   ABN0239
3             0   ABN0239
4             0   ABN0239
..          ...       ...
341           0   ABN0239
342           0   ABN0239
343           0   ABN0239
344           0   ABN0239
345           0   ABN0239

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       3      3        0
1    01-04-2010       5.0      2.0       4.0       3      3        0
2    01-04-2011       2.0      1.0       5.0       3      3        0
3    01-05-2010       4.0      2.0       5.0       6      6        0
4    01-05-2011       3.0      0.0       7.0       5      5        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       7.0       2      2        0
342  12-28-2010       7.0      0.0       4.0       4      4        0
343  12-29-2010       2.0      0.0       9.0       4      4        0
344  12-30-2010       5.0      0.0       6.0       2      2        0
345  01-19-2010       0.0      0.0       0.0       2      2        0

     Disconnect user_name
0             0   ACC0042
1             0   ACC0042
2             0   ACC0042
3             0   ACC0042
4             0   ACC0042
..          ...       ...
341           0   ACC0042
342           0   ACC0042
343           0   ACC0042
344           0   ACC0042
345           0   ACC0042

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0     2.0    2.0        0
1    01-04-2010       2.0      0.0       7.0     2.0    2.0        0
2    01-04-2011       4.0      0.0       5.0     2.0    3.0        0
3    01-05-2010       3.0      0.0       6.0     1.0    2.0        0
4    01-05-2011       2.0      1.0       6.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
349  04-17-2010       0.0      0.0       0.0     1.0    0.0        0
350  04-26-2011       0.0      0.0       0.0     2.0    3.0        0
351  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
352  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
353  10-02-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   ACV0812
1             0   ACV0812
2             0   ACV0812
3             0   ACV0812
4             0   ACV0812
..          ...       ...
349           0   ACV0812
350           0   ACV0812
351           0   ACV0812
352           0   ACV0812
353           0   ACV0812

[354 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       4.0       1      2        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       4.0      0.0       5.0       1      2        0
3    01-05-2010       6.0      1.0       2.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      2        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       6.0      0.0       3.0       1      2        0
344  12-30-2010       3.0      0.0       6.0       1      2        0
345  08-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ADC0391
1             0   ADC0391
2             0   ADC0391
3             0   ADC0391
4             0   ADC0391
..          ...       ...
341           0   ADC0391
342           0   ADC0391
343           0   ADC0391
344           0   ADC0391
345           0   ADC0391

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-26-2010       0.0      0.0       0.0       1      1        0
342  08-31-2010       0.0      0.0       0.0       1      1        0
343  09-03-2010       0.0      0.0       0.0       1      1        0
344  10-05-2010       0.0      0.0       0.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ADD0846
1             0   ADD0846
2             0   ADD0846
3             0   ADD0846
4             0   ADD0846
..          ...       ...
341           0   ADD0846
342           0   ADD0846
343           0   ADD0846
344           0   ADD0846
345           0   ADD0846

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       7.0      0.0       2.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       5.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       6.0      0.0       3.0       1      1        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   ADF0397
1             0   ADF0397
2             0   ADF0397
3             0   ADF0397
4             0   ADF0397
..          ...       ...
341           0   ADF0397
342           0   ADF0397
343           0   ADF0397
344           0   ADF0397
345           0   ADF0397

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-25-2010       0.0      0.0       0.0       1      1        0
342  05-09-2011       0.0      0.0       0.0       1      1        0
343  06-21-2010       0.0      0.0       0.0       1      1        0
344  08-24-2010       0.0      0.0       0.0       1      1        0
345  09-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AES0827
1             0   AES0827
2             0   AES0827
3             0   AES0827
4             0   AES0827
..          ...       ...
341           0   AES0827
342           0   AES0827
343           0   AES0827
344           0   AES0827
345           0   AES0827

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       1.0       1      1        0
342  12-29-2010       0.0      1.0       2.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  03-29-2010       0.0      0.0       0.0       1      1        0
345  03-31-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AGB0186
1             0   AGB0186
2             0   AGB0186
3             0   AGB0186
4             0   AGB0186
..          ...       ...
341           0   AGB0186
342           0   AGB0186
343           0   AGB0186
344           0   AGB0186
345           0   AGB0186

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       0.0      1.0       0.0       1      1        0
344  03-11-2010       0.0      0.0       0.0       1      1        0
345  04-19-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AGB0643
1             0   AGB0643
2             0   AGB0643
3             0   AGB0643
4             0   AGB0643
..          ...       ...
341           0   AGB0643
342           0   AGB0643
343           0   AGB0643
344           0   AGB0643
345           0   AGB0643

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       3.0      0.0       6.0       1      2        0
1    01-02-2010       2.0      0.0       7.0       1      2        0
2    01-02-2011       5.0      1.0       3.0       1      2        0
3    01-03-2011       4.0      1.0       4.0       1      2        0
4    01-04-2010       7.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
381  12-29-2010       2.0      1.0       4.0       1      2        0
382  12-30-2010       2.0      0.0       6.0       1      2        0
383  03-09-2010       0.0      0.0       0.0       1      2        0
384  05-07-2011       0.0      0.0       0.0       1      2        0
385  11-22-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   AHC0142
1             0   AHC0142
2             0   AHC0142
3             0   AHC0142
4             0   AHC0142
..          ...       ...
381           0   AHC0142
382           0   AHC0142
383           0   AHC0142
384           0   AHC0142
385           0   AHC0142

[386 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       0.0      0.0       1.0       1      2      2.0
1    01-03-2011       0.0      0.0       1.0       1      2      0.0
2    01-04-2010       1.0      0.0       0.0       1      2      0.0
3    01-04-2011       0.0      0.0       1.0       1      2      1.0
4    01-05-2010       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
377  05-07-2010       0.0      0.0       0.0       1      2      0.0
378  05-13-2011       0.0      0.0       0.0       1      2      0.0
379  06-24-2010       0.0      0.0       0.0       2      2      0.0
380  10-05-2010       0.0      0.0       0.0       2      3      0.0
381  10-27-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           2.0   AHD0848
1           0.0   AHD0848
2           0.0   AHD0848
3           1.0   AHD0848
4           0.0   AHD0848
..          ...       ...
377         0.0   AHD0848
378         0.0   AHD0848
379         0.0   AHD0848
380         0.0   AHD0848
381         1.0   AHD0848

[382 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0       1      2        0
1    01-05-2010       0.0      1.0       2.0       1      2        0
2    01-06-2010       1.0      0.0       2.0       2      3        0
3    01-07-2010       0.0      0.0       3.0       1      2        0
4    01-08-2010       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
153  08-12-2010       1.0      0.0       2.0       2      2        0
154  08-13-2010       1.0      0.0       2.0       1      2        0
155  08-16-2010       0.0      0.0       3.0       1      1        0
156  02-26-2010       0.0      0.0       0.0       1      2        0
157  08-10-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   AHG0634
1             0   AHG0634
2             0   AHG0634
3             0   AHG0634
4             0   AHG0634
..          ...       ...
153           0   AHG0634
154           0   AHG0634
155           0   AHG0634
156           0   AHG0634
157           0   AHG0634

[158 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      2      1.0
1    01-04-2010       2.0      0.0       7.0       1      1      2.0
2    01-04-2011       5.0      0.0       4.0       1      2      0.0
3    01-05-2010       5.0      0.0       4.0       1      2      2.0
4    01-05-2011       5.0      0.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
348  12-29-2010       9.0      0.0       0.0       1      2      1.0
349  12-30-2010       4.0      1.0       4.0       2      3      0.0
350  12-31-2010       5.0      1.0       3.0       1      2      0.0
351  04-29-2011       0.0      0.0       0.0       2      3      2.0
352  10-11-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   AHM0410
1           2.0   AHM0410
2           0.0   AHM0410
3           2.0   AHM0410
4           0.0   AHM0410
..          ...       ...
348         1.0   AHM0410
349         0.0   AHM0410
350         0.0   AHM0410
351         2.0   AHM0410
352         0.0   AHM0410

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        9
1    01-04-2010       0.0      1.0       0.0       1      2        9
2    01-04-2011       0.0      0.0       1.0       1      2        8
3    01-05-2010       0.0      0.0       1.0       1      2        9
4    01-05-2011       1.0      0.0       0.0       1      2        9
..          ...       ...      ...       ...     ...    ...      ...
341  08-13-2010       0.0      0.0       0.0       1      2        9
342  08-16-2010       0.0      0.0       0.0       1      2        9
343  11-02-2010       0.0      0.0       0.0       1      2        8
344  12-13-2010       0.0      0.0       0.0       2      3        9
345  12-15-2010       0.0      0.0       0.0       1      2        9

     Disconnect user_name
0             9   AIB0948
1             9   AIB0948
2             8   AIB0948
3             9   AIB0948
4             9   AIB0948
..          ...       ...
341           9   AIB0948
342           9   AIB0948
343           8   AIB0948
344           9   AIB0948
345           9   AIB0948

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      2.0       3.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       8.0       1      1        0
342  12-30-2010       3.0      0.0       4.0       1      1        0
343  05-04-2011       0.0      0.0       0.0       1      1        0
344  07-21-2010       0.0      0.0       0.0       1      1        0
345  11-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AIH0675
1             0   AIH0675
2             0   AIH0675
3             0   AIH0675
4             0   AIH0675
..          ...       ...
341           0   AIH0675
342           0   AIH0675
343           0   AIH0675
344           0   AIH0675
345           0   AIH0675

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0      10.0       1      1        0
1    01-04-2010       8.0      1.0       4.0       1      1        0
2    01-04-2011       3.0      1.0      11.0       1      1        0
3    01-05-2010       8.0      1.0       6.0       1      1        0
4    01-05-2011      10.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010      13.0      0.0       2.0       1      1        0
342  12-29-2010       7.0      0.0       8.0       1      1        0
343  12-30-2010       7.0      0.0       8.0       1      1        0
344  02-08-2011       0.0      0.0       0.0       1      1        0
345  02-28-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AIM0627
1             0   AIM0627
2             0   AIM0627
3             0   AIM0627
4             0   AIM0627
..          ...       ...
341           0   AIM0627
342           0   AIM0627
343           0   AIM0627
344           0   AIM0627
345           0   AIM0627

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       2.0     1.0    2.0        0
1    01-04-2010       3.0      1.0       4.0     1.0    2.0        0
2    01-04-2011       5.0      0.0       4.0     2.0    3.0        0
3    01-05-2010       5.0      0.0       4.0     1.0    2.0        0
4    01-05-2011       7.0      0.0       2.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
346  03-07-2011       0.0      0.0       0.0     1.0    2.0        0
347  03-19-2011       0.0      0.0       0.0     1.0    1.0        0
348  05-01-2010       0.0      0.0       0.0     1.0    1.0        0
349  05-08-2010       0.0      0.0       0.0     1.0    1.0        0
350  07-17-2010       0.0      0.0       0.0     1.0    0.0        0

     Disconnect user_name
0             0   AIP0394
1             0   AIP0394
2             0   AIP0394
3             0   AIP0394
4             0   AIP0394
..          ...       ...
346           0   AIP0394
347           0   AIP0394
348           0   AIP0394
349           0   AIP0394
350           0   AIP0394

[351 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       5.0       1      2      1.0
1    01-04-2010       2.0      1.0       7.0       1      2      0.0
2    01-04-2011       7.0      0.0       3.0       1      2      1.0
3    01-05-2010       5.0      0.0       5.0       1      2      0.0
4    01-05-2011       1.0      0.0       9.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       6.0       1      1      1.0
342  12-29-2010       5.0      1.0       4.0       1      2      1.0
343  12-30-2010       4.0      1.0       5.0       1      2      3.0
344  04-30-2010       0.0      0.0       0.0       1      1      0.0
345  08-24-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   AIP0982
1           0.0   AIP0982
2           1.0   AIP0982
3           0.0   AIP0982
4           1.0   AIP0982
..          ...       ...
341         1.0   AIP0982
342         1.0   AIP0982
343         3.0   AIP0982
344         0.0   AIP0982
345         0.0   AIP0982

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       8.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       5.0      1.0       2.0       1      1        0
343  12-28-2010       4.0      0.0       4.0       1      1        0
344  12-29-2010       3.0      1.0       4.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   AIS0405
1             0   AIS0405
2             0   AIS0405
3             0   AIS0405
4             0   AIS0405
..          ...       ...
341           0   AIS0405
342           0   AIS0405
343           0   AIS0405
344           0   AIS0405
345           0   AIS0405

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-21-2011       0.0      0.0       0.0       1      1        0
342  04-26-2010       0.0      0.0       0.0       1      1        0
343  04-30-2010       0.0      0.0       0.0       1      1        0
344  09-22-2010       0.0      0.0       0.0       1      1        0
345  11-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AJC0840
1             0   AJC0840
2             0   AJC0840
3             0   AJC0840
4             0   AJC0840
..          ...       ...
341           0   AJC0840
342           0   AJC0840
343           0   AJC0840
344           0   AJC0840
345           0   AJC0840

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      1.0       4.0       1      2      0.0
1    01-02-2011       6.0      0.0       4.0       1      2      0.0
2    01-03-2011       6.0      0.0       4.0       2      2      0.0
3    01-04-2010       6.0      0.0       4.0       1      2      0.0
4    01-04-2011       4.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
382  12-28-2010       5.0      0.0       5.0       2      2      0.0
383  12-29-2010       8.0      0.0       2.0       1      2      0.0
384  12-30-2010       6.0      0.0       4.0       1      2      1.0
385  12-31-2010       7.0      0.0       3.0       1      2      1.0
386  03-16-2011       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   AJD0074
1           0.0   AJD0074
2           0.0   AJD0074
3           0.0   AJD0074
4           0.0   AJD0074
..          ...       ...
382         0.0   AJD0074
383         0.0   AJD0074
384         0.0   AJD0074
385         1.0   AJD0074
386         0.0   AJD0074

[387 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       2      2       10
1    01-04-2010       5.0      1.0       4.0       5      6       13
2    01-04-2011       3.0      0.0       8.0       5      6       13
3    01-05-2010       2.0      0.0       9.0       5      6       12
4    01-05-2011       3.0      0.0       6.0       6      6       14
..          ...       ...      ...       ...     ...    ...      ...
368  12-27-2010       1.0      1.0       9.0       5      6       13
369  12-28-2010       2.0      1.0       8.0       4      5       12
370  12-29-2010       5.0      0.0       6.0       3      4       11
371  12-30-2010       4.0      0.0       7.0       2      3        9
372  12-31-2010       2.0      0.0       9.0       3      3       11

     Disconnect user_name
0            10   AJF0370
1            13   AJF0370
2            13   AJF0370
3            12   AJF0370
4            14   AJF0370
..          ...       ...
368          13   AJF0370
369          12   AJF0370
370          11   AJF0370
371           9   AJF0370
372          11   AJF0370

[373 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      11.0     1.0    1.0      0.0
1    01-04-2010      10.0      0.0       5.0     1.0    1.0      0.0
2    01-04-2011       7.0      0.0       8.0     2.0    2.0      1.0
3    01-05-2010       4.0      0.0      10.0     1.0    1.0      0.0
4    01-05-2011       7.0      1.0       7.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
348  04-26-2011       0.0      0.0       0.0     1.0    1.0      0.0
349  05-08-2010       0.0      0.0       0.0     1.0    0.0      0.0
350  07-03-2010       0.0      0.0       0.0     1.0    0.0      0.0
351  10-02-2010       0.0      0.0       0.0     1.0    0.0      0.0
352  11-13-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   AJH0175
1           0.0   AJH0175
2           1.0   AJH0175
3           0.0   AJH0175
4           0.0   AJH0175
..          ...       ...
348         0.0   AJH0175
349         0.0   AJH0175
350         0.0   AJH0175
351         0.0   AJH0175
352         0.0   AJH0175

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0     1.0    1.0        0
1    01-04-2010       1.0      0.0       0.0     1.0    2.0        0
2    01-04-2011       0.0      0.0       1.0     2.0    3.0        0
3    01-05-2010       0.0      0.0       1.0     1.0    2.0        0
4    01-05-2011       0.0      0.0       1.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
345  05-25-2010       0.0      0.0       0.0     1.0    2.0        0
346  10-11-2010       0.0      0.0       0.0     1.0    2.0        0
347  11-06-2010       0.0      0.0       0.0     1.0    1.0        0
348  11-22-2010       0.0      0.0       0.0     2.0    3.0        0
349  12-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   AJL0462
1             0   AJL0462
2             0   AJL0462
3             0   AJL0462
4             0   AJL0462
..          ...       ...
345           0   AJL0462
346           0   AJL0462
347           0   AJL0462
348           0   AJL0462
349           0   AJL0462

[350 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       7.0       2      2      3.0
1    01-04-2010       7.0      2.0       6.0       2      3      4.0
2    01-04-2011       9.0      1.0       5.0       1      2      3.0
3    01-05-2010       9.0      0.0       6.0       1      2      1.0
4    01-05-2011       7.0      1.0       7.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0      11.0       1      2      5.0
342  12-28-2010      11.0      0.0       4.0       2      2      2.0
343  12-29-2010       5.0      1.0       8.0       1      2      2.0
344  12-30-2010       9.0      2.0       4.0       1      2      5.0
345  01-14-2011       0.0      0.0       0.0       1      2      3.0

     Disconnect user_name
0           3.0   AJN0607
1           4.0   AJN0607
2           3.0   AJN0607
3           1.0   AJN0607
4           2.0   AJN0607
..          ...       ...
341         5.0   AJN0607
342         2.0   AJN0607
343         2.0   AJN0607
344         5.0   AJN0607
345         3.0   AJN0607

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-28-2010       0.0      0.0       0.0       1      1        0
342  07-16-2010       0.0      0.0       0.0       1      1        0
343  08-23-2010       0.0      0.0       0.0       1      1        0
344  09-01-2010       0.0      0.0       0.0       1      1        0
345  12-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AJP0723
1             0   AJP0723
2             0   AJP0723
3             0   AJP0723
4             0   AJP0723
..          ...       ...
341           0   AJP0723
342           0   AJP0723
343           0   AJP0723
344           0   AJP0723
345           0   AJP0723

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       7.0      2.0       6.0       1      1        0
1    01-02-2011       8.0      2.0       5.0       1      2        0
2    01-03-2010       4.0      1.0      10.0       1      2        0
3    01-03-2011      10.0      1.0       4.0       1      2        0
4    01-04-2010       6.0      0.0       9.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
441  12-27-2010       8.0      1.0       6.0       1      2        0
442  12-28-2010       7.0      1.0       7.0       1      2        0
443  12-29-2010       7.0      1.0       6.0       1      2        0
444  12-30-2010       7.0      1.0       7.0       1      2        0
445  12-31-2010       5.0      0.0      10.0       1      2        0

     Disconnect user_name
0             0   AJR0319
1             0   AJR0319
2             0   AJR0319
3             0   AJR0319
4             0   AJR0319
..          ...       ...
441           0   AJR0319
442           0   AJR0319
443           0   AJR0319
444           0   AJR0319
445           0   AJR0319

[446 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      0.0       7.0     1.0    1.0      0.0
1    01-05-2010       3.0      0.0       6.0     1.0    1.0      0.0
2    01-06-2010       6.0      0.0       3.0     1.0    1.0      0.0
3    01-07-2010       4.0      0.0       5.0     1.0    1.0      0.0
4    01-08-2010       7.0      0.0       2.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
191  10-05-2010       6.0      0.0       3.0     1.0    1.0      0.0
192  10-06-2010       6.0      0.0       2.0     1.0    1.0      0.0
193  10-07-2010       4.0      0.0       5.0     1.0    1.0      0.0
194  09-17-2010       0.0      0.0       0.0     1.0    2.0      0.0
195  09-18-2010       0.0      0.0       0.0     1.0    0.0      1.0

     Disconnect user_name
0           0.0   AJR0932
1           0.0   AJR0932
2           0.0   AJR0932
3           0.0   AJR0932
4           0.0   AJR0932
..          ...       ...
191         0.0   AJR0932
192         0.0   AJR0932
193         0.0   AJR0932
194         0.0   AJR0932
195         1.0   AJR0932

[196 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      1.0       6.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       1.0      0.0       8.0       1      1        0
344  12-29-2010       5.0      0.0       4.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   AKC0924
1             0   AKC0924
2             0   AKC0924
3             0   AKC0924
4             0   AKC0924
..          ...       ...
341           0   AKC0924
342           0   AKC0924
343           0   AKC0924
344           0   AKC0924
345           0   AKC0924

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-07-2010       0.0      0.0       0.0       1      1        0
342  10-06-2010       0.0      0.0       0.0       1      1        0
343  10-14-2010       0.0      0.0       0.0       1      1        0
344  12-20-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AKF0709
1             0   AKF0709
2             0   AKF0709
3             0   AKF0709
4             0   AKF0709
..          ...       ...
341           0   AKF0709
342           0   AKF0709
343           0   AKF0709
344           0   AKF0709
345           0   AKF0709

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-06-2010       3.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      1.0       0.0       1      1        0
342  12-30-2010       3.0      0.0       0.0       1      1        0
343  01-05-2011       0.0      0.0       0.0       1      1        0
344  01-28-2011       0.0      0.0       0.0       1      1        0
345  05-13-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AKH0758
1             0   AKH0758
2             0   AKH0758
3             0   AKH0758
4             0   AKH0758
..          ...       ...
341           0   AKH0758
342           0   AKH0758
343           0   AKH0758
344           0   AKH0758
345           0   AKH0758

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       1.0       1      1        0
342  04-29-2010       0.0      0.0       0.0       1      1        0
343  05-17-2010       0.0      0.0       0.0       1      1        0
344  06-14-2010       0.0      0.0       0.0       1      1        0
345  09-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AKK0329
1             0   AKK0329
2             0   AKK0329
3             0   AKK0329
4             0   AKK0329
..          ...       ...
341           0   AKK0329
342           0   AKK0329
343           0   AKK0329
344           0   AKK0329
345           0   AKK0329

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      0.0       6.0       1      2      3.0
1    01-05-2010       6.0      0.0       5.0       1      2      0.0
2    01-06-2010       3.0      0.0       7.0       1      1      1.0
3    01-07-2010       5.0      1.0       5.0       1      2      4.0
4    01-08-2010       1.0      2.0       8.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
226  11-23-2010       5.0      1.0       5.0       1      1      1.0
227  11-24-2010       6.0      0.0       5.0       1      2      3.0
228  11-29-2010       3.0      0.0       8.0       1      2      7.0
229  11-30-2010       4.0      0.0       7.0       1      2      2.0
230  03-04-2010       0.0      0.0       0.0       2      2      2.0

     Disconnect user_name
0           3.0   AKR0057
1           0.0   AKR0057
2           1.0   AKR0057
3           3.0   AKR0057
4           2.0   AKR0057
..          ...       ...
226         1.0   AKR0057
227         3.0   AKR0057
228         7.0   AKR0057
229         2.0   AKR0057
230         2.0   AKR0057

[231 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       8.0       1      1        0
1    01-04-2010       3.0      0.0       8.0       1      1        0
2    01-04-2011       4.0      0.0       7.0       1      1        0
3    01-05-2010       5.0      1.0       5.0       1      1        0
4    01-05-2011       2.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       7.0       1      1        0
342  12-29-2010       7.0      0.0       4.0       1      1        0
343  12-30-2010       5.0      0.0       4.0       1      1        0
344  01-18-2010       0.0      0.0       0.0       1      1        0
345  01-24-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AKW0167
1             0   AKW0167
2             0   AKW0167
3             0   AKW0167
4             0   AKW0167
..          ...       ...
341           0   AKW0167
342           0   AKW0167
343           0   AKW0167
344           0   AKW0167
345           0   AKW0167

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       0.0      0.0       3.0       1      1        0
1    01-03-2010       0.0      0.0       3.0       1      1        0
2    01-04-2010       1.0      0.0       2.0       1      1        0
3    01-05-2010       3.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
230  09-10-2010       1.0      0.0       2.0       1      1        0
231  02-25-2010       0.0      0.0       0.0       1      1        0
232  07-25-2010       0.0      0.0       0.0       1      1        0
233  08-03-2010       0.0      0.0       0.0       1      1        0
234  08-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ALB0892
1             0   ALB0892
2             0   ALB0892
3             0   ALB0892
4             0   ALB0892
..          ...       ...
230           0   ALB0892
231           0   ALB0892
232           0   ALB0892
233           0   ALB0892
234           0   ALB0892

[235 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       3.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       0.0       1      1        0
342  12-29-2010       1.0      0.0       1.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  09-14-2010       0.0      0.0       0.0       1      1        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ALC0788
1             0   ALC0788
2             0   ALC0788
3             0   ALC0788
4             0   ALC0788
..          ...       ...
341           0   ALC0788
342           0   ALC0788
343           0   ALC0788
344           0   ALC0788
345           0   ALC0788

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        0
1    01-04-2010       1.0      1.0       1.0       1      2        0
2    01-04-2011       0.0      1.0       2.0       1      2        0
3    01-05-2010       3.0      0.0       0.0       1      2        0
4    01-05-2011       3.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-18-2011       0.0      0.0       0.0       1      2        0
342  01-28-2011       0.0      0.0       0.0       1      2        0
343  06-07-2010       0.0      0.0       0.0       1      2        0
344  07-20-2010       0.0      0.0       0.0       1      1        0
345  08-25-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   ALD0529
1             0   ALD0529
2             0   ALD0529
3             0   ALD0529
4             0   ALD0529
..          ...       ...
341           0   ALD0529
342           0   ALD0529
343           0   ALD0529
344           0   ALD0529
345           0   ALD0529

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      3.0       3.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       3.0      0.0       1.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       7.0       1      1        0
342  01-25-2010       0.0      0.0       0.0       1      1        0
343  02-11-2010       0.0      0.0       0.0       1      1        0
344  03-10-2010       0.0      0.0       0.0       1      1        0
345  07-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ALD0544
1             0   ALD0544
2             0   ALD0544
3             0   ALD0544
4             0   ALD0544
..          ...       ...
341           0   ALD0544
342           0   ALD0544
343           0   ALD0544
344           0   ALD0544
345           0   ALD0544

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       2.0       1      1        0
342  12-28-2010       6.0      1.0       2.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       2.0      0.0       7.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ALH0402
1             0   ALH0402
2             0   ALH0402
3             0   ALH0402
4             0   ALH0402
..          ...       ...
341           0   ALH0402
342           0   ALH0402
343           0   ALH0402
344           0   ALH0402
345           0   ALH0402

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      1.0       8.0       1      1        0
1    01-04-2010       9.0      0.0       9.0       1      1        0
2    01-04-2011       8.0      2.0       7.0       1      1        0
3    01-05-2010       8.0      2.0       8.0       1      1        0
4    01-05-2011       9.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      1.0       7.0       1      1        0
342  12-27-2010      10.0      2.0       6.0       1      1        0
343  12-28-2010       9.0      1.0       8.0       1      1        0
344  12-29-2010      10.0      1.0       7.0       1      1        0
345  12-30-2010       4.0      1.0      13.0       1      1        0

     Disconnect user_name
0             0   AMD0077
1             0   AMD0077
2             0   AMD0077
3             0   AMD0077
4             0   AMD0077
..          ...       ...
341           0   AMD0077
342           0   AMD0077
343           0   AMD0077
344           0   AMD0077
345           0   AMD0077

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-25-2010       0.0      0.0       0.0       1      1        0
342  06-18-2010       0.0      0.0       0.0       1      1        0
343  07-13-2010       0.0      0.0       0.0       1      1        0
344  08-23-2010       0.0      0.0       0.0       1      1        0
345  12-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AMH0464
1             0   AMH0464
2             0   AMH0464
3             0   AMH0464
4             0   AMH0464
..          ...       ...
341           0   AMH0464
342           0   AMH0464
343           0   AMH0464
344           0   AMH0464
345           0   AMH0464

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       6.0      1.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       5.0      2.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       1.0       1      1        0
342  12-29-2010       7.0      0.0       2.0       1      1        0
343  12-30-2010       3.0      2.0       4.0       1      1        0
344  02-16-2011       0.0      0.0       0.0       1      1        0
345  09-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AMH0794
1             0   AMH0794
2             0   AMH0794
3             0   AMH0794
4             0   AMH0794
..          ...       ...
341           0   AMH0794
342           0   AMH0794
343           0   AMH0794
344           0   AMH0794
345           0   AMH0794

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-30-2010       0.0      0.0       0.0       1      1        0
342  09-13-2010       0.0      0.0       0.0       1      1        0
343  09-14-2010       0.0      0.0       0.0       1      1        0
344  10-13-2010       0.0      0.0       0.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AMJ0297
1             0   AMJ0297
2             0   AMJ0297
3             0   AMJ0297
4             0   AMJ0297
..          ...       ...
341           0   AMJ0297
342           0   AMJ0297
343           0   AMJ0297
344           0   AMJ0297
345           0   AMJ0297

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0      13.0       1      1        0
1    01-04-2010       5.0      0.0      13.0       1      1        0
2    01-04-2011       3.0      0.0      15.0       1      1        0
3    01-05-2010       4.0      1.0      13.0       1      1        0
4    01-05-2011       9.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      2.0      14.0       1      1        0
342  12-27-2010       4.0      1.0       4.0       1      1        0
343  12-28-2010       3.0      0.0      15.0       1      1        0
344  12-29-2010       3.0      0.0      15.0       1      1        0
345  12-30-2010       2.0      0.0      16.0       1      1        0

     Disconnect user_name
0             0   AMM0014
1             0   AMM0014
2             0   AMM0014
3             0   AMM0014
4             0   AMM0014
..          ...       ...
341           0   AMM0014
342           0   AMM0014
343           0   AMM0014
344           0   AMM0014
345           0   AMM0014

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      1.0       4.0     1.0    1.0      0.0
1    01-04-2010       4.0      1.0      10.0     1.0    2.0      0.0
2    01-04-2011       9.0      0.0       6.0     1.0    2.0      1.0
3    01-05-2010      11.0      0.0       4.0     1.0    2.0      0.0
4    01-05-2011      10.0      1.0       4.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
344  12-29-2010      10.0      0.0       5.0     1.0    2.0      0.0
345  12-30-2010       8.0      0.0       7.0     1.0    2.0      1.0
346  03-20-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  05-14-2011       0.0      0.0       0.0     1.0    1.0      0.0
348  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   AMR0318
1           0.0   AMR0318
2           1.0   AMR0318
3           0.0   AMR0318
4           0.0   AMR0318
..          ...       ...
344         0.0   AMR0318
345         1.0   AMR0318
346         0.0   AMR0318
347         0.0   AMR0318
348         0.0   AMR0318

[349 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       6.0      2.0       1.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       3.0       1      1        0
342  12-28-2010       2.0      1.0       6.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       2.0      0.0       7.0       1      1        0
345  03-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AMR0400
1             0   AMR0400
2             0   AMR0400
3             0   AMR0400
4             0   AMR0400
..          ...       ...
341           0   AMR0400
342           0   AMR0400
343           0   AMR0400
344           0   AMR0400
345           0   AMR0400

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       3.0       1      1        0
1    01-04-2010       5.0      1.0       8.0       1      1        0
2    01-04-2011       5.0      0.0       9.0       1      1        0
3    01-05-2010       7.0      0.0       7.0       1      1        0
4    01-05-2011       6.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0      10.0       1      1        0
342  12-27-2010       3.0      0.0      11.0       1      1        0
343  12-28-2010       2.0      1.0      10.0       1      1        0
344  12-29-2010       3.0      0.0       8.0       1      1        0
345  12-30-2010       4.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   AMV0036
1             0   AMV0036
2             0   AMV0036
3             0   AMV0036
4             0   AMV0036
..          ...       ...
341           0   AMV0036
342           0   AMV0036
343           0   AMV0036
344           0   AMV0036
345           0   AMV0036

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       1.0      0.0       8.0       1      2        0
1    01-02-2010       3.0      0.0       5.0       1      2        0
2    01-03-2010       3.0      0.0       5.0       1      2        0
3    01-03-2011       3.0      0.0       6.0       1      2        0
4    01-04-2010       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
445  12-27-2010       3.0      0.0       6.0       1      2        0
446  12-28-2010       3.0      1.0       5.0       1      2        0
447  12-29-2010       1.0      0.0       8.0       1      2        0
448  12-30-2010       5.0      1.0       3.0       1      2        0
449  12-31-2010       7.0      0.0       2.0       1      2        0

     Disconnect user_name
0             0   AMW0392
1             0   AMW0392
2             0   AMW0392
3             0   AMW0392
4             0   AMW0392
..          ...       ...
445           0   AMW0392
446           0   AMW0392
447           0   AMW0392
448           0   AMW0392
449           0   AMW0392

[450 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       1.0      7.0       3.0       1      1      1.0
1   01-05-2010       5.0      1.0       5.0       1      2      1.0
2   01-06-2010       5.0      0.0       6.0       1      1      2.0
3   01-07-2010       0.0      7.0       1.0       1      2      2.0
4   01-08-2010       7.0      1.0       3.0       1      2      2.0
5   01-11-2010       5.0      2.0       2.0       2      2      1.0
6   01-12-2010       5.0      2.0       4.0       1      2      1.0
7   01-13-2010       1.0      7.0       3.0       1      2      3.0
8   01-14-2010       4.0      1.0       6.0       2      3      2.0
9   01-15-2010       2.0      2.0       7.0       1      2      1.0
10  01-18-2010       5.0      2.0       4.0       2      3      2.0
11  01-19-2010       5.0      3.0       3.0       1      2      1.0
12  01-20-2010       4.0      2.0       5.0       1      2      1.0
13  01-21-2010       3.0      0.0       8.0       1      2      0.0
14  01-22-2010       4.0      0.0       7.0       1      1      1.0
15  01-25-2010       6.0      2.0       3.0       2      2      0.0
16  01-26-2010       3.0      2.0       6.0       1      2      0.0
17  01-27-2010       3.0      3.0       5.0       2      3      0.0
18  01-28-2010       3.0      5.0       3.0       2      2      3.0
19  01-29-2010       1.0      2.0       8.0       1      2      1.0
20  02-01-2010       1.0      1.0       9.0       1      1      1.0
21  02-02-2010       3.0      0.0       8.0       1      2      1.0
22  02-03-2010       2.0      7.0       2.0       1      2      0.0
23  02-04-2010       3.0      1.0       7.0       1      2      0.0
24  02-05-2010       3.0      3.0       5.0       2      3      2.0

    Disconnect user_name
0          1.0   ANM0123
1          1.0   ANM0123
2          2.0   ANM0123
3          2.0   ANM0123
4          2.0   ANM0123
5          1.0   ANM0123
6          1.0   ANM0123
7          3.0   ANM0123
8          2.0   ANM0123
9          1.0   ANM0123
10         2.0   ANM0123
11         1.0   ANM0123
12         1.0   ANM0123
13         0.0   ANM0123
14         1.0   ANM0123
15         0.0   ANM0123
16         0.0   ANM0123
17         0.0   ANM0123
18         2.0   ANM0123
19         1.0   ANM0123
20         1.0   ANM0123
21         1.0   ANM0123
22         0.0   ANM0123
23         0.0   ANM0123
24         2.0   ANM0123
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       7.0      1.0       1.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       3.0      1.0       5.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      3.0       3.0       1      1        0
345  02-08-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ANP0555
1             0   ANP0555
2             0   ANP0555
3             0   ANP0555
4             0   ANP0555
..          ...       ...
341           0   ANP0555
342           0   ANP0555
343           0   ANP0555
344           0   ANP0555
345           0   ANP0555

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      2        0
1    01-04-2010       3.0      1.0       5.0       1      2        0
2    01-04-2011       5.0      0.0       2.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       5.0       1      1        0
342  12-29-2010       3.0      1.0       5.0       1      2        0
343  12-30-2010       2.0      1.0       5.0       1      2        0
344  06-21-2010       0.0      0.0       0.0       1      2        0
345  10-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ANT0430
1             0   ANT0430
2             0   ANT0430
3             0   ANT0430
4             0   ANT0430
..          ...       ...
341           0   ANT0430
342           0   ANT0430
343           0   ANT0430
344           0   ANT0430
345           0   ANT0430

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       2.0      0.0       9.0       1      1        0
2    01-04-2011       6.0      1.0       3.0       1      1        0
3    01-05-2010       6.0      0.0       4.0       1      1        0
4    01-05-2011       7.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       2.0       1      1        0
342  12-29-2010       7.0      0.0       4.0       1      1        0
343  12-30-2010       2.0      0.0       9.0       1      1        0
344  03-03-2011       0.0      0.0       0.0       1      1        0
345  10-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AOB0019
1             0   AOB0019
2             0   AOB0019
3             0   AOB0019
4             0   AOB0019
..          ...       ...
341           0   AOB0019
342           0   AOB0019
343           0   AOB0019
344           0   AOB0019
345           0   AOB0019

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       1      2      1.0
1    01-02-2010       1.0      0.0       0.0       1      1      1.0
2    01-02-2011       0.0      0.0       1.0       1      2      2.0
3    01-03-2010       0.0      0.0       1.0       1      2      0.0
4    01-03-2011       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
378  09-27-2010       0.0      0.0       0.0       1      2      1.0
379  10-07-2010       0.0      0.0       0.0       1      1      1.0
380  10-26-2010       0.0      0.0       0.0       1      2      1.0
381  12-06-2010       0.0      0.0       0.0       1      2      0.0
382  12-14-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           1.0   AOK0844
1           1.0   AOK0844
2           2.0   AOK0844
3           0.0   AOK0844
4           0.0   AOK0844
..          ...       ...
378         1.0   AOK0844
379         1.0   AOK0844
380         1.0   AOK0844
381         0.0   AOK0844
382         1.0   AOK0844

[383 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       2      2        0
1    01-04-2010       4.0      0.0       5.0       2      3        0
2    01-04-2011       5.0      0.0       4.0       1      2        0
3    01-05-2010       3.0      1.0       5.0       1      2        0
4    01-05-2011       3.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       4.0       2      2        0
342  12-29-2010       4.0      1.0       4.0       1      2        0
343  12-30-2010       5.0      1.0       2.0       1      2        0
344  03-30-2011       0.0      0.0       0.0       1      1        0
345  03-31-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   AOS0987
1             0   AOS0987
2             0   AOS0987
3             0   AOS0987
4             0   AOS0987
..          ...       ...
341           0   AOS0987
342           0   AOS0987
343           0   AOS0987
344           0   AOS0987
345           0   AOS0987

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-15-2010       0.0      0.0       0.0       1      1        0
342  09-07-2010       0.0      0.0       0.0       1      1        0
343  10-20-2010       0.0      0.0       0.0       1      1        0
344  10-26-2010       0.0      0.0       0.0       1      1        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   APG0307
1             0   APG0307
2             0   APG0307
3             0   APG0307
4             0   APG0307
..          ...       ...
341           0   APG0307
342           0   APG0307
343           0   APG0307
344           0   APG0307
345           0   APG0307

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       3.0      0.0       5.0       1      1        0
343  12-29-2010       2.0      0.0       7.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  10-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AQD0820
1             0   AQD0820
2             0   AQD0820
3             0   AQD0820
4             0   AQD0820
..          ...       ...
341           0   AQD0820
342           0   AQD0820
343           0   AQD0820
344           0   AQD0820
345           0   AQD0820

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      2        0
2    01-04-2011       2.0      0.0       7.0       1      2        0
3    01-05-2010       3.0      1.0       5.0       1      2        0
4    01-05-2011       5.0      0.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        0
342  12-28-2010       4.0      0.0       4.0       1      1        0
343  12-29-2010       7.0      0.0       2.0       1      2        0
344  12-30-2010       1.0      0.0       8.0       1      2        0
345  05-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ARA0252
1             0   ARA0252
2             0   ARA0252
3             0   ARA0252
4             0   ARA0252
..          ...       ...
341           0   ARA0252
342           0   ARA0252
343           0   ARA0252
344           0   ARA0252
345           0   ARA0252

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-05-2010       1.0      0.0       0.0       1      1        0
2    01-06-2010       1.0      0.0       0.0       1      1        0
3    01-07-2010       0.0      0.0       1.0       1      1        0
4    01-08-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
206  10-29-2010       0.0      0.0       1.0       1      1        0
207  01-13-2010       0.0      0.0       0.0       1      1        0
208  02-03-2010       0.0      0.0       0.0       1      1        0
209  02-10-2010       0.0      0.0       0.0       1      1        0
210  10-25-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ARB0834
1             0   ARB0834
2             0   ARB0834
3             0   ARB0834
4             0   ARB0834
..          ...       ...
206           0   ARB0834
207           0   ARB0834
208           0   ARB0834
209           0   ARB0834
210           0   ARB0834

[211 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  01-07-2011       0.0      0.0       0.0       1      1        0
345  07-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ARB0881
1             0   ARB0881
2             0   ARB0881
3             0   ARB0881
4             0   ARB0881
..          ...       ...
341           0   ARB0881
342           0   ARB0881
343           0   ARB0881
344           0   ARB0881
345           0   ARB0881

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2011       1.0      0.0       2.0       1      1        0
2    01-05-2010       0.0      0.0       3.0       1      1        0
3    01-05-2011       1.0      0.0       2.0       1      1        0
4    01-06-2010       1.0      1.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-14-2011       0.0      0.0       0.0       1      1        0
342  04-27-2010       0.0      0.0       0.0       1      1        0
343  06-11-2010       0.0      0.0       0.0       1      1        0
344  06-15-2010       0.0      0.0       0.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ARD0509
1             0   ARD0509
2             0   ARD0509
3             0   ARD0509
4             0   ARD0509
..          ...       ...
341           0   ARD0509
342           0   ARD0509
343           0   ARD0509
344           0   ARD0509
345           0   ARD0509

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0      10.0       1      1        0
1    01-04-2010       7.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       9.0       1      1        0
3    01-05-2010       6.0      0.0       7.0       1      1        0
4    01-05-2011       8.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       9.0       1      1        0
342  12-28-2010       7.0      0.0       7.0       1      1        0
343  12-29-2010       8.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      0.0      11.0       1      1        0
345  02-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ARL0034
1             0   ARL0034
2             0   ARL0034
3             0   ARL0034
4             0   ARL0034
..          ...       ...
341           0   ARL0034
342           0   ARL0034
343           0   ARL0034
344           0   ARL0034
345           0   ARL0034

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      0.0       4.0       1      1        0
3    01-05-2010       1.0      1.0       7.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
260  12-22-2010       6.0      0.0       2.0       1      1        0
261  12-27-2010       6.0      0.0       3.0       1      1        0
262  12-28-2010       4.0      0.0       5.0       1      1        0
263  12-29-2010       4.0      1.0       4.0       1      1        0
264  12-30-2010       0.0      0.0       9.0       1      1        0

     Disconnect user_name
0             0   ASB0796
1             0   ASB0796
2             0   ASB0796
3             0   ASB0796
4             0   ASB0796
..          ...       ...
260           0   ASB0796
261           0   ASB0796
262           0   ASB0796
263           0   ASB0796
264           0   ASB0796

[265 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-28-2010       0.0      0.0       0.0       1      1        0
342  07-08-2010       0.0      0.0       0.0       1      1        0
343  07-09-2010       0.0      0.0       0.0       1      1        0
344  09-14-2010       0.0      0.0       0.0       1      1        0
345  09-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ASD0577
1             0   ASD0577
2             0   ASD0577
3             0   ASD0577
4             0   ASD0577
..          ...       ...
341           0   ASD0577
342           0   ASD0577
343           0   ASD0577
344           0   ASD0577
345           0   ASD0577

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       7.0       1      1        0
3    01-05-2010       9.0      0.0       2.0       1      1        0
4    01-05-2011       5.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       7.0       1      1        0
342  12-29-2010       2.0      0.0       9.0       1      1        0
343  12-30-2010       4.0      1.0       6.0       1      1        0
344  01-25-2011       0.0      0.0       0.0       1      1        0
345  02-18-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ASG0048
1             0   ASG0048
2             0   ASG0048
3             0   ASG0048
4             0   ASG0048
..          ...       ...
341           0   ASG0048
342           0   ASG0048
343           0   ASG0048
344           0   ASG0048
345           0   ASG0048

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2011       4.0      0.0       5.0       1      1        0
4    01-06-2010       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       6.0      0.0       3.0       1      1        0
343  12-29-2010       3.0      3.0       3.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  01-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ASG0692
1             0   ASG0692
2             0   ASG0692
3             0   ASG0692
4             0   ASG0692
..          ...       ...
341           0   ASG0692
342           0   ASG0692
343           0   ASG0692
344           0   ASG0692
345           0   ASG0692

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      2        0
2    01-04-2011       5.0      0.0       4.0       1      2        0
3    01-05-2010       2.0      2.0       5.0       1      2        0
4    01-05-2011       4.0      1.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       3.0       1      2        0
342  12-29-2010       1.0      1.0       7.0       1      2        0
343  12-30-2010       2.0      1.0       6.0       1      2        0
344  03-31-2010       0.0      0.0       0.0       1      2        0
345  05-11-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   ASL0378
1             0   ASL0378
2             0   ASL0378
3             0   ASL0378
4             0   ASL0378
..          ...       ...
341           0   ASL0378
342           0   ASL0378
343           0   ASL0378
344           0   ASL0378
345           0   ASL0378

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       1.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  10-22-2010       0.0      0.0       0.0       1      2        0
342  11-19-2010       0.0      0.0       0.0       1      2        0
343  12-14-2010       0.0      0.0       0.0       1      2        0
344  12-16-2010       0.0      0.0       0.0       1      2        0
345  12-28-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   ASM0575
1             0   ASM0575
2             0   ASM0575
3             0   ASM0575
4             0   ASM0575
..          ...       ...
341           0   ASM0575
342           0   ASM0575
343           0   ASM0575
344           0   ASM0575
345           0   ASM0575

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       4.0      1.0       9.0       1      1        0
2    01-04-2011       6.0      0.0       7.0       1      1        0
3    01-05-2010       6.0      1.0       6.0       1      1        0
4    01-05-2011       4.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      3.0       4.0       1      1        0
342  12-28-2010       9.0      1.0       4.0       1      1        0
343  12-29-2010       8.0      2.0       4.0       1      1        0
344  12-30-2010       8.0      0.0       6.0       1      1        0
345  11-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ASS0206
1             0   ASS0206
2             0   ASS0206
3             0   ASS0206
4             0   ASS0206
..          ...       ...
341           0   ASS0206
342           0   ASS0206
343           0   ASS0206
344           0   ASS0206
345           0   ASS0206

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       0.0      0.0       3.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      2        0
342  12-30-2010       1.0      0.0       1.0       1      2        0
343  02-01-2010       0.0      0.0       0.0       1      2        0
344  02-25-2010       0.0      0.0       0.0       1      2        0
345  04-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ASS0517
1             0   ASS0517
2             0   ASS0517
3             0   ASS0517
4             0   ASS0517
..          ...       ...
341           0   ASS0517
342           0   ASS0517
343           0   ASS0517
344           0   ASS0517
345           0   ASS0517

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-23-2010       0.0      0.0       0.0       1      2        0
342  09-02-2010       0.0      0.0       0.0       1      2        0
343  10-01-2010       0.0      0.0       0.0       1      1        0
344  10-22-2010       0.0      0.0       0.0       1      2        0
345  11-04-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   ASV0946
1             0   ASV0946
2             0   ASV0946
3             0   ASV0946
4             0   ASV0946
..          ...       ...
341           0   ASV0946
342           0   ASV0946
343           0   ASV0946
344           0   ASV0946
345           0   ASV0946

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       8.0      1.0       7.0       1      1      0.0
1    01-02-2010       8.0      1.0       7.0       1      2      0.0
2    01-02-2011       7.0      1.0       8.0       1      2      0.0
3    01-03-2010      13.0      0.0       3.0       1      2      2.0
4    01-03-2011       7.0      0.0       9.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
481  12-29-2010      10.0      0.0       6.0       1      2      2.0
482  12-30-2010       7.0      0.0       9.0       1      1      0.0
483  12-31-2010       9.0      0.0       7.0       1      2      1.0
484  05-04-2010       0.0      0.0       0.0       1      1      0.0
485  08-15-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   ATE0869
1           0.0   ATE0869
2           0.0   ATE0869
3           2.0   ATE0869
4           0.0   ATE0869
..          ...       ...
481         2.0   ATE0869
482         0.0   ATE0869
483         1.0   ATE0869
484         0.0   ATE0869
485         0.0   ATE0869

[486 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       5.0      1.0       2.0       1      1        0
2    01-04-2011       7.0      0.0       2.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       5.0      0.0       4.0       1      1        0
344  12-30-2010       7.0      0.0       2.0       1      1        0
345  06-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ATF0274
1             0   ATF0274
2             0   ATF0274
3             0   ATF0274
4             0   ATF0274
..          ...       ...
341           0   ATF0274
342           0   ATF0274
343           0   ATF0274
344           0   ATF0274
345           0   ATF0274

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      10.0     1.0    2.0      1.0
1    01-04-2010       7.0      1.0       6.0     1.0    1.0      1.0
2    01-04-2011       2.0      0.0      13.0     2.0    3.0      2.0
3    01-05-2010       8.0      1.0       5.0     1.0    2.0      2.0
4    01-05-2011       3.0      0.0      10.0     1.0    2.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
381  10-02-2010       0.0      0.0       0.0     1.0    1.0      0.0
382  10-16-2010       0.0      0.0       0.0     1.0    0.0      0.0
383  10-23-2010       0.0      0.0       0.0     1.0    1.0      0.0
384  12-18-2010       0.0      0.0       0.0     1.0    0.0      0.0
385  12-31-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           1.0   ATP0662
1           1.0   ATP0662
2           2.0   ATP0662
3           2.0   ATP0662
4           1.0   ATP0662
..          ...       ...
381         0.0   ATP0662
382         0.0   ATP0662
383         0.0   ATP0662
384         0.0   ATP0662
385         0.0   ATP0662

[386 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        9
1    01-04-2011       1.0      0.0       0.0       1      1        8
2    01-05-2010       1.0      0.0       0.0       1      1        7
3    01-05-2011       0.0      0.0       1.0       1      1        9
4    01-06-2010       0.0      0.0       1.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
341  03-30-2010       0.0      0.0       0.0       1      1        9
342  04-15-2010       0.0      0.0       0.0       1      1        7
343  04-21-2011       0.0      0.0       0.0       1      1        8
344  09-07-2010       0.0      0.0       0.0       1      1        9
345  09-15-2010       0.0      0.0       0.0       1      1        9

     Disconnect user_name
0             9   AVM0947
1             8   AVM0947
2             7   AVM0947
3             9   AVM0947
4             9   AVM0947
..          ...       ...
341           9   AVM0947
342           7   AVM0947
343           8   AVM0947
344           9   AVM0947
345           9   AVM0947

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      1.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1        0
342  12-30-2010       1.0      0.0       2.0       1      1        0
343  03-21-2011       0.0      0.0       0.0       1      1        0
344  03-31-2010       0.0      0.0       0.0       1      1        0
345  04-14-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   AWM0764
1             0   AWM0764
2             0   AWM0764
3             0   AWM0764
4             0   AWM0764
..          ...       ...
341           0   AWM0764
342           0   AWM0764
343           0   AWM0764
344           0   AWM0764
345           0   AWM0764

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       9.0     1.0    1.0        0
1    01-04-2010       8.0      0.0       8.0     1.0    1.0        0
2    01-04-2011       6.0      2.0       8.0     1.0    1.0        0
3    01-05-2010       5.0      0.0      10.0     2.0    2.0        0
4    01-05-2011       6.0      0.0      10.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
351  07-03-2010       0.0      0.0       0.0     1.0    0.0        0
352  10-02-2010       0.0      0.0       0.0     1.0    0.0        0
353  11-06-2010       0.0      0.0       0.0     1.0    0.0        0
354  11-13-2010       0.0      0.0       0.0     1.0    1.0        0
355  11-25-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   BAH0875
1             0   BAH0875
2             0   BAH0875
3             0   BAH0875
4             0   BAH0875
..          ...       ...
351           0   BAH0875
352           0   BAH0875
353           0   BAH0875
354           0   BAH0875
355           0   BAH0875

[356 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       2      2      1.0
1    01-04-2010       0.0      0.0       3.0       1      1      1.0
2    01-04-2011       0.0      0.0       2.0       1      1      1.0
3    01-05-2010       1.0      0.0       2.0       1      1      2.0
4    01-05-2011       0.0      0.0       3.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  02-15-2010       0.0      0.0       0.0       1      1      0.0
342  05-19-2010       0.0      0.0       0.0       1      1      0.0
343  08-05-2010       0.0      0.0       0.0       1      1      1.0
344  08-19-2010       0.0      0.0       0.0       1      1      0.0
345  12-15-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   BAJ0654
1           1.0   BAJ0654
2           1.0   BAJ0654
3           2.0   BAJ0654
4           0.0   BAJ0654
..          ...       ...
341         0.0   BAJ0654
342         0.0   BAJ0654
343         1.0   BAJ0654
344         0.0   BAJ0654
345         0.0   BAJ0654

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-14-2011       0.0      0.0       0.0       1      1        0
342  10-18-2010       0.0      0.0       0.0       1      1        0
343  10-26-2010       0.0      0.0       0.0       1      1        0
344  12-07-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BAK0964
1             0   BAK0964
2             0   BAK0964
3             0   BAK0964
4             0   BAK0964
..          ...       ...
341           0   BAK0964
342           0   BAK0964
343           0   BAK0964
344           0   BAK0964
345           0   BAK0964

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       8.0       2      2      1.0
1    01-04-2010       6.0      1.0       4.0       2      3      1.0
2    01-04-2011       5.0      1.0       5.0       4      5      5.0
3    01-05-2010       5.0      1.0       5.0       2      3      3.0
4    01-05-2011       3.0      1.0       7.0       4      5      4.0
..          ...       ...      ...       ...     ...    ...      ...
343  12-30-2010       7.0      1.0       3.0       2      3      3.0
344  02-06-2010       0.0      0.0       0.0       1      1      0.0
345  03-06-2010       0.0      0.0       0.0       1      1      0.0
346  03-31-2010       0.0      0.0       0.0       3      4      2.0
347  04-08-2011       0.0      0.0       0.0       3      4      2.0

     Disconnect user_name
0           1.0   BAL0044
1           1.0   BAL0044
2           5.0   BAL0044
3           3.0   BAL0044
4           4.0   BAL0044
..          ...       ...
343         3.0   BAL0044
344         0.0   BAL0044
345         0.0   BAL0044
346         2.0   BAL0044
347         2.0   BAL0044

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       9.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011      13.0      0.0       2.0       1      2        0
3    01-05-2010       7.0      2.0       4.0       1      2        0
4    01-05-2011      10.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      0.0       7.0       1      2        0
342  12-28-2010       8.0      1.0       6.0       1      1        0
343  12-29-2010       3.0      0.0      12.0       1      2        0
344  12-30-2010      10.0      1.0       4.0       1      2        0
345  02-25-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   BAM0611
1             0   BAM0611
2             0   BAM0611
3             0   BAM0611
4             0   BAM0611
..          ...       ...
341           0   BAM0611
342           0   BAM0611
343           0   BAM0611
344           0   BAM0611
345           0   BAM0611

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      1.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-11-2011       0.0      0.0       0.0       1      1        0
342  03-23-2010       0.0      0.0       0.0       1      1        0
343  04-25-2011       0.0      0.0       0.0       1      1        0
344  05-12-2011       0.0      0.0       0.0       1      1        0
345  11-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BAM0636
1             0   BAM0636
2             0   BAM0636
3             0   BAM0636
4             0   BAM0636
..          ...       ...
341           0   BAM0636
342           0   BAM0636
343           0   BAM0636
344           0   BAM0636
345           0   BAM0636

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       7.0       1      1      0.0
1    01-04-2010       7.0      1.0       7.0       1      1      1.0
2    01-04-2011       8.0      0.0       6.0       1      2      1.0
3    01-05-2010       7.0      1.0       6.0       1      2      1.0
4    01-05-2011      10.0      1.0       4.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       9.0       1      2      1.0
342  12-27-2010       5.0      0.0       6.0       1      2      1.0
343  12-28-2010       6.0      0.0       9.0       1      1      1.0
344  12-29-2010       6.0      0.0       9.0       1      2      0.0
345  12-30-2010      10.0      1.0       4.0       1      2      2.0

     Disconnect user_name
0           0.0   BBG0325
1           1.0   BBG0325
2           1.0   BBG0325
3           1.0   BBG0325
4           1.0   BBG0325
..          ...       ...
341         1.0   BBG0325
342         1.0   BBG0325
343         1.0   BBG0325
344         0.0   BBG0325
345         2.0   BBG0325

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      2.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       5.0      0.0       4.0       1      1        0
343  12-29-2010       6.0      0.0       3.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  08-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BBH0810
1             0   BBH0810
2             0   BBH0810
3             0   BBH0810
4             0   BBH0810
..          ...       ...
341           0   BBH0810
342           0   BBH0810
343           0   BBH0810
344           0   BBH0810
345           0   BBH0810

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0       6.0       3      3      0.0
1    01-05-2010       6.0      1.0       4.0       3      3      0.0
2    01-06-2010       4.0      1.0       5.0       3      3      0.0
3    01-07-2010       5.0      1.0       5.0       3      3      0.0
4    01-08-2010       6.0      0.0       4.0       4      4      0.0
..          ...       ...      ...       ...     ...    ...      ...
152  08-09-2010       4.0      1.0       5.0       2      2      0.0
153  08-10-2010       4.0      0.0       6.0       4      4      0.0
154  08-11-2010       2.0      0.0       6.0       3      3      0.0
155  08-12-2010       4.0      1.0       8.0       4      4      2.0
156  08-13-2010       2.0      0.0       6.0       4      4      0.0

     Disconnect user_name
0           0.0   BBS0039
1           0.0   BBS0039
2           0.0   BBS0039
3           0.0   BBS0039
4           0.0   BBS0039
..          ...       ...
152         0.0   BBS0039
153         0.0   BBS0039
154         0.0   BBS0039
155         2.0   BBS0039
156         0.0   BBS0039

[157 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      0.0       4.0     1.0    1.0      0.0
1    01-03-2011       5.0      1.0       3.0     1.0    1.0      0.0
2    01-04-2010       5.0      0.0       4.0     1.0    1.0      0.0
3    01-04-2011       5.0      1.0       3.0     1.0    1.0      0.0
4    01-05-2010       4.0      0.0       5.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
407  09-11-2010       0.0      0.0       0.0     1.0    1.0      0.0
408  09-18-2010       0.0      0.0       0.0     1.0    1.0      0.0
409  11-25-2010       0.0      0.0       0.0     1.0    1.0      0.0
410  12-11-2010       0.0      0.0       0.0     1.0    1.0      0.0
411  12-26-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   BBS0422
1           0.0   BBS0422
2           0.0   BBS0422
3           0.0   BBS0422
4           0.0   BBS0422
..          ...       ...
407         0.0   BBS0422
408         0.0   BBS0422
409         0.0   BBS0422
410         0.0   BBS0422
411         0.0   BBS0422

[412 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       4.0       2      3        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       3.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
276  12-27-2010       1.0      1.0       7.0       1      2        0
277  12-28-2010       3.0      0.0       6.0       1      2        0
278  12-29-2010       1.0      0.0       8.0       1      2        0
279  12-30-2010       5.0      0.0       4.0       1      2        0
280  06-29-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   BCB0679
1             0   BCB0679
2             0   BCB0679
3             0   BCB0679
4             0   BCB0679
..          ...       ...
276           0   BCB0679
277           0   BCB0679
278           0   BCB0679
279           0   BCB0679
280           0   BCB0679

[281 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      1.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      1.0       1.0       1      1        0
342  12-28-2010       1.0      0.0       2.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      1        0
344  12-30-2010       1.0      0.0       2.0       1      1        0
345  11-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BCM0653
1             0   BCM0653
2             0   BCM0653
3             0   BCM0653
4             0   BCM0653
..          ...       ...
341           0   BCM0653
342           0   BCM0653
343           0   BCM0653
344           0   BCM0653
345           0   BCM0653

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      3        0
1    01-04-2010       1.0      0.0       0.0       1      2        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-28-2010       0.0      0.0       0.0       1      2        0
342  10-12-2010       0.0      0.0       0.0       1      2        0
343  10-29-2010       0.0      0.0       0.0       1      2        0
344  11-29-2010       0.0      0.0       0.0       1      2        0
345  12-15-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   BCR0581
1             0   BCR0581
2             0   BCR0581
3             0   BCR0581
4             0   BCR0581
..          ...       ...
341           0   BCR0581
342           0   BCR0581
343           0   BCR0581
344           0   BCR0581
345           0   BCR0581

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0     1.0    1.0        0
1    01-04-2010       0.0      1.0       0.0     1.0    1.0        0
2    01-04-2011       1.0      0.0       0.0     2.0    2.0        0
3    01-05-2010       0.0      0.0       1.0     1.0    1.0        0
4    01-05-2011       0.0      0.0       1.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
344  04-08-2011       0.0      0.0       0.0     1.0    1.0        0
345  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
346  10-06-2010       0.0      0.0       0.0     1.0    1.0        0
347  11-24-2010       0.0      0.0       0.0     1.0    1.0        0
348  12-29-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   BDB0453
1             0   BDB0453
2             0   BDB0453
3             0   BDB0453
4             0   BDB0453
..          ...       ...
344           0   BDB0453
345           0   BDB0453
346           0   BDB0453
347           0   BDB0453
348           0   BDB0453

[349 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       1.0      0.0       2.0       1      2      0.0
1    01-02-2011       0.0      0.0       3.0       1      2      2.0
2    01-03-2010       3.0      0.0       0.0       1      2      1.0
3    01-03-2011       1.0      0.0       2.0       1      2      3.0
4    01-04-2010       1.0      0.0       2.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
446  12-30-2010       0.0      0.0       3.0       1      2      2.0
447  02-27-2011       0.0      0.0       0.0       1      2      3.0
448  03-07-2011       0.0      0.0       0.0       1      2      2.0
449  05-14-2011       0.0      0.0       0.0       1      2      5.0
450  11-03-2010       0.0      0.0       0.0       1      2      3.0

     Disconnect user_name
0           0.0   BDI0533
1           2.0   BDI0533
2           1.0   BDI0533
3           3.0   BDI0533
4           2.0   BDI0533
..          ...       ...
446         2.0   BDI0533
447         3.0   BDI0533
448         2.0   BDI0533
449         5.0   BDI0533
450         3.0   BDI0533

[451 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      0.0       8.0       1      1      0.0
1    01-05-2010      10.0      0.0       3.0       1      1      0.0
2    01-06-2010       7.0      0.0       8.0       1      1      0.0
3    01-07-2010      10.0      0.0       5.0       1      1      0.0
4    01-08-2010       5.0      1.0       8.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
160  08-19-2010      10.0      1.0       4.0       1      1      0.0
161  08-20-2010       7.0      0.0       8.0       1      1      0.0
162  08-23-2010       5.0      2.0       8.0       1      1      0.0
163  08-24-2010       7.0      2.0       6.0       1      1      0.0
164  08-25-2010       7.0      1.0       7.0       1      1      0.0

     Disconnect user_name
0           0.0   BDV0168
1           0.0   BDV0168
2           0.0   BDV0168
3           0.0   BDV0168
4           0.0   BDV0168
..          ...       ...
160         0.0   BDV0168
161         0.0   BDV0168
162         0.0   BDV0168
163         0.0   BDV0168
164         0.0   BDV0168

[165 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010      11.0      0.0       4.0       1      1        0
2    01-04-2011       6.0      0.0       9.0       1      1        0
3    01-05-2010       8.0      2.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010      11.0      0.0       4.0       1      1        0
342  12-28-2010       9.0      2.0       4.0       1      1        0
343  12-29-2010       3.0      1.0      11.0       1      1        0
344  12-30-2010       8.0      2.0       5.0       1      1        0
345  07-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BEC0505
1             0   BEC0505
2             0   BEC0505
3             0   BEC0505
4             0   BEC0505
..          ...       ...
341           0   BEC0505
342           0   BEC0505
343           0   BEC0505
344           0   BEC0505
345           0   BEC0505

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0       1      2      1.0
1    01-04-2010       8.0      1.0       6.0       1      1      0.0
2    01-04-2011       6.0      0.0       9.0       1      2      1.0
3    01-05-2010      10.0      0.0       5.0       1      2      1.0
4    01-05-2011      10.0      1.0       3.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
348  12-27-2010       7.0      0.0       7.0       1      2      2.0
349  12-28-2010      10.0      1.0       4.0       1      2      2.0
350  12-29-2010       2.0      1.0       6.0       1      1      0.0
351  12-30-2010       6.0      1.0       8.0       1      2      2.0
352  06-25-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   BEH0615
1           0.0   BEH0615
2           1.0   BEH0615
3           1.0   BEH0615
4           2.0   BEH0615
..          ...       ...
348         2.0   BEH0615
349         2.0   BEH0615
350         0.0   BEH0615
351         2.0   BEH0615
352         0.0   BEH0615

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       7.0       1      1        0
1    01-04-2010       4.0      1.0       0.0       1      1        0
2    01-04-2011       8.0      2.0       5.0       1      1        0
3    01-05-2010       5.0      0.0       9.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      0.0       6.0       1      1        0
342  12-28-2010      11.0      0.0       4.0       1      1        0
343  12-29-2010       3.0      1.0      11.0       1      1        0
344  12-30-2010       8.0      0.0       7.0       1      1        0
345  05-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BER0314
1             0   BER0314
2             0   BER0314
3             0   BER0314
4             0   BER0314
..          ...       ...
341           0   BER0314
342           0   BER0314
343           0   BER0314
344           0   BER0314
345           0   BER0314

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       4.0      1.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       8.0       2      2        0
342  12-29-2010       4.0      1.0       4.0       1      1        0
343  12-30-2010       2.0      0.0       7.0       1      1        0
344  02-07-2011       0.0      0.0       0.0       2      2        0
345  02-09-2011       0.0      0.0       0.0       2      2        0

     Disconnect user_name
0             0   BHC0665
1             0   BHC0665
2             0   BHC0665
3             0   BHC0665
4             0   BHC0665
..          ...       ...
341           0   BHC0665
342           0   BHC0665
343           0   BHC0665
344           0   BHC0665
345           0   BHC0665

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-07-2010       0.0      0.0       0.0       1      1        0
342  07-20-2010       0.0      0.0       0.0       1      1        0
343  07-30-2010       0.0      0.0       0.0       1      1        0
344  09-07-2010       0.0      0.0       0.0       1      1        0
345  12-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BHW0458
1             0   BHW0458
2             0   BHW0458
3             0   BHW0458
4             0   BHW0458
..          ...       ...
341           0   BHW0458
342           0   BHW0458
343           0   BHW0458
344           0   BHW0458
345           0   BHW0458

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      8.0       3.0       1      1      0.0
1    01-05-2010       6.0      0.0       9.0       1      1      0.0
2    01-06-2010       9.0      0.0       6.0       1      1      0.0
3    01-07-2010       6.0      4.0       5.0       1      1      0.0
4    01-08-2010       5.0      2.0       5.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
139  07-21-2010       5.0      2.0       8.0       1      1      0.0
140  07-22-2010       5.0      5.0       5.0       1      1      0.0
141  07-23-2010       5.0      0.0      10.0       1      1      0.0
142  07-26-2010       5.0      3.0       5.0       1      1      0.0
143  07-27-2010      10.0      1.0       4.0       1      1      0.0

     Disconnect user_name
0           0.0   BIH0745
1           0.0   BIH0745
2           0.0   BIH0745
3           0.0   BIH0745
4           0.0   BIH0745
..          ...       ...
139         0.0   BIH0745
140         0.0   BIH0745
141         0.0   BIH0745
142         0.0   BIH0745
143         0.0   BIH0745

[144 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0     1.0    1.0      0.0
1    01-04-2010       3.0      1.0       5.0     1.0    2.0      0.0
2    01-04-2011       3.0      0.0       4.0     1.0    2.0      0.0
3    01-05-2010       2.0      2.0       5.0     1.0    2.0      0.0
4    01-05-2011       2.0      0.0       5.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
349  03-20-2010       0.0      0.0       0.0     1.0    1.0      0.0
350  05-01-2010       0.0      0.0       0.0     1.0    1.0      0.0
351  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
352  07-03-2010       0.0      0.0       0.0     1.0    1.0      0.0
353  10-13-2010       0.0      0.0       0.0     1.0    1.0      1.0

     Disconnect user_name
0           0.0   BIS0247
1           0.0   BIS0247
2           0.0   BIS0247
3           0.0   BIS0247
4           0.0   BIS0247
..          ...       ...
349         0.0   BIS0247
350         0.0   BIS0247
351         0.0   BIS0247
352         0.0   BIS0247
353         1.0   BIS0247

[354 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       7.0      0.0       7.0       1      1        0
2    01-04-2011       5.0      1.0       8.0       1      1        0
3    01-05-2010       4.0      1.0       9.0       1      1        0
4    01-05-2011       4.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       7.0       1      1        0
342  12-27-2010       7.0      0.0       7.0       1      1        0
343  12-28-2010       7.0      0.0       7.0       1      1        0
344  12-29-2010       3.0      1.0      10.0       1      1        0
345  12-30-2010       5.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   BJH0354
1             0   BJH0354
2             0   BJH0354
3             0   BJH0354
4             0   BJH0354
..          ...       ...
341           0   BJH0354
342           0   BJH0354
343           0   BJH0354
344           0   BJH0354
345           0   BJH0354

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       2.0      1.0       6.0       1      1        0
344  12-30-2010       4.0      1.0       4.0       1      1        0
345  09-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BJH0811
1             0   BJH0811
2             0   BJH0811
3             0   BJH0811
4             0   BJH0811
..          ...       ...
341           0   BJH0811
342           0   BJH0811
343           0   BJH0811
344           0   BJH0811
345           0   BJH0811

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      2.0       1.0     1.0    1.0      7.0
1    01-04-2010       0.0      0.0       3.0     1.0    1.0      9.0
2    01-04-2011       1.0      1.0       1.0     2.0    2.0      8.0
3    01-05-2010       0.0      0.0       3.0     1.0    1.0      8.0
4    01-05-2011       1.0      0.0       2.0     1.0    1.0      8.0
..          ...       ...      ...       ...     ...    ...      ...
380  07-24-2010       0.0      0.0       0.0     1.0    1.0      0.0
381  08-07-2010       0.0      0.0       0.0     1.0    0.0      0.0
382  09-18-2010       0.0      0.0       0.0     1.0    1.0      0.0
383  11-07-2010       0.0      0.0       0.0     1.0    1.0      0.0
384  12-31-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           7.0   BJM0111
1           9.0   BJM0111
2           8.0   BJM0111
3           8.0   BJM0111
4           8.0   BJM0111
..          ...       ...
380         0.0   BJM0111
381         0.0   BJM0111
382         0.0   BJM0111
383         0.0   BJM0111
384         0.0   BJM0111

[385 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        9
1    01-04-2010       0.0      0.0       1.0       1      2        9
2    01-04-2011       1.0      0.0       0.0       1      2        8
3    01-05-2010       0.0      0.0       1.0       1      2        9
4    01-05-2011       0.0      0.0       1.0       1      2        9
..          ...       ...      ...       ...     ...    ...      ...
341  04-08-2010       0.0      0.0       0.0       1      2        9
342  07-09-2010       0.0      0.0       0.0       1      2        9
343  08-23-2010       0.0      0.0       0.0       1      1        9
344  10-25-2010       0.0      0.0       0.0       1      2        9
345  12-21-2010       0.0      0.0       0.0       1      1        9

     Disconnect user_name
0             9   BJP0134
1             9   BJP0134
2             8   BJP0134
3             9   BJP0134
4             9   BJP0134
..          ...       ...
341           9   BJP0134
342           9   BJP0134
343           9   BJP0134
344           9   BJP0134
345           9   BJP0134

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010       8.0      2.0       5.0       1      1        0
2    01-04-2011       4.0      0.0      11.0       1      1        0
3    01-05-2010       3.0      1.0      10.0       1      1        0
4    01-05-2011       5.0      2.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       9.0       1      1        0
342  12-28-2010       7.0      0.0       8.0       1      1        0
343  12-29-2010      11.0      0.0       4.0       1      1        0
344  12-30-2010       8.0      0.0       7.0       1      1        0
345  09-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BJW0619
1             0   BJW0619
2             0   BJW0619
3             0   BJW0619
4             0   BJW0619
..          ...       ...
341           0   BJW0619
342           0   BJW0619
343           0   BJW0619
344           0   BJW0619
345           0   BJW0619

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       2      2        0
1    01-04-2010       4.0      0.0       6.0       3      3        0
2    01-04-2011       5.0      0.0       6.0       5      5        0
3    01-05-2010       5.0      0.0       6.0       5      5        0
4    01-05-2011       5.0      0.0       6.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       8.0      0.0       3.0       4      4        0
342  12-29-2010       6.0      1.0       4.0       5      5        0
343  12-30-2010       4.0      1.0       5.0       4      4        0
344  01-07-2011       0.0      0.0       0.0       3      3        0
345  05-12-2010       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   BKW0374
1             0   BKW0374
2             0   BKW0374
3             0   BKW0374
4             0   BKW0374
..          ...       ...
341           0   BKW0374
342           0   BKW0374
343           0   BKW0374
344           0   BKW0374
345           0   BKW0374

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       2      2        0
1    01-04-2010       1.0      1.0       7.0       1      2        0
2    01-04-2011       2.0      1.0       6.0       1      2        0
3    01-05-2010       2.0      2.0       5.0       1      2        0
4    01-05-2011       3.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       3.0       1      2        0
342  12-28-2010       3.0      1.0       4.0       2      2        0
343  12-29-2010       3.0      0.0       6.0       1      2        0
344  12-30-2010       2.0      0.0       7.0       1      2        0
345  01-28-2010       0.0      0.0       0.0       2      3        0

     Disconnect user_name
0             0   BLB0114
1             0   BLB0114
2             0   BLB0114
3             0   BLB0114
4             0   BLB0114
..          ...       ...
341           0   BLB0114
342           0   BLB0114
343           0   BLB0114
344           0   BLB0114
345           0   BLB0114

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       2.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2011       3.0      1.0       5.0       1      1        0
4    01-06-2010       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       4.0      0.0       5.0       1      1        0
342  01-05-2010       0.0      0.0       0.0       1      1        0
343  04-19-2011       0.0      0.0       0.0       1      1        0
344  06-28-2010       0.0      0.0       0.0       1      1        0
345  09-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BLL0929
1             0   BLL0929
2             0   BLL0929
3             0   BLL0929
4             0   BLL0929
..          ...       ...
341           0   BLL0929
342           0   BLL0929
343           0   BLL0929
344           0   BLL0929
345           0   BLL0929

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      1.0       3.0       1      2      0.0
1    01-05-2010       2.0      1.0       6.0       1      2      0.0
2    01-06-2010       2.0      0.0       4.0       1      1      0.0
3    01-07-2010       4.0      1.0       4.0       1      2      0.0
4    01-08-2010       5.0      0.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
196  10-12-2010       4.0      1.0       4.0       1      2      0.0
197  10-13-2010       2.0      0.0       7.0       1      1      0.0
198  10-14-2010       2.0      0.0       6.0       1      2      0.0
199  10-15-2010       4.0      0.0       5.0       1      2      0.0
200  07-26-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   BLS0678
1           0.0   BLS0678
2           0.0   BLS0678
3           0.0   BLS0678
4           0.0   BLS0678
..          ...       ...
196         0.0   BLS0678
197         0.0   BLS0678
198         0.0   BLS0678
199         0.0   BLS0678
200         0.0   BLS0678

[201 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       2.0      3.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-28-2010       6.0      0.0       2.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  06-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BMC0547
1             0   BMC0547
2             0   BMC0547
3             0   BMC0547
4             0   BMC0547
..          ...       ...
341           0   BMC0547
342           0   BMC0547
343           0   BMC0547
344           0   BMC0547
345           0   BMC0547

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1      9.0
1    01-04-2010       2.0      1.0       6.0       1      1      9.0
2    01-04-2011       2.0      1.0       6.0       1      2      9.0
3    01-05-2010       3.0      0.0       6.0       1      2      9.0
4    01-05-2011       3.0      1.0       5.0       1      2      9.0
..          ...       ...      ...       ...     ...    ...      ...
344  12-30-2010       5.0      0.0       4.0       1      2      9.0
345  01-08-2011       0.0      0.0       0.0       1      1      0.0
346  01-15-2011       0.0      0.0       0.0       1      1      0.0
347  02-14-2011       0.0      0.0       0.0       1      2      8.0
348  03-19-2011       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           9.0   BMG0917
1           9.0   BMG0917
2           9.0   BMG0917
3           9.0   BMG0917
4           9.0   BMG0917
..          ...       ...
344         9.0   BMG0917
345         0.0   BMG0917
346         0.0   BMG0917
347         8.0   BMG0917
348         0.0   BMG0917

[349 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       1.0       1      1        0
342  12-28-2010       1.0      1.0       1.0       1      1        0
343  12-29-2010       0.0      0.0       3.0       1      1        0
344  12-30-2010       2.0      0.0       1.0       1      1        0
345  01-10-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BMM0112
1             0   BMM0112
2             0   BMM0112
3             0   BMM0112
4             0   BMM0112
..          ...       ...
341           0   BMM0112
342           0   BMM0112
343           0   BMM0112
344           0   BMM0112
345           0   BMM0112

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0      10.0       1      1        0
1    01-05-2010       9.0      0.0       6.0       1      1        0
2    01-06-2010       7.0      2.0       6.0       1      1        0
3    01-07-2010       8.0      0.0       7.0       1      1        0
4    01-08-2010       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
121  06-25-2010       7.0      0.0       8.0       1      1        0
122  06-28-2010       6.0      1.0       8.0       1      1        0
123  06-29-2010       5.0      1.0       9.0       1      1        0
124  06-30-2010       7.0      1.0       7.0       1      1        0
125  04-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BMS0877
1             0   BMS0877
2             0   BMS0877
3             0   BMS0877
4             0   BMS0877
..          ...       ...
121           0   BMS0877
122           0   BMS0877
123           0   BMS0877
124           0   BMS0877
125           0   BMS0877

[126 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1      3.0
1    01-04-2010       2.0      0.0       1.0       1      1      1.0
2    01-04-2011       0.0      0.0       3.0       1      1      3.0
3    01-05-2010       1.0      0.0       2.0       1      1      3.0
4    01-05-2011       2.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1      0.0
342  12-30-2010       1.0      0.0       2.0       1      1      2.0
343  03-16-2011       0.0      0.0       0.0       1      1      1.0
344  08-05-2010       0.0      0.0       0.0       1      1      4.0
345  12-20-2010       0.0      0.0       0.0       1      1      3.0

     Disconnect user_name
0           3.0   BMT0528
1           1.0   BMT0528
2           3.0   BMT0528
3           3.0   BMT0528
4           0.0   BMT0528
..          ...       ...
341         0.0   BMT0528
342         2.0   BMT0528
343         1.0   BMT0528
344         4.0   BMT0528
345         3.0   BMT0528

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       3.0       1      1        0
1    01-04-2010       7.0      0.0       2.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       4.0       1      2        0
342  12-29-2010       5.0      0.0       4.0       1      2        0
343  12-30-2010       4.0      1.0       4.0       1      2        0
344  01-12-2010       0.0      0.0       0.0       1      2        0
345  07-01-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   BNG0237
1             0   BNG0237
2             0   BNG0237
3             0   BNG0237
4             0   BNG0237
..          ...       ...
341           0   BNG0237
342           0   BNG0237
343           0   BNG0237
344           0   BNG0237
345           0   BNG0237

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-06-2010       1.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-02-2010       0.0      0.0       0.0       1      2        0
342  06-21-2010       0.0      0.0       0.0       1      2        0
343  07-01-2010       0.0      0.0       0.0       1      2        0
344  07-23-2010       0.0      0.0       0.0       1      2        0
345  08-26-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   BNR0965
1             0   BNR0965
2             0   BNR0965
3             0   BNR0965
4             0   BNR0965
..          ...       ...
341           0   BNR0965
342           0   BNR0965
343           0   BNR0965
344           0   BNR0965
345           0   BNR0965

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-02-2010       0.0      1.0       2.0       1      1        6
1   01-03-2010       0.0      0.0       3.0       1      1        9
2   01-04-2010       0.0      0.0       3.0       1      1        9
3   01-05-2010       1.0      0.0       2.0       1      1        8
4   01-06-2010       0.0      0.0       2.0       1      1        7
5   01-07-2010       1.0      0.0       2.0       2      2        9
6   01-08-2010       2.0      0.0       1.0       1      1        7
7   01-09-2010       0.0      0.0       3.0       1      1        9
8   01-10-2010       0.0      0.0       3.0       2      2        9
9   01-11-2010       1.0      0.0       2.0       1      1        8
10  01-12-2010       1.0      0.0       1.0       1      1        7
11  01-13-2010       0.0      0.0       3.0       1      1        7
12  01-14-2010       0.0      0.0       3.0       1      1        8
13  01-15-2010       1.0      0.0       2.0       1      1        7
14  01-16-2010       1.0      0.0       2.0       1      1        8
15  01-17-2010       0.0      0.0       3.0       1      1        7
16  01-18-2010       0.0      1.0       2.0       1      1        8
17  01-19-2010       1.0      0.0       2.0       1      1        9
18  01-20-2010       2.0      0.0       1.0       2      2        8
19  01-21-2010       1.0      0.0       2.0       1      1        9
20  01-22-2010       0.0      0.0       3.0       1      1        6
21  01-23-2010       1.0      0.0       2.0       1      1        8
22  01-24-2010       1.0      0.0       2.0       1      1        8
23  01-25-2010       0.0      0.0       3.0       1      1        9
24  01-26-2010       0.0      1.0       2.0       2      2        9
25  01-27-2010       0.0      0.0       2.0       1      1        9
26  01-28-2010       0.0      0.0       3.0       1      1        7
27  01-29-2010       1.0      0.0       2.0       1      1        9
28  01-30-2010       0.0      0.0       3.0       1      1        8
29  01-31-2010       1.0      0.0       2.0       1      1        8
30  02-01-2010       2.0      0.0       1.0       2      2        7
31  02-02-2010       1.0      0.0       2.0       1      1        8
32  02-03-2010       0.0      0.0       3.0       1      1        8
33  02-04-2010       0.0      1.0       2.0       1      1        9
34  02-05-2010       1.0      0.0       2.0       1      1        7
35  02-06-2010       0.0      0.0       2.0       1      1        9
36  02-07-2010       1.0      1.0       1.0       2      2        9
37  02-08-2010       0.0      1.0       2.0       1      1        9
38  02-09-2010       1.0      0.0       2.0       1      1        8
39  02-10-2010       0.0      0.0       3.0       1      1        7
40  02-11-2010       0.0      0.0       3.0       2      2        9
41  02-12-2010       1.0      0.0       2.0       1      1        8
42  02-13-2010       0.0      0.0       3.0       1      1        7
43  02-14-2010       1.0      0.0       2.0       1      1        8
44  02-15-2010       1.0      0.0       1.0       1      1        9
45  02-16-2010       1.0      1.0       1.0       1      1        8
46  02-17-2010       2.0      0.0       1.0       1      1        7
47  02-18-2010       1.0      0.0       2.0       1      1        9
48  02-19-2010       1.0      1.0       1.0       1      1        7

    Disconnect user_name
0            6   BQS0525
1            9   BQS0525
2            9   BQS0525
3            8   BQS0525
4            7   BQS0525
5            9   BQS0525
6            7   BQS0525
7            9   BQS0525
8            8   BQS0525
9            8   BQS0525
10           6   BQS0525
11           7   BQS0525
12           8   BQS0525
13           7   BQS0525
14           8   BQS0525
15           7   BQS0525
16           8   BQS0525
17           9   BQS0525
18           8   BQS0525
19           9   BQS0525
20           6   BQS0525
21           8   BQS0525
22           8   BQS0525
23           9   BQS0525
24           9   BQS0525
25           9   BQS0525
26           7   BQS0525
27           9   BQS0525
28           8   BQS0525
29           8   BQS0525
30           6   BQS0525
31           8   BQS0525
32           8   BQS0525
33           9   BQS0525
34           7   BQS0525
35           9   BQS0525
36           9   BQS0525
37           9   BQS0525
38           8   BQS0525
39           7   BQS0525
40           8   BQS0525
41           8   BQS0525
42           7   BQS0525
43           8   BQS0525
44           9   BQS0525
45           8   BQS0525
46           7   BQS0525
47           9   BQS0525
48           7   BQS0525
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       2.0      0.0       8.0       1      2      2.0
1    01-02-2011       3.0      0.0       7.0       1      2      2.0
2    01-03-2010       6.0      0.0       4.0       1      2      3.0
3    01-03-2011       1.0      0.0       9.0       1      2      0.0
4    01-04-2010       4.0      1.0       4.0       1      1      4.0
..          ...       ...      ...       ...     ...    ...      ...
450  12-29-2010       6.0      1.0       3.0       1      2      2.0
451  12-30-2010       4.0      0.0       6.0       2      3      3.0
452  04-05-2010       0.0      0.0       0.0       2      2      1.0
453  07-11-2010       0.0      0.0       0.0       1      2      1.0
454  10-03-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           2.0   BRB0355
1           2.0   BRB0355
2           3.0   BRB0355
3           0.0   BRB0355
4           4.0   BRB0355
..          ...       ...
450         2.0   BRB0355
451         3.0   BRB0355
452         1.0   BRB0355
453         1.0   BRB0355
454         0.0   BRB0355

[455 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       2.0       1      1        9
1    01-04-2010       4.0      1.0       4.0       1      2        7
2    01-04-2011       4.0      3.0       2.0       1      2        9
3    01-05-2010       0.0      5.0       4.0       1      2        9
4    01-05-2011       4.0      4.0       1.0       1      2        8
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      3.0       3.0       1      2        9
342  12-30-2010       3.0      3.0       3.0       1      2        9
343  03-01-2010       0.0      0.0       0.0       1      1        8
344  06-07-2010       0.0      0.0       0.0       1      2        9
345  06-14-2010       0.0      0.0       0.0       1      2        8

     Disconnect user_name
0             9   BRM0995
1             7   BRM0995
2             9   BRM0995
3             9   BRM0995
4             8   BRM0995
..          ...       ...
341           9   BRM0995
342           9   BRM0995
343           8   BRM0995
344           9   BRM0995
345           8   BRM0995

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       1.0      7.0       2.0       1      1      2.0
1    01-04-2010       5.0      1.0       8.0       1      1      2.0
2    01-05-2010       2.0      7.0       4.0       1      1      3.0
3    01-06-2010       1.0      6.0       7.0       1      1      0.0
4    01-07-2010       4.0      0.0      10.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
105  05-07-2010       2.0      8.0       4.0       1      1      0.0
106  05-08-2010       1.0      9.0       4.0       1      1      1.0
107  05-10-2010       7.0      1.0       6.0       1      1      0.0
108  05-11-2010       7.0      2.0       5.0       1      1      1.0
109  05-12-2010       4.0     10.0       0.0       1      1      1.0

     Disconnect user_name
0           2.0   BRS0734
1           2.0   BRS0734
2           3.0   BRS0734
3           0.0   BRS0734
4           0.0   BRS0734
..          ...       ...
105         0.0   BRS0734
106         1.0   BRS0734
107         0.0   BRS0734
108         1.0   BRS0734
109         1.0   BRS0734

[110 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  01-06-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BSA0431
1             0   BSA0431
2             0   BSA0431
3             0   BSA0431
4             0   BSA0431
..          ...       ...
341           0   BSA0431
342           0   BSA0431
343           0   BSA0431
344           0   BSA0431
345           0   BSA0431

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       0.0      0.0       9.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       1.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       3.0       1      1        0
342  12-29-2010       2.0      0.0       7.0       1      1        0
343  12-30-2010       3.0      1.0       5.0       1      1        0
344  01-15-2010       0.0      0.0       0.0       1      1        0
345  10-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BSB0990
1             0   BSB0990
2             0   BSB0990
3             0   BSB0990
4             0   BSB0990
..          ...       ...
341           0   BSB0990
342           0   BSB0990
343           0   BSB0990
344           0   BSB0990
345           0   BSB0990

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       2.0      2.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       3.0      1.0       5.0       1      1        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       3.0      0.0       4.0       1      1        0
345  12-30-2010       2.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   BSH0445
1             0   BSH0445
2             0   BSH0445
3             0   BSH0445
4             0   BSH0445
..          ...       ...
341           0   BSH0445
342           0   BSH0445
343           0   BSH0445
344           0   BSH0445
345           0   BSH0445

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       5.0      0.0       5.0       2      2      9.0
1    01-04-2010       4.0      0.0       6.0       4      4     12.0
2    01-05-2010       4.0      0.0       5.0       5      5     13.0
3    01-06-2010       5.0      1.0       4.0       6      6     13.0
4    01-07-2010       3.0      0.0       7.0       6      6     14.0
..          ...       ...      ...       ...     ...    ...      ...
234  10-01-2010       2.0      0.0       8.0       4      4     10.0
235  10-02-2010       7.0      0.0       3.0       6      6     14.0
236  10-03-2010       6.0      0.0       4.0       3      3     10.0
237  02-03-2010       0.0      0.0       0.0       6      6     14.0
238  10-04-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           9.0   BSS0369
1          12.0   BSS0369
2          13.0   BSS0369
3          13.0   BSS0369
4          14.0   BSS0369
..          ...       ...
234        10.0   BSS0369
235        14.0   BSS0369
236        10.0   BSS0369
237        14.0   BSS0369
238         0.0   BSS0369

[239 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-20-2010       0.0      0.0       0.0       1      1        0
342  07-26-2010       0.0      0.0       0.0       1      1        0
343  09-13-2010       0.0      0.0       0.0       1      1        0
344  11-30-2010       0.0      0.0       0.0       1      1        0
345  12-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BSS0463
1             0   BSS0463
2             0   BSS0463
3             0   BSS0463
4             0   BSS0463
..          ...       ...
341           0   BSS0463
342           0   BSS0463
343           0   BSS0463
344           0   BSS0463
345           0   BSS0463

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       4.0       1      1      0.0
1    01-05-2010       2.0      1.0       6.0       1      2      0.0
2    01-06-2010       5.0      0.0       4.0       1      1      0.0
3    01-07-2010       4.0      0.0       5.0       1      2      0.0
4    01-08-2010       3.0      1.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
208  10-28-2010       4.0      1.0       4.0       1      2      0.0
209  10-29-2010       6.0      0.0       3.0       1      2      0.0
210  11-02-2010       3.0      0.0       6.0       1      2      0.0
211  05-13-2010       0.0      0.0       0.0       1      1      0.0
212  11-01-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   BTL0226
1           0.0   BTL0226
2           0.0   BTL0226
3           0.0   BTL0226
4           0.0   BTL0226
..          ...       ...
208         0.0   BTL0226
209         0.0   BTL0226
210         0.0   BTL0226
211         0.0   BTL0226
212         0.0   BTL0226

[213 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-26-2010       0.0      0.0       0.0       1      1        0
342  06-02-2010       0.0      0.0       0.0       1      1        0
343  06-23-2010       0.0      0.0       0.0       1      1        0
344  09-28-2010       0.0      0.0       0.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BTL0722
1             0   BTL0722
2             0   BTL0722
3             0   BTL0722
4             0   BTL0722
..          ...       ...
341           0   BTL0722
342           0   BTL0722
343           0   BTL0722
344           0   BTL0722
345           0   BTL0722

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       2      2        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       3.0      1.0       5.0       1      2        0
3    01-05-2010       5.0      1.0       3.0       1      2        0
4    01-05-2011       5.0      0.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       5.0       1      2        0
342  12-27-2010       4.0      0.0       5.0       1      2        0
343  12-28-2010       5.0      1.0       3.0       1      2        0
344  12-29-2010       0.0      0.0       9.0       1      2        0
345  12-30-2010       2.0      0.0       7.0       1      2        0

     Disconnect user_name
0             0   BTN0061
1             0   BTN0061
2             0   BTN0061
3             0   BTN0061
4             0   BTN0061
..          ...       ...
341           0   BTN0061
342           0   BTN0061
343           0   BTN0061
344           0   BTN0061
345           0   BTN0061

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       8.0       2      2      1.0
1    01-04-2010       2.0      1.0       6.0       1      2      2.0
2    01-04-2011       3.0      0.0       6.0       1      2      3.0
3    01-05-2010       4.0      0.0       5.0       1      2      1.0
4    01-05-2011       4.0      1.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      1.0       6.0       1      2      1.0
342  12-28-2010       4.0      0.0       5.0       2      2      2.0
343  12-29-2010       5.0      0.0       4.0       1      2      1.0
344  12-30-2010       1.0      0.0       8.0       1      2      2.0
345  03-15-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   BTR0403
1           2.0   BTR0403
2           3.0   BTR0403
3           1.0   BTR0403
4           0.0   BTR0403
..          ...       ...
341         1.0   BTR0403
342         2.0   BTR0403
343         1.0   BTR0403
344         2.0   BTR0403
345         0.0   BTR0403

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       9.0       1      1        0
1    01-04-2010       6.0      1.0      11.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010       7.0      0.0      10.0       1      1        0
4    01-05-2011       6.0      1.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0      15.0       1      1        0
342  12-29-2010       8.0      0.0      10.0       1      1        0
343  12-30-2010       6.0      0.0      12.0       1      1        0
344  06-07-2010       0.0      0.0       0.0       1      1        0
345  08-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BTS0011
1             0   BTS0011
2             0   BTS0011
3             0   BTS0011
4             0   BTS0011
..          ...       ...
341           0   BTS0011
342           0   BTS0011
343           0   BTS0011
344           0   BTS0011
345           0   BTS0011

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      1.0      16.0       1      1        0
1    01-04-2010      11.0      1.0      15.0       2      2        0
2    01-04-2011      15.0      2.0      10.0       1      1        0
3    01-05-2010       9.0      3.0      14.0       1      1        0
4    01-05-2011       5.0      0.0      22.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       9.0      0.0      18.0       1      1        0
342  12-27-2010       7.0      3.0      16.0       1      1        0
343  12-28-2010      12.0      1.0      14.0       2      2        0
344  12-29-2010      11.0      2.0      14.0       1      1        0
345  12-30-2010      12.0      2.0      13.0       1      1        0

     Disconnect user_name
0             0   BTW0005
1             0   BTW0005
2             0   BTW0005
3             0   BTW0005
4             0   BTW0005
..          ...       ...
341           0   BTW0005
342           0   BTW0005
343           0   BTW0005
344           0   BTW0005
345           0   BTW0005

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       1.0      1.0       7.0       1      1      1.0
1    01-03-2010       2.0      0.0       7.0       1      2      2.0
2    01-03-2011       0.0      1.0       8.0       1      2      1.0
3    01-04-2010       4.0      0.0       5.0       1      2      1.0
4    01-04-2011       3.0      0.0       5.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
433  04-22-2011       0.0      0.0       0.0       1      1      0.0
434  09-18-2010       0.0      0.0       0.0       1      1      0.0
435  10-04-2010       0.0      0.0       0.0       1      2      2.0
436  12-11-2010       0.0      0.0       0.0       1      1      0.0
437  12-30-2010       0.0      0.0       0.0       2      3      3.0

     Disconnect user_name
0           1.0   BVC0790
1           2.0   BVC0790
2           1.0   BVC0790
3           1.0   BVC0790
4           2.0   BVC0790
..          ...       ...
433         0.0   BVC0790
434         0.0   BVC0790
435         2.0   BVC0790
436         0.0   BVC0790
437         3.0   BVC0790

[438 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      1.0       1.0       1      1        0
1    01-05-2010       0.0      0.0       3.0       1      1        0
2    01-06-2010       0.0      1.0       2.0       1      1        0
3    01-07-2010       2.0      0.0       1.0       1      1        0
4    01-08-2010       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
105  06-02-2010       2.0      0.0       1.0       1      1        0
106  06-03-2010       0.0      0.0       3.0       1      1        0
107  06-04-2010       0.0      0.0       3.0       1      1        0
108  06-07-2010       1.0      0.0       2.0       2      2        0
109  06-08-2010       0.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   BVN0514
1             0   BVN0514
2             0   BVN0514
3             0   BVN0514
4             0   BVN0514
..          ...       ...
105           0   BVN0514
106           0   BVN0514
107           0   BVN0514
108           0   BVN0514
109           0   BVN0514

[110 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       2.0      1.0       6.0       1      1        0
344  12-30-2010       4.0      1.0       4.0       1      1        0
345  10-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BWH0813
1             0   BWH0813
2             0   BWH0813
3             0   BWH0813
4             0   BWH0813
..          ...       ...
341           0   BWH0813
342           0   BWH0813
343           0   BWH0813
344           0   BWH0813
345           0   BWH0813

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0     2.0    3.0      0.0
1    01-04-2010       4.0      0.0       7.0     2.0    3.0      0.0
2    01-04-2011       6.0      0.0       5.0     2.0    3.0      0.0
3    01-05-2010       6.0      1.0       4.0     1.0    2.0      1.0
4    01-05-2011       4.0      0.0       6.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
350  05-01-2010       0.0      0.0       0.0     1.0    1.0      0.0
351  05-08-2010       0.0      0.0       0.0     1.0    0.0      0.0
352  10-02-2010       0.0      0.0       0.0     1.0    1.0      0.0
353  10-26-2010       0.0      0.0       0.0     2.0    3.0      0.0
354  11-06-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   BWP0202
1           0.0   BWP0202
2           0.0   BWP0202
3           1.0   BWP0202
4           0.0   BWP0202
..          ...       ...
350         0.0   BWP0202
351         0.0   BWP0202
352         0.0   BWP0202
353         0.0   BWP0202
354         0.0   BWP0202

[355 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0      12.0       1      1        0
1    01-04-2010      13.0      1.0       4.0       1      1        0
2    01-04-2011       7.0      0.0      11.0       1      1        0
3    01-05-2010       3.0      1.0      14.0       1      1        0
4    01-05-2011       7.0      0.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010      10.0      1.0       7.0       1      1        0
342  12-28-2010       8.0      4.0       6.0       1      1        0
343  12-29-2010      10.0      1.0       7.0       1      1        0
344  12-30-2010       7.0      0.0      11.0       1      1        0
345  04-27-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BXJ0010
1             0   BXJ0010
2             0   BXJ0010
3             0   BXJ0010
4             0   BXJ0010
..          ...       ...
341           0   BXJ0010
342           0   BXJ0010
343           0   BXJ0010
344           0   BXJ0010
345           0   BXJ0010

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       5.0       1      1        0
1    01-05-2010       7.0      0.0       2.0       1      1        0
2    01-06-2010       5.0      0.0       4.0       1      1        0
3    01-07-2010       6.0      0.0       3.0       1      1        0
4    01-08-2010       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
233  12-06-2010       6.0      1.0       2.0       1      1        0
234  12-07-2010       5.0      0.0       4.0       1      1        0
235  12-08-2010       2.0      0.0       7.0       1      1        0
236  12-09-2010       4.0      2.0       3.0       1      1        0
237  08-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   BYP0070
1             0   BYP0070
2             0   BYP0070
3             0   BYP0070
4             0   BYP0070
..          ...       ...
233           0   BYP0070
234           0   BYP0070
235           0   BYP0070
236           0   BYP0070
237           0   BYP0070

[238 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      11.0      0.0       5.0       1      2      0.0
1    01-04-2010       7.0      2.0       6.0       1      2      1.0
2    01-04-2011       2.0      1.0      13.0       1      2      0.0
3    01-05-2010       3.0      1.0       7.0       1      2      1.0
4    01-05-2011       6.0      0.0       9.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       9.0       1      2      2.0
342  12-28-2010       6.0      0.0      10.0       1      2      1.0
343  12-29-2010       7.0      0.0       9.0       1      2      1.0
344  12-30-2010       7.0      0.0       8.0       1      2      0.0
345  11-19-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   CAA0612
1           1.0   CAA0612
2           0.0   CAA0612
3           1.0   CAA0612
4           0.0   CAA0612
..          ...       ...
341         2.0   CAA0612
342         1.0   CAA0612
343         1.0   CAA0612
344         0.0   CAA0612
345         1.0   CAA0612

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      2        0
1    01-04-2010       3.0      1.0       5.0       1      2        0
2    01-04-2011       6.0      1.0       2.0       1      2        0
3    01-05-2010       4.0      0.0       5.0       1      2        0
4    01-05-2011       2.0      1.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-18-2011       0.0      0.0       0.0       1      2        0
342  01-20-2011       0.0      0.0       0.0       1      2        0
343  02-09-2010       0.0      0.0       0.0       1      2        0
344  06-16-2010       0.0      0.0       0.0       1      2        0
345  12-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CAB0388
1             0   CAB0388
2             0   CAB0388
3             0   CAB0388
4             0   CAB0388
..          ...       ...
341           0   CAB0388
342           0   CAB0388
343           0   CAB0388
344           0   CAB0388
345           0   CAB0388

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       6.0       2      3      2.0
1    01-04-2010       6.0      0.0      10.0       1      2      2.0
2    01-04-2011       8.0      0.0       8.0       1      2      0.0
3    01-05-2010      10.0      0.0       6.0       1      2      3.0
4    01-05-2011      10.0      0.0       6.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       9.0      0.0       7.0       1      2      1.0
342  12-28-2010      11.0      0.0       5.0       1      1      1.0
343  12-29-2010       3.0      0.0      13.0       1      2      1.0
344  12-30-2010      10.0      2.0       4.0       1      2      2.0
345  11-03-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           2.0   CAB0614
1           2.0   CAB0614
2           0.0   CAB0614
3           3.0   CAB0614
4           1.0   CAB0614
..          ...       ...
341         1.0   CAB0614
342         1.0   CAB0614
343         1.0   CAB0614
344         2.0   CAB0614
345         1.0   CAB0614

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       2.0      0.0       1.0       1      1        0
1   01-05-2010       0.0      1.0       2.0       1      1        0
2   01-06-2010       1.0      0.0       2.0       1      1        0
3   01-07-2010       1.0      0.0       2.0       1      1        0
4   01-08-2010       2.0      0.0       1.0       1      1        0
5   01-11-2010       1.0      0.0       2.0       1      1        0
6   01-12-2010       0.0      0.0       3.0       1      1        0
7   01-13-2010       1.0      0.0       1.0       1      1        0
8   01-14-2010       0.0      0.0       3.0       1      1        0
9   01-15-2010       1.0      1.0       1.0       1      1        0
10  01-18-2010       0.0      0.0       3.0       1      1        0
11  01-19-2010       1.0      0.0       2.0       1      1        0
12  01-20-2010       0.0      1.0       2.0       1      1        0
13  01-21-2010       2.0      0.0       1.0       1      1        0
14  01-22-2010       1.0      0.0       0.0       1      1        0
15  01-25-2010       1.0      0.0       2.0       1      1        0
16  01-26-2010       0.0      0.0       3.0       1      1        0
17  01-27-2010       3.0      0.0       0.0       1      1        0
18  01-28-2010       1.0      0.0       2.0       1      1        0
19  01-29-2010       0.0      1.0       2.0       1      1        0
20  02-01-2010       1.0      0.0       2.0       1      1        0
21  02-02-2010       0.0      0.0       3.0       1      1        0
22  02-03-2010       1.0      0.0       2.0       1      1        0
23  02-04-2010       2.0      0.0       1.0       1      1        0
24  02-05-2010       1.0      0.0       2.0       1      1        0
25  02-08-2010       2.0      0.0       1.0       1      1        0
26  02-09-2010       0.0      1.0       2.0       1      1        0
27  02-10-2010       0.0      1.0       2.0       1      1        0
28  02-11-2010       1.0      0.0       2.0       1      1        0
29  02-12-2010       2.0      0.0       1.0       1      1        0
30  02-15-2010       1.0      0.0       2.0       1      1        0
31  02-16-2010       1.0      0.0       2.0       1      1        0
32  02-17-2010       1.0      0.0       2.0       1      1        0
33  02-18-2010       1.0      0.0       2.0       1      1        0
34  02-19-2010       1.0      0.0       2.0       1      1        0
35  02-22-2010       0.0      0.0       3.0       1      1        0
36  02-23-2010       2.0      0.0       1.0       1      1        0
37  02-24-2010       0.0      0.0       3.0       1      1        0
38  02-26-2010       1.0      0.0       2.0       1      1        0
39  03-01-2010       1.0      0.0       2.0       1      1        0
40  03-02-2010       0.0      0.0       3.0       1      1        0
41  03-03-2010       1.0      0.0       2.0       1      1        0
42  03-04-2010       1.0      0.0       2.0       1      1        0
43  03-05-2010       0.0      1.0       2.0       1      1        0
44  03-08-2010       0.0      1.0       1.0       1      1        0
45  03-09-2010       3.0      0.0       0.0       1      1        0
46  03-10-2010       2.0      0.0       1.0       1      1        0
47  03-11-2010       0.0      0.0       3.0       1      1        0
48  03-12-2010       0.0      0.0       3.0       1      1        0
49  03-15-2010       3.0      0.0       0.0       1      1        0
50  03-16-2010       2.0      0.0       1.0       1      1        0
51  03-17-2010       1.0      0.0       2.0       1      1        0
52  03-18-2010       1.0      0.0       1.0       1      1        0
53  03-19-2010       0.0      2.0       1.0       1      1        0
54  03-22-2010       0.0      0.0       3.0       1      1        0
55  03-23-2010       1.0      0.0       2.0       1      1        0
56  03-24-2010       3.0      0.0       0.0       1      1        0
57  03-25-2010       1.0      0.0       0.0       1      1        0
58  03-26-2010       0.0      0.0       3.0       1      1        0
59  02-25-2010       0.0      0.0       0.0       1      1        0

    Disconnect user_name
0            0   CAC0889
1            0   CAC0889
2            0   CAC0889
3            0   CAC0889
4            0   CAC0889
5            0   CAC0889
6            0   CAC0889
7            0   CAC0889
8            0   CAC0889
9            0   CAC0889
10           0   CAC0889
11           0   CAC0889
12           0   CAC0889
13           0   CAC0889
14           0   CAC0889
15           0   CAC0889
16           0   CAC0889
17           0   CAC0889
18           0   CAC0889
19           0   CAC0889
20           0   CAC0889
21           0   CAC0889
22           0   CAC0889
23           0   CAC0889
24           0   CAC0889
25           0   CAC0889
26           0   CAC0889
27           0   CAC0889
28           0   CAC0889
29           0   CAC0889
30           0   CAC0889
31           0   CAC0889
32           0   CAC0889
33           0   CAC0889
34           0   CAC0889
35           0   CAC0889
36           0   CAC0889
37           0   CAC0889
38           0   CAC0889
39           0   CAC0889
40           0   CAC0889
41           0   CAC0889
42           0   CAC0889
43           0   CAC0889
44           0   CAC0889
45           0   CAC0889
46           0   CAC0889
47           0   CAC0889
48           0   CAC0889
49           0   CAC0889
50           0   CAC0889
51           0   CAC0889
52           0   CAC0889
53           0   CAC0889
54           0   CAC0889
55           0   CAC0889
56           0   CAC0889
57           0   CAC0889
58           0   CAC0889
59           0   CAC0889
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       6.0      0.0       2.0       1      2      0.0
1    01-05-2010       4.0      1.0       4.0       1      2      0.0
2    01-06-2010       2.0      2.0       5.0       2      2      0.0
3    01-07-2010       4.0      1.0       4.0       1      2      0.0
4    01-08-2010       3.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
167  08-30-2010       2.0      0.0       6.0       1      2      0.0
168  08-31-2010       4.0      1.0       4.0       1      2      0.0
169  09-01-2010       4.0      1.0       4.0       1      2      0.0
170  09-02-2010       4.0      0.0       5.0       2      2      0.0
171  09-03-2010       4.0      0.0       5.0       1      2      0.0

     Disconnect user_name
0           0.0   CAH0936
1           0.0   CAH0936
2           0.0   CAH0936
3           0.0   CAH0936
4           0.0   CAH0936
..          ...       ...
167         0.0   CAH0936
168         0.0   CAH0936
169         0.0   CAH0936
170         0.0   CAH0936
171         0.0   CAH0936

[172 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       9.0      0.0       0.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       4.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       2.0      1.0       6.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       2.0      1.0       6.0       1      1        0

     Disconnect user_name
0             0   CAM0102
1             0   CAM0102
2             0   CAM0102
3             0   CAM0102
4             0   CAM0102
..          ...       ...
341           0   CAM0102
342           0   CAM0102
343           0   CAM0102
344           0   CAM0102
345           0   CAM0102

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      2      0.0
1    01-04-2010       4.0      0.0       5.0       1      2      0.0
2    01-04-2011       1.0      1.0       7.0       1      2      1.0
3    01-05-2010       3.0      0.0       6.0       1      2      1.0
4    01-05-2011       4.0      1.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      2      0.0
342  12-28-2010       6.0      1.0       2.0       1      2      1.0
343  12-29-2010       5.0      0.0       4.0       1      2      3.0
344  12-30-2010       6.0      1.0       2.0       1      2      1.0
345  06-18-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   CAM0681
1           0.0   CAM0681
2           1.0   CAM0681
3           1.0   CAM0681
4           0.0   CAM0681
..          ...       ...
341         0.0   CAM0681
342         1.0   CAM0681
343         3.0   CAM0681
344         1.0   CAM0681
345         1.0   CAM0681

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-26-2010       0.0      0.0       0.0       1      1        0
342  05-10-2011       0.0      0.0       0.0       1      1        0
343  07-28-2010       0.0      0.0       0.0       1      1        0
344  07-29-2010       0.0      0.0       0.0       1      1        0
345  08-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CAN0842
1             0   CAN0842
2             0   CAN0842
3             0   CAN0842
4             0   CAN0842
..          ...       ...
341           0   CAN0842
342           0   CAN0842
343           0   CAN0842
344           0   CAN0842
345           0   CAN0842

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0     1.0    2.0      0.0
1    01-04-2010       0.0      0.0       3.0     2.0    3.0      1.0
2    01-04-2011       2.0      0.0       1.0     2.0    2.0      1.0
3    01-05-2010       2.0      0.0       1.0     1.0    2.0      0.0
4    01-05-2011       1.0      0.0       2.0     1.0    2.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
342  05-16-2011       0.0      0.0       0.0     1.0    2.0      2.0
343  06-15-2010       0.0      0.0       0.0     1.0    2.0      1.0
344  06-17-2010       0.0      0.0       0.0     1.0    2.0      0.0
345  10-02-2010       0.0      0.0       0.0     1.0    0.0      0.0
346  11-01-2010       0.0      0.0       0.0     1.0    2.0      2.0

     Disconnect user_name
0           0.0   CAS0507
1           1.0   CAS0507
2           1.0   CAS0507
3           0.0   CAS0507
4           2.0   CAS0507
..          ...       ...
342         2.0   CAS0507
343         1.0   CAS0507
344         0.0   CAS0507
345         0.0   CAS0507
346         2.0   CAS0507

[347 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       7.0       6      6        0
1    01-04-2010       6.0      1.0       4.0       5      6        0
2    01-04-2011       4.0      1.0       6.0       3      4        0
3    01-05-2010       4.0      0.0       7.0       3      4        0
4    01-05-2011       6.0      1.0       4.0       3      4        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      1.0       6.0       4      5        0
342  12-28-2010       2.0      0.0       8.0       7      8        0
343  12-29-2010       4.0      1.0       6.0       6      7        0
344  12-30-2010       6.0      0.0       5.0       6      7        0
345  03-22-2010       0.0      0.0       0.0       6      7        0

     Disconnect user_name
0             0   CBB0365
1             0   CBB0365
2             0   CBB0365
3             0   CBB0365
4             0   CBB0365
..          ...       ...
341           0   CBB0365
342           0   CBB0365
343           0   CBB0365
344           0   CBB0365
345           0   CBB0365

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      1.0       6.0       1      1        0
2    01-04-2011       3.0      1.0       4.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      1.0       3.0       1      1        0
342  12-29-2010       3.0      0.0       6.0       1      1        0
343  12-30-2010       2.0      2.0       5.0       1      1        0
344  02-03-2010       0.0      0.0       0.0       1      1        0
345  04-18-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CBG0398
1             0   CBG0398
2             0   CBG0398
3             0   CBG0398
4             0   CBG0398
..          ...       ...
341           0   CBG0398
342           0   CBG0398
343           0   CBG0398
344           0   CBG0398
345           0   CBG0398

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010       8.0      2.0       4.0       1      1        0
2    01-04-2011       7.0      2.0       6.0       1      1        0
3    01-05-2010       7.0      0.0       7.0       1      1        0
4    01-05-2011      10.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       7.0       1      1        0
342  12-28-2010      13.0      0.0       2.0       1      1        0
343  12-29-2010       9.0      0.0       6.0       1      1        0
344  12-30-2010       7.0      1.0       7.0       1      1        0
345  01-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CBG0490
1             0   CBG0490
2             0   CBG0490
3             0   CBG0490
4             0   CBG0490
..          ...       ...
341           0   CBG0490
342           0   CBG0490
343           0   CBG0490
344           0   CBG0490
345           0   CBG0490

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      2.0       4.0       2      2      1.0
1    01-05-2010       0.0      0.0       6.0       2      2      2.0
2    01-06-2010       5.0      0.0       5.0       2      2      1.0
3    01-07-2010       6.0      1.0       4.0       4      4      3.0
4    01-08-2010       2.0      0.0       9.0       3      3      3.0
..          ...       ...      ...       ...     ...    ...      ...
196  10-11-2010       4.0      1.0       6.0       2      2      1.0
197  10-12-2010       2.0      1.0       5.0       3      3      2.0
198  10-13-2010       4.0      0.0       7.0       5      5      4.0
199  10-14-2010       7.0      0.0       6.0       6      6      8.0
200  10-15-2010       4.0      0.0       7.0       8      8      5.0

     Disconnect user_name
0           1.0   CCA0046
1           2.0   CCA0046
2           1.0   CCA0046
3           3.0   CCA0046
4           3.0   CCA0046
..          ...       ...
196         1.0   CCA0046
197         2.0   CCA0046
198         4.0   CCA0046
199         8.0   CCA0046
200         5.0   CCA0046

[201 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       4.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       5.0       1      1        0
342  12-27-2010       5.0      1.0       3.0       1      1        0
343  12-28-2010       3.0      1.0       5.0       1      1        0
344  12-29-2010       3.0      1.0       5.0       1      1        0
345  12-30-2010       4.0      1.0       4.0       1      1        0

     Disconnect user_name
0             0   CCC0393
1             0   CCC0393
2             0   CCC0393
3             0   CCC0393
4             0   CCC0393
..          ...       ...
341           0   CCC0393
342           0   CCC0393
343           0   CCC0393
344           0   CCC0393
345           0   CCC0393

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  02-02-2010       0.0      0.0       0.0       1      1        0
345  05-09-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CCH0182
1             0   CCH0182
2             0   CCH0182
3             0   CCH0182
4             0   CCH0182
..          ...       ...
341           0   CCH0182
342           0   CCH0182
343           0   CCH0182
344           0   CCH0182
345           0   CCH0182

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      2.0       4.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      2        0
2    01-04-2011       4.0      0.0       5.0       1      2        0
3    01-05-2010       6.0      0.0       2.0       1      2        0
4    01-05-2011       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2        0
342  12-27-2010       3.0      2.0       4.0       1      2        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      2        0
345  12-30-2010       6.0      0.0       3.0       1      2        0

     Disconnect user_name
0             0   CCH0685
1             0   CCH0685
2             0   CCH0685
3             0   CCH0685
4             0   CCH0685
..          ...       ...
341           0   CCH0685
342           0   CCH0685
343           0   CCH0685
344           0   CCH0685
345           0   CCH0685

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1      3.0
1    01-04-2010       2.0      0.0       7.0       1      1      3.0
2    01-04-2011       4.0      0.0       7.0       1      1      1.0
3    01-05-2010       5.0      0.0       4.0       1      1      1.0
4    01-05-2011       4.0      1.0       4.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
283  12-22-2010       4.0      1.0       4.0       1      1      1.0
284  12-27-2010       6.0      0.0       3.0       1      1      2.0
285  12-28-2010       1.0      0.0       8.0       1      1      2.0
286  12-29-2010       5.0      0.0       4.0       1      1      1.0
287  12-30-2010       4.0      1.0       5.0       1      1      3.0

     Disconnect user_name
0           3.0   CCL0068
1           3.0   CCL0068
2           1.0   CCL0068
3           1.0   CCL0068
4           2.0   CCL0068
..          ...       ...
283         1.0   CCL0068
284         2.0   CCL0068
285         2.0   CCL0068
286         1.0   CCL0068
287         3.0   CCL0068

[288 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2      0.0
1    01-04-2010       1.0      0.0       0.0       1      2      0.0
2    01-04-2011       0.0      0.0       1.0       1      2      2.0
3    01-05-2010       1.0      0.0       0.0       1      2      0.0
4    01-05-2011       0.0      0.0       1.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  06-03-2010       0.0      0.0       0.0       1      2      0.0
342  06-25-2010       0.0      0.0       0.0       1      2      0.0
343  09-28-2010       0.0      0.0       0.0       1      1      0.0
344  12-08-2010       0.0      0.0       0.0       1      2      0.0
345  12-27-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   CCM0136
1           0.0   CCM0136
2           2.0   CCM0136
3           0.0   CCM0136
4           1.0   CCM0136
..          ...       ...
341         0.0   CCM0136
342         0.0   CCM0136
343         0.0   CCM0136
344         0.0   CCM0136
345         0.0   CCM0136

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-30-2010       0.0      0.0       0.0       1      1        0
342  06-22-2010       0.0      0.0       0.0       1      1        0
343  07-08-2010       0.0      0.0       0.0       1      1        0
344  11-19-2010       0.0      0.0       0.0       1      1        0
345  12-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CCM0467
1             0   CCM0467
2             0   CCM0467
3             0   CCM0467
4             0   CCM0467
..          ...       ...
341           0   CCM0467
342           0   CCM0467
343           0   CCM0467
344           0   CCM0467
345           0   CCM0467

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010      12.0      0.0       3.0       1      1        0
2    01-04-2011       4.0      0.0      11.0       1      1        0
3    01-05-2010       9.0      0.0       6.0       1      1        0
4    01-05-2011       8.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       5.0       1      1        0
342  12-27-2010       4.0      0.0      11.0       1      1        0
343  12-28-2010       1.0      1.0      13.0       1      1        0
344  12-29-2010       4.0      0.0      11.0       1      1        0
345  12-30-2010       7.0      1.0       6.0       1      1        0

     Disconnect user_name
0             0   CCM0855
1             0   CCM0855
2             0   CCM0855
3             0   CCM0855
4             0   CCM0855
..          ...       ...
341           0   CCM0855
342           0   CCM0855
343           0   CCM0855
344           0   CCM0855
345           0   CCM0855

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010       9.0      1.0       5.0       1      1        0
2    01-04-2011       8.0      0.0       7.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011      11.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       9.0      0.0       6.0       1      1        0
342  12-27-2010       6.0      1.0       8.0       1      1        0
343  12-28-2010       8.0      0.0       7.0       1      1        0
344  12-29-2010       8.0      1.0       6.0       1      1        0
345  12-30-2010       6.0      2.0       6.0       1      1        0

     Disconnect user_name
0             0   CCR0863
1             0   CCR0863
2             0   CCR0863
3             0   CCR0863
4             0   CCR0863
..          ...       ...
341           0   CCR0863
342           0   CCR0863
343           0   CCR0863
344           0   CCR0863
345           0   CCR0863

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      3.0       6.0       1      1        0
1    01-04-2010       7.0      0.0       7.0       1      1        0
2    01-04-2011       7.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      1.0       7.0       1      1        0
4    01-05-2011       2.0      1.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       8.0       1      1        0
342  12-27-2010       8.0      0.0       6.0       1      1        0
343  12-28-2010       7.0      0.0       4.0       1      1        0
344  12-29-2010       9.0      0.0       5.0       1      1        0
345  12-30-2010       1.0      3.0      10.0       1      1        0

     Disconnect user_name
0             0   CCW0031
1             0   CCW0031
2             0   CCW0031
3             0   CCW0031
4             0   CCW0031
..          ...       ...
341           0   CCW0031
342           0   CCW0031
343           0   CCW0031
344           0   CCW0031
345           0   CCW0031

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      1.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       1.0       1      1        0
342  04-08-2010       0.0      0.0       0.0       1      1        0
343  06-16-2010       0.0      0.0       0.0       1      1        0
344  07-28-2010       0.0      0.0       0.0       1      1        0
345  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CCW0524
1             0   CCW0524
2             0   CCW0524
3             0   CCW0524
4             0   CCW0524
..          ...       ...
341           0   CCW0524
342           0   CCW0524
343           0   CCW0524
344           0   CCW0524
345           0   CCW0524

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      1.0       9.0       1      1        0
2    01-04-2011       5.0      0.0       8.0       1      1        0
3    01-05-2010       5.0      2.0       7.0       1      1        0
4    01-05-2011       5.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       6.0      2.0       6.0       1      1        0
342  02-14-2011       0.0      0.0       0.0       1      1        0
343  04-01-2010       0.0      0.0       0.0       1      1        0
344  06-29-2010       0.0      0.0       0.0       1      1        0
345  07-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CEB0210
1             0   CEB0210
2             0   CEB0210
3             0   CEB0210
4             0   CEB0210
..          ...       ...
341           0   CEB0210
342           0   CEB0210
343           0   CEB0210
344           0   CEB0210
345           0   CEB0210

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1      3.0
1    01-04-2010       3.0      0.0       6.0       1      1      1.0
2    01-04-2011       4.0      1.0       4.0       1      1      2.0
3    01-05-2010       3.0      0.0       6.0       1      1      1.0
4    01-05-2011       5.0      0.0       4.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
313  12-28-2010       3.0      0.0       5.0       1      1      2.0
314  12-29-2010       0.0      1.0       8.0       1      1      1.0
315  12-30-2010       5.0      0.0       4.0       1      1      2.0
316  03-04-2011       0.0      0.0       0.0       1      1      2.0
317  09-28-2010       0.0      0.0       0.0       1      1      2.0

     Disconnect user_name
0           3.0   CEJ0109
1           1.0   CEJ0109
2           2.0   CEJ0109
3           1.0   CEJ0109
4           2.0   CEJ0109
..          ...       ...
313         2.0   CEJ0109
314         0.0   CEJ0109
315         2.0   CEJ0109
316         2.0   CEJ0109
317         2.0   CEJ0109

[318 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      2        0
2    01-04-2011       6.0      1.0       2.0       1      2        0
3    01-05-2010       6.0      0.0       3.0       1      2        0
4    01-05-2011       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        0
342  12-28-2010       6.0      1.0       2.0       1      1        0
343  12-29-2010       7.0      0.0       2.0       1      2        0
344  12-30-2010       5.0      1.0       3.0       1      2        0
345  02-08-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   CEL0561
1             0   CEL0561
2             0   CEL0561
3             0   CEL0561
4             0   CEL0561
..          ...       ...
341           0   CEL0561
342           0   CEL0561
343           0   CEL0561
344           0   CEL0561
345           0   CEL0561

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2        0
1    01-04-2010       0.0      0.0       1.0       2      2        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-25-2010       0.0      0.0       0.0       1      1        0
342  05-16-2011       0.0      0.0       0.0       1      1        0
343  08-19-2010       0.0      0.0       0.0       2      2        0
344  09-16-2010       0.0      0.0       0.0       1      1        0
345  11-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CFG0959
1             0   CFG0959
2             0   CFG0959
3             0   CFG0959
4             0   CFG0959
..          ...       ...
341           0   CFG0959
342           0   CFG0959
343           0   CFG0959
344           0   CFG0959
345           0   CFG0959

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0     1.0    1.0      1.0
1    01-04-2010       2.0      0.0       1.0     1.0    2.0      1.0
2    01-04-2011       3.0      0.0       0.0     1.0    2.0      0.0
3    01-05-2010       1.0      0.0       2.0     1.0    2.0      0.0
4    01-05-2011       1.0      0.0       2.0     1.0    2.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
345  01-15-2011       0.0      0.0       0.0     1.0    0.0      0.0
346  03-06-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  07-03-2010       0.0      0.0       0.0     1.0    0.0      0.0
348  08-26-2010       0.0      0.0       0.0     1.0    2.0      0.0
349  10-02-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           1.0   CFM0767
1           1.0   CFM0767
2           0.0   CFM0767
3           0.0   CFM0767
4           1.0   CFM0767
..          ...       ...
345         0.0   CFM0767
346         0.0   CFM0767
347         0.0   CFM0767
348         0.0   CFM0767
349         0.0   CFM0767

[350 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       6.0      0.0       3.0       1      1        0
1   01-05-2010       5.0      0.0       4.0       1      1        0
2   01-06-2010       5.0      1.0       3.0       1      1        0
3   01-07-2010       4.0      3.0       2.0       1      1        0
4   01-08-2010       5.0      0.0       4.0       1      1        0
5   01-11-2010       5.0      0.0       4.0       1      1        0
6   01-12-2010       1.0      1.0       7.0       1      1        0
7   01-13-2010       3.0      0.0       6.0       1      1        0
8   01-14-2010       4.0      1.0       4.0       1      1        0
9   01-15-2010       3.0      2.0       4.0       1      1        0
10  01-18-2010       5.0      0.0       4.0       1      1        0
11  01-19-2010       2.0      1.0       4.0       1      1        0
12  01-20-2010       4.0      1.0       3.0       1      1        0
13  01-21-2010       2.0      1.0       5.0       1      1        0
14  01-22-2010       3.0      1.0       4.0       1      1        0
15  01-25-2010       4.0      0.0       4.0       1      1        0
16  01-26-2010       3.0      1.0       5.0       1      1        0
17  01-27-2010       2.0      0.0       7.0       1      1        0
18  01-28-2010       4.0      0.0       4.0       1      1        0
19  01-29-2010       4.0      1.0       4.0       1      1        0
20  02-01-2010       3.0      1.0       5.0       1      1        0
21  02-02-2010       3.0      0.0       6.0       1      1        0
22  02-03-2010       6.0      1.0       2.0       1      1        0
23  02-04-2010       5.0      0.0       4.0       1      1        0
24  02-05-2010       6.0      1.0       1.0       1      1        0
25  02-08-2010       8.0      0.0       1.0       1      1        0
26  02-09-2010       2.0      3.0       4.0       1      1        0
27  02-10-2010       5.0      1.0       3.0       1      1        0
28  02-11-2010       3.0      0.0       4.0       1      1        0
29  02-12-2010       3.0      2.0       4.0       1      1        0
30  02-15-2010       3.0      0.0       4.0       1      1        0
31  02-16-2010       3.0      1.0       5.0       1      1        0
32  02-17-2010       3.0      0.0       3.0       1      1        0
33  02-18-2010       5.0      2.0       2.0       1      1        0
34  02-19-2010       3.0      2.0       4.0       1      1        0
35  02-22-2010       3.0      0.0       6.0       1      1        0
36  02-23-2010       3.0      0.0       6.0       1      1        0
37  02-24-2010       1.0      0.0       8.0       1      1        0
38  02-25-2010       5.0      0.0       4.0       1      1        0
39  02-26-2010       4.0      1.0       4.0       1      1        0
40  03-01-2010       3.0      0.0       6.0       1      1        0
41  03-02-2010       3.0      0.0       6.0       1      1        0
42  03-03-2010       5.0      1.0       3.0       1      1        0
43  03-04-2010       4.0      0.0       5.0       1      1        0
44  03-05-2010       3.0      1.0       5.0       1      1        0
45  03-08-2010       4.0      0.0       5.0       1      1        0
46  03-09-2010       4.0      0.0       5.0       1      1        0
47  03-10-2010       4.0      0.0       5.0       1      1        0
48  03-11-2010       7.0      0.0       2.0       1      1        0
49  03-12-2010       5.0      1.0       3.0       1      1        0
50  03-15-2010       3.0      0.0       6.0       1      1        0
51  03-16-2010       6.0      1.0       1.0       1      1        0
52  03-17-2010       6.0      0.0       3.0       1      1        0
53  03-18-2010       3.0      0.0       6.0       1      1        0
54  03-19-2010       2.0      0.0       7.0       1      1        0
55  03-22-2010       6.0      0.0       3.0       1      1        0
56  03-23-2010       4.0      0.0       5.0       1      1        0
57  03-24-2010       3.0      0.0       6.0       1      1        0
58  03-25-2010       2.0      1.0       6.0       1      1        0
59  03-26-2010       8.0      0.0       1.0       1      1        0

    Disconnect user_name
0            0   CFW0264
1            0   CFW0264
2            0   CFW0264
3            0   CFW0264
4            0   CFW0264
5            0   CFW0264
6            0   CFW0264
7            0   CFW0264
8            0   CFW0264
9            0   CFW0264
10           0   CFW0264
11           0   CFW0264
12           0   CFW0264
13           0   CFW0264
14           0   CFW0264
15           0   CFW0264
16           0   CFW0264
17           0   CFW0264
18           0   CFW0264
19           0   CFW0264
20           0   CFW0264
21           0   CFW0264
22           0   CFW0264
23           0   CFW0264
24           0   CFW0264
25           0   CFW0264
26           0   CFW0264
27           0   CFW0264
28           0   CFW0264
29           0   CFW0264
30           0   CFW0264
31           0   CFW0264
32           0   CFW0264
33           0   CFW0264
34           0   CFW0264
35           0   CFW0264
36           0   CFW0264
37           0   CFW0264
38           0   CFW0264
39           0   CFW0264
40           0   CFW0264
41           0   CFW0264
42           0   CFW0264
43           0   CFW0264
44           0   CFW0264
45           0   CFW0264
46           0   CFW0264
47           0   CFW0264
48           0   CFW0264
49           0   CFW0264
50           0   CFW0264
51           0   CFW0264
52           0   CFW0264
53           0   CFW0264
54           0   CFW0264
55           0   CFW0264
56           0   CFW0264
57           0   CFW0264
58           0   CFW0264
59           0   CFW0264

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      1.0       5.0       1      1        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011      10.0      0.0       4.0       1      1        0
3    01-05-2010       8.0      1.0       6.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0       1      1        0
342  12-28-2010       7.0      1.0       7.0       1      1        0
343  12-29-2010       7.0      1.0       7.0       1      1        0
344  12-30-2010      11.0      0.0       4.0       1      1        0
345  11-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CGA0629
1             0   CGA0629
2             0   CGA0629
3             0   CGA0629
4             0   CGA0629
..          ...       ...
341           0   CGA0629
342           0   CGA0629
343           0   CGA0629
344           0   CGA0629
345           0   CGA0629

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       0.0       1      1      4.0
1    01-04-2010       0.0      0.0       1.0       1      2      3.0
2    01-04-2011       2.0      0.0       1.0       1      2      3.0
3    01-05-2010       2.0      0.0       0.0       1      2      3.0
4    01-05-2011       0.0      0.0       3.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      2      3.0
342  12-28-2010       2.0      0.0       1.0       1      1      3.0
343  12-29-2010       1.0      0.0       2.0       1      2      3.0
344  12-30-2010       0.0      0.0       3.0       1      2      3.0
345  12-07-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           4.0   CGB0637
1           3.0   CGB0637
2           3.0   CGB0637
3           3.0   CGB0637
4           3.0   CGB0637
..          ...       ...
341         3.0   CGB0637
342         3.0   CGB0637
343         3.0   CGB0637
344         3.0   CGB0637
345         2.0   CGB0637

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  03-09-2011       0.0      0.0       0.0       1      1        0
345  04-06-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CGF0337
1             0   CGF0337
2             0   CGF0337
3             0   CGF0337
4             0   CGF0337
..          ...       ...
341           0   CGF0337
342           0   CGF0337
343           0   CGF0337
344           0   CGF0337
345           0   CGF0337

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       9.0       1      1        0
1    01-04-2010       5.0      0.0       8.0       1      1        0
2    01-04-2011       7.0      0.0       7.0       1      1        0
3    01-05-2010       4.0      1.0       9.0       1      1        0
4    01-05-2011       4.0      1.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0      12.0       1      1        0
342  12-27-2010       1.0      0.0      13.0       1      1        0
343  12-28-2010       6.0      2.0       6.0       1      1        0
344  12-29-2010       4.0      0.0      10.0       1      1        0
345  12-30-2010       1.0      0.0      13.0       1      1        0

     Disconnect user_name
0             0   CHG0146
1             0   CHG0146
2             0   CHG0146
3             0   CHG0146
4             0   CHG0146
..          ...       ...
341           0   CHG0146
342           0   CHG0146
343           0   CHG0146
344           0   CHG0146
345           0   CHG0146

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2      0.0
1    01-04-2010       0.0      0.0       1.0       1      2      1.0
2    01-04-2011       1.0      0.0       0.0       1      2      0.0
3    01-05-2010       1.0      0.0       0.0       1      2      1.0
4    01-05-2011       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  07-19-2010       0.0      0.0       0.0       1      2      2.0
342  07-21-2010       0.0      0.0       0.0       1      2      2.0
343  10-08-2010       0.0      0.0       0.0       1      2      0.0
344  10-26-2010       0.0      0.0       0.0       1      2      0.0
345  11-05-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   CHM0821
1           1.0   CHM0821
2           0.0   CHM0821
3           1.0   CHM0821
4           0.0   CHM0821
..          ...       ...
341         2.0   CHM0821
342         2.0   CHM0821
343         0.0   CHM0821
344         0.0   CHM0821
345         0.0   CHM0821

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      1        0
2    01-04-2011       3.0      1.0       7.0       1      1        0
3    01-05-2010       4.0      0.0       7.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       5.0       1      1        0
342  12-27-2010       1.0      0.0      10.0       1      1        0
343  12-28-2010       3.0      0.0       8.0       1      1        0
344  12-29-2010       3.0      0.0       8.0       1      1        0
345  12-30-2010       2.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   CIG0052
1             0   CIG0052
2             0   CIG0052
3             0   CIG0052
4             0   CIG0052
..          ...       ...
341           0   CIG0052
342           0   CIG0052
343           0   CIG0052
344           0   CIG0052
345           0   CIG0052

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       5.0       1      2      2.0
1    01-04-2010       5.0      0.0       4.0       1      2      2.0
2    01-04-2011       4.0      2.0       3.0       1      2      3.0
3    01-05-2010       6.0      0.0       3.0       1      2      2.0
4    01-05-2011       3.0      0.0       6.0       1      2      4.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       5.0       1      2      4.0
342  12-29-2010       2.0      1.0       6.0       1      2      1.0
343  12-30-2010       4.0      0.0       5.0       1      2      1.0
344  05-11-2010       0.0      0.0       0.0       1      2      1.0
345  08-17-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           2.0   CIM0271
1           2.0   CIM0271
2           3.0   CIM0271
3           2.0   CIM0271
4           4.0   CIM0271
..          ...       ...
341         4.0   CIM0271
342         1.0   CIM0271
343         1.0   CIM0271
344         1.0   CIM0271
345         2.0   CIM0271

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       5.0       1      1        0
1    01-05-2010       7.0      0.0       2.0       1      1        0
2    01-06-2010       0.0      0.0       9.0       1      1        0
3    01-07-2010       4.0      1.0       4.0       1      1        0
4    01-08-2010       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
224  11-19-2010       0.0      2.0       7.0       1      1        0
225  11-22-2010       4.0      0.0       5.0       1      1        0
226  11-23-2010       1.0      0.0       8.0       1      1        0
227  11-24-2010       4.0      0.0       5.0       1      1        0
228  10-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CIM0926
1             0   CIM0926
2             0   CIM0926
3             0   CIM0926
4             0   CIM0926
..          ...       ...
224           0   CIM0926
225           0   CIM0926
226           0   CIM0926
227           0   CIM0926
228           0   CIM0926

[229 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      2.0       5.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011       8.0      0.0       7.0       1      1        0
3    01-05-2010      11.0      1.0       3.0       1      1        0
4    01-05-2011       7.0      2.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       8.0       1      1        0
342  12-28-2010       7.0      2.0       6.0       1      1        0
343  12-29-2010       9.0      1.0       5.0       1      1        0
344  12-30-2010      11.0      0.0       4.0       1      1        0
345  08-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJC0494
1             0   CJC0494
2             0   CJC0494
3             0   CJC0494
4             0   CJC0494
..          ...       ...
341           0   CJC0494
342           0   CJC0494
343           0   CJC0494
344           0   CJC0494
345           0   CJC0494

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0     1.0    3.0        0
1    01-04-2010       3.0      0.0       6.0     1.0    2.0        0
2    01-04-2011       4.0      4.0       1.0     2.0    2.0        0
3    01-05-2010       5.0      1.0       3.0     1.0    2.0        0
4    01-05-2011       2.0      1.0       6.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
347  02-26-2011       0.0      0.0       0.0     1.0    0.0        0
348  05-08-2010       0.0      0.0       0.0     1.0    1.0        0
349  05-17-2010       0.0      0.0       0.0     1.0    2.0        0
350  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
351  08-21-2010       0.0      0.0       0.0     1.0    0.0        0

     Disconnect user_name
0             0   CJF0802
1             0   CJF0802
2             0   CJF0802
3             0   CJF0802
4             0   CJF0802
..          ...       ...
347           0   CJF0802
348           0   CJF0802
349           0   CJF0802
350           0   CJF0802
351           0   CJF0802

[352 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-01-2011       0.0      0.0       0.0       1      1        0
342  04-11-2011       0.0      0.0       0.0       1      1        0
343  05-25-2010       0.0      0.0       0.0       1      1        0
344  08-23-2010       0.0      0.0       0.0       1      1        0
345  11-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJG0470
1             0   CJG0470
2             0   CJG0470
3             0   CJG0470
4             0   CJG0470
..          ...       ...
341           0   CJG0470
342           0   CJG0470
343           0   CJG0470
344           0   CJG0470
345           0   CJG0470

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-01-2010       0.0      0.0       0.0       1      1        0
342  04-25-2011       0.0      0.0       0.0       1      1        0
343  06-08-2010       0.0      0.0       0.0       1      1        0
344  07-15-2010       0.0      0.0       0.0       1      1        0
345  08-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJH0702
1             0   CJH0702
2             0   CJH0702
3             0   CJH0702
4             0   CJH0702
..          ...       ...
341           0   CJH0702
342           0   CJH0702
343           0   CJH0702
344           0   CJH0702
345           0   CJH0702

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       6.0       1      1        0
1    01-04-2010       5.0      0.0       6.0       1      1        0
2    01-04-2011       6.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       8.0       1      1        0
4    01-05-2011       4.0      2.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       2.0       1      1        0
342  12-28-2010       7.0      0.0       2.0       1      1        0
343  12-29-2010       6.0      0.0       5.0       1      1        0
344  12-30-2010       5.0      1.0       5.0       1      1        0
345  02-23-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJK0200
1             0   CJK0200
2             0   CJK0200
3             0   CJK0200
4             0   CJK0200
..          ...       ...
341           0   CJK0200
342           0   CJK0200
343           0   CJK0200
344           0   CJK0200
345           0   CJK0200

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-30-2010       0.0      0.0       0.0       1      1        0
342  10-21-2010       0.0      0.0       0.0       1      1        0
343  12-13-2010       0.0      0.0       0.0       1      1        0
344  12-17-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJM0138
1             0   CJM0138
2             0   CJM0138
3             0   CJM0138
4             0   CJM0138
..          ...       ...
341           0   CJM0138
342           0   CJM0138
343           0   CJM0138
344           0   CJM0138
345           0   CJM0138

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       1      1        0
1    01-02-2010       2.0      0.0       1.0       1      1        0
2    01-03-2010       2.0      0.0       0.0       1      1        0
3    01-03-2011       0.0      1.0       2.0       1      1        0
4    01-04-2010       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
459  05-07-2010       0.0      0.0       0.0       1      1        0
460  08-02-2010       0.0      0.0       0.0       1      1        0
461  08-13-2010       0.0      0.0       0.0       1      1        0
462  11-01-2010       0.0      0.0       0.0       1      1        0
463  11-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CJM0521
1             0   CJM0521
2             0   CJM0521
3             0   CJM0521
4             0   CJM0521
..          ...       ...
459           0   CJM0521
460           0   CJM0521
461           0   CJM0521
462           0   CJM0521
463           0   CJM0521

[464 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0     2.0    3.0        0
1    01-04-2010       1.0      0.0       0.0     1.0    1.0        0
2    01-04-2011       1.0      0.0       0.0     1.0    2.0        0
3    01-05-2010       0.0      0.0       1.0     1.0    2.0        0
4    01-05-2011       1.0      0.0       0.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
343  09-03-2010       0.0      0.0       0.0     1.0    2.0        0
344  09-15-2010       0.0      0.0       0.0     1.0    2.0        0
345  11-06-2010       0.0      0.0       0.0     1.0    0.0        0
346  11-24-2010       0.0      0.0       0.0     1.0    2.0        0
347  12-29-2010       0.0      0.0       0.0     1.0    2.0        0

     Disconnect user_name
0             0   CJP0952
1             0   CJP0952
2             0   CJP0952
3             0   CJP0952
4             0   CJP0952
..          ...       ...
343           0   CJP0952
344           0   CJP0952
345           0   CJP0952
346           0   CJP0952
347           0   CJP0952

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       0.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-22-2010       0.0      0.0       0.0       1      1        0
342  01-28-2010       0.0      0.0       0.0       1      1        0
343  03-16-2011       0.0      0.0       0.0       1      2        0
344  06-08-2010       0.0      0.0       0.0       1      2        0
345  12-20-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   CJV0286
1             0   CJV0286
2             0   CJV0286
3             0   CJV0286
4             0   CJV0286
..          ...       ...
341           0   CJV0286
342           0   CJV0286
343           0   CJV0286
344           0   CJV0286
345           0   CJV0286

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       5.0       1      1        0
342  12-29-2010       4.0      1.0       4.0       1      1        0
343  12-30-2010       4.0      0.0       1.0       1      1        0
344  03-15-2011       0.0      0.0       0.0       1      1        0
345  04-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CKB0427
1             0   CKB0427
2             0   CKB0427
3             0   CKB0427
4             0   CKB0427
..          ...       ...
341           0   CKB0427
342           0   CKB0427
343           0   CKB0427
344           0   CKB0427
345           0   CKB0427

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       7.0       1      1        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011       8.0      0.0       7.0       1      1        0
3    01-05-2010       9.0      1.0       5.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       9.0       1      1        0
342  12-28-2010       9.0      1.0       5.0       1      1        0
343  12-29-2010       6.0      2.0       7.0       1      1        0
344  12-30-2010       3.0      0.0      12.0       1      1        0
345  06-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CKB0482
1             0   CKB0482
2             0   CKB0482
3             0   CKB0482
4             0   CKB0482
..          ...       ...
341           0   CKB0482
342           0   CKB0482
343           0   CKB0482
344           0   CKB0482
345           0   CKB0482

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       5.0       1      1        0
342  12-27-2010       2.0      0.0       7.0       1      1        0
343  12-28-2010       4.0      0.0       5.0       1      1        0
344  12-29-2010       2.0      1.0       6.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   CKD0680
1             0   CKD0680
2             0   CKD0680
3             0   CKD0680
4             0   CKD0680
..          ...       ...
341           0   CKD0680
342           0   CKD0680
343           0   CKD0680
344           0   CKD0680
345           0   CKD0680

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       6.0      1.0       2.0       1      1        0
3    01-05-2010       8.0      0.0       1.0       1      1        0
4    01-05-2011       7.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       7.0       1      1        0
342  12-28-2010       2.0      1.0       6.0       1      1        0
343  12-29-2010       4.0      1.0       4.0       1      1        0
344  12-30-2010       6.0      1.0       2.0       1      1        0
345  02-01-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CKH0144
1             0   CKH0144
2             0   CKH0144
3             0   CKH0144
4             0   CKH0144
..          ...       ...
341           0   CKH0144
342           0   CKH0144
343           0   CKH0144
344           0   CKH0144
345           0   CKH0144

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-13-2010       0.0      0.0       0.0       1      1        0
342  09-23-2010       0.0      0.0       0.0       1      1        0
343  09-28-2010       0.0      0.0       0.0       1      1        0
344  10-11-2010       0.0      0.0       0.0       1      1        0
345  11-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CKP0721
1             0   CKP0721
2             0   CKP0721
3             0   CKP0721
4             0   CKP0721
..          ...       ...
341           0   CKP0721
342           0   CKP0721
343           0   CKP0721
344           0   CKP0721
345           0   CKP0721

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0     1.0    1.0      9.0
1    01-04-2010       1.0      0.0       2.0     1.0    1.0      8.0
2    01-04-2011       3.0      0.0       0.0     1.0    1.0      8.0
3    01-05-2010       2.0      0.0       1.0     1.0    1.0      9.0
4    01-05-2011       2.0      1.0       0.0     1.0    1.0      8.0
..          ...       ...      ...       ...     ...    ...      ...
352  09-27-2010       0.0      0.0       0.0     1.0    1.0      8.0
353  10-07-2010       0.0      0.0       0.0     1.0    1.0      9.0
354  11-13-2010       0.0      0.0       0.0     1.0    0.0      0.0
355  11-25-2010       0.0      0.0       0.0     1.0    0.0      0.0
356  12-04-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           9.0   CLB0774
1           8.0   CLB0774
2           8.0   CLB0774
3           9.0   CLB0774
4           8.0   CLB0774
..          ...       ...
352         8.0   CLB0774
353         9.0   CLB0774
354         0.0   CLB0774
355         0.0   CLB0774
356         0.0   CLB0774

[357 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      1.0       2.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  08-23-2010       0.0      0.0       0.0       1      1        0
345  10-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CLD0894
1             0   CLD0894
2             0   CLD0894
3             0   CLD0894
4             0   CLD0894
..          ...       ...
341           0   CLD0894
342           0   CLD0894
343           0   CLD0894
344           0   CLD0894
345           0   CLD0894

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      2        0
1    01-04-2010       7.0      0.0       7.0       2      3        0
2    01-04-2011       9.0      0.0       5.0       1      2        0
3    01-05-2010       9.0      0.0       6.0       1      2        0
4    01-05-2011       6.0      0.0       9.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0      10.0       1      2        0
342  12-27-2010      11.0      1.0       3.0       1      2        0
343  12-28-2010       5.0      1.0       9.0       2      2        0
344  12-29-2010       6.0      2.0       7.0       1      2        0
345  12-30-2010       5.0      1.0       9.0       1      2        0

     Disconnect user_name
0             0   CLF0852
1             0   CLF0852
2             0   CLF0852
3             0   CLF0852
4             0   CLF0852
..          ...       ...
341           0   CLF0852
342           0   CLF0852
343           0   CLF0852
344           0   CLF0852
345           0   CLF0852

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2011       0.0      1.0       0.0       1      1        0
2    01-05-2010       1.0      0.0       0.0       1      1        0
3    01-06-2010       1.0      0.0       0.0       1      1        0
4    01-06-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-16-2010       0.0      0.0       0.0       1      1        0
342  09-14-2010       0.0      0.0       0.0       1      1        0
343  10-22-2010       0.0      0.0       0.0       1      1        0
344  12-06-2010       0.0      0.0       0.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CLH0703
1             0   CLH0703
2             0   CLH0703
3             0   CLH0703
4             0   CLH0703
..          ...       ...
341           0   CLH0703
342           0   CLH0703
343           0   CLH0703
344           0   CLH0703
345           0   CLH0703

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-29-2010       0.0      0.0       0.0       1      1        0
342  08-13-2010       0.0      0.0       0.0       1      1        0
343  09-28-2010       0.0      0.0       0.0       1      1        0
344  10-26-2010       0.0      0.0       0.0       1      1        0
345  11-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CLS0296
1             0   CLS0296
2             0   CLS0296
3             0   CLS0296
4             0   CLS0296
..          ...       ...
341           0   CLS0296
342           0   CLS0296
343           0   CLS0296
344           0   CLS0296
345           0   CLS0296

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       8.0      0.0       6.0       1      2        0
1    01-03-2011       6.0      0.0       8.0       1      2        0
2    01-04-2010       2.0      1.0      11.0       1      2        0
3    01-04-2011       7.0      1.0       6.0       1      1        0
4    01-05-2010       5.0      0.0       9.0       3      3        0
..          ...       ...      ...       ...     ...    ...      ...
418  12-24-2010       3.0      0.0      11.0       1      2        0
419  12-27-2010       4.0      0.0      10.0       1      2        0
420  12-28-2010       7.0      0.0       7.0       2      3        0
421  12-29-2010       8.0      2.0       4.0       1      1        0
422  12-30-2010       1.0      1.0      12.0       1      2        0

     Disconnect user_name
0             0   CMB0912
1             0   CMB0912
2             0   CMB0912
3             0   CMB0912
4             0   CMB0912
..          ...       ...
418           0   CMB0912
419           0   CMB0912
420           0   CMB0912
421           0   CMB0912
422           0   CMB0912

[423 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0      10.0       1      1        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011       1.0      1.0       2.0       1      1        0
3    01-05-2010       5.0      1.0       9.0       1      1        0
4    01-05-2011       7.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      3.0       5.0       1      1        0
342  12-28-2010       8.0      1.0       6.0       1      1        0
343  12-29-2010       8.0      0.0       7.0       1      1        0
344  12-30-2010       7.0      0.0       8.0       1      1        0
345  05-13-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CMM0487
1             0   CMM0487
2             0   CMM0487
3             0   CMM0487
4             0   CMM0487
..          ...       ...
341           0   CMM0487
342           0   CMM0487
343           0   CMM0487
344           0   CMM0487
345           0   CMM0487

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-19-2010       0.0      0.0       0.0       1      1        0
342  08-20-2010       0.0      0.0       0.0       1      1        0
343  11-08-2010       0.0      0.0       0.0       1      1        0
344  11-10-2010       0.0      0.0       0.0       1      1        0
345  12-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CMS0454
1             0   CMS0454
2             0   CMS0454
3             0   CMS0454
4             0   CMS0454
..          ...       ...
341           0   CMS0454
342           0   CMS0454
343           0   CMS0454
344           0   CMS0454
345           0   CMS0454

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       1.0       1      1        0
342  01-26-2010       0.0      0.0       0.0       1      1        0
343  03-11-2010       0.0      0.0       0.0       1      1        0
344  06-17-2010       0.0      0.0       0.0       1      1        0
345  07-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CMW0783
1             0   CMW0783
2             0   CMW0783
3             0   CMW0783
4             0   CMW0783
..          ...       ...
341           0   CMW0783
342           0   CMW0783
343           0   CMW0783
344           0   CMW0783
345           0   CMW0783

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       1.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  03-10-2011       0.0      0.0       0.0       1      1        0
345  09-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CNB0900
1             0   CNB0900
2             0   CNB0900
3             0   CNB0900
4             0   CNB0900
..          ...       ...
341           0   CNB0900
342           0   CNB0900
343           0   CNB0900
344           0   CNB0900
345           0   CNB0900

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      3.0       5.0       1      1        0
1    01-04-2010       5.0      1.0      12.0       1      1        0
2    01-04-2011       9.0      0.0       9.0       1      1        0
3    01-05-2010      12.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      1.0      14.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      12.0      0.0       6.0       1      1        0
342  12-27-2010       6.0      0.0      12.0       1      1        0
343  12-28-2010       6.0      0.0      12.0       1      1        0
344  12-29-2010       2.0      1.0      15.0       1      1        0
345  12-30-2010       8.0      1.0       9.0       1      1        0

     Disconnect user_name
0             0   CNE0352
1             0   CNE0352
2             0   CNE0352
3             0   CNE0352
4             0   CNE0352
..          ...       ...
341           0   CNE0352
342           0   CNE0352
343           0   CNE0352
344           0   CNE0352
345           0   CNE0352

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       3.0       1      1        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       3.0      1.0       5.0       1      1        0
344  12-30-2010       4.0      1.0       4.0       1      1        0
345  09-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CNM0800
1             0   CNM0800
2             0   CNM0800
3             0   CNM0800
4             0   CNM0800
..          ...       ...
341           0   CNM0800
342           0   CNM0800
343           0   CNM0800
344           0   CNM0800
345           0   CNM0800

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      9.0       1.0       1      1        0
1    01-04-2010       1.0      5.0       4.0       1      1        0
2    01-04-2011       2.0      7.0       1.0       1      1        0
3    01-05-2010       5.0      2.0       3.0       1      1        0
4    01-05-2011       2.0      4.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
261  01-08-2011       0.0      0.0       0.0       1      1        0
262  03-06-2010       0.0      0.0       0.0       1      1        0
263  03-20-2010       0.0      0.0       0.0       1      1        0
264  05-01-2010       0.0      0.0       0.0       1      1        0
265  11-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   COF0120
1             0   COF0120
2             0   COF0120
3             0   COF0120
4             0   COF0120
..          ...       ...
261           0   COF0120
262           0   COF0120
263           0   COF0120
264           0   COF0120
265           0   COF0120

[266 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0      11.0       1      1        0
1    01-04-2010       5.0      0.0      10.0       1      1        0
2    01-04-2011       6.0      1.0       8.0       1      1        0
3    01-05-2010       9.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       7.0       1      1        0
342  12-27-2010       3.0      1.0      11.0       1      1        0
343  12-28-2010       7.0      0.0       8.0       1      1        0
344  12-29-2010       4.0      0.0       4.0       1      1        0
345  12-30-2010       8.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   COM0321
1             0   COM0321
2             0   COM0321
3             0   COM0321
4             0   COM0321
..          ...       ...
341           0   COM0321
342           0   COM0321
343           0   COM0321
344           0   COM0321
345           0   COM0321

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      3.0       7.0       2      2      2.0
1    01-04-2010       6.0      0.0       9.0       2      2      0.0
2    01-04-2011       7.0      1.0       7.0       1      1      0.0
3    01-05-2010       5.0      1.0       8.0       1      1      0.0
4    01-05-2011       6.0      3.0       6.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       7.0       1      1      0.0
342  12-27-2010       3.0      1.0      11.0       1      1      1.0
343  12-28-2010       3.0      1.0       9.0       2      2      1.0
344  12-29-2010       8.0      0.0       7.0       1      1      0.0
345  12-30-2010       7.0      1.0       7.0       1      1      0.0

     Disconnect user_name
0           2.0   CPG0322
1           0.0   CPG0322
2           0.0   CPG0322
3           0.0   CPG0322
4           0.0   CPG0322
..          ...       ...
341         0.0   CPG0322
342         1.0   CPG0322
343         1.0   CPG0322
344         0.0   CPG0322
345         0.0   CPG0322

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1      1.0
1    01-04-2011       0.0      0.0       1.0       1      2      0.0
2    01-05-2010       0.0      1.0       0.0       1      2      1.0
3    01-05-2011       1.0      0.0       0.0       1      2      0.0
4    01-06-2010       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  04-11-2011       0.0      0.0       0.0       1      2      0.0
342  04-29-2010       0.0      0.0       0.0       1      2      0.0
343  09-16-2010       0.0      0.0       0.0       1      2      0.0
344  11-18-2010       0.0      0.0       0.0       1      1      1.0
345  11-22-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   CQH0701
1           0.0   CQH0701
2           1.0   CQH0701
3           0.0   CQH0701
4           0.0   CQH0701
..          ...       ...
341         0.0   CQH0701
342         0.0   CQH0701
343         0.0   CQH0701
344         1.0   CQH0701
345         0.0   CQH0701

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      7.0       4.0       1      1        0
1    01-04-2010       4.0      7.0       3.0       1      1        0
2    01-04-2011       7.0      2.0       5.0       1      1        0
3    01-05-2010       4.0      2.0       9.0       1      1        0
4    01-05-2011       3.0      3.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      9.0       2.0       1      1        0
342  12-28-2010       0.0     14.0       1.0       1      1        0
343  12-29-2010       3.0      1.0      11.0       1      1        0
344  12-30-2010       1.0     10.0       4.0       1      1        0
345  12-03-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CQH0730
1             0   CQH0730
2             0   CQH0730
3             0   CQH0730
4             0   CQH0730
..          ...       ...
341           0   CQH0730
342           0   CQH0730
343           0   CQH0730
344           0   CQH0730
345           0   CQH0730

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1      2.0
1    01-04-2010       0.0      1.0       2.0       1      1      0.0
2    01-04-2011       1.0      0.0       1.0       1      1      3.0
3    01-05-2010       0.0      0.0       3.0       1      1      1.0
4    01-05-2011       1.0      0.0       2.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
322  12-27-2010       1.0      0.0       2.0       1      1      0.0
323  12-28-2010       1.0      0.0       2.0       1      1      3.0
324  12-29-2010       0.0      0.0       3.0       1      1      2.0
325  12-30-2010       2.0      0.0       1.0       1      1      1.0
326  08-20-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           2.0   CQW0652
1           0.0   CQW0652
2           3.0   CQW0652
3           1.0   CQW0652
4           2.0   CQW0652
..          ...       ...
322         0.0   CQW0652
323         3.0   CQW0652
324         2.0   CQW0652
325         1.0   CQW0652
326         1.0   CQW0652

[327 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       9.0      1.0       5.0       1      1        0
1   01-05-2010      10.0      0.0       3.0       1      1        0
2   01-06-2010      10.0      0.0       5.0       1      1        0
3   01-07-2010       7.0      0.0       8.0       2      2        0
4   01-08-2010       8.0      1.0       6.0       1      1        0
5   01-11-2010       5.0      0.0      10.0       1      1        0
6   01-12-2010       5.0      2.0       7.0       1      1        0
7   01-13-2010       7.0      0.0       8.0       1      1        0
8   01-14-2010       8.0      2.0       5.0       1      1        0
9   01-15-2010       9.0      1.0       5.0       1      1        0
10  01-18-2010       8.0      0.0       6.0       1      1        0
11  01-19-2010       7.0      0.0       8.0       1      1        0
12  01-20-2010       7.0      1.0       7.0       1      1        0
13  01-21-2010       7.0      0.0       8.0       1      1        0
14  01-22-2010       7.0      0.0       5.0       1      1        0
15  01-25-2010       7.0      1.0       7.0       1      1        0
16  01-26-2010       7.0      1.0       4.0       1      1        0
17  01-27-2010       8.0      2.0       5.0       1      1        0
18  01-28-2010       3.0      0.0      12.0       1      1        0
19  01-29-2010       8.0      1.0       6.0       1      1        0
20  02-01-2010       8.0      3.0       4.0       1      1        0
21  02-02-2010       8.0      0.0       7.0       1      1        0
22  02-03-2010       3.0      0.0      10.0       1      1        0
23  02-04-2010       6.0      1.0       7.0       1      1        0
24  02-05-2010       4.0      1.0       0.0       1      1        0
25  02-08-2010       9.0      1.0       5.0       1      2        0
26  02-09-2010       6.0      1.0       8.0       2      1        0
27  02-10-2010       3.0      0.0      12.0       1      1        0
28  02-11-2010      10.0      0.0       2.0       1      1        0
29  02-12-2010       1.0      0.0      14.0       1      1        0
30  02-15-2010       8.0      0.0       7.0       1      2        0
31  02-16-2010       6.0      0.0       9.0       2      1        0
32  02-17-2010       4.0      1.0      10.0       1      1        0
33  02-18-2010       6.0      0.0       9.0       1      1        0
34  02-19-2010       5.0      1.0       9.0       1      1        0
35  02-22-2010       7.0      1.0       7.0       1      1        0
36  02-23-2010       8.0      0.0       7.0       1      2        0
37  02-24-2010      11.0      1.0       3.0       2      1        0
38  02-25-2010       7.0      0.0       7.0       1      1        0
39  02-26-2010       2.0      0.0       3.0       1      1        0
40  03-01-2010       7.0      0.0       8.0       2      2        0
41  03-02-2010       6.0      0.0       9.0       1      1        0
42  03-03-2010      12.0      0.0       3.0       1      1        0
43  03-04-2010       9.0      1.0       5.0       1      1        0
44  03-05-2010       6.0      1.0       8.0       1      1        0

    Disconnect user_name
0            0   CRD0624
1            0   CRD0624
2            0   CRD0624
3            0   CRD0624
4            0   CRD0624
5            0   CRD0624
6            0   CRD0624
7            0   CRD0624
8            0   CRD0624
9            0   CRD0624
10           0   CRD0624
11           0   CRD0624
12           0   CRD0624
13           0   CRD0624
14           0   CRD0624
15           0   CRD0624
16           0   CRD0624
17           0   CRD0624
18           0   CRD0624
19           0   CRD0624
20           0   CRD0624
21           0   CRD0624
22           0   CRD0624
23           0   CRD0624
24           0   CRD0624
25           0   CRD0624
26           0   CRD0624
27           0   CRD0624
28           0   CRD0624
29           0   CRD0624
30           0   CRD0624
31           0   CRD0624
32           0   CRD0624
33           0   CRD0624
34           0   CRD0624
35           0   CRD0624
36           0   CRD0624
37           0   CRD0624
38           0   CRD0624
39           0   CRD0624
40           0   CRD0624
41           0   CRD0624
42           0   CRD0624
43           0   CRD0624
44           0   CRD0624

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       7.0     1.0    1.0        0
1    01-04-2010       4.0      1.0       5.0     1.0    1.0        0
2    01-04-2011       6.0      0.0       4.0     1.0    2.0        0
3    01-05-2010       5.0      0.0       5.0     1.0    2.0        0
4    01-05-2011       5.0      0.0       5.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
346  03-06-2010       0.0      0.0       0.0     1.0    1.0        0
347  05-08-2010       0.0      0.0       0.0     1.0    1.0        0
348  05-10-2011       0.0      0.0       0.0     1.0    1.0        0
349  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
350  10-02-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   CRK0916
1             0   CRK0916
2             0   CRK0916
3             0   CRK0916
4             0   CRK0916
..          ...       ...
346           0   CRK0916
347           0   CRK0916
348           0   CRK0916
349           0   CRK0916
350           0   CRK0916

[351 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       2      2        0
1    01-04-2010       2.0      0.0       7.0       1      2        0
2    01-04-2011       1.0      0.0       8.0       1      2        0
3    01-05-2010       5.0      0.0       4.0       1      2        0
4    01-05-2011       4.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
343  12-29-2010       6.0      0.0       3.0       1      2        0
344  12-30-2010       1.0      0.0       8.0       1      2        0
345  03-16-2011       0.0      0.0       0.0       1      2        0
346  05-14-2011       0.0      0.0       0.0       1      1        0
347  08-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CRO0027
1             0   CRO0027
2             0   CRO0027
3             0   CRO0027
4             0   CRO0027
..          ...       ...
343           0   CRO0027
344           0   CRO0027
345           0   CRO0027
346           0   CRO0027
347           0   CRO0027

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-15-2010       0.0      0.0       0.0       1      1        0
342  06-04-2010       0.0      0.0       0.0       1      1        0
343  09-28-2010       0.0      0.0       0.0       1      1        0
344  10-11-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CRP0456
1             0   CRP0456
2             0   CRP0456
3             0   CRP0456
4             0   CRP0456
..          ...       ...
341           0   CRP0456
342           0   CRP0456
343           0   CRP0456
344           0   CRP0456
345           0   CRP0456

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      1.0       6.0       1      1        0
3    01-05-2010       5.0      1.0       5.0       1      1        0
4    01-05-2011       5.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      2.0       6.0       1      1        0
342  12-27-2010       6.0      0.0       4.0       1      1        0
343  12-28-2010       6.0      0.0       5.0       1      1        0
344  12-29-2010       6.0      0.0       5.0       1      1        0
345  12-30-2010       6.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   CSB0080
1             0   CSB0080
2             0   CSB0080
3             0   CSB0080
4             0   CSB0080
..          ...       ...
341           0   CSB0080
342           0   CSB0080
343           0   CSB0080
344           0   CSB0080
345           0   CSB0080

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0       1.0       5      5      0.0
1    01-05-2010       4.0      0.0       6.0       4      4      0.0
2    01-06-2010       3.0      0.0       8.0       2      2      0.0
3    01-07-2010       4.0      0.0       7.0       6      6      0.0
4    01-08-2010       3.0      0.0       8.0       5      5      0.0
..          ...       ...      ...       ...     ...    ...      ...
108  06-09-2010       6.0      0.0       5.0       2      2      0.0
109  06-10-2010       5.0      1.0       7.0       8      8      2.0
110  06-11-2010       6.0      0.0       5.0       7      7      0.0
111  04-13-2010       0.0      0.0       0.0       3      3      0.0
112  06-08-2010       0.0      0.0       0.0       6      6      0.0

     Disconnect user_name
0           0.0   CSC0217
1           0.0   CSC0217
2           0.0   CSC0217
3           0.0   CSC0217
4           0.0   CSC0217
..          ...       ...
108         0.0   CSC0217
109         2.0   CSC0217
110         0.0   CSC0217
111         0.0   CSC0217
112         0.0   CSC0217

[113 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       4.0      1.0       9.0     1.0    2.0        0
1    01-02-2011       9.0      1.0       4.0     1.0    2.0        0
2    01-03-2011       8.0      1.0       5.0     2.0    2.0        0
3    01-04-2010       9.0      0.0       5.0     1.0    1.0        0
4    01-04-2011       8.0      1.0       5.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
399  05-14-2011       0.0      0.0       0.0     1.0    0.0        0
400  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
401  10-09-2010       0.0      0.0       0.0     1.0    1.0        0
402  10-30-2010       0.0      0.0       0.0     1.0    1.0        0
403  11-02-2010       0.0      0.0       0.0     1.0    2.0        0

     Disconnect user_name
0             0   CSH0626
1             0   CSH0626
2             0   CSH0626
3             0   CSH0626
4             0   CSH0626
..          ...       ...
399           0   CSH0626
400           0   CSH0626
401           0   CSH0626
402           0   CSH0626
403           0   CSH0626

[404 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      2.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       3.0      0.0       0.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  02-09-2010       0.0      0.0       0.0       1      1        0
345  03-29-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CSJ0340
1             0   CSJ0340
2             0   CSJ0340
3             0   CSJ0340
4             0   CSJ0340
..          ...       ...
341           0   CSJ0340
342           0   CSJ0340
343           0   CSJ0340
344           0   CSJ0340
345           0   CSJ0340

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-15-2011       0.0      0.0       0.0       1      1        0
342  06-24-2010       0.0      0.0       0.0       1      1        0
343  07-16-2010       0.0      0.0       0.0       1      1        0
344  09-10-2010       0.0      0.0       0.0       1      1        0
345  10-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CSL0949
1             0   CSL0949
2             0   CSL0949
3             0   CSL0949
4             0   CSL0949
..          ...       ...
341           0   CSL0949
342           0   CSL0949
343           0   CSL0949
344           0   CSL0949
345           0   CSL0949

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      3.0       5.0       2      3        0
1    01-04-2010       1.0      7.0       3.0       2      3        0
2    01-04-2011       2.0      5.0       2.0       1      2        0
3    01-05-2010       3.0      3.0       3.0       1      2        0
4    01-05-2011       4.0      3.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       4.0       1      2        0
342  12-27-2010       5.0      1.0       5.0       1      2        0
343  12-28-2010       5.0      2.0       4.0       2      3        0
344  12-29-2010       6.0      1.0       4.0       1      2        0
345  12-30-2010       5.0      0.0       6.0       1      2        0

     Disconnect user_name
0             0   CSP0197
1             0   CSP0197
2             0   CSP0197
3             0   CSP0197
4             0   CSP0197
..          ...       ...
341           0   CSP0197
342           0   CSP0197
343           0   CSP0197
344           0   CSP0197
345           0   CSP0197

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       1      2        9
1    01-04-2010       4.0      1.0       6.0       1      1        8
2    01-04-2011       5.0      1.0       5.0       1      2        9
3    01-05-2010       4.0      0.0       7.0       1      2        7
4    01-05-2011       6.0      0.0       5.0       1      2        8
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       7.0       1      2        9
342  12-28-2010       4.0      0.0       7.0       1      2        9
343  12-29-2010       1.0      0.0      10.0       1      2        9
344  12-30-2010       5.0      0.0       6.0       1      2        8
345  02-07-2011       0.0      0.0       0.0       1      1        9

     Disconnect user_name
0             9   CTA0020
1             8   CTA0020
2             9   CTA0020
3             7   CTA0020
4             8   CTA0020
..          ...       ...
341           9   CTA0020
342           9   CTA0020
343           9   CTA0020
344           8   CTA0020
345           9   CTA0020

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       1.0      0.0       2.0       1      2        0
1    01-02-2010       1.0      0.0       2.0       1      2        0
2    01-02-2011       2.0      0.0       1.0       1      2        0
3    01-03-2010       1.0      0.0       2.0       1      2        0
4    01-03-2011       2.0      0.0       1.0       2      3        0
..          ...       ...      ...       ...     ...    ...      ...
486  03-21-2010       0.0      0.0       0.0       1      2        0
487  05-02-2010       0.0      0.0       0.0       2      2        0
488  08-12-2010       0.0      0.0       0.0       1      2        0
489  08-21-2010       0.0      0.0       0.0       2      2        0
490  12-03-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   CTR0341
1             0   CTR0341
2             0   CTR0341
3             0   CTR0341
4             0   CTR0341
..          ...       ...
486           0   CTR0341
487           0   CTR0341
488           0   CTR0341
489           0   CTR0341
490           0   CTR0341

[491 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        0
1    01-04-2010       1.0      0.0       0.0       1      2        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-14-2010       0.0      0.0       0.0       1      2        0
342  09-17-2010       0.0      0.0       0.0       1      2        0
343  10-14-2010       0.0      0.0       0.0       1      2        0
344  10-19-2010       0.0      0.0       0.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   CTR0697
1             0   CTR0697
2             0   CTR0697
3             0   CTR0697
4             0   CTR0697
..          ...       ...
341           0   CTR0697
342           0   CTR0697
343           0   CTR0697
344           0   CTR0697
345           0   CTR0697

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0      10.0       1      1        0
1    01-04-2010       6.0      0.0       9.0       1      1        0
2    01-04-2011       5.0      1.0       9.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0       1      1        0
342  12-28-2010       5.0      2.0       6.0       1      1        0
343  12-29-2010       5.0      0.0      10.0       1      1        0
344  12-30-2010       2.0      2.0      11.0       1      1        0
345  05-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CTW0500
1             0   CTW0500
2             0   CTW0500
3             0   CTW0500
4             0   CTW0500
..          ...       ...
341           0   CTW0500
342           0   CTW0500
343           0   CTW0500
344           0   CTW0500
345           0   CTW0500

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       2.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       7.0       1      1        0
342  12-27-2010       3.0      0.0       6.0       1      1        0
343  12-28-2010       6.0      0.0       3.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   CUD0795
1             0   CUD0795
2             0   CUD0795
3             0   CUD0795
4             0   CUD0795
..          ...       ...
341           0   CUD0795
342           0   CUD0795
343           0   CUD0795
344           0   CUD0795
345           0   CUD0795

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      2.0       4.0       1      2        0
1    01-04-2010       5.0      1.0       3.0       2      2        0
2    01-04-2011       4.0      1.0       4.0       1      2        0
3    01-05-2010       3.0      2.0       4.0       1      2        0
4    01-05-2011       2.0      0.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       7.0       1      2        0
342  12-28-2010       5.0      1.0       3.0       2      3        0
343  12-29-2010       1.0      0.0       2.0       1      2        0
344  12-30-2010       4.0      0.0       5.0       1      2        0
345  05-05-2011       0.0      0.0       0.0       2      2        0

     Disconnect user_name
0             0   CWB0065
1             0   CWB0065
2             0   CWB0065
3             0   CWB0065
4             0   CWB0065
..          ...       ...
341           0   CWB0065
342           0   CWB0065
343           0   CWB0065
344           0   CWB0065
345           0   CWB0065

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       7.0       2      2      1.0
1    01-04-2010       3.0      0.0      10.0       1      2      2.0
2    01-04-2011       3.0      0.0      11.0       1      2      1.0
3    01-05-2010       1.0      0.0      12.0       1      2      3.0
4    01-05-2011       3.0      1.0      10.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       7.0       1      2      1.0
342  12-27-2010       6.0      1.0       6.0       1      2      0.0
343  12-28-2010      10.0      1.0       3.0       1      2      1.0
344  12-29-2010       5.0      1.0       8.0       1      2      1.0
345  12-30-2010       6.0      0.0       8.0       1      2      2.0

     Disconnect user_name
0           1.0   CWR0502
1           2.0   CWR0502
2           1.0   CWR0502
3           3.0   CWR0502
4           1.0   CWR0502
..          ...       ...
341         1.0   CWR0502
342         0.0   CWR0502
343         1.0   CWR0502
344         1.0   CWR0502
345         2.0   CWR0502

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      2.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      0.0       3.0       1      1        0
342  03-21-2011       0.0      0.0       0.0       1      1        0
343  06-25-2010       0.0      0.0       0.0       1      1        0
344  12-01-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CXC0336
1             0   CXC0336
2             0   CXC0336
3             0   CXC0336
4             0   CXC0336
..          ...       ...
341           0   CXC0336
342           0   CXC0336
343           0   CXC0336
344           0   CXC0336
345           0   CXC0336

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0       1      1        0
1    01-05-2010       0.0      0.0       3.0       1      1        0
2    01-06-2010       0.0      0.0       3.0       1      1        0
3    01-07-2010       3.0      0.0       0.0       1      1        0
4    01-08-2010       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
100  05-26-2010       0.0      0.0       3.0       1      1        0
101  05-27-2010       2.0      0.0       1.0       1      1        0
102  05-28-2010       1.0      0.0       2.0       1      1        0
103  06-01-2010       1.0      0.0       2.0       1      1        0
104  01-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   CYA0506
1             0   CYA0506
2             0   CYA0506
3             0   CYA0506
4             0   CYA0506
..          ...       ...
100           0   CYA0506
101           0   CYA0506
102           0   CYA0506
103           0   CYA0506
104           0   CYA0506

[105 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       4.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      1.0       7.0       1      1        0
342  12-30-2010       4.0      1.0       4.0       1      1        0
343  03-17-2011       0.0      0.0       0.0       1      1        0
344  08-12-2010       0.0      0.0       0.0       1      1        0
345  10-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DAG0558
1             0   DAG0558
2             0   DAG0558
3             0   DAG0558
4             0   DAG0558
..          ...       ...
341           0   DAG0558
342           0   DAG0558
343           0   DAG0558
344           0   DAG0558
345           0   DAG0558

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      2.0       4.0       2      3      1.0
1    01-04-2010       2.0      0.0       7.0       1      2      1.0
2    01-04-2011       2.0      1.0       6.0       1      2      0.0
3    01-05-2010       5.0      0.0       4.0       1      2      1.0
4    01-05-2011       3.0      1.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       4.0       1      2      1.0
342  12-30-2010       0.0      0.0       2.0       1      2      0.0
343  04-13-2011       0.0      0.0       0.0       1      2      0.0
344  06-22-2010       0.0      0.0       0.0       1      2      0.0
345  10-05-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   DAL0673
1           1.0   DAL0673
2           0.0   DAL0673
3           1.0   DAL0673
4           0.0   DAL0673
..          ...       ...
341         1.0   DAL0673
342         0.0   DAL0673
343         0.0   DAL0673
344         0.0   DAL0673
345         0.0   DAL0673

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-02-2010       1.0      1.0       1.0       1      1        0
1   01-03-2010       1.0      0.0       2.0       1      1        0
2   01-04-2010       1.0      0.0       2.0       1      1        0
3   01-05-2010       0.0      0.0       3.0       2      2        0
4   01-06-2010       1.0      0.0       2.0       1      1        0
5   01-07-2010       2.0      0.0       1.0       3      3        0
6   01-08-2010       0.0      0.0       3.0       2      2        0
7   01-09-2010       2.0      1.0       0.0       1      1        0
8   01-10-2010       2.0      0.0       1.0       2      3        0
9   01-11-2010       1.0      0.0       2.0       2      1        0
10  01-12-2010       0.0      1.0       1.0       3      4        0
11  01-13-2010       1.0      0.0       2.0       2      1        0
12  01-14-2010       0.0      0.0       3.0       1      1        0
13  01-15-2010       0.0      0.0       3.0       1      1        0
14  01-16-2010       0.0      1.0       2.0       2      2        0
15  01-17-2010       3.0      0.0       0.0       1      1        0
16  01-18-2010       2.0      1.0       0.0       1      1        0
17  01-19-2010       1.0      0.0       2.0       2      2        0
18  01-20-2010       0.0      0.0       3.0       2      2        0
19  01-21-2010       1.0      0.0       2.0       1      1        0
20  01-22-2010       2.0      0.0       1.0       1      1        0
21  01-23-2010       0.0      0.0       3.0       1      1        0
22  01-24-2010       2.0      0.0       1.0       1      1        0
23  01-25-2010       1.0      0.0       2.0       1      1        0
24  01-26-2010       0.0      0.0       3.0       3      4        0
25  01-27-2010       1.0      0.0       2.0       2      1        0
26  01-28-2010       1.0      0.0       2.0       2      2        0
27  01-29-2010       0.0      0.0       3.0       1      1        0
28  01-30-2010       2.0      0.0       1.0       2      2        0
29  01-31-2010       2.0      0.0       0.0       2      2        0
30  02-01-2010       0.0      0.0       3.0       2      2        0
31  02-02-2010       1.0      0.0       2.0       1      1        0
32  02-03-2010       2.0      0.0       1.0       2      2        0
33  02-04-2010       0.0      0.0       3.0       1      1        0
34  02-05-2010       1.0      0.0       2.0       1      1        0
35  02-06-2010       0.0      0.0       3.0       1      1        0
36  02-07-2010       2.0      0.0       1.0       1      1        0
37  02-08-2010       0.0      0.0       0.0       1      1        0

    Disconnect user_name
0            0   DAR0885
1            0   DAR0885
2            0   DAR0885
3            0   DAR0885
4            0   DAR0885
5            0   DAR0885
6            0   DAR0885
7            0   DAR0885
8            0   DAR0885
9            0   DAR0885
10           0   DAR0885
11           0   DAR0885
12           0   DAR0885
13           0   DAR0885
14           0   DAR0885
15           0   DAR0885
16           0   DAR0885
17           0   DAR0885
18           0   DAR0885
19           0   DAR0885
20           0   DAR0885
21           0   DAR0885
22           0   DAR0885
23           0   DAR0885
24           0   DAR0885
25           0   DAR0885
26           0   DAR0885
27           0   DAR0885
28           0   DAR0885
29           0   DAR0885
30           0   DAR0885
31           0   DAR0885
32           0   DAR0885
33           0   DAR0885
34           0   DAR0885
35           0   DAR0885
36           0   DAR0885
37           0   DAR0885
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        9
1    01-04-2010       5.0      1.0       3.0       1      1        9
2    01-04-2011       0.0      0.0       9.0       1      1        8
3    01-05-2010       5.0      0.0       4.0       1      1        9
4    01-05-2011       4.0      2.0       3.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      2.0       4.0       1      1        9
342  12-28-2010       6.0      0.0       3.0       1      1        9
343  12-29-2010       3.0      1.0       5.0       1      1        9
344  12-30-2010       2.0      1.0       6.0       1      1        8
345  06-25-2010       0.0      0.0       0.0       1      1        8

     Disconnect user_name
0             9   DBB0384
1             9   DBB0384
2             8   DBB0384
3             9   DBB0384
4             9   DBB0384
..          ...       ...
341           9   DBB0384
342           9   DBB0384
343           9   DBB0384
344           8   DBB0384
345           8   DBB0384

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       6.0      0.0       3.0       1      1        0
344  12-30-2010       2.0      0.0       7.0       1      1        0
345  02-24-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DBG0261
1             0   DBG0261
2             0   DBG0261
3             0   DBG0261
4             0   DBG0261
..          ...       ...
341           0   DBG0261
342           0   DBG0261
343           0   DBG0261
344           0   DBG0261
345           0   DBG0261

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       0.0      0.0       9.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       7.0       1      1        0
342  12-27-2010       2.0      0.0       7.0       1      1        0
343  12-28-2010       2.0      2.0       5.0       1      1        0
344  12-29-2010       4.0      1.0       4.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   DBS0235
1             0   DBS0235
2             0   DBS0235
3             0   DBS0235
4             0   DBS0235
..          ...       ...
341           0   DBS0235
342           0   DBS0235
343           0   DBS0235
344           0   DBS0235
345           0   DBS0235

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       7.0     1.0    1.0        0
1    01-04-2010       9.0      0.0       5.0     1.0    1.0        0
2    01-04-2011       6.0      1.0       8.0     1.0    1.0        0
3    01-05-2010       6.0      1.0       8.0     1.0    1.0        0
4    01-05-2011       5.0      0.0      10.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0      10.0     1.0    1.0        0
342  12-27-2010       5.0      1.0       9.0     1.0    1.0        0
343  12-28-2010       6.0      0.0       9.0     1.0    1.0        0
344  12-29-2010       7.0      1.0       7.0     1.0    1.0        0
345  12-30-2010      10.0      1.0       4.0     1.0    1.0        0

     Disconnect user_name
0             0   DBW0483
1             0   DBW0483
2             0   DBW0483
3             0   DBW0483
4             0   DBW0483
..          ...       ...
341           0   DBW0483
342           0   DBW0483
343           0   DBW0483
344           0   DBW0483
345           0   DBW0483

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       9.0       1      1        0
1    01-04-2010       5.0      1.0      12.0       1      1        0
2    01-05-2010       3.0      1.0       6.0       1      1        0
3    01-05-2011       6.0      0.0      12.0       1      1        0
4    01-06-2010      12.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      1.0      10.0       1      1        0
342  12-28-2010       8.0      1.0       9.0       1      1        0
343  12-29-2010       4.0      1.0      13.0       1      1        0
344  12-30-2010       6.0      1.0      11.0       1      1        0
345  01-04-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DCC0160
1             0   DCC0160
2             0   DCC0160
3             0   DCC0160
4             0   DCC0160
..          ...       ...
341           0   DCC0160
342           0   DCC0160
343           0   DCC0160
344           0   DCC0160
345           0   DCC0160

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1      0.0
1    01-04-2010       0.0      0.0       1.0       1      1      0.0
2    01-04-2011       1.0      0.0       0.0       1      1      0.0
3    01-05-2010       1.0      0.0       0.0       1      1      0.0
4    01-05-2011       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
285  03-03-2010       0.0      0.0       0.0       1      1      0.0
286  06-25-2010       0.0      0.0       0.0       1      1      0.0
287  08-12-2010       0.0      0.0       0.0       1      1      0.0
288  10-12-2010       0.0      0.0       0.0       1      1      0.0
289  12-08-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   DCH0843
1           0.0   DCH0843
2           0.0   DCH0843
3           0.0   DCH0843
4           0.0   DCH0843
..          ...       ...
285         0.0   DCH0843
286         0.0   DCH0843
287         0.0   DCH0843
288         0.0   DCH0843
289         0.0   DCH0843

[290 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      1.0       7.0       1      1        0
2    01-04-2011       6.0      2.0       7.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011       6.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       9.0       1      1        0
342  12-29-2010       7.0      0.0       8.0       1      1        0
343  12-30-2010       4.0      1.0       9.0       1      1        0
344  02-25-2010       0.0      0.0       0.0       1      1        0
345  05-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DDA0476
1             0   DDA0476
2             0   DDA0476
3             0   DDA0476
4             0   DDA0476
..          ...       ...
341           0   DDA0476
342           0   DDA0476
343           0   DDA0476
344           0   DDA0476
345           0   DDA0476

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-21-2011       0.0      0.0       0.0       1      1        0
342  04-23-2010       0.0      0.0       0.0       1      1        0
343  04-29-2011       0.0      0.0       0.0       1      1        0
344  09-13-2010       0.0      0.0       0.0       1      1        0
345  09-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DDM0579
1             0   DDM0579
2             0   DDM0579
3             0   DDM0579
4             0   DDM0579
..          ...       ...
341           0   DDM0579
342           0   DDM0579
343           0   DDM0579
344           0   DDM0579
345           0   DDM0579

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  01-25-2010       0.0      0.0       0.0       1      1        0
343  03-24-2010       0.0      0.0       0.0       1      1        0
344  10-29-2010       0.0      0.0       0.0       1      1        0
345  11-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DEB0782
1             0   DEB0782
2             0   DEB0782
3             0   DEB0782
4             0   DEB0782
..          ...       ...
341           0   DEB0782
342           0   DEB0782
343           0   DEB0782
344           0   DEB0782
345           0   DEB0782

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       2      2      0.0
1    01-04-2010       2.0      0.0       1.0       2      3      1.0
2    01-04-2011       0.0      0.0       3.0       1      2      2.0
3    01-05-2010       3.0      0.0       0.0       1      2      1.0
4    01-05-2011       0.0      1.0       2.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      2      2.0
342  12-28-2010       2.0      0.0       1.0       1      1      2.0
343  12-29-2010       0.0      1.0       2.0       1      2      1.0
344  12-30-2010       0.0      0.0       3.0       1      2      3.0
345  03-10-2010       0.0      0.0       0.0       2      3      1.0

     Disconnect user_name
0           0.0   DFH0188
1           1.0   DFH0188
2           1.0   DFH0188
3           1.0   DFH0188
4           1.0   DFH0188
..          ...       ...
341         2.0   DFH0188
342         2.0   DFH0188
343         1.0   DFH0188
344         3.0   DFH0188
345         1.0   DFH0188

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       7.0       3      3        0
1    01-04-2010       4.0      1.0       6.0       4      4        0
2    01-04-2011       1.0      1.0       9.0       3      3        0
3    01-05-2010       4.0      1.0       6.0       2      2        0
4    01-05-2011       4.0      0.0       7.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       8.0       2      2        0
342  12-27-2010       5.0      0.0       6.0       5      5        0
343  12-28-2010       1.0      0.0      10.0       5      5        0
344  12-29-2010       2.0      0.0       9.0       3      3        0
345  12-30-2010       6.0      0.0       5.0       3      3        0

     Disconnect user_name
0             0   DFR0218
1             0   DFR0218
2             0   DFR0218
3             0   DFR0218
4             0   DFR0218
..          ...       ...
341           0   DFR0218
342           0   DFR0218
343           0   DFR0218
344           0   DFR0218
345           0   DFR0218

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      1.0       7.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      0.0       8.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       0.0      0.0       5.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   DGF0443
1             0   DGF0443
2             0   DGF0443
3             0   DGF0443
4             0   DGF0443
..          ...       ...
341           0   DGF0443
342           0   DGF0443
343           0   DGF0443
344           0   DGF0443
345           0   DGF0443

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       4.0      1.0      10.0       1      1        0
1   01-05-2010       1.0      6.0       8.0       1      1        0
2   01-06-2010       2.0      6.0       6.0       1      1        0
3   01-07-2010       3.0      7.0       5.0       1      1        0
4   01-08-2010       5.0      2.0       8.0       1      1        0
5   01-11-2010       3.0      1.0      11.0       1      1        0
6   01-12-2010       6.0      1.0       8.0       1      1        0
7   01-13-2010       2.0      8.0       4.0       1      1        0
8   01-14-2010       3.0      8.0       4.0       1      1        0
9   01-15-2010       7.0      2.0       6.0       1      1        0
10  01-18-2010       4.0      7.0       4.0       1      1        0
11  01-19-2010       0.0     13.0       2.0       1      1        0
12  01-20-2010       6.0      1.0       8.0       1      1        0
13  01-21-2010       5.0      2.0       8.0       1      1        0
14  01-22-2010       7.0      4.0       4.0       1      1        0
15  01-25-2010       5.0      5.0       5.0       1      1        0
16  01-26-2010       5.0      2.0       8.0       1      1        0
17  01-27-2010       4.0      3.0       8.0       1      1        0
18  01-28-2010       3.0      3.0       9.0       1      1        0
19  01-29-2010       7.0      2.0       6.0       1      1        0
20  02-01-2010       3.0      2.0      10.0       1      1        0
21  02-02-2010       3.0      8.0       4.0       1      1        0
22  02-03-2010       7.0      3.0       4.0       1      1        0
23  02-04-2010       8.0      2.0       5.0       1      1        0
24  02-05-2010       6.0      1.0       7.0       1      1        0
25  02-08-2010       0.0      2.0      13.0       1      1        0
26  02-09-2010       2.0      3.0      10.0       1      1        0
27  02-10-2010       1.0      9.0       5.0       1      1        0
28  02-11-2010       3.0      4.0       8.0       1      1        0

    Disconnect user_name
0            0   DGM0754
1            0   DGM0754
2            0   DGM0754
3            0   DGM0754
4            0   DGM0754
5            0   DGM0754
6            0   DGM0754
7            0   DGM0754
8            0   DGM0754
9            0   DGM0754
10           0   DGM0754
11           0   DGM0754
12           0   DGM0754
13           0   DGM0754
14           0   DGM0754
15           0   DGM0754
16           0   DGM0754
17           0   DGM0754
18           0   DGM0754
19           0   DGM0754
20           0   DGM0754
21           0   DGM0754
22           0   DGM0754
23           0   DGM0754
24           0   DGM0754
25           0   DGM0754
26           0   DGM0754
27           0   DGM0754
28           0   DGM0754
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0      10.0       1      1        0
1    01-04-2010       4.0      1.0      10.0       1      1        0
2    01-04-2011       2.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      0.0      13.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
324  12-22-2010       6.0      1.0       8.0       1      1        0
325  12-27-2010       6.0      2.0       7.0       1      1        0
326  12-28-2010       6.0      1.0       8.0       1      1        0
327  12-29-2010       9.0      0.0       5.0       1      1        0
328  12-30-2010       6.0      0.0       9.0       1      1        0

     Disconnect user_name
0             0   DGN0480
1             0   DGN0480
2             0   DGN0480
3             0   DGN0480
4             0   DGN0480
..          ...       ...
324           0   DGN0480
325           0   DGN0480
326           0   DGN0480
327           0   DGN0480
328           0   DGN0480

[329 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0       1      2        0
1    01-04-2010       3.0      2.0      10.0       1      1        0
2    01-04-2011       4.0      2.0       9.0       1      2        0
3    01-05-2010       8.0      2.0       4.0       1      2        0
4    01-05-2011       3.0      1.0      11.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      2.0      11.0       1      2        0
342  12-30-2010       9.0      1.0       5.0       1      2        0
343  03-30-2010       0.0      0.0       0.0       1      2        0
344  07-29-2010       0.0      0.0       0.0       1      2        0
345  12-21-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   DGW0752
1             0   DGW0752
2             0   DGW0752
3             0   DGW0752
4             0   DGW0752
..          ...       ...
341           0   DGW0752
342           0   DGW0752
343           0   DGW0752
344           0   DGW0752
345           0   DGW0752

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       1.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      2.0       4.0       1      1        0
342  12-29-2010       6.0      0.0       3.0       1      1        0
343  12-30-2010       5.0      1.0       3.0       1      1        0
344  02-17-2010       0.0      0.0       0.0       1      1        0
345  07-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DHM0937
1             0   DHM0937
2             0   DHM0937
3             0   DHM0937
4             0   DHM0937
..          ...       ...
341           0   DHM0937
342           0   DHM0937
343           0   DHM0937
344           0   DHM0937
345           0   DHM0937

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      0.0       5.0       2      2      2.0
1    01-05-2010       2.0      0.0       7.0       1      2      2.0
2    01-06-2010       2.0      1.0       6.0       2      3      3.0
3    01-07-2010       4.0      1.0       4.0       1      2      1.0
4    01-08-2010       6.0      0.0       3.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
157  08-16-2010       3.0      1.0       5.0       2      2      5.0
158  08-17-2010       6.0      0.0       3.0       1      2      3.0
159  08-18-2010       2.0      1.0       6.0       1      1      3.0
160  08-19-2010       5.0      1.0       2.0       2      3      4.0
161  08-20-2010       1.0      0.0       8.0       1      2      4.0

     Disconnect user_name
0           2.0   DIB0081
1           2.0   DIB0081
2           3.0   DIB0081
3           1.0   DIB0081
4           3.0   DIB0081
..          ...       ...
157         5.0   DIB0081
158         3.0   DIB0081
159         3.0   DIB0081
160         4.0   DIB0081
161         4.0   DIB0081

[162 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      0.0       1.0       1      1      3.0
1    01-05-2010       0.0      0.0       5.0       1      1      2.0
2    01-06-2010       4.0      0.0       5.0       1      1      2.0
3    01-07-2010       7.0      0.0       2.0       1      1      3.0
4    01-08-2010       7.0      1.0       1.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
179  09-17-2010       2.0      0.0       7.0       1      1      2.0
180  09-20-2010       2.0      1.0       6.0       1      1      2.0
181  09-21-2010       3.0      0.0       6.0       1      1      1.0
182  09-22-2010       2.0      0.0       7.0       1      1      3.0
183  09-01-2010       0.0      0.0       0.0       1      1      4.0

     Disconnect user_name
0           3.0   DIB0285
1           2.0   DIB0285
2           2.0   DIB0285
3           3.0   DIB0285
4           2.0   DIB0285
..          ...       ...
179         2.0   DIB0285
180         2.0   DIB0285
181         1.0   DIB0285
182         3.0   DIB0285
183         4.0   DIB0285

[184 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       2.0      2.0       5.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       5.0      0.0       4.0       1      1        0
343  12-29-2010       6.0      0.0       3.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  04-13-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DIC0988
1             0   DIC0988
2             0   DIC0988
3             0   DIC0988
4             0   DIC0988
..          ...       ...
341           0   DIC0988
342           0   DIC0988
343           0   DIC0988
344           0   DIC0988
345           0   DIC0988

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      1.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      1.0       1.0       1      1        0
342  12-28-2010       1.0      0.0       2.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      1        0
344  12-30-2010       1.0      0.0       2.0       1      1        0
345  07-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DID0650
1             0   DID0650
2             0   DID0650
3             0   DID0650
4             0   DID0650
..          ...       ...
341           0   DID0650
342           0   DID0650
343           0   DID0650
344           0   DID0650
345           0   DID0650

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       7.0       2      3      2.0
1    01-04-2010       6.0      1.0       7.0       2      3      3.0
2    01-04-2011       7.0      0.0       7.0       1      2      1.0
3    01-05-2010       8.0      0.0       6.0       1      2      2.0
4    01-05-2011       9.0      0.0       4.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      2.0       9.0       2      2      2.0
342  12-29-2010       3.0      2.0       9.0       1      2      3.0
343  12-30-2010       5.0      0.0       9.0       1      2      2.0
344  01-27-2010       0.0      0.0       0.0       2      3      2.0
345  05-05-2011       0.0      0.0       0.0       2      2      1.0

     Disconnect user_name
0           2.0   DIW0118
1           3.0   DIW0118
2           1.0   DIW0118
3           2.0   DIW0118
4           3.0   DIW0118
..          ...       ...
341         2.0   DIW0118
342         3.0   DIW0118
343         2.0   DIW0118
344         2.0   DIW0118
345         1.0   DIW0118

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0      12.0       1      2        0
1    01-04-2010       4.0      1.0      13.0       1      2        0
2    01-04-2011       6.0      1.0      12.0       1      2        0
3    01-05-2010       9.0      0.0      10.0       1      2        0
4    01-05-2011       6.0      1.0      12.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       8.0      0.0      11.0       1      2        0
342  12-29-2010      12.0      0.0       7.0       1      2        0
343  12-30-2010       3.0      1.0      15.0       1      2        0
344  06-29-2010       0.0      0.0       0.0       1      2        0
345  10-11-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   DJB0159
1             0   DJB0159
2             0   DJB0159
3             0   DJB0159
4             0   DJB0159
..          ...       ...
341           0   DJB0159
342           0   DJB0159
343           0   DJB0159
344           0   DJB0159
345           0   DJB0159

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      2.0       4.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       5.0       1      1        0
342  12-28-2010       2.0      1.0       6.0       1      1        0
343  12-29-2010       4.0      1.0       4.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  12-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DJS0682
1             0   DJS0682
2             0   DJS0682
3             0   DJS0682
4             0   DJS0682
..          ...       ...
341           0   DJS0682
342           0   DJS0682
343           0   DJS0682
344           0   DJS0682
345           0   DJS0682

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  02-05-2010       0.0      0.0       0.0       1      1        0
345  02-22-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DKB0631
1             0   DKB0631
2             0   DKB0631
3             0   DKB0631
4             0   DKB0631
..          ...       ...
341           0   DKB0631
342           0   DKB0631
343           0   DKB0631
344           0   DKB0631
345           0   DKB0631

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       3.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       5.0      1.0       3.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   DLF0377
1             0   DLF0377
2             0   DLF0377
3             0   DLF0377
4             0   DLF0377
..          ...       ...
341           0   DLF0377
342           0   DLF0377
343           0   DLF0377
344           0   DLF0377
345           0   DLF0377

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       1.0       1      1        0
1    01-04-2010       2.0      1.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       6.0      0.0       3.0       1      1        0
343  12-29-2010       2.0      1.0       6.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  05-03-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DLH0029
1             0   DLH0029
2             0   DLH0029
3             0   DLH0029
4             0   DLH0029
..          ...       ...
341           0   DLH0029
342           0   DLH0029
343           0   DLH0029
344           0   DLH0029
345           0   DLH0029

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       8.0      0.0      10.0       2      3        9
1    01-03-2010       5.0      0.0      13.0       1      1        9
2    01-03-2011      10.0      1.0       6.0       1      1        9
3    01-04-2010       9.0      1.0       8.0       1      2        8
4    01-04-2011       8.0      0.0      10.0       1      2        8
..          ...       ...      ...       ...     ...    ...      ...
431  12-28-2010       9.0      0.0       7.0       1      2        9
432  12-29-2010       5.0      2.0      10.0       1      2        8
433  12-30-2010      12.0      0.0       6.0       1      2        9
434  03-24-2011       0.0      0.0       0.0       1      2        8
435  10-12-2010       0.0      0.0       0.0       1      2        9

     Disconnect user_name
0             9   DLM0051
1             9   DLM0051
2             9   DLM0051
3             8   DLM0051
4             8   DLM0051
..          ...       ...
431           9   DLM0051
432           8   DLM0051
433           9   DLM0051
434           8   DLM0051
435           9   DLM0051

[436 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      2        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       4.0      0.0       5.0       1      2        0
342  08-13-2010       0.0      0.0       0.0       1      2        0
343  09-01-2010       0.0      0.0       0.0       1      2        0
344  10-04-2010       0.0      0.0       0.0       1      2        0
345  10-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DLS0383
1             0   DLS0383
2             0   DLS0383
3             0   DLS0383
4             0   DLS0383
..          ...       ...
341           0   DLS0383
342           0   DLS0383
343           0   DLS0383
344           0   DLS0383
345           0   DLS0383

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       7.0       3      3        0
1    01-04-2010       5.0      0.0       6.0       4      5        0
2    01-04-2011       4.0      2.0       5.0       4      5        0
3    01-05-2010       6.0      0.0       5.0       4      5        0
4    01-05-2011       5.0      0.0       6.0       3      4        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0      10.0       2      3        0
342  12-29-2010       2.0      0.0       9.0       3      4        0
343  12-30-2010       4.0      0.0       3.0       5      6        0
344  03-15-2010       0.0      0.0       0.0       2      3        0
345  07-16-2010       0.0      0.0       0.0       6      7        0

     Disconnect user_name
0             0   DMG0358
1             0   DMG0358
2             0   DMG0358
3             0   DMG0358
4             0   DMG0358
..          ...       ...
341           0   DMG0358
342           0   DMG0358
343           0   DMG0358
344           0   DMG0358
345           0   DMG0358

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0     1.0    1.0      2.0
1    01-04-2010       4.0      0.0       5.0     1.0    2.0      1.0
2    01-04-2011       5.0      1.0       3.0     1.0    2.0      2.0
3    01-05-2010       5.0      0.0       4.0     2.0    3.0      2.0
4    01-05-2011       3.0      0.0       6.0     1.0    2.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
351  05-01-2010       0.0      0.0       0.0     1.0    0.0      0.0
352  05-08-2010       0.0      0.0       0.0     1.0    0.0      0.0
353  05-14-2011       0.0      0.0       0.0     1.0    1.0      0.0
354  10-02-2010       0.0      0.0       0.0     1.0    1.0      0.0
355  11-13-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           2.0   DMK0257
1           1.0   DMK0257
2           1.0   DMK0257
3           2.0   DMK0257
4           1.0   DMK0257
..          ...       ...
351         0.0   DMK0257
352         0.0   DMK0257
353         0.0   DMK0257
354         0.0   DMK0257
355         0.0   DMK0257

[356 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       6.0       1      2        0
1    01-04-2010       7.0      1.0       7.0       1      2        0
2    01-04-2011       8.0      1.0       6.0       1      2        0
3    01-05-2010      13.0      0.0       2.0       1      2        0
4    01-05-2011       7.0      2.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
350  12-27-2010       8.0      0.0       7.0       1      2        0
351  12-28-2010      10.0      2.0       3.0       1      1        0
352  12-29-2010      10.0      0.0       4.0       1      2        0
353  12-30-2010       8.0      0.0       7.0       1      2        0
354  12-31-2010       4.0      0.0      10.0       1      2        0

     Disconnect user_name
0             0   DMM0623
1             0   DMM0623
2             0   DMM0623
3             0   DMM0623
4             0   DMM0623
..          ...       ...
350           0   DMM0623
351           0   DMM0623
352           0   DMM0623
353           0   DMM0623
354           0   DMM0623

[355 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       3.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      1.0       2.0       1      1        0
342  12-28-2010       0.0      0.0       2.0       1      1        0
343  12-29-2010       0.0      1.0       2.0       1      1        0
344  12-30-2010       0.0      0.0       3.0       1      1        0
345  01-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DOL0332
1             0   DOL0332
2             0   DOL0332
3             0   DOL0332
4             0   DOL0332
..          ...       ...
341           0   DOL0332
342           0   DOL0332
343           0   DOL0332
344           0   DOL0332
345           0   DOL0332

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       2.0      1.0       6.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      1.0       2.0       1      1        0
342  12-29-2010       3.0      0.0       6.0       1      1        0
343  12-30-2010       3.0      1.0       5.0       1      1        0
344  03-16-2011       0.0      0.0       0.0       1      1        0
345  04-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DOP0562
1             0   DOP0562
2             0   DOP0562
3             0   DOP0562
4             0   DOP0562
..          ...       ...
341           0   DOP0562
342           0   DOP0562
343           0   DOP0562
344           0   DOP0562
345           0   DOP0562

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1      4.0
1    01-04-2010       2.0      0.0       7.0       2      2      2.0
2    01-04-2011       5.0      0.0       4.0       1      1      5.0
3    01-05-2010       5.0      1.0       3.0       1      1      5.0
4    01-05-2011       2.0      0.0       7.0       1      1      4.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       7.0       1      1      3.0
342  12-27-2010       3.0      0.0       6.0       1      1      4.0
343  12-28-2010       5.0      0.0       4.0       2      2      3.0
344  12-29-2010       1.0      0.0       8.0       1      1      2.0
345  12-30-2010       5.0      0.0       4.0       1      1      7.0

     Disconnect user_name
0           4.0   DPM0423
1           2.0   DPM0423
2           5.0   DPM0423
3           5.0   DPM0423
4           4.0   DPM0423
..          ...       ...
341         3.0   DPM0423
342         4.0   DPM0423
343         3.0   DPM0423
344         2.0   DPM0423
345         7.0   DPM0423

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       6.0      1.0       2.0       1      1        0
1    01-05-2010       4.0      0.0       5.0       1      1        0
2    01-06-2010       3.0      1.0       5.0       1      1        0
3    01-07-2010       5.0      0.0       4.0       2      2        0
4    01-08-2010       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
108  06-08-2010       4.0      0.0       5.0       1      1        0
109  06-09-2010       4.0      0.0       5.0       1      1        0
110  03-13-2010       0.0      0.0       0.0       1      1        0
111  04-17-2010       0.0      0.0       0.0       1      1        0
112  04-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DPS0262
1             0   DPS0262
2             0   DPS0262
3             0   DPS0262
4             0   DPS0262
..          ...       ...
108           0   DPS0262
109           0   DPS0262
110           0   DPS0262
111           0   DPS0262
112           0   DPS0262

[113 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       9.0       1      1      2.0
1    01-04-2010       4.0      0.0       7.0       1      1      3.0
2    01-04-2011       3.0      0.0       7.0       1      1      7.0
3    01-05-2010       2.0      0.0       9.0       1      1      4.0
4    01-05-2011       3.0      0.0       8.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
251  12-22-2010       3.0      0.0       8.0       1      1      5.0
252  12-27-2010       5.0      1.0       6.0       1      1      2.0
253  12-28-2010       4.0      0.0       7.0       1      1      9.0
254  12-29-2010       4.0      0.0       7.0       1      1      7.0
255  12-30-2010       3.0      0.0       8.0       1      1      1.0

     Disconnect user_name
0           2.0   DRR0162
1           3.0   DRR0162
2           7.0   DRR0162
3           4.0   DRR0162
4           1.0   DRR0162
..          ...       ...
251         5.0   DRR0162
252         2.0   DRR0162
253         9.0   DRR0162
254         7.0   DRR0162
255         1.0   DRR0162

[256 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       7.0      1.0       1.0       1      1        0
1    01-03-2010       4.0      0.0       5.0       1      1        0
2    01-03-2011       5.0      1.0       3.0       1      1        0
3    01-04-2010       6.0      0.0       3.0       1      1        0
4    01-04-2011       2.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
437  12-30-2010       4.0      0.0       5.0       1      1        0
438  12-31-2010       1.0      1.0       7.0       1      1        0
439  06-05-2010       0.0      0.0       0.0       1      1        0
440  06-09-2010       0.0      0.0       0.0       1      1        0
441  10-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DRR0242
1             0   DRR0242
2             0   DRR0242
3             0   DRR0242
4             0   DRR0242
..          ...       ...
437           0   DRR0242
438           0   DRR0242
439           0   DRR0242
440           0   DRR0242
441           0   DRR0242

[442 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      4.0       4.0       1      1        0
1    01-04-2010       1.0     10.0       4.0       1      1        0
2    01-04-2011       7.0      3.0       5.0       1      1        0
3    01-05-2010       7.0      2.0       6.0       1      1        0
4    01-05-2011       7.0      2.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      1.0       5.0       1      1        0
342  12-28-2010       8.0      1.0       6.0       1      1        0
343  12-29-2010       4.0      5.0       6.0       1      1        0
344  12-30-2010       5.0      3.0       7.0       1      1        0
345  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DSB0731
1             0   DSB0731
2             0   DSB0731
3             0   DSB0731
4             0   DSB0731
..          ...       ...
341           0   DSB0731
342           0   DSB0731
343           0   DSB0731
344           0   DSB0731
345           0   DSB0731

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-16-2010       0.0      0.0       0.0       1      1        0
342  08-23-2010       0.0      0.0       0.0       1      1        0
343  11-04-2010       0.0      0.0       0.0       1      1        0
344  11-22-2010       0.0      0.0       0.0       1      1        0
345  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DSM0591
1             0   DSM0591
2             0   DSM0591
3             0   DSM0591
4             0   DSM0591
..          ...       ...
341           0   DSM0591
342           0   DSM0591
343           0   DSM0591
344           0   DSM0591
345           0   DSM0591

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       6.0       2      2        0
1    01-04-2010       4.0      0.0       6.0       1      2        0
2    01-04-2011       3.0      0.0       7.0       1      2        0
3    01-05-2010       4.0      1.0       5.0       1      2        0
4    01-05-2011       5.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       4.0      1.0       5.0       1      2        0
342  12-30-2010       5.0      0.0       5.0       1      2        0
343  01-27-2010       0.0      0.0       0.0       2      3        0
344  03-23-2011       0.0      0.0       0.0       1      2        0
345  04-11-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   DTP0379
1             0   DTP0379
2             0   DTP0379
3             0   DTP0379
4             0   DTP0379
..          ...       ...
341           0   DTP0379
342           0   DTP0379
343           0   DTP0379
344           0   DTP0379
345           0   DTP0379

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      13.0      1.0       3.0       1      1        0
1    01-04-2010       8.0      0.0      10.0       1      1        0
2    01-04-2011       8.0      0.0      10.0       1      1        0
3    01-05-2010       9.0      2.0       7.0       1      1        0
4    01-05-2011       8.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0      10.0       1      1        0
342  12-27-2010       6.0      0.0      12.0       1      1        0
343  12-28-2010       9.0      1.0       7.0       1      1        0
344  12-29-2010      14.0      1.0       3.0       1      1        0
345  12-30-2010       8.0      0.0      10.0       1      1        0

     Disconnect user_name
0             0   DTT0076
1             0   DTT0076
2             0   DTT0076
3             0   DTT0076
4             0   DTT0076
..          ...       ...
341           0   DTT0076
342           0   DTT0076
343           0   DTT0076
344           0   DTT0076
345           0   DTT0076

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       2      2        0
1    01-04-2010       5.0      2.0       1.0       2      2        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       5.0      1.0       2.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       2.0      0.0       2.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   DVM0265
1             0   DVM0265
2             0   DVM0265
3             0   DVM0265
4             0   DVM0265
..          ...       ...
341           0   DVM0265
342           0   DVM0265
343           0   DVM0265
344           0   DVM0265
345           0   DVM0265

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       0.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      1        0
342  12-27-2010       3.0      0.0       3.0       1      1        0
343  12-28-2010       2.0      0.0       7.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   DVW0103
1             0   DVW0103
2             0   DVW0103
3             0   DVW0103
4             0   DVW0103
..          ...       ...
341           0   DVW0103
342           0   DVW0103
343           0   DVW0103
344           0   DVW0103
345           0   DVW0103

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       1.0      1.0       6.0       1      1        0
4    01-05-2011       2.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       3.0      0.0       6.0       1      1        0
343  12-28-2010       7.0      0.0       2.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   DZC0228
1             0   DZC0228
2             0   DZC0228
3             0   DZC0228
4             0   DZC0228
..          ...       ...
341           0   DZC0228
342           0   DZC0228
343           0   DZC0228
344           0   DZC0228
345           0   DZC0228

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       0.0      0.0       1.0       1      1      1.0
1   01-05-2010       1.0      0.0       0.0       1      2      0.0
2   01-06-2010       0.0      0.0       1.0       1      1      1.0
3   01-07-2010       0.0      0.0       1.0       1      2      2.0
4   01-08-2010       1.0      0.0       0.0       1      2      1.0
5   01-11-2010       1.0      0.0       0.0       2      2      0.0
6   01-12-2010       0.0      0.0       1.0       1      2      0.0
7   01-14-2010       1.0      0.0       0.0       2      3      1.0
8   01-15-2010       0.0      0.0       1.0       1      2      1.0
9   01-18-2010       1.0      0.0       0.0       1      1      0.0
10  01-19-2010       1.0      0.0       0.0       1      2      0.0
11  01-20-2010       0.0      1.0       0.0       1      2      0.0
12  01-21-2010       0.0      0.0       1.0       1      2      0.0
13  01-22-2010       1.0      0.0       0.0       1      1      0.0
14  01-25-2010       0.0      0.0       1.0       1      2      0.0
15  01-26-2010       0.0      0.0       1.0       1      2      0.0
16  01-27-2010       0.0      0.0       1.0       1      2      0.0
17  01-28-2010       1.0      0.0       0.0       1      2      0.0
18  01-29-2010       0.0      0.0       1.0       1      2      1.0
19  02-01-2010       0.0      0.0       1.0       2      2      0.0
20  02-02-2010       0.0      0.0       1.0       1      2      0.0
21  02-03-2010       1.0      0.0       0.0       1      2      0.0
22  02-04-2010       0.0      0.0       1.0       1      2      0.0
23  02-05-2010       0.0      0.0       1.0       2      3      1.0
24  02-08-2010       1.0      0.0       0.0       1      2      0.0
25  02-09-2010       1.0      0.0       0.0       1      2      1.0
26  02-10-2010       1.0      0.0       0.0       1      2      0.0
27  02-11-2010       0.0      0.0       1.0       1      1      1.0
28  02-12-2010       0.0      0.0       1.0       1      2      1.0
29  02-15-2010       0.0      0.0       1.0       1      1      1.0
30  02-16-2010       1.0      0.0       0.0       1      2      0.0
31  02-17-2010       0.0      0.0       1.0       1      1      1.0
32  02-18-2010       1.0      0.0       0.0       1      2      0.0
33  02-19-2010       0.0      0.0       1.0       1      2      1.0
34  01-13-2010       0.0      0.0       0.0       1      2      0.0

    Disconnect user_name
0          1.0   EAH0466
1          0.0   EAH0466
2          1.0   EAH0466
3          2.0   EAH0466
4          1.0   EAH0466
5          0.0   EAH0466
6          0.0   EAH0466
7          1.0   EAH0466
8          1.0   EAH0466
9          0.0   EAH0466
10         0.0   EAH0466
11         0.0   EAH0466
12         0.0   EAH0466
13         0.0   EAH0466
14         0.0   EAH0466
15         0.0   EAH0466
16         0.0   EAH0466
17         0.0   EAH0466
18         1.0   EAH0466
19         0.0   EAH0466
20         0.0   EAH0466
21         0.0   EAH0466
22         0.0   EAH0466
23         1.0   EAH0466
24         0.0   EAH0466
25         1.0   EAH0466
26         0.0   EAH0466
27         1.0   EAH0466
28         1.0   EAH0466
29         1.0   EAH0466
30         0.0   EAH0466
31         1.0   EAH0466
32         0.0   EAH0466
33         1.0   EAH0466
34         0.0   EAH0466
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       3.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      2.0       3.0       1      1        0
342  12-28-2010       0.0      0.0       5.0       1      1        0
343  12-29-2010       6.0      1.0       2.0       1      1        0
344  12-30-2010       2.0      1.0       6.0       1      1        0
345  10-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EBC0390
1             0   EBC0390
2             0   EBC0390
3             0   EBC0390
4             0   EBC0390
..          ...       ...
341           0   EBC0390
342           0   EBC0390
343           0   EBC0390
344           0   EBC0390
345           0   EBC0390

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-05-2010       1.0      0.0       0.0       1      1        0
2    01-06-2010       0.0      0.0       1.0       1      1        0
3    01-07-2010       0.0      0.0       1.0       1      1        0
4    01-08-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
206  10-29-2010       0.0      0.0       1.0       1      1        0
207  04-01-2010       0.0      0.0       0.0       1      1        0
208  08-05-2010       0.0      0.0       0.0       1      1        0
209  08-30-2010       0.0      0.0       0.0       1      1        0
210  08-31-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ECF0828
1             0   ECF0828
2             0   ECF0828
3             0   ECF0828
4             0   ECF0828
..          ...       ...
206           0   ECF0828
207           0   ECF0828
208           0   ECF0828
209           0   ECF0828
210           0   ECF0828

[211 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      0.0       2.0       1      1        0
2    01-04-2011       4.0      0.0       4.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       3.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0       7.0       1      2        0
342  12-27-2010       4.0      0.0       5.0       1      2        0
343  12-28-2010       4.0      2.0       3.0       1      2        0
344  12-29-2010       2.0      1.0       6.0       1      2        0
345  12-30-2010       3.0      0.0       6.0       1      2        0

     Disconnect user_name
0             0   ECL0930
1             0   ECL0930
2             0   ECL0930
3             0   ECL0930
4             0   ECL0930
..          ...       ...
341           0   ECL0930
342           0   ECL0930
343           0   ECL0930
344           0   ECL0930
345           0   ECL0930

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-11-2010       0.0      0.0       0.0       1      1        0
342  05-18-2010       0.0      0.0       0.0       1      1        0
343  05-20-2010       0.0      0.0       0.0       1      1        0
344  07-29-2010       0.0      0.0       0.0       1      1        0
345  08-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ECR0822
1             0   ECR0822
2             0   ECR0822
3             0   ECR0822
4             0   ECR0822
..          ...       ...
341           0   ECR0822
342           0   ECR0822
343           0   ECR0822
344           0   ECR0822
345           0   ECR0822

[346 rows x 9 columns]

aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       4.0      1.0       4.0       1      1        0
1   01-05-2010       3.0      1.0       5.0       1      1        0
2   01-06-2010       4.0      0.0       6.0       2      3        0
3   01-07-2010       3.0      0.0       6.0       2      1        0
4   01-08-2010       7.0      0.0       2.0       1      1        0
5   01-11-2010       7.0      0.0       2.0       2      2        0
6   01-12-2010       5.0      0.0       4.0       1      1        0
7   01-13-2010       7.0      0.0       2.0       1      1        0
8   01-14-2010       1.0      1.0       7.0       1      1        0
9   01-15-2010       5.0      0.0       4.0       2      2        0
10  01-18-2010       3.0      0.0       6.0       2      2        0
11  01-19-2010       4.0      0.0       5.0       1      1        0
12  01-20-2010       4.0      0.0       5.0       1      1        0
13  01-21-2010       4.0      0.0       5.0       1      1        0
14  01-22-2010       3.0      0.0       6.0       1      1        0
15  01-25-2010       5.0      0.0       4.0       1      1        0
16  01-26-2010       5.0      0.0       4.0       1      1        0
17  01-27-2010       5.0      0.0       4.0       1      1        0
18  01-28-2010       1.0      0.0       8.0       1      1        0
19  01-29-2010       4.0      0.0       5.0       2      2        0
20  02-01-2010       6.0      0.0       4.0       1      2        0
21  02-02-2010       5.0      0.0       4.0       2      1        0
22  02-03-2010       3.0      0.0       4.0       1      1        0
23  02-04-2010       6.0      0.0       3.0       1      1        0
24  02-05-2010       7.0      0.0       2.0       2      2        0
25  02-08-2010       1.0      1.0       8.0       1      2        0
26  02-09-2010       3.0      1.0       5.0       2      1        0
27  02-10-2010       3.0      0.0       5.0       1      1        0
28  02-11-2010       5.0      0.0       4.0       1      1        0
29  02-12-2010       2.0      0.0       7.0       1      1        0
30  02-15-2010       5.0      0.0       4.0       1      1        0
31  02-16-2010       2.0      1.0       6.0       1      1        0
32  02-17-2010       5.0      0.0       4.0       1      1        0
33  02-18-2010       2.0      0.0       5.0       1      1        0
34  02-19-2010       0.0      0.0       0.0       1      1        0

    Disconnect user_name
0            0   EDA0684
1            0   EDA0684
2            0   EDA0684
3            0   EDA0684
4            0   EDA0684
5            0   EDA0684
6            0   EDA0684
7            0   EDA0684
8            0   EDA0684
9            0   EDA0684
10           0   EDA0684
11           0   EDA0684
12           0   EDA0684
13           0   EDA0684
14           0   EDA0684
15           0   EDA0684
16           0   EDA0684
17           0   EDA0684
18           0   EDA0684
19           0   EDA0684
20           0   EDA0684
21           0   EDA0684
22           0   EDA0684
23           0   EDA0684
24           0   EDA0684
25           0   EDA0684
26           0   EDA0684
27           0   EDA0684
28           0   EDA0684
29           0   EDA0684
30           0   EDA0684
31           0   EDA0684
32           0   EDA0684
33           0   EDA0684
34           0   EDA0684
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1      2.0
1    01-05-2010       0.0      0.0       1.0       1      1      2.0
2    01-06-2010       0.0      0.0       1.0       1      1      3.0
3    01-07-2010       1.0      0.0       0.0       1      1      4.0
4    01-08-2010       0.0      1.0       0.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
237  02-05-2010       0.0      0.0       0.0       1      1      2.0
238  04-14-2010       0.0      0.0       0.0       1      1      3.0
239  09-08-2010       0.0      0.0       0.0       1      1      3.0
240  10-26-2010       0.0      0.0       0.0       1      1      2.0
241  12-14-2010       0.0      0.0       0.0       1      1      6.0

     Disconnect user_name
0           2.0   EDB0714
1           2.0   EDB0714
2           3.0   EDB0714
3           4.0   EDB0714
4           2.0   EDB0714
..          ...       ...
237         2.0   EDB0714
238         3.0   EDB0714
239         3.0   EDB0714
240         2.0   EDB0714
241         6.0   EDB0714

[242 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      1.0       0.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      1        0
342  12-28-2010       0.0      0.0       3.0       1      1        0
343  12-29-2010       0.0      0.0       3.0       1      1        0
344  12-30-2010       0.0      0.0       3.0       1      1        0
345  07-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EFS0882
1             0   EFS0882
2             0   EFS0882
3             0   EFS0882
4             0   EFS0882
..          ...       ...
341           0   EFS0882
342           0   EFS0882
343           0   EFS0882
344           0   EFS0882
345           0   EFS0882

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1      1.0
1    01-05-2010       0.0      0.0       1.0       1      1      1.0
2    01-06-2010       0.0      0.0       1.0       1      1      1.0
3    01-07-2010       1.0      0.0       0.0       1      1      2.0
4    01-08-2010       1.0      0.0       0.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
184  04-06-2010       0.0      0.0       0.0       1      1      3.0
185  04-20-2010       0.0      0.0       0.0       1      1      1.0
186  05-06-2010       0.0      0.0       0.0       1      1      3.0
187  08-19-2010       0.0      0.0       0.0       1      1      2.0
188  09-09-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           1.0   EGD0132
1           1.0   EGD0132
2           1.0   EGD0132
3           2.0   EGD0132
4           1.0   EGD0132
..          ...       ...
184         3.0   EGD0132
185         1.0   EGD0132
186         3.0   EGD0132
187         2.0   EGD0132
188         1.0   EGD0132

[189 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0       4.0       1      2        0
1    01-05-2010       3.0      0.0       6.0       1      2        0
2    01-06-2010       3.0      0.0       4.0       1      1        0
3    01-07-2010       3.0      0.0       6.0       1      2        0
4    01-08-2010       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
135  07-15-2010       1.0      0.0       8.0       1      1        0
136  07-16-2010       3.0      0.0       6.0       1      2        0
137  07-19-2010       5.0      0.0       4.0       1      2        0
138  07-20-2010       2.0      0.0       7.0       1      1        0
139  07-21-2010       5.0      0.0       4.0       1      2        0

     Disconnect user_name
0             0   EGD0409
1             0   EGD0409
2             0   EGD0409
3             0   EGD0409
4             0   EGD0409
..          ...       ...
135           0   EGD0409
136           0   EGD0409
137           0   EGD0409
138           0   EGD0409
139           0   EGD0409

[140 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      1.0       1.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  01-24-2011       0.0      0.0       0.0       1      1        0
345  02-15-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EGK0893
1             0   EGK0893
2             0   EGK0893
3             0   EGK0893
4             0   EGK0893
..          ...       ...
341           0   EGK0893
342           0   EGK0893
343           0   EGK0893
344           0   EGK0893
345           0   EGK0893

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       5.0      1.0       3.0     2.0    3.0        0
1    01-03-2010       6.0      0.0       3.0     2.0    2.0        0
2    01-03-2011       2.0      1.0       6.0     2.0    3.0        0
3    01-04-2010       2.0      0.0       3.0     1.0    2.0        0
4    01-04-2011       1.0      1.0       7.0     2.0    3.0        0
..          ...       ...      ...       ...     ...    ...      ...
437  05-25-2010       0.0      0.0       0.0     2.0    2.0        0
438  07-25-2010       0.0      0.0       0.0     1.0    1.0        0
439  08-07-2010       0.0      0.0       0.0     1.0    1.0        0
440  09-18-2010       0.0      0.0       0.0     1.0    1.0        0
441  11-13-2010       0.0      0.0       0.0     1.0    0.0        0

     Disconnect user_name
0             0   EHB0420
1             0   EHB0420
2             0   EHB0420
3             0   EHB0420
4             0   EHB0420
..          ...       ...
437           0   EHB0420
438           0   EHB0420
439           0   EHB0420
440           0   EHB0420
441           0   EHB0420

[442 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1      0.0
1    01-05-2010       0.0      0.0       1.0       1      1      0.0
2    01-06-2010       0.0      0.0       1.0       1      1      0.0
3    01-07-2010       0.0      0.0       1.0       1      1      0.0
4    01-08-2010       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
154  03-22-2010       0.0      0.0       0.0       1      1      0.0
155  04-16-2010       0.0      0.0       0.0       1      1      0.0
156  06-11-2010       0.0      0.0       0.0       1      1      0.0
157  07-02-2010       0.0      0.0       0.0       1      1      0.0
158  07-30-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   EHB0824
1           0.0   EHB0824
2           0.0   EHB0824
3           0.0   EHB0824
4           0.0   EHB0824
..          ...       ...
154         0.0   EHB0824
155         0.0   EHB0824
156         0.0   EHB0824
157         0.0   EHB0824
158         0.0   EHB0824

[159 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1      0.0
1    01-06-2010       1.0      0.0       0.0       1      1      0.0
2    01-07-2010       0.0      0.0       1.0       1      2      0.0
3    01-08-2010       1.0      0.0       0.0       1      2      0.0
4    01-11-2010       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
206  10-27-2010       0.0      0.0       1.0       2      2      0.0
207  10-28-2010       1.0      0.0       0.0       1      1      0.0
208  01-05-2010       0.0      0.0       0.0       1      2      0.0
209  05-20-2010       0.0      0.0       0.0       2      2      0.0
210  10-02-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           0.0   EHD0584
1           0.0   EHD0584
2           0.0   EHD0584
3           0.0   EHD0584
4           0.0   EHD0584
..          ...       ...
206         0.0   EHD0584
207         0.0   EHD0584
208         0.0   EHD0584
209         0.0   EHD0584
210         1.0   EHD0584

[211 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       3.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       3.0      2.0       4.0       1      1        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       1.0      0.0       8.0       1      1        0
345  12-30-2010       5.0      1.0       3.0       1      1        0

     Disconnect user_name
0             0   EHR0096
1             0   EHR0096
2             0   EHR0096
3             0   EHR0096
4             0   EHR0096
..          ...       ...
341           0   EHR0096
342           0   EHR0096
343           0   EHR0096
344           0   EHR0096
345           0   EHR0096

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       1.0      0.0       8.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       7.0       1      1        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       3.0      0.0       2.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  05-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EIM0156
1             0   EIM0156
2             0   EIM0156
3             0   EIM0156
4             0   EIM0156
..          ...       ...
341           0   EIM0156
342           0   EIM0156
343           0   EIM0156
344           0   EIM0156
345           0   EIM0156

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      6.0       0.0       1      1        0
1    01-04-2010       2.0      5.0       1.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       3.0      4.0       2.0       1      1        0
4    01-05-2011       1.0      3.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      4.0       3.0       1      1        0
342  12-29-2010       2.0      1.0       6.0       1      1        0
343  12-30-2010       3.0      2.0       4.0       1      1        0
344  06-29-2010       0.0      0.0       0.0       1      1        0
345  10-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EIP0997
1             0   EIP0997
2             0   EIP0997
3             0   EIP0997
4             0   EIP0997
..          ...       ...
341           0   EIP0997
342           0   EIP0997
343           0   EIP0997
344           0   EIP0997
345           0   EIP0997

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       5.0       4      4        5
1    01-04-2010       5.0      0.0       5.0       6      6        6
2    01-04-2011       5.0      0.0       5.0       3      4        3
3    01-05-2010       7.0      0.0       2.0       2      3        3
4    01-05-2011       6.0      0.0       4.0       4      5        3
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       8.0       5      6        5
342  12-30-2010       2.0      0.0       0.0       2      3        2
343  03-16-2010       0.0      0.0       0.0       4      5        3
344  05-10-2010       0.0      0.0       0.0       3      4        3
345  08-27-2010       0.0      0.0       0.0       2      3        1

     Disconnect user_name
0             5   EIS0041
1             6   EIS0041
2             3   EIS0041
3             3   EIS0041
4             3   EIS0041
..          ...       ...
341           5   EIS0041
342           2   EIS0041
343           3   EIS0041
344           3   EIS0041
345           1   EIS0041

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0     1.0    1.0        0
1    01-04-2010       1.0      0.0       2.0     1.0    1.0        0
2    01-04-2011       1.0      0.0       2.0     1.0    1.0        0
3    01-05-2010       2.0      0.0       1.0     1.0    1.0        0
4    01-05-2011       0.0      0.0       3.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      1.0       2.0     1.0    1.0        0
342  12-28-2010       0.0      0.0       3.0     1.0    1.0        0
343  12-29-2010       1.0      0.0       2.0     1.0    1.0        0
344  12-30-2010       0.0      0.0       3.0     1.0    1.0        0
345  01-07-2011       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   EJW0884
1             0   EJW0884
2             0   EJW0884
3             0   EJW0884
4             0   EJW0884
..          ...       ...
341           0   EJW0884
342           0   EJW0884
343           0   EJW0884
344           0   EJW0884
345           0   EJW0884

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-08-2010       0.0      0.0       0.0       1      1        0
342  04-28-2010       0.0      0.0       0.0       1      1        0
343  06-18-2010       0.0      0.0       0.0       1      1        0
344  09-14-2010       0.0      0.0       0.0       1      1        0
345  10-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ELB0847
1             0   ELB0847
2             0   ELB0847
3             0   ELB0847
4             0   ELB0847
..          ...       ...
341           0   ELB0847
342           0   ELB0847
343           0   ELB0847
344           0   ELB0847
345           0   ELB0847

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-12-2010       0.0      0.0       0.0       1      1        0
342  08-24-2010       0.0      0.0       0.0       1      1        0
343  10-08-2010       0.0      0.0       0.0       1      1        0
344  10-25-2010       0.0      0.0       0.0       1      1        0
345  12-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ELH0960
1             0   ELH0960
2             0   ELH0960
3             0   ELH0960
4             0   ELH0960
..          ...       ...
341           0   ELH0960
342           0   ELH0960
343           0   ELH0960
344           0   ELH0960
345           0   ELH0960

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       0.0      2.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       2.0      0.0       1.0       1      1        0
343  12-30-2010       0.0      1.0       2.0       1      1        0
344  01-28-2011       0.0      0.0       0.0       1      1        0
345  02-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ELT0769
1             0   ELT0769
2             0   ELT0769
3             0   ELT0769
4             0   ELT0769
..          ...       ...
341           0   ELT0769
342           0   ELT0769
343           0   ELT0769
344           0   ELT0769
345           0   ELT0769

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-03-2010       0.0      0.0       0.0       1      2        0
342  06-07-2010       0.0      0.0       0.0       1      2        0
343  07-15-2010       0.0      0.0       0.0       1      1        0
344  09-07-2010       0.0      0.0       0.0       1      2        0
345  09-20-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   EMB0531
1             0   EMB0531
2             0   EMB0531
3             0   EMB0531
4             0   EMB0531
..          ...       ...
341           0   EMB0531
342           0   EMB0531
343           0   EMB0531
344           0   EMB0531
345           0   EMB0531

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       6.0       1      1        0
1    01-04-2010       9.0      1.0       5.0       1      1        0
2    01-04-2011       9.0      1.0       5.0       1      1        0
3    01-05-2010       8.0      1.0       6.0       1      1        0
4    01-05-2011       7.0      2.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0      10.0       1      1        0
342  12-28-2010       6.0      0.0       9.0       1      1        0
343  12-29-2010       6.0      2.0       7.0       1      1        0
344  12-30-2010       5.0      0.0      10.0       1      1        0
345  04-19-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EMS0317
1             0   EMS0317
2             0   EMS0317
3             0   EMS0317
4             0   EMS0317
..          ...       ...
341           0   EMS0317
342           0   EMS0317
343           0   EMS0317
344           0   EMS0317
345           0   EMS0317

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       1      1        0
1    01-04-2010       5.0      1.0       4.0       1      1        0
2    01-04-2011       2.0      1.0       8.0       1      1        0
3    01-05-2010       2.0      1.0       7.0       1      1        0
4    01-05-2011       7.0      2.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       7.0       1      1        0
342  12-29-2010       5.0      0.0       6.0       1      1        0
343  12-30-2010       2.0      0.0       9.0       1      1        0
344  05-07-2010       0.0      0.0       0.0       1      1        0
345  10-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EMW0105
1             0   EMW0105
2             0   EMW0105
3             0   EMW0105
4             0   EMW0105
..          ...       ...
341           0   EMW0105
342           0   EMW0105
343           0   EMW0105
344           0   EMW0105
345           0   EMW0105

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1      2.0
1    01-04-2010       2.0      0.0       1.0       1      1      0.0
2    01-04-2011       2.0      0.0       1.0       1      1      0.0
3    01-05-2010       1.0      0.0       2.0       1      1      0.0
4    01-05-2011       1.0      0.0       2.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       3.0      0.0       0.0       1      1      0.0
342  01-24-2011       0.0      0.0       0.0       1      1      1.0
343  06-25-2010       0.0      0.0       0.0       1      1      1.0
344  07-06-2010       0.0      0.0       0.0       1      1      0.0
345  09-02-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           2.0   EMW0772
1           0.0   EMW0772
2           0.0   EMW0772
3           0.0   EMW0772
4           1.0   EMW0772
..          ...       ...
341         0.0   EMW0772
342         1.0   EMW0772
343         1.0   EMW0772
344         0.0   EMW0772
345         0.0   EMW0772

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      2        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       5.0      0.0       4.0       1      2        0
4    01-05-2011       6.0      1.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
254  12-22-2010       3.0      1.0       5.0       1      2        0
255  12-27-2010       6.0      1.0       2.0       1      2        0
256  12-28-2010       5.0      1.0       3.0       1      2        0
257  12-29-2010       4.0      0.0       5.0       1      2        0
258  12-30-2010       4.0      0.0       5.0       1      2        0

     Disconnect user_name
0             0   ENC0234
1             0   ENC0234
2             0   ENC0234
3             0   ENC0234
4             0   ENC0234
..          ...       ...
254           0   ENC0234
255           0   ENC0234
256           0   ENC0234
257           0   ENC0234
258           0   ENC0234

[259 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      1.0       2.0       1      1        0
3    01-05-2010       4.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       4.0      1.0       4.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       2.0      0.0       5.0       1      1        0
345  12-30-2010       6.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   ENL0100
1             0   ENL0100
2             0   ENL0100
3             0   ENL0100
4             0   ENL0100
..          ...       ...
341           0   ENL0100
342           0   ENL0100
343           0   ENL0100
344           0   ENL0100
345           0   ENL0100

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       4.0      2.0       3.0       1      1        0
343  12-28-2010       5.0      1.0       3.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       3.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   EPW0434
1             0   EPW0434
2             0   EPW0434
3             0   EPW0434
4             0   EPW0434
..          ...       ...
341           0   EPW0434
342           0   EPW0434
343           0   EPW0434
344           0   EPW0434
345           0   EPW0434

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  10-05-2010       0.0      0.0       0.0       1      1        0
342  10-13-2010       0.0      0.0       0.0       1      1        0
343  11-19-2010       0.0      0.0       0.0       1      1        0
344  11-29-2010       0.0      0.0       0.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ERH0449
1             0   ERH0449
2             0   ERH0449
3             0   ERH0449
4             0   ERH0449
..          ...       ...
341           0   ERH0449
342           0   ERH0449
343           0   ERH0449
344           0   ERH0449
345           0   ERH0449

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       3.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  03-09-2010       0.0      0.0       0.0       1      1        0
345  07-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ESA0642
1             0   ESA0642
2             0   ESA0642
3             0   ESA0642
4             0   ESA0642
..          ...       ...
341           0   ESA0642
342           0   ESA0642
343           0   ESA0642
344           0   ESA0642
345           0   ESA0642

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-08-2010       0.0      0.0       0.0       1      1        0
342  09-16-2010       0.0      0.0       0.0       1      1        0
343  10-07-2010       0.0      0.0       0.0       1      1        0
344  10-26-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ESH0135
1             0   ESH0135
2             0   ESH0135
3             0   ESH0135
4             0   ESH0135
..          ...       ...
341           0   ESH0135
342           0   ESH0135
343           0   ESH0135
344           0   ESH0135
345           0   ESH0135

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1      0.0
1    01-04-2010       3.0      0.0       6.0       1      1      0.0
2    01-04-2011       4.0      1.0       4.0       1      1      0.0
3    01-05-2010       4.0      0.0       5.0       1      1      0.0
4    01-05-2011       4.0      0.0       5.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1      0.0
342  12-27-2010       3.0      1.0       5.0       1      1      1.0
343  12-28-2010       4.0      1.0       4.0       1      1      0.0
344  12-29-2010       5.0      0.0       4.0       1      1      0.0
345  12-30-2010       1.0      0.0       8.0       1      1      1.0

     Disconnect user_name
0           0.0   ESH0283
1           0.0   ESH0283
2           0.0   ESH0283
3           0.0   ESH0283
4           1.0   ESH0283
..          ...       ...
341         0.0   ESH0283
342         1.0   ESH0283
343         0.0   ESH0283
344         0.0   ESH0283
345         1.0   ESH0283

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      0.0       5.0       1      1      0.0
1    01-02-2010       4.0      0.0       6.0       1      1      0.0
2    01-02-2011       4.0      0.0       6.0       1      1      0.0
3    01-03-2010       2.0      2.0       6.0       1      1      1.0
4    01-03-2011       5.0      0.0       5.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
466  12-31-2010       4.0      0.0       6.0       1      1      0.0
467  02-07-2010       0.0      0.0       0.0       1      1      0.0
468  02-18-2011       0.0      0.0       0.0       1      1      1.0
469  02-23-2010       0.0      0.0       0.0       1      1      0.0
470  04-24-2011       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   ESJ0670
1           0.0   ESJ0670
2           0.0   ESJ0670
3           1.0   ESJ0670
4           0.0   ESJ0670
..          ...       ...
466         0.0   ESJ0670
467         0.0   ESJ0670
468         1.0   ESJ0670
469         0.0   ESJ0670
470         0.0   ESJ0670

[471 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      0.0       2.0       1      1      1.0
1    01-05-2010       2.0      0.0       7.0       1      1      2.0
2    01-06-2010       5.0      0.0       4.0       1      1      0.0
3    01-07-2010       3.0      1.0       4.0       1      1      1.0
4    01-08-2010       2.0      0.0       7.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
164  08-25-2010       6.0      0.0       3.0       1      1      1.0
165  08-26-2010       2.0      1.0       6.0       1      1      0.0
166  08-27-2010       1.0      0.0       7.0       1      1      0.0
167  08-30-2010       3.0      1.0       5.0       1      1      1.0
168  08-31-2010       3.0      1.0       5.0       1      1      0.0

     Disconnect user_name
0           1.0   ESR0693
1           2.0   ESR0693
2           0.0   ESR0693
3           1.0   ESR0693
4           3.0   ESR0693
..          ...       ...
164         1.0   ESR0693
165         0.0   ESR0693
166         0.0   ESR0693
167         1.0   ESR0693
168         0.0   ESR0693

[169 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       1      1        0
1    01-04-2010       2.0      2.0       7.0       1      1        0
2    01-04-2011       5.0      1.0       5.0       1      1        0
3    01-05-2010       2.0      0.0       9.0       1      1        0
4    01-05-2011       6.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       6.0       1      1        0
342  12-28-2010       3.0      2.0       5.0       1      1        0
343  12-29-2010       3.0      0.0       8.0       1      1        0
344  12-30-2010       2.0      1.0       3.0       1      1        0
345  06-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ETR0177
1             0   ETR0177
2             0   ETR0177
3             0   ETR0177
4             0   ETR0177
..          ...       ...
341           0   ETR0177
342           0   ETR0177
343           0   ETR0177
344           0   ETR0177
345           0   ETR0177

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       2      2        0
1    01-04-2010       5.0      0.0       4.0       2      2        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       2.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       2.0      1.0       6.0       1      1        0
343  12-28-2010       2.0      0.0       7.0       1      1        0
344  12-29-2010       4.0      1.0       4.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   ETR0428
1             0   ETR0428
2             0   ETR0428
3             0   ETR0428
4             0   ETR0428
..          ...       ...
341           0   ETR0428
342           0   ETR0428
343           0   ETR0428
344           0   ETR0428
345           0   ETR0428

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       4.0       1      1        0
1    01-04-2010      10.0      0.0       4.0       1      2        0
2    01-04-2011       7.0      0.0       7.0       1      2        0
3    01-05-2010       2.0      2.0       9.0       1      2        0
4    01-05-2011       6.0      0.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       4.0       1      2        0
342  12-27-2010       8.0      0.0       6.0       1      2        0
343  12-29-2010       9.0      1.0       3.0       1      2        0
344  12-30-2010       2.0      0.0       4.0       1      2        0
345  12-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   EWH0191
1             0   EWH0191
2             0   EWH0191
3             0   EWH0191
4             0   EWH0191
..          ...       ...
341           0   EWH0191
342           0   EWH0191
343           0   EWH0191
344           0   EWH0191
345           0   EWH0191

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      8.0       1.0       1      1        0
1    01-04-2010       1.0      5.0       9.0       1      1        0
2    01-04-2011       7.0      2.0       6.0       1      1        0
3    01-05-2010       3.0      6.0       4.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0     10.0       0.0       1      1        0
342  12-27-2010       2.0     12.0       1.0       1      1        0
343  12-28-2010       7.0      4.0       4.0       1      1        0
344  12-29-2010       9.0      1.0       5.0       1      1        0
345  12-30-2010       9.0      2.0       4.0       1      1        0

     Disconnect user_name
0             0   EZH0736
1             0   EZH0736
2             0   EZH0736
3             0   EZH0736
4             0   EZH0736
..          ...       ...
341           0   EZH0736
342           0   EZH0736
343           0   EZH0736
344           0   EZH0736
345           0   EZH0736

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       2.0      0.0       1.0       1      2        0
3    01-05-2010       0.0      0.0       3.0       1      2        0
4    01-05-2011       3.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       2      3        0
342  12-29-2010       0.0      0.0       3.0       1      2        0
343  12-30-2010       0.0      0.0       3.0       1      2        0
344  03-03-2011       0.0      0.0       0.0       1      2        0
345  05-16-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   EZT0640
1             0   EZT0640
2             0   EZT0640
3             0   EZT0640
4             0   EZT0640
..          ...       ...
341           0   EZT0640
342           0   EZT0640
343           0   EZT0640
344           0   EZT0640
345           0   EZT0640

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       8.0       1      1        0
2    01-04-2011       3.0      0.0      11.0       1      1        0
3    01-05-2010       4.0      0.0      10.0       1      1        0
4    01-05-2011       6.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      1.0       6.0       1      1        0
342  12-28-2010       5.0      0.0       9.0       1      1        0
343  12-29-2010       6.0      1.0       7.0       1      1        0
344  12-30-2010       7.0      0.0       4.0       1      1        0
345  10-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FAW0032
1             0   FAW0032
2             0   FAW0032
3             0   FAW0032
4             0   FAW0032
..          ...       ...
341           0   FAW0032
342           0   FAW0032
343           0   FAW0032
344           0   FAW0032
345           0   FAW0032

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      2.0       5.0       1      1        0
1    01-04-2010       6.0      2.0       6.0       1      1        0
2    01-04-2011       7.0      0.0       7.0       1      1        0
3    01-05-2010       7.0      1.0       5.0       1      1        0
4    01-05-2011       7.0      3.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       4.0       1      1        0
342  12-27-2010       7.0      2.0       3.0       1      1        0
343  12-28-2010       6.0      1.0       7.0       1      1        0
344  12-29-2010       9.0      0.0       5.0       1      1        0
345  12-30-2010       5.0      2.0       7.0       1      1        0

     Disconnect user_name
0             0   FBA0348
1             0   FBA0348
2             0   FBA0348
3             0   FBA0348
4             0   FBA0348
..          ...       ...
341           0   FBA0348
342           0   FBA0348
343           0   FBA0348
344           0   FBA0348
345           0   FBA0348

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       4.0      1.0      10.0       1      1        0
1    01-02-2011       3.0      1.0      11.0       1      1        0
2    01-03-2011       2.0      6.0       7.0       1      1        0
3    01-04-2010       6.0      4.0       5.0       1      1        0
4    01-04-2011       2.0      8.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
361  12-27-2010       1.0     12.0       2.0       1      1        0
362  12-28-2010       5.0      2.0       8.0       1      1        0
363  12-29-2010       4.0      2.0       9.0       1      1        0
364  12-30-2010       6.0      1.0       8.0       1      1        0
365  06-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FBW0747
1             0   FBW0747
2             0   FBW0747
3             0   FBW0747
4             0   FBW0747
..          ...       ...
361           0   FBW0747
362           0   FBW0747
363           0   FBW0747
364           0   FBW0747
365           0   FBW0747

[366 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      3.0       8.0       1      1        0
1    01-04-2010       5.0      0.0       9.0       1      1        0
2    01-04-2011       5.0      3.0       6.0       1      1        0
3    01-05-2010      10.0      0.0       4.0       1      1        0
4    01-05-2011       1.0      8.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      6.0       3.0       1      1        0
342  12-27-2010       2.0      2.0      10.0       1      1        0
343  12-28-2010       6.0      3.0       5.0       1      1        0
344  12-29-2010       4.0      9.0       0.0       1      1        0
345  12-30-2010       4.0      5.0       5.0       1      1        0

     Disconnect user_name
0             0   FDE0117
1             0   FDE0117
2             0   FDE0117
3             0   FDE0117
4             0   FDE0117
..          ...       ...
341           0   FDE0117
342           0   FDE0117
343           0   FDE0117
344           0   FDE0117
345           0   FDE0117

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       2      3      1.0
1    01-04-2010       1.0      0.0       0.0       1      2      1.0
2    01-04-2011       1.0      0.0       0.0       1      2      0.0
3    01-05-2010       1.0      0.0       0.0       1      2      0.0
4    01-05-2011       0.0      0.0       1.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  07-19-2010       0.0      0.0       0.0       1      2      2.0
342  07-28-2010       0.0      0.0       0.0       1      2      2.0
343  08-24-2010       0.0      0.0       0.0       1      2      0.0
344  08-27-2010       0.0      0.0       0.0       1      2      0.0
345  12-16-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           1.0   FEB0306
1           1.0   FEB0306
2           0.0   FEB0306
3           0.0   FEB0306
4           2.0   FEB0306
..          ...       ...
341         2.0   FEB0306
342         2.0   FEB0306
343         0.0   FEB0306
344         0.0   FEB0306
345         1.0   FEB0306

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0     2.0    3.0      1.0
1    01-06-2010       1.0      0.0       2.0     2.0    2.0      2.0
2    01-07-2010       0.0      1.0       2.0     1.0    2.0      2.0
3    01-08-2010       1.0      0.0       2.0     1.0    2.0      3.0
4    01-11-2010       0.0      0.0       3.0     2.0    3.0      3.0
..          ...       ...      ...       ...     ...    ...      ...
194  01-05-2010       0.0      0.0       0.0     1.0    2.0      1.0
195  03-20-2010       0.0      0.0       0.0     1.0    0.0      0.0
196  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
197  08-21-2010       0.0      0.0       0.0     1.0    1.0      0.0
198  09-09-2010       0.0      0.0       0.0     1.0    2.0      3.0

     Disconnect user_name
0           1.0   FFC0891
1           2.0   FFC0891
2           2.0   FFC0891
3           3.0   FFC0891
4           3.0   FFC0891
..          ...       ...
194         1.0   FFC0891
195         0.0   FFC0891
196         0.0   FFC0891
197         0.0   FFC0891
198         3.0   FFC0891

[199 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       6.0     1.0    1.0        0
1    01-04-2010       8.0      0.0       6.0     1.0    1.0        0
2    01-04-2011       1.0      0.0      12.0     1.0    1.0        0
3    01-05-2010      10.0      1.0       3.0     1.0    1.0        0
4    01-05-2011       1.0      0.0      13.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
350  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
351  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
352  08-21-2010       0.0      0.0       0.0     1.0    1.0        0
353  11-06-2010       0.0      0.0       0.0     1.0    0.0        0
354  11-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   FGW0853
1             0   FGW0853
2             0   FGW0853
3             0   FGW0853
4             0   FGW0853
..          ...       ...
350           0   FGW0853
351           0   FGW0853
352           0   FGW0853
353           0   FGW0853
354           0   FGW0853

[355 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       9.0       1      1        0
1    01-04-2010       6.0      0.0       8.0       1      1        0
2    01-04-2011       6.0      0.0       9.0       1      1        0
3    01-05-2010      10.0      0.0       5.0       1      1        0
4    01-05-2011       7.0      2.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0       7.0       1      1        0
342  12-27-2010       2.0      0.0      12.0       1      1        0
343  12-28-2010       8.0      0.0       7.0       1      1        0
344  12-29-2010       4.0      1.0      10.0       1      1        0
345  12-30-2010       7.0      1.0       7.0       1      1        0

     Disconnect user_name
0             0   FHO0630
1             0   FHO0630
2             0   FHO0630
3             0   FHO0630
4             0   FHO0630
..          ...       ...
341           0   FHO0630
342           0   FHO0630
343           0   FHO0630
344           0   FHO0630
345           0   FHO0630

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-20-2010       0.0      0.0       0.0       1      1        0
342  09-21-2010       0.0      0.0       0.0       1      1        0
343  10-18-2010       0.0      0.0       0.0       1      1        0
344  11-19-2010       0.0      0.0       0.0       1      1        0
345  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FHS0837
1             0   FHS0837
2             0   FHS0837
3             0   FHS0837
4             0   FHS0837
..          ...       ...
341           0   FHS0837
342           0   FHS0837
343           0   FHS0837
344           0   FHS0837
345           0   FHS0837

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       3.0      0.0       5.0       2      2        0
2    01-04-2011       2.0      1.0       5.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       1.0      0.0       5.0       2      2        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   FIR0920
1             0   FIR0920
2             0   FIR0920
3             0   FIR0920
4             0   FIR0920
..          ...       ...
341           0   FIR0920
342           0   FIR0920
343           0   FIR0920
344           0   FIR0920
345           0   FIR0920

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       4.0      0.0       5.0       1      1        0
343  12-29-2010       2.0      0.0       7.0       1      1        0
344  12-30-2010       4.0      0.0       4.0       1      1        0
345  04-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FKB0163
1             0   FKB0163
2             0   FKB0163
3             0   FKB0163
4             0   FKB0163
..          ...       ...
341           0   FKB0163
342           0   FKB0163
343           0   FKB0163
344           0   FKB0163
345           0   FKB0163

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       4.0      0.0       4.0       1      2      0.0
1    01-03-2010       1.0      1.0       7.0       1      2      0.0
2    01-03-2011       5.0      0.0       4.0       1      1      0.0
3    01-04-2010       4.0      0.0       4.0       2      2      0.0
4    01-04-2011       4.0      0.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
459  12-28-2010       4.0      0.0       5.0       1      2      0.0
460  12-29-2010       2.0      0.0       7.0       1      2      1.0
461  12-30-2010       4.0      0.0       5.0       1      2      0.0
462  12-31-2010       4.0      0.0       5.0       1      2      0.0
463  05-15-2011       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   FKK0055
1           0.0   FKK0055
2           0.0   FKK0055
3           0.0   FKK0055
4           0.0   FKK0055
..          ...       ...
459         0.0   FKK0055
460         1.0   FKK0055
461         0.0   FKK0055
462         0.0   FKK0055
463         1.0   FKK0055

[464 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0      12.0     1.0    1.0        0
1    01-04-2010       9.0      1.0       4.0     1.0    1.0        0
2    01-04-2011       8.0      0.0       6.0     1.0    1.0        0
3    01-05-2010       2.0      0.0      12.0     1.0    1.0        0
4    01-05-2011      10.0      0.0       4.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      1.0       8.0     1.0    1.0        0
342  12-29-2010       5.0      0.0       9.0     1.0    1.0        0
343  12-30-2010       2.0      1.0       3.0     1.0    1.0        0
344  03-08-2011       0.0      0.0       0.0     1.0    1.0        0
345  06-14-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   FLM0213
1             0   FLM0213
2             0   FLM0213
3             0   FLM0213
4             0   FLM0213
..          ...       ...
341           0   FLM0213
342           0   FLM0213
343           0   FLM0213
344           0   FLM0213
345           0   FLM0213

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       0.0     1.0    1.0      0.0
1    01-04-2010       1.0      0.0       1.0     1.0    1.0      0.0
2    01-04-2011       0.0      0.0       3.0     1.0    1.0      0.0
3    01-05-2010       1.0      1.0       1.0     1.0    1.0      0.0
4    01-05-2011       2.0      0.0       1.0     2.0    2.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
266  12-28-2010       0.0      0.0       3.0     1.0    1.0      0.0
267  12-29-2010       0.0      0.0       3.0     1.0    1.0      0.0
268  12-30-2010       0.0      0.0       3.0     1.0    2.0      5.0
269  05-28-2010       0.0      0.0       0.0     1.0    1.0      0.0
270  12-31-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   FMG0527
1           0.0   FMG0527
2           0.0   FMG0527
3           0.0   FMG0527
4           1.0   FMG0527
..          ...       ...
266         0.0   FMG0527
267         0.0   FMG0527
268         5.0   FMG0527
269         0.0   FMG0527
270         0.0   FMG0527

[271 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       0.0      1.0       2.0       1      2      0.0
1    01-02-2011       2.0      0.0       1.0       2      3      0.0
2    01-04-2010       1.0      0.0       2.0       1      2      0.0
3    01-04-2011       0.0      1.0       2.0       2      2      0.0
4    01-05-2010       0.0      0.0       3.0       2      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
420  01-03-2011       0.0      0.0       0.0       1      1      1.0
421  03-25-2011       0.0      0.0       0.0       2      3      0.0
422  04-28-2011       0.0      0.0       0.0       2      3      0.0
423  05-14-2010       0.0      0.0       0.0       1      2      2.0
424  06-30-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   FOB0756
1           0.0   FOB0756
2           0.0   FOB0756
3           0.0   FOB0756
4           0.0   FOB0756
..          ...       ...
420         1.0   FOB0756
421         0.0   FOB0756
422         0.0   FOB0756
423         2.0   FOB0756
424         1.0   FOB0756

[425 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-08-2010       0.0      0.0       0.0       1      1        0
342  02-19-2010       0.0      0.0       0.0       1      1        0
343  05-05-2011       0.0      0.0       0.0       1      1        0
344  10-27-2010       0.0      0.0       0.0       1      1        0
345  11-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FPC0954
1             0   FPC0954
2             0   FPC0954
3             0   FPC0954
4             0   FPC0954
..          ...       ...
341           0   FPC0954
342           0   FPC0954
343           0   FPC0954
344           0   FPC0954
345           0   FPC0954

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      2.0       9.0       1      1        0
1    01-04-2010       8.0      0.0       6.0       1      1        0
2    01-04-2011       6.0      2.0       7.0       1      1        0
3    01-05-2010       3.0      0.0       2.0       1      1        0
4    01-05-2011       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0      10.0       1      1        0
342  12-28-2010       8.0      0.0       7.0       1      1        0
343  12-29-2010       6.0      2.0       7.0       1      1        0
344  12-30-2010       5.0      1.0       9.0       1      1        0
345  04-08-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FQA0854
1             0   FQA0854
2             0   FQA0854
3             0   FQA0854
4             0   FQA0854
..          ...       ...
341           0   FQA0854
342           0   FQA0854
343           0   FQA0854
344           0   FQA0854
345           0   FQA0854

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       8.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      2.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       5.0       1      1        0
342  12-28-2010       2.0      0.0       9.0       1      1        0
343  12-29-2010       8.0      0.0       3.0       1      1        0
344  12-30-2010       3.0      1.0       7.0       1      1        0
345  01-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FRB0023
1             0   FRB0023
2             0   FRB0023
3             0   FRB0023
4             0   FRB0023
..          ...       ...
341           0   FRB0023
342           0   FRB0023
343           0   FRB0023
344           0   FRB0023
345           0   FRB0023

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       1.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       1.0      1.0       1.0       1      1        0
344  04-21-2010       0.0      0.0       0.0       1      1        0
345  05-25-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FRL0511
1             0   FRL0511
2             0   FRL0511
3             0   FRL0511
4             0   FRL0511
..          ...       ...
341           0   FRL0511
342           0   FRL0511
343           0   FRL0511
344           0   FRL0511
345           0   FRL0511

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-15-2010       0.0      0.0       0.0       1      1        0
342  07-30-2010       0.0      0.0       0.0       1      1        0
343  08-16-2010       0.0      0.0       0.0       1      1        0
344  09-02-2010       0.0      0.0       0.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FRR0832
1             0   FRR0832
2             0   FRR0832
3             0   FRR0832
4             0   FRR0832
..          ...       ...
341           0   FRR0832
342           0   FRR0832
343           0   FRR0832
344           0   FRR0832
345           0   FRR0832

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
330  12-28-2010       5.0      0.0       4.0       1      1        0
331  12-29-2010       4.0      1.0       4.0       1      1        0
332  12-30-2010       6.0      0.0       3.0       1      1        0
333  03-15-2011       0.0      0.0       0.0       1      1        0
334  07-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FSB0399
1             0   FSB0399
2             0   FSB0399
3             0   FSB0399
4             0   FSB0399
..          ...       ...
330           0   FSB0399
331           0   FSB0399
332           0   FSB0399
333           0   FSB0399
334           0   FSB0399

[335 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       1      1      1.0
1    01-04-2010       9.0      2.0       3.0       1      1      2.0
2    01-04-2011       8.0      0.0       6.0       1      1      1.0
3    01-05-2010       5.0      0.0       8.0       1      1      0.0
4    01-05-2011       7.0      0.0       7.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
301  12-22-2010       7.0      0.0       6.0       1      1      2.0
302  12-27-2010       7.0      0.0       7.0       1      1      0.0
303  12-28-2010       5.0      0.0       9.0       1      1      1.0
304  12-29-2010       7.0      0.0       7.0       1      1      2.0
305  12-30-2010      10.0      1.0       3.0       1      1      3.0

     Disconnect user_name
0           1.0   FSC0601
1           2.0   FSC0601
2           1.0   FSC0601
3           0.0   FSC0601
4           2.0   FSC0601
..          ...       ...
301         2.0   FSC0601
302         0.0   FSC0601
303         1.0   FSC0601
304         2.0   FSC0601
305         3.0   FSC0601

[306 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       5.0       1      1      0.0
1    01-05-2010       3.0      1.0       5.0       1      1      0.0
2    01-06-2010       3.0      0.0       5.0       1      1      0.0
3    01-07-2010       6.0      0.0       3.0       1      1      0.0
4    01-08-2010       5.0      2.0       2.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
241  12-16-2010       1.0      1.0       7.0       1      1      0.0
242  12-17-2010       6.0      0.0       3.0       1      1      0.0
243  12-20-2010       1.0      0.0       8.0       1      1      0.0
244  05-19-2010       0.0      0.0       0.0       1      1      0.0
245  11-25-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           0.0   FTM0406
1           0.0   FTM0406
2           0.0   FTM0406
3           0.0   FTM0406
4           0.0   FTM0406
..          ...       ...
241         0.0   FTM0406
242         0.0   FTM0406
243         0.0   FTM0406
244         0.0   FTM0406
245         1.0   FTM0406

[246 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      3.0       7.0       1      1        0
1    01-04-2010       8.0      1.0       9.0       1      1        0
2    01-04-2011      10.0      1.0       7.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      0.0      14.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      1.0       7.0       1      1        0
342  12-27-2010       2.0      0.0      16.0       1      1        0
343  12-28-2010       4.0      3.0      10.0       1      1        0
344  12-29-2010       4.0      1.0      13.0       1      1        0
345  12-30-2010       9.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   FUM0015
1             0   FUM0015
2             0   FUM0015
3             0   FUM0015
4             0   FUM0015
..          ...       ...
341           0   FUM0015
342           0   FUM0015
343           0   FUM0015
344           0   FUM0015
345           0   FUM0015

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       2      2        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-29-2010       0.0      0.0       0.0       1      1        0
342  08-11-2010       0.0      0.0       0.0       1      1        0
343  08-19-2010       0.0      0.0       0.0       1      1        0
344  11-22-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FWM0707
1             0   FWM0707
2             0   FWM0707
3             0   FWM0707
4             0   FWM0707
..          ...       ...
341           0   FWM0707
342           0   FWM0707
343           0   FWM0707
344           0   FWM0707
345           0   FWM0707

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-03-2010       0.0      0.0       0.0       1      1        0
342  08-12-2010       0.0      0.0       0.0       1      1        0
343  08-25-2010       0.0      0.0       0.0       1      1        0
344  09-01-2010       0.0      0.0       0.0       1      1        0
345  09-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   FXF0957
1             0   FXF0957
2             0   FXF0957
3             0   FXF0957
4             0   FXF0957
..          ...       ...
341           0   FXF0957
342           0   FXF0957
343           0   FXF0957
344           0   FXF0957
345           0   FXF0957

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       6.0       1      1        0
1    01-04-2010       2.0      1.0       6.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       5.0       1      1        0
342  12-27-2010       1.0      1.0       7.0       1      1        0
343  12-28-2010       3.0      1.0       5.0       1      1        0
344  12-29-2010       5.0      1.0       3.0       1      1        0
345  12-30-2010       2.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   GAF0060
1             0   GAF0060
2             0   GAF0060
3             0   GAF0060
4             0   GAF0060
..          ...       ...
341           0   GAF0060
342           0   GAF0060
343           0   GAF0060
344           0   GAF0060
345           0   GAF0060

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       2      2        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       3.0      1.0       4.0       1      2        0
3    01-05-2010       2.0      1.0       6.0       1      2        0
4    01-05-2011       5.0      1.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       5.0       1      2        0
342  12-29-2010       4.0      0.0       5.0       1      2        0
343  12-30-2010       7.0      0.0       2.0       1      2        0
344  03-24-2011       0.0      0.0       0.0       1      2        0
345  10-08-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   GAF0570
1             0   GAF0570
2             0   GAF0570
3             0   GAF0570
4             0   GAF0570
..          ...       ...
341           0   GAF0570
342           0   GAF0570
343           0   GAF0570
344           0   GAF0570
345           0   GAF0570

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       7.0       1      1        0
1    01-04-2010       7.0      1.0       7.0       1      1        0
2    01-04-2011       3.0      0.0       5.0       1      1        0
3    01-05-2010       7.0      2.0       5.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
317  12-27-2010       1.0      0.0      14.0       1      1        0
318  12-28-2010       2.0      0.0       1.0       1      1        0
319  12-29-2010       6.0      2.0       7.0       1      1        0
320  12-30-2010       8.0      0.0       7.0       1      1        0
321  09-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GBM0603
1             0   GBM0603
2             0   GBM0603
3             0   GBM0603
4             0   GBM0603
..          ...       ...
317           0   GBM0603
318           0   GBM0603
319           0   GBM0603
320           0   GBM0603
321           0   GBM0603

[322 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      4.0       7.0       1      1        0
1    01-04-2010       4.0      3.0       7.0       1      1        0
2    01-04-2011       5.0      2.0       8.0       1      1        0
3    01-05-2010       0.0      5.0      10.0       1      1        0
4    01-05-2011       7.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      2.0       5.0       1      1        0
342  12-27-2010       5.0      2.0       7.0       1      1        0
343  12-28-2010       2.0      9.0       3.0       1      1        0
344  12-29-2010       3.0      5.0       7.0       1      1        0
345  12-30-2010       3.0      2.0      10.0       1      1        0

     Disconnect user_name
0             0   GCC0744
1             0   GCC0744
2             0   GCC0744
3             0   GCC0744
4             0   GCC0744
..          ...       ...
341           0   GCC0744
342           0   GCC0744
343           0   GCC0744
344           0   GCC0744
345           0   GCC0744

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-20-2010       0.0      0.0       0.0       1      1        0
342  05-10-2011       0.0      0.0       0.0       1      1        0
343  05-16-2011       0.0      0.0       0.0       1      1        0
344  07-27-2010       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GCC0945
1             0   GCC0945
2             0   GCC0945
3             0   GCC0945
4             0   GCC0945
..          ...       ...
341           0   GCC0945
342           0   GCC0945
343           0   GCC0945
344           0   GCC0945
345           0   GCC0945

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       0.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-19-2010       0.0      0.0       0.0       1      2        0
342  07-20-2010       0.0      0.0       0.0       1      2        0
343  08-30-2010       0.0      0.0       0.0       1      2        0
344  09-16-2010       0.0      0.0       0.0       1      2        0
345  11-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GCG0951
1             0   GCG0951
2             0   GCG0951
3             0   GCG0951
4             0   GCG0951
..          ...       ...
341           0   GCG0951
342           0   GCG0951
343           0   GCG0951
344           0   GCG0951
345           0   GCG0951

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       4.0      1.0       6.0       1      2      2.0
1    01-02-2011       3.0      2.0       6.0       1      1      0.0
2    01-03-2011       4.0      0.0       6.0       1      2      1.0
3    01-04-2010       1.0      0.0       6.0       1      2      0.0
4    01-04-2011       3.0      0.0       8.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
383  12-25-2010       5.0      1.0       4.0       2      2      0.0
384  12-27-2010       2.0      0.0       9.0       1      2      0.0
385  12-28-2010       6.0      2.0       3.0       1      2      0.0
386  12-29-2010       2.0      2.0       7.0       1      2      1.0
387  12-30-2010       6.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           2.0   GCL0016
1           0.0   GCL0016
2           1.0   GCL0016
3           0.0   GCL0016
4           0.0   GCL0016
..          ...       ...
383         0.0   GCL0016
384         0.0   GCL0016
385         0.0   GCL0016
386         1.0   GCL0016
387         1.0   GCL0016

[388 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       2.0       1      1        0
342  12-28-2010       1.0      0.0       8.0       1      1        0
343  12-29-2010       1.0      0.0       8.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  11-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GCR0554
1             0   GCR0554
2             0   GCR0554
3             0   GCR0554
4             0   GCR0554
..          ...       ...
341           0   GCR0554
342           0   GCR0554
343           0   GCR0554
344           0   GCR0554
345           0   GCR0554

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      1.0       2.0       1      1        0
342  02-08-2011       0.0      0.0       0.0       1      1        0
343  08-06-2010       0.0      0.0       0.0       1      1        0
344  10-04-2010       0.0      0.0       0.0       1      1        0
345  12-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GCS0518
1             0   GCS0518
2             0   GCS0518
3             0   GCS0518
4             0   GCS0518
..          ...       ...
341           0   GCS0518
342           0   GCS0518
343           0   GCS0518
344           0   GCS0518
345           0   GCS0518

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      2      0.0
1    01-04-2011       0.0      0.0       1.0       1      2      1.0
2    01-05-2010       1.0      0.0       0.0       1      2      2.0
3    01-05-2011       1.0      0.0       0.0       1      2      1.0
4    01-06-2010       1.0      0.0       0.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  05-13-2011       0.0      0.0       0.0       1      2      0.0
342  06-28-2010       0.0      0.0       0.0       1      1      0.0
343  07-09-2010       0.0      0.0       0.0       1      2      0.0
344  09-13-2010       0.0      0.0       0.0       1      1      0.0
345  09-24-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   GCS0571
1           1.0   GCS0571
2           2.0   GCS0571
3           1.0   GCS0571
4           1.0   GCS0571
..          ...       ...
341         0.0   GCS0571
342         0.0   GCS0571
343         0.0   GCS0571
344         0.0   GCS0571
345         0.0   GCS0571

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-12-2010       0.0      0.0       0.0       1      2        0
342  08-11-2010       0.0      0.0       0.0       1      2        0
343  08-27-2010       0.0      0.0       0.0       1      2        0
344  11-01-2010       0.0      0.0       0.0       1      2        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GDF0704
1             0   GDF0704
2             0   GDF0704
3             0   GDF0704
4             0   GDF0704
..          ...       ...
341           0   GDF0704
342           0   GDF0704
343           0   GDF0704
344           0   GDF0704
345           0   GDF0704

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2      1.0
1    01-04-2010       0.0      0.0       1.0       1      1      2.0
2    01-04-2011       1.0      0.0       0.0       1      1      2.0
3    01-05-2010       0.0      0.0       1.0       1      1      2.0
4    01-05-2011       0.0      0.0       1.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
343  08-04-2010       0.0      0.0       0.0       1      1      3.0
344  08-05-2010       0.0      0.0       0.0       1      1      2.0
345  09-29-2010       0.0      0.0       0.0       1      1      2.0
346  10-22-2010       0.0      0.0       0.0       2      1      2.0
347  12-17-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           1.0   GHH0288
1           2.0   GHH0288
2           2.0   GHH0288
3           2.0   GHH0288
4           3.0   GHH0288
..          ...       ...
343         3.0   GHH0288
344         2.0   GHH0288
345         2.0   GHH0288
346         2.0   GHH0288
347         1.0   GHH0288

[348 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0     1.0    1.0      0.0
1    01-05-2010       1.0      0.0       0.0     1.0    1.0      0.0
2    01-06-2010       0.0      0.0       1.0     1.0    1.0      0.0
3    01-07-2010       0.0      0.0       1.0     1.0    1.0      0.0
4    01-08-2010       1.0      0.0       0.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
225  06-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
226  06-14-2010       0.0      0.0       0.0     1.0    1.0      0.0
227  07-12-2010       0.0      0.0       0.0     1.0    1.0      0.0
228  09-22-2010       0.0      0.0       0.0     1.0    1.0      0.0
229  11-13-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   GHL0460
1           0.0   GHL0460
2           0.0   GHL0460
3           0.0   GHL0460
4           0.0   GHL0460
..          ...       ...
225         0.0   GHL0460
226         0.0   GHL0460
227         0.0   GHL0460
228         0.0   GHL0460
229         0.0   GHL0460

[230 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-17-2010       0.0      0.0       0.0       1      1        0
342  04-16-2010       0.0      0.0       0.0       1      1        0
343  04-27-2010       0.0      0.0       0.0       1      1        0
344  06-09-2010       0.0      0.0       0.0       1      1        0
345  06-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GJD0298
1             0   GJD0298
2             0   GJD0298
3             0   GJD0298
4             0   GJD0298
..          ...       ...
341           0   GJD0298
342           0   GJD0298
343           0   GJD0298
344           0   GJD0298
345           0   GJD0298

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       2.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       5.0       1      1        0
342  12-27-2010       3.0      0.0       5.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       4.0      0.0       3.0       1      1        0
345  12-30-2010       0.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   GJT0386
1             0   GJT0386
2             0   GJT0386
3             0   GJT0386
4             0   GJT0386
..          ...       ...
341           0   GJT0386
342           0   GJT0386
343           0   GJT0386
344           0   GJT0386
345           0   GJT0386

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0      12.0       2      3      2.0
1    01-04-2010       5.0      0.0      12.0       2      3      0.0
2    01-04-2011       5.0      0.0      13.0       1      2      1.0
3    01-05-2010       5.0      0.0      13.0       1      2      2.0
4    01-05-2011       6.0      1.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010      11.0      1.0       5.0       1      2      2.0
342  12-28-2010       8.0      2.0       8.0       2      2      2.0
343  12-29-2010       9.0      2.0       7.0       1      2      0.0
344  12-30-2010       6.0      0.0      12.0       1      2      0.0
345  01-25-2010       0.0      0.0       0.0       2      3      0.0

     Disconnect user_name
0           2.0   GKO0078
1           0.0   GKO0078
2           1.0   GKO0078
3           2.0   GKO0078
4           0.0   GKO0078
..          ...       ...
341         2.0   GKO0078
342         2.0   GKO0078
343         0.0   GKO0078
344         0.0   GKO0078
345         0.0   GKO0078

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      2        0
2    01-04-2011       3.0      0.0       8.0       1      2        0
3    01-05-2010       1.0      0.0      10.0       1      2        0
4    01-05-2011       4.0      4.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       7.0       1      2        0
342  12-27-2010       5.0      0.0       6.0       1      2        0
343  12-28-2010       5.0      0.0       6.0       1      1        0
344  12-29-2010       4.0      0.0       7.0       1      2        0
345  12-30-2010       6.0      1.0       4.0       1      2        0

     Disconnect user_name
0             0   GLR0975
1             0   GLR0975
2             0   GLR0975
3             0   GLR0975
4             0   GLR0975
..          ...       ...
341           0   GLR0975
342           0   GLR0975
343           0   GLR0975
344           0   GLR0975
345           0   GLR0975

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      9.0       1.0       1      1        0
1    01-04-2010       2.0      1.0       8.0       1      1        0
2    01-04-2011       4.0      3.0       8.0       1      1        0
3    01-05-2010       5.0      0.0      10.0       1      1        0
4    01-05-2011       3.0      6.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0     13.0       1.0       1      1        0
342  12-29-2010       9.0      1.0       5.0       1      1        0
343  12-30-2010       4.0      6.0       4.0       1      1        0
344  07-08-2010       0.0      0.0       0.0       1      1        0
345  11-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GMF0738
1             0   GMF0738
2             0   GMF0738
3             0   GMF0738
4             0   GMF0738
..          ...       ...
341           0   GMF0738
342           0   GMF0738
343           0   GMF0738
344           0   GMF0738
345           0   GMF0738

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0     1.0    2.0      2.0
1    01-04-2010       4.0      0.0       5.0     1.0    2.0      0.0
2    01-04-2011       6.0      0.0       3.0     2.0    2.0      0.0
3    01-05-2010       3.0      0.0       6.0     1.0    2.0      0.0
4    01-05-2011       4.0      0.0       5.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
344  01-18-2011       0.0      0.0       0.0     2.0    3.0      0.0
345  03-06-2010       0.0      0.0       0.0     1.0    0.0      0.0
346  03-10-2011       0.0      0.0       0.0     1.0    2.0      1.0
347  04-18-2011       0.0      0.0       0.0     1.0    2.0      0.0
348  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           2.0   GNS0178
1           0.0   GNS0178
2           0.0   GNS0178
3           0.0   GNS0178
4           0.0   GNS0178
..          ...       ...
344         0.0   GNS0178
345         0.0   GNS0178
346         1.0   GNS0178
347         0.0   GNS0178
348         0.0   GNS0178

[349 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-02-2010       0.0      0.0       0.0       1      1        0
342  09-21-2010       0.0      0.0       0.0       1      2        0
343  10-06-2010       0.0      0.0       0.0       1      2        0
344  12-07-2010       0.0      0.0       0.0       1      2        0
345  12-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   GNZ0953
1             0   GNZ0953
2             0   GNZ0953
3             0   GNZ0953
4             0   GNZ0953
..          ...       ...
341           0   GNZ0953
342           0   GNZ0953
343           0   GNZ0953
344           0   GNZ0953
345           0   GNZ0953

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       4.0       1      1        0
1    01-05-2010       5.0      0.0       4.0       1      1        0
2    01-06-2010       4.0      1.0       2.0       1      1        0
3    01-07-2010       4.0      0.0       5.0       1      1        0
4    01-08-2010       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
236  12-09-2010       6.0      1.0       2.0       1      1        0
237  12-10-2010       5.0      0.0       4.0       1      1        0
238  12-13-2010       2.0      0.0       6.0       1      1        0
239  12-14-2010       6.0      0.0       3.0       1      1        0
240  03-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GOK0238
1             0   GOK0238
2             0   GOK0238
3             0   GOK0238
4             0   GOK0238
..          ...       ...
236           0   GOK0238
237           0   GOK0238
238           0   GOK0238
239           0   GOK0238
240           0   GOK0238

[241 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  08-10-2010       0.0      0.0       0.0       1      1        0
345  11-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GQF0659
1             0   GQF0659
2             0   GQF0659
3             0   GQF0659
4             0   GQF0659
..          ...       ...
341           0   GQF0659
342           0   GQF0659
343           0   GQF0659
344           0   GQF0659
345           0   GQF0659

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       7.0       1      1        0
1    01-04-2010       2.0      2.0      11.0       1      1        0
2    01-04-2011       3.0      5.0       6.0       1      1        0
3    01-05-2010       3.0      2.0      10.0       1      1        0
4    01-05-2011       5.0      2.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      4.0       6.0       1      1        0
342  12-29-2010       5.0      1.0       8.0       1      1        0
343  12-30-2010       3.0      2.0      10.0       1      1        0
344  01-25-2010       0.0      0.0       0.0       1      1        0
345  05-05-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GQP0743
1             0   GQP0743
2             0   GQP0743
3             0   GQP0743
4             0   GQP0743
..          ...       ...
341           0   GQP0743
342           0   GQP0743
343           0   GQP0743
344           0   GQP0743
345           0   GQP0743

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       9.0       1      1        0
1    01-04-2010       3.0      1.0       7.0       1      1        0
2    01-04-2011       4.0      1.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       9.0       1      1        0
4    01-05-2011       1.0      2.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       7.0       1      1        0
342  12-27-2010       2.0      0.0       9.0       1      1        0
343  12-28-2010       5.0      0.0       6.0       1      1        0
344  12-29-2010       7.0      1.0       3.0       1      1        0
345  12-30-2010       2.0      2.0       7.0       1      1        0

     Disconnect user_name
0             0   GRC0145
1             0   GRC0145
2             0   GRC0145
3             0   GRC0145
4             0   GRC0145
..          ...       ...
341           0   GRC0145
342           0   GRC0145
343           0   GRC0145
344           0   GRC0145
345           0   GRC0145

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       9.0       1      1        0
1    01-04-2010       9.0      0.0       6.0       1      1        0
2    01-04-2011       9.0      1.0       5.0       1      1        0
3    01-05-2010       4.0      1.0      10.0       1      1        0
4    01-05-2011       5.0      1.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       9.0       1      1        0
342  12-27-2010       9.0      1.0       5.0       1      1        0
343  12-28-2010       8.0      1.0       6.0       1      1        0
344  12-29-2010       7.0      0.0       8.0       1      1        0
345  12-30-2010       8.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   GRM0868
1             0   GRM0868
2             0   GRM0868
3             0   GRM0868
4             0   GRM0868
..          ...       ...
341           0   GRM0868
342           0   GRM0868
343           0   GRM0868
344           0   GRM0868
345           0   GRM0868

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       7.0       1      1        0
1    01-04-2010       4.0      4.0       6.0       1      1        0
2    01-04-2011       5.0      5.0       3.0       1      1        0
3    01-05-2010       4.0      8.0       2.0       1      1        0
4    01-05-2011       6.0      3.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      2.0       4.0       1      1        0
342  12-28-2010       8.0      0.0       6.0       1      1        0
343  12-29-2010       7.0      4.0       1.0       1      1        0
344  12-30-2010       8.0      3.0       3.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GTD0116
1             0   GTD0116
2             0   GTD0116
3             0   GTD0116
4             0   GTD0116
..          ...       ...
341           0   GTD0116
342           0   GTD0116
343           0   GTD0116
344           0   GTD0116
345           0   GTD0116

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       5.0       6      6        6
1    01-05-2010       5.0      0.0       6.0       5      5        5
2    01-06-2010       5.0      0.0       6.0       6      6        6
3    01-07-2010       5.0      2.0       4.0       5      5        5
4    01-08-2010       7.0      0.0       4.0       5      5        6
..          ...       ...      ...       ...     ...    ...      ...
113  06-14-2010       9.0      0.0       2.0       3      3        2
114  06-15-2010       3.0      0.0       8.0       4      4        5
115  06-16-2010       4.0      3.0       4.0       2      2        3
116  06-17-2010       8.0      0.0       5.0       6      6        5
117  06-18-2010       5.0      0.0       6.0       5      5        3

     Disconnect user_name
0             6   GTD0219
1             5   GTD0219
2             6   GTD0219
3             5   GTD0219
4             6   GTD0219
..          ...       ...
113           2   GTD0219
114           5   GTD0219
115           3   GTD0219
116           5   GTD0219
117           3   GTD0219

[118 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      2.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  09-07-2010       0.0      0.0       0.0       1      1        0
345  11-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GTD0898
1             0   GTD0898
2             0   GTD0898
3             0   GTD0898
4             0   GTD0898
..          ...       ...
341           0   GTD0898
342           0   GTD0898
343           0   GTD0898
344           0   GTD0898
345           0   GTD0898

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-30-2010       0.0      0.0       0.0       1      1        0
342  05-26-2010       0.0      0.0       0.0       1      1        0
343  08-12-2010       0.0      0.0       0.0       1      1        0
344  09-08-2010       0.0      0.0       0.0       1      1        0
345  12-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   GZB0469
1             0   GZB0469
2             0   GZB0469
3             0   GZB0469
4             0   GZB0469
..          ...       ...
341           0   GZB0469
342           0   GZB0469
343           0   GZB0469
344           0   GZB0469
345           0   GZB0469

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       2.0     10.0       3.0       1      2      1.0
1    01-02-2011       2.0     10.0       3.0       1      2      1.0
2    01-03-2011       4.0      1.0      10.0       1      2      2.0
3    01-04-2010       0.0      2.0       0.0       1      2      1.0
4    01-04-2011       8.0      3.0       3.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
394  12-24-2010       2.0      9.0       4.0       1      1      0.0
395  12-27-2010       4.0      3.0       8.0       1      2      1.0
396  12-28-2010       8.0      2.0       5.0       1      2      1.0
397  12-29-2010       5.0      7.0       3.0       1      2      3.0
398  12-30-2010       0.0     13.0       2.0       1      2      0.0

     Disconnect user_name
0           1.0   GZC0735
1           1.0   GZC0735
2           2.0   GZC0735
3           1.0   GZC0735
4           1.0   GZC0735
..          ...       ...
394         0.0   GZC0735
395         1.0   GZC0735
396         1.0   GZC0735
397         3.0   GZC0735
398         0.0   GZC0735

[399 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       6.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       1.0      0.0       8.0       1      1        0
4    01-05-2011       1.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       3.0       1      1        0
342  12-29-2010       2.0      2.0       5.0       1      1        0
343  12-30-2010       3.0      0.0       6.0       1      1        0
344  01-24-2011       0.0      0.0       0.0       1      1        0
345  02-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HAC0282
1             0   HAC0282
2             0   HAC0282
3             0   HAC0282
4             0   HAC0282
..          ...       ...
341           0   HAC0282
342           0   HAC0282
343           0   HAC0282
344           0   HAC0282
345           0   HAC0282

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       3.0      0.0       7.0       1      2      1.0
1    01-02-2010       5.0      2.0       3.0       1      2      0.0
2    01-02-2011       1.0      0.0       6.0       1      2      0.0
3    01-03-2010       6.0      1.0       3.0       1      2      1.0
4    01-03-2011       5.0      0.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
489  12-29-2010       2.0      0.0       8.0       1      2      0.0
490  12-30-2010       5.0      0.0       5.0       1      2      1.0
491  12-31-2010       6.0      0.0       4.0       1      2      0.0
492  03-28-2010       0.0      0.0       0.0       1      1      0.0
493  05-30-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   HAD0246
1           0.0   HAD0246
2           0.0   HAD0246
3           1.0   HAD0246
4           0.0   HAD0246
..          ...       ...
489         0.0   HAD0246
490         1.0   HAD0246
491         0.0   HAD0246
492         0.0   HAD0246
493         0.0   HAD0246

[494 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       7.0      0.0       2.0       1      1        0
343  12-30-2010       2.0      0.0       6.0       1      1        0
344  03-24-2010       0.0      0.0       0.0       1      1        0
345  06-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HAH0248
1             0   HAH0248
2             0   HAH0248
3             0   HAH0248
4             0   HAH0248
..          ...       ...
341           0   HAH0248
342           0   HAH0248
343           0   HAH0248
344           0   HAH0248
345           0   HAH0248

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      1.0       2.0       1      2      4.0
1    01-04-2011       0.0      1.0       2.0       1      2      1.0
2    01-05-2010       1.0      0.0       2.0       1      2      1.0
3    01-05-2011       2.0      0.0       0.0       1      2      3.0
4    01-06-2010       0.0      0.0       3.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       1.0       1      2      0.0
342  12-28-2010       2.0      0.0       1.0       1      1      4.0
343  12-29-2010       2.0      0.0       0.0       1      2      1.0
344  12-30-2010       2.0      0.0       1.0       1      2      4.0
345  01-03-2011       0.0      0.0       0.0       1      1      3.0

     Disconnect user_name
0           4.0   HAH0760
1           1.0   HAH0760
2           1.0   HAH0760
3           3.0   HAH0760
4           2.0   HAH0760
..          ...       ...
341         0.0   HAH0760
342         4.0   HAH0760
343         1.0   HAH0760
344         4.0   HAH0760
345         3.0   HAH0760

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      3.0       4.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       2.0      1.0       6.0       1      1        0
345  12-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HAM0985
1             0   HAM0985
2             0   HAM0985
3             0   HAM0985
4             0   HAM0985
..          ...       ...
341           0   HAM0985
342           0   HAM0985
343           0   HAM0985
344           0   HAM0985
345           0   HAM0985

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      4.0       2.0       1      1        0
1    01-04-2010       3.0      0.0       5.0       1      1        0
2    01-04-2011       1.0      7.0       1.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      4.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       5.0      1.0       3.0       1      1        0
343  12-29-2010       3.0      2.0       4.0       1      1        0
344  12-30-2010       4.0      1.0       4.0       1      1        0
345  02-04-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HAV0121
1             0   HAV0121
2             0   HAV0121
3             0   HAV0121
4             0   HAV0121
..          ...       ...
341           0   HAV0121
342           0   HAV0121
343           0   HAV0121
344           0   HAV0121
345           0   HAV0121

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1        0
342  12-29-2010       3.0      1.0       5.0       1      1        0
343  12-30-2010       6.0      0.0       3.0       1      1        0
344  04-12-2010       0.0      0.0       0.0       1      1        0
345  07-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HBB0056
1             0   HBB0056
2             0   HBB0056
3             0   HBB0056
4             0   HBB0056
..          ...       ...
341           0   HBB0056
342           0   HBB0056
343           0   HBB0056
344           0   HBB0056
345           0   HBB0056

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1      2.0
1    01-04-2010       2.0      0.0       6.0       1      1      3.0
2    01-04-2011       5.0      0.0       4.0       1      1      1.0
3    01-05-2010       5.0      0.0       4.0       1      1      2.0
4    01-05-2011       3.0      0.0       6.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
318  12-22-2010       4.0      2.0       3.0       1      1      0.0
319  12-27-2010       5.0      0.0       4.0       1      1      0.0
320  12-28-2010       3.0      0.0       5.0       1      1      3.0
321  12-29-2010       3.0      1.0       5.0       1      1      1.0
322  12-30-2010       5.0      0.0       4.0       1      1      2.0

     Disconnect user_name
0           2.0   HBO0413
1           3.0   HBO0413
2           1.0   HBO0413
3           2.0   HBO0413
4           3.0   HBO0413
..          ...       ...
318         0.0   HBO0413
319         0.0   HBO0413
320         3.0   HBO0413
321         1.0   HBO0413
322         2.0   HBO0413

[323 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      1.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-10-2011       0.0      0.0       0.0       1      1        0
342  03-09-2011       0.0      0.0       0.0       1      1        0
343  03-17-2010       0.0      0.0       0.0       1      1        0
344  08-27-2010       0.0      0.0       0.0       1      1        0
345  10-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HCC0344
1             0   HCC0344
2             0   HCC0344
3             0   HCC0344
4             0   HCC0344
..          ...       ...
341           0   HCC0344
342           0   HCC0344
343           0   HCC0344
344           0   HCC0344
345           0   HCC0344

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       3.0      2.0       4.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       3.0      0.0       5.0       1      1        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       5.0      1.0       3.0       1      1        0

     Disconnect user_name
0             0   HCL0113
1             0   HCL0113
2             0   HCL0113
3             0   HCL0113
4             0   HCL0113
..          ...       ...
341           0   HCL0113
342           0   HCL0113
343           0   HCL0113
344           0   HCL0113
345           0   HCL0113

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1      3.0
1    01-04-2010       0.0      0.0       3.0       1      2      2.0
2    01-04-2011       1.0      0.0       2.0       1      2      1.0
3    01-05-2010       2.0      0.0       1.0       1      2      3.0
4    01-05-2011       1.0      0.0       2.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1      3.0
342  12-29-2010       1.0      0.0       2.0       1      2      2.0
343  12-30-2010       2.0      0.0       1.0       1      2      2.0
344  01-06-2010       0.0      0.0       0.0       1      1      3.0
345  01-28-2011       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           3.0   HCL0651
1           2.0   HCL0651
2           1.0   HCL0651
3           3.0   HCL0651
4           2.0   HCL0651
..          ...       ...
341         3.0   HCL0651
342         2.0   HCL0651
343         2.0   HCL0651
344         3.0   HCL0651
345         1.0   HCL0651

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       2.0       1      1        9
1    01-04-2010       5.0      1.0       3.0       1      1        9
2    01-04-2011       2.0      0.0       7.0       1      1        7
3    01-05-2010       5.0      1.0       3.0       1      1        9
4    01-05-2011       5.0      0.0       4.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      1        9
342  12-27-2010       1.0      0.0       8.0       1      1        9
343  12-28-2010       4.0      0.0       5.0       1      1        9
344  12-29-2010       4.0      0.0       5.0       1      1        9
345  12-30-2010       4.0      0.0       5.0       1      1        7

     Disconnect user_name
0             8   HCM0267
1             9   HCM0267
2             7   HCM0267
3             9   HCM0267
4             9   HCM0267
..          ...       ...
341           9   HCM0267
342           9   HCM0267
343           9   HCM0267
344           9   HCM0267
345           7   HCM0267

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      2.0      16.0       1      1      1.0
1    01-04-2010       9.0      2.0      16.0       1      1      3.0
2    01-04-2011       9.0      0.0      18.0       1      1      4.0
3    01-05-2010      10.0      1.0      15.0       1      1      3.0
4    01-05-2011      13.0      0.0      14.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      2.0      15.0       1      1      3.0
342  12-27-2010       8.0      2.0      17.0       1      1      3.0
343  12-28-2010      10.0      2.0      15.0       1      1      1.0
344  12-29-2010       7.0      0.0      20.0       1      1      1.0
345  12-30-2010       9.0      2.0      16.0       1      1      5.0

     Disconnect user_name
0           1.0   HCS0003
1           3.0   HCS0003
2           4.0   HCS0003
3           3.0   HCS0003
4           3.0   HCS0003
..          ...       ...
341         3.0   HCS0003
342         3.0   HCS0003
343         1.0   HCS0003
344         1.0   HCS0003
345         5.0   HCS0003

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010       6.0      0.0       9.0       1      2        0
2    01-04-2011      10.0      1.0       4.0       1      2        0
3    01-05-2010       5.0      1.0       8.0       1      2        0
4    01-05-2011       7.0      0.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       8.0       1      2        0
342  12-28-2010      10.0      1.0       4.0       1      2        0
343  12-29-2010       8.0      0.0       7.0       1      2        0
344  12-30-2010       6.0      1.0       8.0       1      2        0
345  04-08-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   HCV0478
1             0   HCV0478
2             0   HCV0478
3             0   HCV0478
4             0   HCV0478
..          ...       ...
341           0   HCV0478
342           0   HCV0478
343           0   HCV0478
344           0   HCV0478
345           0   HCV0478

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      2        0
3    01-05-2010       5.0      0.0       4.0       1      2        0
4    01-05-2011       4.0      1.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       2.0       1      2        0
342  12-27-2010       3.0      2.0       3.0       1      2        0
343  12-28-2010       4.0      0.0       5.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      2        0
345  12-30-2010       6.0      0.0       3.0       1      2        0

     Disconnect user_name
0             0   HCW0419
1             0   HCW0419
2             0   HCW0419
3             0   HCW0419
4             0   HCW0419
..          ...       ...
341           0   HCW0419
342           0   HCW0419
343           0   HCW0419
344           0   HCW0419
345           0   HCW0419

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      3.0       3.0       1      1        0
1    01-04-2010       6.0      0.0       8.0       1      1        0
2    01-04-2011       5.0      0.0       9.0       1      1        0
3    01-05-2010       5.0      1.0       8.0       1      1        0
4    01-05-2011       6.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       4.0       1      1        0
342  12-27-2010       5.0      0.0       9.0       1      1        0
343  12-28-2010       7.0      1.0       6.0       1      1        0
344  12-29-2010       8.0      0.0       5.0       1      1        0
345  12-30-2010      10.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   HDD0789
1             0   HDD0789
2             0   HDD0789
3             0   HDD0789
4             0   HDD0789
..          ...       ...
341           0   HDD0789
342           0   HDD0789
343           0   HDD0789
344           0   HDD0789
345           0   HDD0789

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      0.0       6.0       1      2        0
1    01-03-2010       5.0      0.0       4.0       1      2        0
2    01-03-2011       6.0      1.0       2.0       1      2        0
3    01-04-2010       5.0      0.0       4.0       1      2        0
4    01-04-2011       2.0      0.0       7.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
467  12-27-2010       4.0      3.0       2.0       1      2        0
468  12-28-2010       4.0      0.0       5.0       1      2        0
469  12-29-2010       6.0      1.0       2.0       1      2        0
470  12-30-2010       3.0      1.0       5.0       1      2        0
471  05-02-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   HDD0806
1             0   HDD0806
2             0   HDD0806
3             0   HDD0806
4             0   HDD0806
..          ...       ...
467           0   HDD0806
468           0   HDD0806
469           0   HDD0806
470           0   HDD0806
471           0   HDD0806

[472 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1      1.0
1    01-04-2010       1.0      1.0       7.0       1      1      2.0
2    01-04-2011       5.0      0.0       4.0       1      1      2.0
3    01-05-2010       3.0      2.0       4.0       1      1      2.0
4    01-05-2011       2.0      0.0       7.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       2.0       1      1      2.0
342  12-27-2010       0.0      0.0       9.0       1      1      0.0
343  12-28-2010       4.0      0.0       5.0       1      1      2.0
344  12-29-2010       3.0      1.0       5.0       1      1      2.0
345  12-30-2010       5.0      0.0       4.0       1      1      2.0

     Disconnect user_name
0           1.0   HDH0928
1           2.0   HDH0928
2           2.0   HDH0928
3           2.0   HDH0928
4           1.0   HDH0928
..          ...       ...
341         2.0   HDH0928
342         0.0   HDH0928
343         2.0   HDH0928
344         2.0   HDH0928
345         2.0   HDH0928

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  11-04-2010       0.0      0.0       0.0       1      1        0
342  11-09-2010       0.0      0.0       0.0       1      1        0
343  12-08-2010       0.0      0.0       0.0       1      1        0
344  12-16-2010       0.0      0.0       0.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HDJ0446
1             0   HDJ0446
2             0   HDJ0446
3             0   HDJ0446
4             0   HDJ0446
..          ...       ...
341           0   HDJ0446
342           0   HDJ0446
343           0   HDJ0446
344           0   HDJ0446
345           0   HDJ0446

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       7.0       1      1        0
1    01-04-2010       4.0      3.0       8.0       1      1        0
2    01-04-2011       6.0      2.0       7.0       1      1        0
3    01-05-2010       7.0      3.0       5.0       1      1        0
4    01-05-2011       4.0     10.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      5.0       3.0       1      1        0
342  12-28-2010       6.0      1.0       8.0       1      1        0
343  12-29-2010       2.0      2.0      11.0       1      1        0
344  12-30-2010       3.0     11.0       1.0       1      1        0
345  01-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HDL0748
1             0   HDL0748
2             0   HDL0748
3             0   HDL0748
4             0   HDL0748
..          ...       ...
341           0   HDL0748
342           0   HDL0748
343           0   HDL0748
344           0   HDL0748
345           0   HDL0748

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       6      7      5.0
1    01-04-2010       6.0      1.0       4.0       3      4      1.0
2    01-04-2011       5.0      1.0       5.0       3      4      3.0
3    01-05-2010       5.0      0.0       6.0       5      6      4.0
4    01-05-2011       4.0      0.0       7.0       6      7      5.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       4.0       5      6      3.0
342  12-28-2010       3.0      0.0       7.0       4      5      4.0
343  12-29-2010       7.0      0.0       4.0       3      4      5.0
344  07-08-2010       0.0      0.0       0.0       6      6      7.0
345  12-30-2010       0.0      0.0       0.0       5      6      6.0

     Disconnect user_name
0           5.0   HDS0367
1           1.0   HDS0367
2           3.0   HDS0367
3           4.0   HDS0367
4           5.0   HDS0367
..          ...       ...
341         3.0   HDS0367
342         3.0   HDS0367
343         5.0   HDS0367
344         7.0   HDS0367
345         6.0   HDS0367

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       1.0      0.0       2.0       1      1      1.0
1    01-03-2011       1.0      0.0       2.0       1      1      1.0
2    01-04-2010       1.0      0.0       2.0       1      1      0.0
3    01-04-2011       2.0      0.0       1.0       1      1      0.0
4    01-05-2010       1.0      0.0       2.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
259  12-31-2010       2.0      0.0       1.0       1      1      1.0
260  01-07-2010       0.0      0.0       0.0       1      1      1.0
261  08-10-2010       0.0      0.0       0.0       1      1      0.0
262  08-31-2010       0.0      0.0       0.0       1      1      2.0
263  09-16-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   HFB0347
1           1.0   HFB0347
2           0.0   HFB0347
3           0.0   HFB0347
4           0.0   HFB0347
..          ...       ...
259         1.0   HFB0347
260         1.0   HFB0347
261         0.0   HFB0347
262         2.0   HFB0347
263         0.0   HFB0347

[264 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       2.0       1      1        0
342  12-28-2010       2.0      0.0       6.0       1      1        0
343  12-29-2010       5.0      1.0       3.0       1      1        0
344  12-30-2010       3.0      1.0       5.0       1      1        0
345  05-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HGG0240
1             0   HGG0240
2             0   HGG0240
3             0   HGG0240
4             0   HGG0240
..          ...       ...
341           0   HGG0240
342           0   HGG0240
343           0   HGG0240
344           0   HGG0240
345           0   HGG0240

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-11-2010       0.0      0.0       0.0       1      1        0
342  07-08-2010       0.0      0.0       0.0       1      1        0
343  10-06-2010       0.0      0.0       0.0       1      1        0
344  10-25-2010       0.0      0.0       0.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HGH0595
1             0   HGH0595
2             0   HGH0595
3             0   HGH0595
4             0   HGH0595
..          ...       ...
341           0   HGH0595
342           0   HGH0595
343           0   HGH0595
344           0   HGH0595
345           0   HGH0595

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      1.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       6.0       1      1        0
342  12-28-2010       3.0      0.0       7.0       1      1        0
343  12-29-2010       4.0      0.0       6.0       1      1        0
344  12-30-2010       5.0      0.0       5.0       1      1        0
345  05-03-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HGN0287
1             0   HGN0287
2             0   HGN0287
3             0   HGN0287
4             0   HGN0287
..          ...       ...
341           0   HGN0287
342           0   HGN0287
343           0   HGN0287
344           0   HGN0287
345           0   HGN0287

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       7.0       1      1        0
342  12-28-2010       1.0      0.0       8.0       1      1        0
343  12-29-2010       6.0      1.0       2.0       1      1        0
344  12-30-2010       0.0      0.0       9.0       1      1        0
345  11-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HIA0414
1             0   HIA0414
2             0   HIA0414
3             0   HIA0414
4             0   HIA0414
..          ...       ...
341           0   HIA0414
342           0   HIA0414
343           0   HIA0414
344           0   HIA0414
345           0   HIA0414

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       9.0       1      1        0
1    01-04-2010       3.0      0.0       8.0       1      1        0
2    01-04-2011       6.0      0.0       8.0       1      1        0
3    01-05-2010       3.0      1.0      10.0       1      1        0
4    01-05-2011       4.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      0.0       1.0       1      1        0
342  12-28-2010       6.0      0.0       8.0       1      1        0
343  12-29-2010       4.0      0.0      10.0       1      1        0
344  12-30-2010       6.0      0.0       8.0       1      1        0
345  01-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HIW0536
1             0   HIW0536
2             0   HIW0536
3             0   HIW0536
4             0   HIW0536
..          ...       ...
341           0   HIW0536
342           0   HIW0536
343           0   HIW0536
344           0   HIW0536
345           0   HIW0536

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       5.0       1      1        0
2    01-04-2011       0.0      1.0      10.0       1      2        0
3    01-05-2010       4.0      1.0       6.0       1      2        0
4    01-05-2011       8.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2        0
342  12-27-2010       3.0      1.0       7.0       1      2        0
343  12-28-2010       6.0      1.0       2.0       1      1        0
344  12-29-2010       3.0      1.0       6.0       1      2        0
345  12-30-2010       5.0      0.0       6.0       1      2        0

     Disconnect user_name
0             0   HJA0018
1             0   HJA0018
2             0   HJA0018
3             0   HJA0018
4             0   HJA0018
..          ...       ...
341           0   HJA0018
342           0   HJA0018
343           0   HJA0018
344           0   HJA0018
345           0   HJA0018

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      7.0       6.0     1.0    2.0      0.0
1    01-05-2010       4.0      4.0       7.0     1.0    2.0      0.0
2    01-06-2010       2.0     11.0       2.0     1.0    1.0      0.0
3    01-07-2010       2.0      2.0      11.0     1.0    2.0      0.0
4    01-08-2010       5.0      2.0       8.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
237  12-09-2010       7.0      0.0       8.0     1.0    1.0      0.0
238  12-10-2010       9.0      0.0       6.0     1.0    2.0      0.0
239  12-13-2010       8.0      2.0       5.0     1.0    2.0      0.0
240  12-14-2010       5.0      1.0       9.0     1.0    2.0      0.0
241  11-25-2010       0.0      0.0       0.0     1.0    0.0      1.0

     Disconnect user_name
0           0.0   HJB0742
1           0.0   HJB0742
2           0.0   HJB0742
3           0.0   HJB0742
4           0.0   HJB0742
..          ...       ...
237         0.0   HJB0742
238         0.0   HJB0742
239         0.0   HJB0742
240         0.0   HJB0742
241         1.0   HJB0742

[242 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       2.0      0.0       7.0       1      2      1.0
1   01-05-2010       7.0      0.0       2.0       1      2      2.0
2   01-06-2010       4.0      0.0       4.0       2      3      1.0
3   01-07-2010       1.0      2.0       5.0       1      2      0.0
4   01-08-2010       5.0      0.0       3.0       1      2      2.0
5   01-09-2010       5.0      0.0       4.0       1      1      0.0
6   01-11-2010       4.0      1.0       3.0       1      2      1.0
7   01-12-2010       6.0      0.0       2.0       1      2      2.0
8   01-13-2010       3.0      0.0       6.0       1      1      0.0
9   01-14-2010       7.0      0.0       2.0       1      2      2.0
10  01-15-2010       3.0      0.0       6.0       2      3      2.0
11  01-17-2010       4.0      0.0       3.0       1      1      2.0
12  01-18-2010       4.0      2.0       3.0       1      2      1.0
13  01-19-2010       5.0      0.0       4.0       1      2      1.0
14  01-20-2010       6.0      0.0       3.0       1      1      1.0
15  01-21-2010       5.0      1.0       3.0       1      2      0.0
16  01-22-2010       3.0      1.0       4.0       1      2      3.0
17  01-25-2010       5.0      0.0       4.0       1      2      2.0
18  01-26-2010       2.0      1.0       5.0       1      1      0.0
19  01-27-2010       4.0      1.0       4.0       1      2      0.0
20  01-28-2010       2.0      1.0       6.0       1      2      0.0
21  01-29-2010       2.0      0.0       7.0       1      2      0.0
22  02-01-2010       5.0      1.0       3.0       1      2      1.0
23  02-02-2010       6.0      0.0       3.0       1      2      1.0
24  02-03-2010       6.0      0.0       3.0       1      1      1.0

    Disconnect user_name
0          1.0   HJS0072
1          2.0   HJS0072
2          1.0   HJS0072
3          0.0   HJS0072
4          2.0   HJS0072
5          0.0   HJS0072
6          1.0   HJS0072
7          2.0   HJS0072
8          0.0   HJS0072
9          2.0   HJS0072
10         2.0   HJS0072
11         2.0   HJS0072
12         1.0   HJS0072
13         1.0   HJS0072
14         1.0   HJS0072
15         0.0   HJS0072
16         3.0   HJS0072
17         2.0   HJS0072
18         0.0   HJS0072
19         0.0   HJS0072
20         0.0   HJS0072
21         0.0   HJS0072
22         1.0   HJS0072
23         1.0   HJS0072
24         1.0   HJS0072

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
327  12-27-2010       4.0      0.0       5.0       1      1        0
328  12-28-2010       3.0      0.0       1.0       1      1        0
329  12-29-2010       6.0      0.0       3.0       1      1        0
330  12-30-2010       4.0      0.0       5.0       1      1        0
331  04-04-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HKB0418
1             0   HKB0418
2             0   HKB0418
3             0   HKB0418
4             0   HKB0418
..          ...       ...
327           0   HKB0418
328           0   HKB0418
329           0   HKB0418
330           0   HKB0418
331           0   HKB0418

[332 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-05-2011       0.0      0.0       0.0       1      1        0
342  08-05-2010       0.0      0.0       0.0       1      1        0
343  08-06-2010       0.0      0.0       0.0       1      1        0
344  08-12-2010       0.0      0.0       0.0       1      1        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HKF0831
1             0   HKF0831
2             0   HKF0831
3             0   HKF0831
4             0   HKF0831
..          ...       ...
341           0   HKF0831
342           0   HKF0831
343           0   HKF0831
344           0   HKF0831
345           0   HKF0831

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0     1.0    1.0        0
1    01-04-2010       2.0      0.0       2.0     1.0    1.0        0
2    01-04-2011       2.0      0.0      10.0     1.0    1.0        0
3    01-05-2010       4.0      1.0      10.0     1.0    1.0        0
4    01-05-2011       3.0      2.0       9.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0     1.0    1.0        0
342  12-28-2010      11.0      1.0       3.0     1.0    1.0        0
343  12-29-2010      12.0      0.0       3.0     1.0    1.0        0
344  12-30-2010       7.0      0.0       8.0     1.0    1.0        0
345  08-27-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   HKI0171
1             0   HKI0171
2             0   HKI0171
3             0   HKI0171
4             0   HKI0171
..          ...       ...
341           0   HKI0171
342           0   HKI0171
343           0   HKI0171
344           0   HKI0171
345           0   HKI0171

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      11.0      0.0       4.0       2      3        0
1    01-04-2010       9.0      0.0       6.0       1      2        0
2    01-04-2011       9.0      0.0       6.0       1      2        0
3    01-05-2010       9.0      0.0       4.0       1      2        0
4    01-05-2011       7.0      1.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       9.0       1      2        0
342  12-27-2010       6.0      0.0       8.0       1      2        0
343  12-28-2010       5.0      1.0       9.0       2      3        0
344  12-29-2010       7.0      1.0       7.0       1      2        0
345  12-30-2010       5.0      1.0       9.0       1      2        0

     Disconnect user_name
0             0   HKR0628
1             0   HKR0628
2             0   HKR0628
3             0   HKR0628
4             0   HKR0628
..          ...       ...
341           0   HKR0628
342           0   HKR0628
343           0   HKR0628
344           0   HKR0628
345           0   HKR0628

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       3.0       1      1        0
1    01-02-2010       0.0      0.0       3.0       1      1        0
2    01-02-2011       3.0      0.0       0.0       1      1        0
3    01-03-2010       0.0      0.0       3.0       1      1        0
4    01-03-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
487  12-31-2010       0.0      0.0       3.0       1      1        0
488  01-29-2010       0.0      0.0       0.0       1      1        0
489  05-09-2011       0.0      0.0       0.0       1      1        0
490  06-01-2010       0.0      0.0       0.0       1      1        0
491  06-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HLH0512
1             0   HLH0512
2             0   HLH0512
3             0   HLH0512
4             0   HLH0512
..          ...       ...
487           0   HLH0512
488           0   HLH0512
489           0   HLH0512
490           0   HLH0512
491           0   HLH0512

[492 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       7.0      0.0       2.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       5.0      1.0       3.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   HLM0933
1             0   HLM0933
2             0   HLM0933
3             0   HLM0933
4             0   HLM0933
..          ...       ...
341           0   HLM0933
342           0   HLM0933
343           0   HLM0933
344           0   HLM0933
345           0   HLM0933

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       2.0      1.0       7.0       2      3      1.0
1   01-05-2010       2.0      1.0       7.0       1      2      2.0
2   01-06-2010       3.0      2.0       4.0       2      2      1.0
3   01-07-2010       2.0      1.0       7.0       1      2      1.0
4   01-08-2010       4.0      1.0       5.0       1      2      2.0
5   01-11-2010       2.0      0.0       8.0       2      2      2.0
6   01-12-2010       5.0      1.0       4.0       2      3      2.0
7   01-13-2010       1.0      0.0       9.0       1      2      1.0
8   01-14-2010       7.0      0.0       2.0       2      3      2.0
9   01-15-2010       0.0      1.0       9.0       1      2      3.0
10  01-18-2010       3.0      0.0       6.0       2      2      2.0
11  01-19-2010       3.0      0.0       7.0       2      3      1.0
12  01-20-2010       0.0      0.0       9.0       1      2      0.0
13  01-21-2010       5.0      0.0       4.0       1      2      3.0
14  01-22-2010       8.0      0.0       2.0       2      2      3.0
15  01-25-2010       1.0      1.0       8.0       2      3      2.0
16  01-26-2010       6.0      0.0       4.0       1      2      1.0
17  01-27-2010       6.0      2.0       2.0       2      2      4.0
18  01-28-2010       4.0      0.0       5.0       2      2      1.0
19  01-29-2010       3.0      1.0       6.0       1      2      0.0
20  02-01-2010       4.0      0.0       6.0       2      2      2.0
21  02-02-2010       3.0      0.0       7.0       1      2      1.0
22  02-03-2010       1.0      1.0       8.0       1      2      2.0
23  02-04-2010       3.0      1.0       6.0       1      2      2.0
24  02-05-2010       4.0      0.0       6.0       1      2      0.0
25  02-08-2010       3.0      1.0       6.0       2      3      3.0
26  02-09-2010       4.0      0.0       6.0       1      2      3.0
27  02-10-2010       4.0      0.0       6.0       1      2      1.0
28  02-11-2010       0.0      1.0       8.0       2      2      2.0
29  02-12-2010       2.0      2.0       5.0       1      2      2.0
30  02-15-2010       5.0      0.0       5.0       2      2      2.0
31  02-16-2010       3.0      0.0       7.0       1      2      0.0
32  02-17-2010       2.0      0.0       8.0       2      2      1.0
33  02-18-2010       3.0      1.0       6.0       1      2      2.0
34  02-19-2010       4.0      2.0       4.0       2      3      3.0
35  02-22-2010       1.0      1.0       8.0       1      2      1.0
36  02-23-2010       2.0      0.0       8.0       2      2      3.0
37  02-24-2010       1.0      0.0       9.0       1      2      2.0
38  02-25-2010       3.0      0.0       7.0       1      2      2.0
39  02-26-2010       3.0      0.0       7.0       1      2      1.0
40  03-01-2010       6.0      0.0       4.0       2      3      2.0
41  03-02-2010       6.0      0.0       4.0       1      2      2.0
42  03-03-2010       5.0      3.0       2.0       1      2      2.0
43  03-04-2010       4.0      0.0       6.0       2      3      2.0
44  03-05-2010       5.0      0.0       5.0       1      2      2.0
45  03-08-2010       4.0      0.0       6.0       1      2      2.0
46  03-09-2010       4.0      2.0       4.0       2      2      2.0
47  03-10-2010       3.0      0.0       7.0       2      2      2.0
48  03-11-2010       3.0      0.0       7.0       1      2      1.0
49  03-12-2010       6.0      0.0       4.0       2      2      2.0
50  03-15-2010       3.0      0.0       7.0       2      3      3.0
51  03-16-2010       2.0      1.0       5.0       1      2      3.0
52  03-17-2010       3.0      1.0       6.0       1      2      1.0
53  03-18-2010       5.0      1.0       4.0       2      2      3.0
54  03-19-2010       6.0      0.0       4.0       1      2      2.0

    Disconnect user_name
0          1.0   HMM0108
1          2.0   HMM0108
2          1.0   HMM0108
3          1.0   HMM0108
4          2.0   HMM0108
5          2.0   HMM0108
6          2.0   HMM0108
7          1.0   HMM0108
8          2.0   HMM0108
9          3.0   HMM0108
10         2.0   HMM0108
11         1.0   HMM0108
12         0.0   HMM0108
13         3.0   HMM0108
14         3.0   HMM0108
15         2.0   HMM0108
16         1.0   HMM0108
17         4.0   HMM0108
18         1.0   HMM0108
19         0.0   HMM0108
20         2.0   HMM0108
21         1.0   HMM0108
22         2.0   HMM0108
23         2.0   HMM0108
24         0.0   HMM0108
25         3.0   HMM0108
26         3.0   HMM0108
27         1.0   HMM0108
28         2.0   HMM0108
29         2.0   HMM0108
30         2.0   HMM0108
31         0.0   HMM0108
32         1.0   HMM0108
33         2.0   HMM0108
34         3.0   HMM0108
35         1.0   HMM0108
36         3.0   HMM0108
37         2.0   HMM0108
38         2.0   HMM0108
39         1.0   HMM0108
40         1.0   HMM0108
41         2.0   HMM0108
42         2.0   HMM0108
43         2.0   HMM0108
44         2.0   HMM0108
45         2.0   HMM0108
46         2.0   HMM0108
47         2.0   HMM0108
48         1.0   HMM0108
49         2.0   HMM0108
50         3.0   HMM0108
51         2.0   HMM0108
52         1.0   HMM0108
53         3.0   HMM0108
54         2.0   HMM0108
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-20-2010       0.0      0.0       0.0       1      1        0
342  11-03-2010       0.0      0.0       0.0       1      1        0
343  11-08-2010       0.0      0.0       0.0       1      1        0
344  11-19-2010       0.0      0.0       0.0       1      1        0
345  12-03-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HMW0713
1             0   HMW0713
2             0   HMW0713
3             0   HMW0713
4             0   HMW0713
..          ...       ...
341           0   HMW0713
342           0   HMW0713
343           0   HMW0713
344           0   HMW0713
345           0   HMW0713

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      6.0       2.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       5.0      2.0       2.0       1      1        0
3    01-05-2010       4.0      2.0       2.0       1      1        0
4    01-06-2010       5.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       5.0      1.0       3.0       1      1        0
342  12-30-2010       0.0      9.0       0.0       1      1        0
343  01-05-2011       0.0      0.0       0.0       1      1        0
344  04-01-2010       0.0      0.0       0.0       1      1        0
345  06-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HOB0994
1             0   HOB0994
2             0   HOB0994
3             0   HOB0994
4             0   HOB0994
..          ...       ...
341           0   HOB0994
342           0   HOB0994
343           0   HOB0994
344           0   HOB0994
345           0   HOB0994

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010      15.0      0.0       4.0       1      2        7
1    01-02-2011       8.0      1.0       9.0       1      2        9
2    01-03-2011       9.0      0.0      10.0       1      1        7
3    01-04-2010       7.0      1.0      11.0       1      2        7
4    01-04-2011       8.0      0.0      11.0       1      2        8
..          ...       ...      ...       ...     ...    ...      ...
399  12-26-2010       9.0      1.0       8.0       1      2        8
400  12-27-2010       9.0      0.0      10.0       1      2        8
401  12-28-2010       8.0      1.0       6.0       1      1        8
402  12-29-2010      11.0      0.0       7.0       1      2        9
403  12-30-2010      12.0      1.0       6.0       1      2        9

     Disconnect user_name
0             7   HPH0075
1             9   HPH0075
2             7   HPH0075
3             7   HPH0075
4             8   HPH0075
..          ...       ...
399           8   HPH0075
400           8   HPH0075
401           7   HPH0075
402           9   HPH0075
403           9   HPH0075

[404 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       1      1        0
1    01-04-2010       7.0      1.0       6.0       1      1        0
2    01-04-2011       8.0      0.0       6.0       1      1        0
3    01-05-2010       5.0      0.0       9.0       1      1        0
4    01-05-2011       3.0      2.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       9.0       1      1        0
342  12-27-2010       8.0      0.0       6.0       1      1        0
343  12-28-2010       3.0      0.0      11.0       1      1        0
344  12-29-2010       5.0      2.0       7.0       1      1        0
345  12-30-2010       5.0      1.0       8.0       1      1        0

     Disconnect user_name
0             0   HPM0986
1             0   HPM0986
2             0   HPM0986
3             0   HPM0986
4             0   HPM0986
..          ...       ...
341           0   HPM0986
342           0   HPM0986
343           0   HPM0986
344           0   HPM0986
345           0   HPM0986

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-16-2010       0.0      0.0       0.0       1      2        0
342  07-28-2010       0.0      0.0       0.0       1      2        0
343  08-06-2010       0.0      0.0       0.0       1      2        0
344  10-15-2010       0.0      0.0       0.0       1      2        0
345  10-18-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   HPR0585
1             0   HPR0585
2             0   HPR0585
3             0   HPR0585
4             0   HPR0585
..          ...       ...
341           0   HPR0585
342           0   HPR0585
343           0   HPR0585
344           0   HPR0585
345           0   HPR0585

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       8.0      0.0      10.0       1      2      0.0
1    01-03-2011       7.0      0.0      11.0       1      2      0.0
2    01-04-2010       6.0      1.0      11.0       1      2      0.0
3    01-04-2011      12.0      1.0       4.0       1      2      0.0
4    01-05-2010      12.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
378  12-27-2010      11.0      1.0       6.0       1      2      1.0
379  12-28-2010       8.0      0.0      10.0       1      2      0.0
380  12-29-2010      10.0      0.0       8.0       1      2      0.0
381  12-30-2010      13.0      0.0       4.0       1      2      0.0
382  12-31-2010       7.0      1.0      10.0       2      3      1.0

     Disconnect user_name
0           0.0   HRB0351
1           0.0   HRB0351
2           0.0   HRB0351
3           0.0   HRB0351
4           0.0   HRB0351
..          ...       ...
378         1.0   HRB0351
379         0.0   HRB0351
380         0.0   HRB0351
381         0.0   HRB0351
382         1.0   HRB0351

[383 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       1.0      0.0       2.0       1      1        0
1   01-05-2010       1.0      0.0       2.0       1      2        0
2   01-06-2010       1.0      0.0       2.0       2      3        0
3   01-07-2010       0.0      0.0       3.0       2      3        0
4   01-08-2010       1.0      0.0       2.0       1      2        0
..         ...       ...      ...       ...     ...    ...      ...
85  05-04-2010       0.0      0.0       3.0       1      2        0
86  05-05-2010       1.0      0.0       2.0       1      2        0
87  05-06-2010       1.0      0.0       2.0       1      2        0
88  05-07-2010       0.0      0.0       3.0       2      3        0
89  05-10-2010       0.0      0.0       3.0       2      3        0

    Disconnect user_name
0            0   HRD0635
1            0   HRD0635
2            0   HRD0635
3            0   HRD0635
4            0   HRD0635
..         ...       ...
85           0   HRD0635
86           0   HRD0635
87           0   HRD0635
88           0   HRD0635
89           0   HRD0635

[90 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1      7.0
1    01-04-2010       4.0      1.0       4.0       1      1      9.0
2    01-04-2011       5.0      0.0       4.0       1      2      9.0
3    01-05-2010       2.0      0.0       7.0       1      2      9.0
4    01-05-2011       2.0      1.0       6.0       1      2      9.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       8.0       1      1      9.0
342  12-29-2010       3.0      0.0       6.0       1      2      9.0
343  12-30-2010       3.0      0.0       6.0       1      2      9.0
344  03-09-2010       0.0      0.0       0.0       1      1      0.0
345  03-21-2011       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           7.0   HRL0540
1           9.0   HRL0540
2           9.0   HRL0540
3           9.0   HRL0540
4           9.0   HRL0540
..          ...       ...
341         9.0   HRL0540
342         9.0   HRL0540
343         9.0   HRL0540
344         0.0   HRL0540
345         0.0   HRL0540

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       4.0      2.0       3.0       1      1        0
4    01-05-2011       5.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      1.0       3.0       1      1        0
342  12-29-2010       5.0      1.0       3.0       1      1        0
343  12-30-2010       4.0      0.0       4.0       1      1        0
344  07-21-2010       0.0      0.0       0.0       1      1        0
345  10-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HRW0550
1             0   HRW0550
2             0   HRW0550
3             0   HRW0550
4             0   HRW0550
..          ...       ...
341           0   HRW0550
342           0   HRW0550
343           0   HRW0550
344           0   HRW0550
345           0   HRW0550

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       4.0      5.0       2.0       1      1        9
1    01-02-2011       4.0      1.0       6.0       1      1        9
2    01-03-2010       0.0      6.0       1.0       1      1        9
3    01-03-2011       5.0      0.0       6.0       1      1        7
4    01-04-2010       4.0      3.0       3.0       1      1        8
..          ...       ...      ...       ...     ...    ...      ...
470  12-27-2010       8.0      1.0       1.0       1      1        8
471  12-28-2010       1.0      5.0       5.0       1      1        8
472  12-29-2010       1.0      3.0       7.0       1      1        6
473  12-30-2010       0.0      1.0      10.0       1      1        9
474  12-31-2010       2.0      0.0       9.0       1      1        5

     Disconnect user_name
0             9   HSB0196
1             9   HSB0196
2             9   HSB0196
3             7   HSB0196
4             8   HSB0196
..          ...       ...
470           8   HSB0196
471           8   HSB0196
472           6   HSB0196
473           9   HSB0196
474           5   HSB0196

[475 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-29-2010       0.0      0.0       0.0       1      1        0
342  04-16-2010       0.0      0.0       0.0       1      1        0
343  05-13-2011       0.0      0.0       0.0       1      1        0
344  08-20-2010       0.0      0.0       0.0       1      1        0
345  10-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HSD0457
1             0   HSD0457
2             0   HSD0457
3             0   HSD0457
4             0   HSD0457
..          ...       ...
341           0   HSD0457
342           0   HSD0457
343           0   HSD0457
344           0   HSD0457
345           0   HSD0457

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      2        0
1    01-04-2010       5.0      0.0       4.0       1      2        0
2    01-04-2011       4.0      0.0       5.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       2.0      2.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       3.0       1      2        0
342  12-28-2010       6.0      0.0       3.0       1      1        0
343  12-29-2010       1.0      2.0       6.0       1      2        0
344  12-30-2010       3.0      0.0       6.0       1      2        0
345  06-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HSG0818
1             0   HSG0818
2             0   HSG0818
3             0   HSG0818
4             0   HSG0818
..          ...       ...
341           0   HSG0818
342           0   HSG0818
343           0   HSG0818
344           0   HSG0818
345           0   HSG0818

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-20-2010       0.0      0.0       0.0       1      1        0
342  04-21-2010       0.0      0.0       0.0       1      1        0
343  04-26-2010       0.0      0.0       0.0       1      1        0
344  11-15-2010       0.0      0.0       0.0       1      1        0
345  12-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HSP0290
1             0   HSP0290
2             0   HSP0290
3             0   HSP0290
4             0   HSP0290
..          ...       ...
341           0   HSP0290
342           0   HSP0290
343           0   HSP0290
344           0   HSP0290
345           0   HSP0290

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      1.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       0.0      1.0       2.0       1      1        0
342  12-27-2010       0.0      2.0       1.0       1      1        0
343  12-28-2010       0.0      0.0       3.0       1      1        0
344  12-29-2010       0.0      0.0       3.0       1      1        0
345  12-30-2010       1.0      0.0       2.0       1      1        0

     Disconnect user_name
0             0   HTF0641
1             0   HTF0641
2             0   HTF0641
3             0   HTF0641
4             0   HTF0641
..          ...       ...
341           0   HTF0641
342           0   HTF0641
343           0   HTF0641
344           0   HTF0641
345           0   HTF0641

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0      17.0       1      1        0
1    01-04-2010      14.0      0.0      13.0       1      2        0
2    01-04-2011       4.0      0.0      23.0       1      2        0
3    01-05-2010      11.0      1.0      15.0       1      2        0
4    01-05-2011       5.0      2.0      19.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0      20.0       1      2        0
342  12-27-2010      12.0      1.0      14.0       1      2        0
343  12-28-2010       7.0      0.0      20.0       1      1        0
344  12-29-2010       7.0      0.0      20.0       1      2        0
345  12-30-2010      16.0      0.0      11.0       1      2        0

     Disconnect user_name
0             0   HTH0007
1             0   HTH0007
2             0   HTH0007
3             0   HTH0007
4             0   HTH0007
..          ...       ...
341           0   HTH0007
342           0   HTH0007
343           0   HTH0007
344           0   HTH0007
345           0   HTH0007

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       3.0      1.0      10.0       1      1        0
1    01-02-2010       4.0      0.0       8.0       1      1        0
2    01-02-2011       2.0      1.0      11.0       1      1        0
3    01-03-2011       8.0      1.0       5.0       1      1        0
4    01-04-2010       7.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
398  12-28-2010       5.0      0.0       8.0       1      1        0
399  12-29-2010       8.0      0.0       6.0       1      1        0
400  12-30-2010       5.0      0.0       9.0       1      1        0
401  12-31-2010       6.0      0.0       8.0       1      1        0
402  11-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HVB0037
1             0   HVB0037
2             0   HVB0037
3             0   HVB0037
4             0   HVB0037
..          ...       ...
398           0   HVB0037
399           0   HVB0037
400           0   HVB0037
401           0   HVB0037
402           0   HVB0037

[403 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1      2.0
1    01-04-2010       1.0      1.0       3.0       1      2      4.0
2    01-04-2011       4.0      1.0       4.0       1      2      2.0
3    01-05-2010       3.0      0.0       6.0       1      2      1.0
4    01-05-2011       5.0      1.0       3.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      2.0       5.0       1      2      2.0
342  12-27-2010       5.0      1.0       3.0       1      2      2.0
343  12-28-2010       2.0      0.0       7.0       1      1      2.0
344  12-29-2010       4.0      0.0       5.0       1      2      3.0
345  12-30-2010       1.0      3.0       5.0       1      2      2.0

     Disconnect user_name
0           2.0   HVF0067
1           4.0   HVF0067
2           2.0   HVF0067
3           1.0   HVF0067
4           2.0   HVF0067
..          ...       ...
341         2.0   HVF0067
342         2.0   HVF0067
343         2.0   HVF0067
344         3.0   HVF0067
345         2.0   HVF0067

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      2        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       0.0      0.0       3.0       1      2        0
4    01-05-2011       2.0      1.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      2        0
342  12-28-2010       1.0      1.0       1.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      2        0
344  12-30-2010       2.0      0.0       1.0       1      2        0
345  03-08-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   HWH0646
1             0   HWH0646
2             0   HWH0646
3             0   HWH0646
4             0   HWH0646
..          ...       ...
341           0   HWH0646
342           0   HWH0646
343           0   HWH0646
344           0   HWH0646
345           0   HWH0646

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      1.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       0.0      1.0       2.0       1      1        0
344  02-22-2010       0.0      0.0       0.0       1      1        0
345  05-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   HWM0342
1             0   HWM0342
2             0   HWM0342
3             0   HWM0342
4             0   HWM0342
..          ...       ...
341           0   HWM0342
342           0   HWM0342
343           0   HWM0342
344           0   HWM0342
345           0   HWM0342

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       7.0     1.0    2.0      1.0
1    01-04-2010       4.0      0.0       5.0     2.0    2.0      2.0
2    01-04-2011       5.0      0.0       5.0     1.0    2.0      2.0
3    01-05-2010       2.0      0.0       7.0     1.0    2.0      2.0
4    01-05-2011       7.0      1.0       2.0     1.0    2.0      3.0
..          ...       ...      ...       ...     ...    ...      ...
345  05-06-2010       0.0      0.0       0.0     1.0    2.0      0.0
346  08-21-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  10-04-2010       0.0      0.0       0.0     1.0    2.0      1.0
348  11-02-2010       0.0      0.0       0.0     1.0    2.0      1.0
349  11-23-2010       0.0      0.0       0.0     3.0    3.0      1.0

     Disconnect user_name
0           1.0   HWW0436
1           2.0   HWW0436
2           1.0   HWW0436
3           2.0   HWW0436
4           3.0   HWW0436
..          ...       ...
345         0.0   HWW0436
346         0.0   HWW0436
347         1.0   HWW0436
348         1.0   HWW0436
349         1.0   HWW0436

[350 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0       6.0       6      6        0
1    01-05-2010       2.0      2.0       6.0       2      2        0
2    01-06-2010       6.0      0.0       4.0       2      2        0
3    01-07-2010       4.0      0.0       7.0       5      5        0
4    01-08-2010       5.0      1.0       5.0       6      6        0
..          ...       ...      ...       ...     ...    ...      ...
103  05-28-2010       1.0      1.0       8.0       2      2        0
104  06-01-2010       2.0      1.0       8.0       5      5        0
105  06-02-2010       1.0      0.0      10.0       4      4        0
106  06-03-2010       5.0      0.0       6.0       6      6        0
107  06-04-2010       0.0      0.0       2.0       4      4        0

     Disconnect user_name
0             0   HWY0038
1             0   HWY0038
2             0   HWY0038
3             0   HWY0038
4             0   HWY0038
..          ...       ...
103           0   HWY0038
104           0   HWY0038
105           0   HWY0038
106           0   HWY0038
107           0   HWY0038

[108 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1      3.0
1    01-05-2010       1.0      0.0       0.0       1      1      2.0
2    01-06-2010       0.0      0.0       1.0       1      1      2.0
3    01-07-2010       0.0      0.0       1.0       1      1      3.0
4    01-11-2010       1.0      0.0       0.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
206  04-13-2010       0.0      0.0       0.0       1      1      2.0
207  04-30-2010       0.0      0.0       0.0       1      1      3.0
208  05-05-2010       0.0      0.0       0.0       1      1      4.0
209  07-09-2010       0.0      0.0       0.0       1      1      2.0
210  09-27-2010       0.0      0.0       0.0       1      1      3.0

     Disconnect user_name
0           3.0   HXL0968
1           2.0   HXL0968
2           2.0   HXL0968
3           3.0   HXL0968
4           2.0   HXL0968
..          ...       ...
206         2.0   HXL0968
207         3.0   HXL0968
208         4.0   HXL0968
209         2.0   HXL0968
210         3.0   HXL0968

[211 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      1.0       3.0       2      2        0
1    01-02-2010       6.0      0.0       3.0       1      1        0
2    01-02-2011       3.0      1.0       5.0       1      2        0
3    01-03-2011       5.0      0.0       4.0       1      2        0
4    01-04-2010       3.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
399  12-31-2010       3.0      2.0       4.0       1      2        0
400  03-07-2011       0.0      0.0       0.0       1      2        0
401  05-03-2010       0.0      0.0       0.0       2      3        0
402  05-17-2010       0.0      0.0       0.0       1      2        0
403  06-01-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   IAR0694
1             0   IAR0694
2             0   IAR0694
3             0   IAR0694
4             0   IAR0694
..          ...       ...
399           0   IAR0694
400           0   IAR0694
401           0   IAR0694
402           0   IAR0694
403           0   IAR0694

[404 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1        0
1    01-05-2010       2.0      1.0       7.0       1      1        0
2    01-06-2010       4.0      0.0       6.0       1      1        0
3    01-07-2010       3.0      1.0       5.0       1      1        0
4    01-08-2010       3.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
181  09-22-2010       6.0      0.0       4.0       1      1        0
182  09-23-2010       8.0      0.0       1.0       1      1        0
183  09-24-2010       5.0      2.0       3.0       1      1        0
184  01-15-2010       0.0      0.0       0.0       1      1        0
185  05-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IAT0263
1             0   IAT0263
2             0   IAT0263
3             0   IAT0263
4             0   IAT0263
..          ...       ...
181           0   IAT0263
182           0   IAT0263
183           0   IAT0263
184           0   IAT0263
185           0   IAT0263

[186 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       7.0     3.0    4.0      9.0
1    01-04-2010       3.0      0.0       8.0     2.0    3.0      9.0
2    01-04-2011       6.0      0.0       4.0     4.0    5.0     12.0
3    01-05-2010       4.0      3.0       4.0     3.0    4.0     10.0
4    01-05-2011       3.0      1.0       7.0     4.0    5.0     10.0
..          ...       ...      ...       ...     ...    ...      ...
344  12-30-2010       6.0      0.0       5.0     3.0    4.0     11.0
345  01-15-2011       0.0      0.0       0.0     1.0    0.0      0.0
346  04-17-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  04-23-2010       0.0      0.0       0.0     6.0    7.0     12.0
348  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           9.0   IBB0359
1           9.0   IBB0359
2          12.0   IBB0359
3          10.0   IBB0359
4          10.0   IBB0359
..          ...       ...
344        11.0   IBB0359
345         0.0   IBB0359
346         0.0   IBB0359
347        12.0   IBB0359
348         0.0   IBB0359

[349 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       2      2      1.0
1    01-04-2010       0.0      0.0       1.0       1      2      1.0
2    01-04-2011       1.0      0.0       0.0       1      2      2.0
3    01-05-2010       0.0      0.0       1.0       1      2      2.0
4    01-05-2011       0.0      0.0       1.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  06-24-2010       0.0      0.0       0.0       1      2      3.0
342  07-09-2010       0.0      0.0       0.0       1      2      2.0
343  08-03-2010       0.0      0.0       0.0       1      2      4.0
344  09-07-2010       0.0      0.0       0.0       1      1      4.0
345  10-29-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           1.0   IBB0696
1           1.0   IBB0696
2           2.0   IBB0696
3           2.0   IBB0696
4           1.0   IBB0696
..          ...       ...
341         3.0   IBB0696
342         2.0   IBB0696
343         4.0   IBB0696
344         4.0   IBB0696
345         2.0   IBB0696

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       7.0       1      1      0.0
1    01-04-2010       6.0      0.0       4.0       1      2      0.0
2    01-04-2011       1.0      0.0       9.0       1      2      0.0
3    01-05-2010       4.0      0.0       6.0       1      2      0.0
4    01-05-2011       7.0      0.0       3.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       7.0      0.0       3.0       1      1      1.0
342  12-29-2010       3.0      1.0       6.0       1      2      1.0
343  12-30-2010       4.0      0.0       6.0       1      2      0.0
344  03-31-2010       0.0      0.0       0.0       1      2      0.0
345  08-27-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   IBM0671
1           0.0   IBM0671
2           0.0   IBM0671
3           0.0   IBM0671
4           0.0   IBM0671
..          ...       ...
341         1.0   IBM0671
342         1.0   IBM0671
343         0.0   IBM0671
344         0.0   IBM0671
345         1.0   IBM0671

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0     1.0    1.0        0
1    01-04-2010       1.0      0.0       2.0     1.0    2.0        0
2    01-04-2011       1.0      0.0       2.0     2.0    3.0        0
3    01-05-2010       1.0      0.0       2.0     1.0    2.0        0
4    01-05-2011       1.0      1.0       1.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
348  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
349  10-02-2010       0.0      0.0       0.0     1.0    1.0        0
350  10-18-2010       0.0      0.0       0.0     1.0    1.0        0
351  11-06-2010       0.0      0.0       0.0     1.0    1.0        0
352  12-04-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   IBP0883
1             0   IBP0883
2             0   IBP0883
3             0   IBP0883
4             0   IBP0883
..          ...       ...
348           0   IBP0883
349           0   IBP0883
350           0   IBP0883
351           0   IBP0883
352           0   IBP0883

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       1.0      0.0       0.0       2      3      0.0
1    01-03-2011       0.0      0.0       1.0       1      1      2.0
2    01-04-2010       1.0      0.0       0.0       1      2      2.0
3    01-04-2011       0.0      0.0       1.0       1      2      1.0
4    01-05-2010       0.0      1.0       0.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
379  11-04-2010       0.0      0.0       0.0       1      1      0.0
380  11-24-2010       0.0      0.0       0.0       1      2      0.0
381  11-26-2010       0.0      0.0       0.0       1      2      0.0
382  12-10-2010       0.0      0.0       0.0       2      3      2.0
383  12-31-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   IBS0836
1           2.0   IBS0836
2           2.0   IBS0836
3           1.0   IBS0836
4           0.0   IBS0836
..          ...       ...
379         0.0   IBS0836
380         0.0   IBS0836
381         0.0   IBS0836
382         2.0   IBS0836
383         0.0   IBS0836

[384 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2      2.0
1    01-04-2010       0.0      0.0       1.0       1      1      1.0
2    01-04-2011       0.0      0.0       1.0       1      1      2.0
3    01-05-2010       1.0      0.0       0.0       1      1      3.0
4    01-05-2011       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  04-20-2010       0.0      0.0       0.0       1      1      2.0
342  05-06-2010       0.0      0.0       0.0       1      1      2.0
343  09-17-2010       0.0      0.0       0.0       1      1      3.0
344  10-08-2010       0.0      0.0       0.0       1      1      3.0
345  11-17-2010       0.0      0.0       0.0       2      2      2.0

     Disconnect user_name
0           2.0   ICH0294
1           1.0   ICH0294
2           2.0   ICH0294
3           3.0   ICH0294
4           0.0   ICH0294
..          ...       ...
341         2.0   ICH0294
342         2.0   ICH0294
343         3.0   ICH0294
344         3.0   ICH0294
345         2.0   ICH0294

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-05-2010       0.0      0.0       1.0       1      1        0
2    01-06-2010       1.0      0.0       0.0       1      1        0
3    01-07-2010       1.0      0.0       0.0       1      1        0
4    01-08-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
246  03-02-2010       0.0      0.0       0.0       1      1        0
247  09-03-2010       0.0      0.0       0.0       1      1        0
248  09-13-2010       0.0      0.0       0.0       1      1        0
249  09-21-2010       0.0      0.0       0.0       1      1        0
250  12-03-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ICS0956
1             0   ICS0956
2             0   ICS0956
3             0   ICS0956
4             0   ICS0956
..          ...       ...
246           0   ICS0956
247           0   ICS0956
248           0   ICS0956
249           0   ICS0956
250           0   ICS0956

[251 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       8.0       1      1        0
1    01-04-2010       8.0      1.0       6.0       1      1        0
2    01-04-2011       4.0      0.0      11.0       1      1        0
3    01-05-2010       9.0      1.0       5.0       1      1        0
4    01-05-2011       6.0      2.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      11.0      0.0       4.0       1      1        0
342  12-28-2010       6.0      0.0       9.0       1      1        0
343  12-29-2010       8.0      0.0       7.0       1      1        0
344  12-30-2010       4.0      0.0      11.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IDO0176
1             0   IDO0176
2             0   IDO0176
3             0   IDO0176
4             0   IDO0176
..          ...       ...
341           0   IDO0176
342           0   IDO0176
343           0   IDO0176
344           0   IDO0176
345           0   IDO0176

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       4.0      0.0       1.0       1      1        0
1    01-02-2011       4.0      0.0       1.0       1      1        0
2    01-03-2011       2.0      0.0       3.0       1      1        0
3    01-04-2010       2.0      0.0       3.0       1      1        0
4    01-04-2011       2.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
367  12-27-2010       4.0      0.0       1.0       1      1        0
368  12-28-2010       3.0      0.0       2.0       1      1        0
369  12-29-2010       2.0      0.0       3.0       1      1        0
370  12-30-2010       2.0      0.0       3.0       1      1        0
371  03-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IEB0153
1             0   IEB0153
2             0   IEB0153
3             0   IEB0153
4             0   IEB0153
..          ...       ...
367           0   IEB0153
368           0   IEB0153
369           0   IEB0153
370           0   IEB0153
371           0   IEB0153

[372 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-19-2011       0.0      0.0       0.0       1      1        0
342  05-27-2010       0.0      0.0       0.0       1      1        0
343  06-02-2010       0.0      0.0       0.0       1      1        0
344  07-30-2010       0.0      0.0       0.0       1      1        0
345  11-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IHK0841
1             0   IHK0841
2             0   IHK0841
3             0   IHK0841
4             0   IHK0841
..          ...       ...
341           0   IHK0841
342           0   IHK0841
343           0   IHK0841
344           0   IHK0841
345           0   IHK0841

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       2.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       7.0      0.0       1.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       2.0      1.0       6.0       1      1        0
343  12-29-2010       4.0      1.0       4.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  04-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IIA0092
1             0   IIA0092
2             0   IIA0092
3             0   IIA0092
4             0   IIA0092
..          ...       ...
341           0   IIA0092
342           0   IIA0092
343           0   IIA0092
344           0   IIA0092
345           0   IIA0092

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       3.0       1      1        0
1    01-03-2010       0.0      0.0       3.0       1      1        0
2    01-03-2011       1.0      0.0       2.0       1      1        0
3    01-04-2010       0.0      0.0       3.0       1      1        0
4    01-04-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
434  12-29-2010       1.0      0.0       2.0       1      1        0
435  12-30-2010       1.0      0.0       2.0       1      1        0
436  05-04-2011       0.0      0.0       0.0       1      1        0
437  06-10-2010       0.0      0.0       0.0       1      1        0
438  09-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IIL0513
1             0   IIL0513
2             0   IIL0513
3             0   IIL0513
4             0   IIL0513
..          ...       ...
434           0   IIL0513
435           0   IIL0513
436           0   IIL0513
437           0   IIL0513
438           0   IIL0513

[439 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      0.0       6.0     1.0    1.0      9.0
1    01-02-2011       4.0      0.0       5.0     1.0    1.0      7.0
2    01-03-2011       4.0      0.0       5.0     1.0    1.0      9.0
3    01-04-2010       5.0      1.0       3.0     1.0    1.0      8.0
4    01-04-2011       4.0      0.0       5.0     1.0    1.0      9.0
..          ...       ...      ...       ...     ...    ...      ...
394  08-28-2010       0.0      0.0       0.0     1.0    1.0      0.0
395  11-18-2010       0.0      0.0       0.0     1.0    1.0      9.0
396  12-04-2010       0.0      0.0       0.0     1.0    0.0      0.0
397  12-24-2010       0.0      0.0       0.0     1.0    1.0      0.0
398  12-28-2010       0.0      0.0       0.0     1.0    1.0      8.0

     Disconnect user_name
0           9.0   IIW0249
1           7.0   IIW0249
2           9.0   IIW0249
3           8.0   IIW0249
4           9.0   IIW0249
..          ...       ...
394         0.0   IIW0249
395         9.0   IIW0249
396         0.0   IIW0249
397         0.0   IIW0249
398         8.0   IIW0249

[399 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-05-2010       1.0      0.0       0.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-01-2010       0.0      0.0       0.0       1      1        0
342  04-07-2011       0.0      0.0       0.0       1      1        0
343  04-18-2011       0.0      0.0       0.0       1      1        0
344  07-08-2010       0.0      0.0       0.0       1      1        0
345  08-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IJM0139
1             0   IJM0139
2             0   IJM0139
3             0   IJM0139
4             0   IJM0139
..          ...       ...
341           0   IJM0139
342           0   IJM0139
343           0   IJM0139
344           0   IJM0139
345           0   IJM0139

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0     1.0    1.0      1.0
1    01-04-2011       1.0      3.0       5.0     1.0    2.0      0.0
2    01-05-2010       0.0      0.0       4.0     1.0    2.0      1.0
3    01-05-2011       6.0      0.0       3.0     1.0    2.0      0.0
4    01-06-2010       4.0      0.0       5.0     1.0    1.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
343  12-29-2010       0.0      2.0       7.0     1.0    2.0      2.0
344  12-30-2010       2.0      0.0       7.0     1.0    2.0      0.0
345  01-04-2010       0.0      0.0       0.0     2.0    3.0      1.0
346  08-21-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           1.0   IJM0444
1           0.0   IJM0444
2           1.0   IJM0444
3           0.0   IJM0444
4           2.0   IJM0444
..          ...       ...
343         2.0   IJM0444
344         0.0   IJM0444
345         1.0   IJM0444
346         0.0   IJM0444
347         0.0   IJM0444

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0       1      1      3.0
1    01-05-2010       1.0      0.0       2.0       1      1      1.0
2    01-06-2010       0.0      0.0       3.0       1      1      0.0
3    01-07-2010       1.0      0.0       2.0       1      1      2.0
4    01-08-2010       1.0      0.0       2.0       1      1      4.0
..          ...       ...      ...       ...     ...    ...      ...
166  08-27-2010       0.0      0.0       3.0       1      1      1.0
167  08-30-2010       1.0      1.0       1.0       1      1      3.0
168  08-31-2010       1.0      1.0       1.0       1      1      1.0
169  09-01-2010       0.0      0.0       3.0       1      1      7.0
170  09-02-2010       0.0      0.0       3.0       1      1      2.0

     Disconnect user_name
0           3.0   IJM0776
1           1.0   IJM0776
2           0.0   IJM0776
3           1.0   IJM0776
4           4.0   IJM0776
..          ...       ...
166         0.0   IJM0776
167         3.0   IJM0776
168         1.0   IJM0776
169         7.0   IJM0776
170         2.0   IJM0776

[171 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-29-2011       0.0      0.0       0.0       1      1        0
342  05-03-2011       0.0      0.0       0.0       1      1        0
343  05-09-2011       0.0      0.0       0.0       1      1        0
344  07-02-2010       0.0      0.0       0.0       1      1        0
345  09-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IJR0825
1             0   IJR0825
2             0   IJR0825
3             0   IJR0825
4             0   IJR0825
..          ...       ...
341           0   IJR0825
342           0   IJR0825
343           0   IJR0825
344           0   IJR0825
345           0   IJR0825

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0      12.0       1      1        0
1    01-04-2010       3.0      1.0       6.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010      12.0      0.0       3.0       1      1        0
4    01-05-2011      10.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0       1      1        0
342  12-28-2010       9.0      2.0       4.0       1      1        0
343  12-29-2010      11.0      0.0       4.0       1      1        0
344  12-30-2010      10.0      1.0       4.0       1      1        0
345  07-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IJW0851
1             0   IJW0851
2             0   IJW0851
3             0   IJW0851
4             0   IJW0851
..          ...       ...
341           0   IJW0851
342           0   IJW0851
343           0   IJW0851
344           0   IJW0851
345           0   IJW0851

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       1      2      2.0
1    01-02-2010       0.0      0.0       1.0       2      3      1.0
2    01-02-2011       0.0      0.0       1.0       1      2      0.0
3    01-03-2010       0.0      0.0       1.0       1      2      0.0
4    01-03-2011       1.0      0.0       0.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
490  10-14-2010       0.0      0.0       0.0       2      2      2.0
491  11-16-2010       0.0      0.0       0.0       1      2      2.0
492  11-21-2010       0.0      0.0       0.0       1      2      1.0
493  12-04-2010       0.0      0.0       0.0       1      2      2.0
494  12-17-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           2.0   IKP0472
1           1.0   IKP0472
2           0.0   IKP0472
3           0.0   IKP0472
4           2.0   IKP0472
..          ...       ...
490         2.0   IKP0472
491         2.0   IKP0472
492         1.0   IKP0472
493         2.0   IKP0472
494         2.0   IKP0472

[495 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       2.0       1      1      1.0
1    01-04-2010       3.0      0.0       4.0       1      1      2.0
2    01-04-2011       4.0      0.0       3.0       1      1      2.0
3    01-05-2010       3.0      1.0       5.0       1      1      2.0
4    01-05-2011       6.0      1.0       1.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
282  12-22-2010       4.0      1.0       3.0       1      1      0.0
283  12-27-2010       5.0      1.0       3.0       1      1      2.0
284  12-28-2010       1.0      1.0       7.0       1      1      2.0
285  12-29-2010       5.0      0.0       7.0       1      1      2.0
286  12-30-2010       2.0      0.0       7.0       1      1      2.0

     Disconnect user_name
0           1.0   IKR0401
1           2.0   IKR0401
2           2.0   IKR0401
3           2.0   IKR0401
4           2.0   IKR0401
..          ...       ...
282         0.0   IKR0401
283         2.0   IKR0401
284         2.0   IKR0401
285         2.0   IKR0401
286         2.0   IKR0401

[287 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-04-2011       0.0      0.0       0.0       1      1        0
342  04-30-2010       0.0      0.0       0.0       1      1        0
343  06-09-2010       0.0      0.0       0.0       1      1        0
344  09-13-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ILC0838
1             0   ILC0838
2             0   ILC0838
3             0   ILC0838
4             0   ILC0838
..          ...       ...
341           0   ILC0838
342           0   ILC0838
343           0   ILC0838
344           0   ILC0838
345           0   ILC0838

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      2      0.0
1    01-04-2010       0.0      0.0       1.0       2      3      0.0
2    01-04-2011       1.0      0.0       0.0       1      2      1.0
3    01-05-2010       0.0      0.0       1.0       1      2      0.0
4    01-05-2011       1.0      0.0       0.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  05-10-2010       0.0      0.0       0.0       1      2      0.0
342  05-10-2011       0.0      0.0       0.0       1      1      1.0
343  07-01-2010       0.0      0.0       0.0       1      2      0.0
344  09-15-2010       0.0      0.0       0.0       2      2      0.0
345  10-04-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   ILH0958
1           0.0   ILH0958
2           1.0   ILH0958
3           0.0   ILH0958
4           0.0   ILH0958
..          ...       ...
341         0.0   ILH0958
342         1.0   ILH0958
343         0.0   ILH0958
344         0.0   ILH0958
345         0.0   ILH0958

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       2.0      0.0       1.0       3      3      1.0
1    01-02-2011       0.0      0.0       3.0       2      3      1.0
2    01-03-2011       1.0      1.0       1.0       2      3      1.0
3    01-04-2010       0.0      0.0       3.0       2      3      2.0
4    01-04-2011       1.0      0.0       2.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
370  12-29-2010       2.0      0.0       1.0       1      2      2.0
371  12-30-2010       1.0      0.0       2.0       1      2      0.0
372  12-31-2010       3.0      0.0       0.0       2      2      1.0
373  05-06-2011       0.0      0.0       0.0       1      2      2.0
374  05-16-2011       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           1.0   ILJ0526
1           1.0   ILJ0526
2           1.0   ILJ0526
3           2.0   ILJ0526
4           0.0   ILJ0526
..          ...       ...
370         2.0   ILJ0526
371         0.0   ILJ0526
372         1.0   ILJ0526
373         2.0   ILJ0526
374         2.0   ILJ0526

[375 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      1        0
2    01-05-2011       0.0      0.0       1.0       1      1        0
3    01-06-2010       1.0      0.0       0.0       1      1        0
4    01-06-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-25-2010       0.0      0.0       0.0       1      1        0
342  06-04-2010       0.0      0.0       0.0       1      1        0
343  08-09-2010       0.0      0.0       0.0       1      1        0
344  10-13-2010       0.0      0.0       0.0       1      1        0
345  11-03-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ILR0304
1             0   ILR0304
2             0   ILR0304
3             0   ILR0304
4             0   ILR0304
..          ...       ...
341           0   ILR0304
342           0   ILR0304
343           0   ILR0304
344           0   ILR0304
345           0   ILR0304

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0      12.0       1      1        0
1    01-04-2010       7.0      1.0       6.0       1      1        0
2    01-04-2011      10.0      0.0       5.0       1      1        0
3    01-05-2010      10.0      0.0       5.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0       7.0       1      1        0
342  12-27-2010       5.0      0.0      10.0       1      1        0
343  12-28-2010       7.0      1.0       7.0       1      1        0
344  12-29-2010       6.0      0.0       9.0       1      1        0
345  12-30-2010      10.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   IMB0481
1             0   IMB0481
2             0   IMB0481
3             0   IMB0481
4             0   IMB0481
..          ...       ...
341           0   IMB0481
342           0   IMB0481
343           0   IMB0481
344           0   IMB0481
345           0   IMB0481

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011       9.0      0.0       6.0       1      1        0
3    01-05-2010       9.0      0.0       6.0       1      1        0
4    01-05-2011       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       9.0      1.0       5.0       1      1        0
342  12-28-2010       3.0      1.0      11.0       1      1        0
343  12-29-2010       7.0      1.0       6.0       1      1        0
344  02-08-2011       0.0      0.0       0.0       1      1        0
345  12-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IMG0320
1             0   IMG0320
2             0   IMG0320
3             0   IMG0320
4             0   IMG0320
..          ...       ...
341           0   IMG0320
342           0   IMG0320
343           0   IMG0320
344           0   IMG0320
345           0   IMG0320

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      0.0       3.0       1      1        0
342  12-30-2010       2.0      1.0       0.0       1      1        0
343  01-20-2010       0.0      0.0       0.0       1      1        0
344  03-14-2011       0.0      0.0       0.0       1      1        0
345  04-05-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IMP0530
1             0   IMP0530
2             0   IMP0530
3             0   IMP0530
4             0   IMP0530
..          ...       ...
341           0   IMP0530
342           0   IMP0530
343           0   IMP0530
344           0   IMP0530
345           0   IMP0530

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       3.0      1.0       5.0       1      2      0.0
1    01-02-2010       1.0      2.0       6.0       2      3      0.0
2    01-02-2011       2.0      0.0       7.0       2      3      1.0
3    01-03-2010       3.0      0.0       6.0       1      2      1.0
4    01-03-2011       4.0      1.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
474  12-31-2010       0.0      1.0       8.0       1      2      1.0
475  04-15-2010       0.0      0.0       0.0       1      2      1.0
476  05-17-2011       0.0      0.0       0.0       1      1      0.0
477  08-12-2010       0.0      0.0       0.0       2      3      1.0
478  10-03-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   IRM0931
1           0.0   IRM0931
2           1.0   IRM0931
3           1.0   IRM0931
4           0.0   IRM0931
..          ...       ...
474         1.0   IRM0931
475         1.0   IRM0931
476         0.0   IRM0931
477         1.0   IRM0931
478         0.0   IRM0931

[479 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0      11.0       1      1        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011       8.0      2.0       5.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011       7.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       7.0       1      1        0
342  12-27-2010       6.0      2.0       7.0       1      1        0
343  12-28-2010       8.0      0.0       7.0       1      1        0
344  12-29-2010       6.0      1.0       8.0       1      1        0
345  12-30-2010       9.0      2.0       4.0       1      1        0

     Disconnect user_name
0             0   IRT0491
1             0   IRT0491
2             0   IRT0491
3             0   IRT0491
4             0   IRT0491
..          ...       ...
341           0   IRT0491
342           0   IRT0491
343           0   IRT0491
344           0   IRT0491
345           0   IRT0491

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      0.0       2.0       1      1      2.0
1    01-05-2010       7.0      0.0       2.0       1      1      2.0
2    01-06-2010       5.0      0.0       4.0       1      1      2.0
3    01-07-2010       5.0      0.0       4.0       1      1      0.0
4    01-08-2010       3.0      1.0       5.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
229  11-29-2010       4.0      0.0       5.0       1      1      1.0
230  11-30-2010       5.0      0.0       4.0       1      1      7.0
231  12-01-2010       5.0      0.0       4.0       1      1      2.0
232  12-02-2010       5.0      0.0       4.0       1      1      1.0
233  12-03-2010       6.0      1.0       2.0       1      1      2.0

     Disconnect user_name
0           2.0   IUB0565
1           2.0   IUB0565
2           2.0   IUB0565
3           0.0   IUB0565
4           1.0   IUB0565
..          ...       ...
229         1.0   IUB0565
230         7.0   IUB0565
231         2.0   IUB0565
232         1.0   IUB0565
233         2.0   IUB0565

[234 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      2        0
3    01-05-2010       4.0      0.0       5.0       1      2        0
4    01-05-2011       3.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       3.0       1      2        0
342  12-27-2010       3.0      1.0       4.0       1      2        0
343  12-28-2010       0.0      0.0       9.0       1      1        0
344  12-29-2010       1.0      1.0       7.0       1      2        0
345  12-30-2010       2.0      0.0       7.0       1      2        0

     Disconnect user_name
0             0   IUY0279
1             0   IUY0279
2             0   IUY0279
3             0   IUY0279
4             0   IUY0279
..          ...       ...
341           0   IUY0279
342           0   IUY0279
343           0   IUY0279
344           0   IUY0279
345           0   IUY0279

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       1.0       1      1        0
1    01-04-2010       5.0      0.0       3.0       1      2        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       4.0       1      2        0
342  12-27-2010       5.0      0.0       4.0       1      2        0
343  12-28-2010       3.0      1.0       5.0       1      2        0
344  12-29-2010       4.0      1.0       4.0       1      2        0
345  12-30-2010       4.0      0.0       5.0       1      2        0

     Disconnect user_name
0             0   IWM0816
1             0   IWM0816
2             0   IWM0816
3             0   IWM0816
4             0   IWM0816
..          ...       ...
341           0   IWM0816
342           0   IWM0816
343           0   IWM0816
344           0   IWM0816
345           0   IWM0816

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      2.0       4.0       1      1        0
342  12-28-2010       3.0      1.0       5.0       1      1        0
343  12-29-2010       2.0      1.0       6.0       1      1        0
344  12-30-2010       2.0      1.0       6.0       1      1        0
345  01-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   IYB0918
1             0   IYB0918
2             0   IYB0918
3             0   IYB0918
4             0   IYB0918
..          ...       ...
341           0   IYB0918
342           0   IYB0918
343           0   IYB0918
344           0   IYB0918
345           0   IYB0918

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       7.0       1      1        0
1    01-04-2010      11.0      0.0       4.0       2      2        0
2    01-04-2011      10.0      1.0       4.0       1      1        0
3    01-05-2010       6.0      2.0       5.0       1      1        0
4    01-05-2011      10.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       8.0       1      1        0
342  12-27-2010       8.0      1.0       6.0       1      1        0
343  12-28-2010       2.0      0.0      10.0       2      2        0
344  12-29-2010       9.0      1.0       4.0       1      1        0
345  12-30-2010      10.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   JAD0609
1             0   JAD0609
2             0   JAD0609
3             0   JAD0609
4             0   JAD0609
..          ...       ...
341           0   JAD0609
342           0   JAD0609
343           0   JAD0609
344           0   JAD0609
345           0   JAD0609

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0     1.0    2.0        0
1    01-03-2010       0.0      1.0       0.0     1.0    2.0        0
2    01-03-2011       0.0      0.0       1.0     1.0    2.0        0
3    01-04-2010       0.0      0.0       1.0     1.0    2.0        0
4    01-04-2011       0.0      1.0       0.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
441  09-21-2010       0.0      0.0       0.0     1.0    2.0        0
442  10-23-2010       0.0      0.0       0.0     1.0    2.0        0
443  10-30-2010       0.0      0.0       0.0     1.0    2.0        0
444  11-17-2010       0.0      0.0       0.0     1.0    2.0        0
445  11-24-2010       0.0      0.0       0.0     1.0    2.0        0

     Disconnect user_name
0             0   JAJ0849
1             0   JAJ0849
2             0   JAJ0849
3             0   JAJ0849
4             0   JAJ0849
..          ...       ...
441           0   JAJ0849
442           0   JAJ0849
443           0   JAJ0849
444           0   JAJ0849
445           0   JAJ0849

[446 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       1.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       6.0      0.0       3.0       1      1        0
343  12-28-2010       4.0      1.0       3.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       1.0      0.0       8.0       1      1        0

     Disconnect user_name
0             0   JAM0382
1             0   JAM0382
2             0   JAM0382
3             0   JAM0382
4             0   JAM0382
..          ...       ...
341           0   JAM0382
342           0   JAM0382
343           0   JAM0382
344           0   JAM0382
345           0   JAM0382

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       3      3        0
1    01-04-2010       5.0      2.0       4.0       5      5        0
2    01-04-2011       2.0      2.0       4.0       2      2        0
3    01-05-2010       4.0      0.0       7.0       4      4        0
4    01-05-2011       6.0      1.0       4.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       7.0       6      6        0
342  12-29-2010       2.0      0.0       9.0       5      5        0
343  12-30-2010       4.0      0.0       7.0       3      3        0
344  02-02-2010       0.0      0.0       0.0       2      2        0
345  09-15-2010       0.0      0.0       0.0       2      2        0

     Disconnect user_name
0             0   JAV0361
1             0   JAV0361
2             0   JAV0361
3             0   JAV0361
4             0   JAV0361
..          ...       ...
341           0   JAV0361
342           0   JAV0361
343           0   JAV0361
344           0   JAV0361
345           0   JAV0361

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       7.0       1      2        8
1    01-04-2010       5.0      2.0       8.0       1      2        9
2    01-04-2011       4.0      0.0      11.0       1      2        9
3    01-05-2010       9.0      3.0       3.0       1      2        8
4    01-05-2011       5.0      1.0       9.0       1      2        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       4.0       1      2        9
342  12-27-2010       6.0      1.0       8.0       1      2        9
343  12-28-2010       8.0      0.0       7.0       1      1        9
344  12-29-2010      12.0      0.0       3.0       1      2        9
345  12-30-2010      11.0      0.0       4.0       1      2        9

     Disconnect user_name
0             8   JBD0616
1             9   JBD0616
2             9   JBD0616
3             8   JBD0616
4             9   JBD0616
..          ...       ...
341           9   JBD0616
342           9   JBD0616
343           9   JBD0616
344           9   JBD0616
345           9   JBD0616

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       6.0     1.0    1.0        0
1    01-04-2010       6.0      0.0       8.0     1.0    1.0        0
2    01-04-2011       3.0      1.0      10.0     2.0    2.0        0
3    01-05-2010       6.0      1.0       7.0     1.0    1.0        0
4    01-05-2011       8.0      0.0       6.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
347  02-06-2010       0.0      0.0       0.0     1.0    0.0        0
348  02-26-2011       0.0      0.0       0.0     1.0    1.0        0
349  04-17-2010       0.0      0.0       0.0     1.0    1.0        0
350  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
351  05-14-2011       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   JBM0350
1             0   JBM0350
2             0   JBM0350
3             0   JBM0350
4             0   JBM0350
..          ...       ...
347           0   JBM0350
348           0   JBM0350
349           0   JBM0350
350           0   JBM0350
351           0   JBM0350

[352 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       4      4        0
1    01-04-2010       5.0      0.0       6.0       3      3        0
2    01-04-2011       4.0      0.0       7.0       3      3        0
3    01-05-2010       5.0      0.0       5.0       5      5        0
4    01-05-2011       5.0      0.0       6.0       3      3        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       6.0       4      4        0
342  12-28-2010       5.0      1.0       5.0       6      6        0
343  12-29-2010       6.0      2.0       3.0       3      3        0
344  12-30-2010       0.0      0.0      11.0       6      6        0
345  10-25-2010       0.0      0.0       0.0       5      5        0

     Disconnect user_name
0             0   JCC0225
1             0   JCC0225
2             0   JCC0225
3             0   JCC0225
4             0   JCC0225
..          ...       ...
341           0   JCC0225
342           0   JCC0225
343           0   JCC0225
344           0   JCC0225
345           0   JCC0225

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1      4.0
1    01-04-2010       8.0      0.0       7.0       2      2      2.0
2    01-04-2011       7.0      0.0       7.0       1      2      3.0
3    01-05-2010       6.0      2.0       6.0       1      2      2.0
4    01-05-2011       7.0      0.0       8.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       7.0       1      2      0.0
342  12-27-2010       9.0      0.0       6.0       1      2      2.0
343  12-28-2010       8.0      0.0       4.0       2      2      3.0
344  12-29-2010       9.0      1.0       5.0       1      2      2.0
345  12-30-2010       5.0      1.0       9.0       1      2      1.0

     Disconnect user_name
0           4.0   JCG0316
1           2.0   JCG0316
2           3.0   JCG0316
3           2.0   JCG0316
4           1.0   JCG0316
..          ...       ...
341         0.0   JCG0316
342         2.0   JCG0316
343         3.0   JCG0316
344         2.0   JCG0316
345         1.0   JCG0316

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       5.0      1.0       4.0       1      1      1.0
1    01-03-2011       5.0      1.0       9.0       1      2      1.0
2    01-04-2010       5.0      0.0       9.0       1      2      0.0
3    01-04-2011      10.0      1.0       3.0       1      2      1.0
4    01-05-2010       4.0      0.0      11.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
402  12-25-2010       8.0      2.0       5.0       1      2      0.0
403  12-27-2010       8.0      1.0       6.0       1      2      0.0
404  12-28-2010       8.0      1.0       6.0       1      2      0.0
405  12-29-2010       5.0      0.0       9.0       1      1      2.0
406  12-30-2010       7.0      0.0       8.0       1      2      1.0

     Disconnect user_name
0           1.0   JCR0172
1           1.0   JCR0172
2           0.0   JCR0172
3           1.0   JCR0172
4           0.0   JCR0172
..          ...       ...
402         0.0   JCR0172
403         0.0   JCR0172
404         0.0   JCR0172
405         2.0   JCR0172
406         1.0   JCR0172

[407 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2011       1.0      0.0       0.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-25-2011       0.0      0.0       0.0       1      1        0
342  03-01-2011       0.0      0.0       0.0       1      1        0
343  07-26-2010       0.0      0.0       0.0       1      1        0
344  08-31-2010       0.0      0.0       0.0       1      1        0
345  10-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JCR0289
1             0   JCR0289
2             0   JCR0289
3             0   JCR0289
4             0   JCR0289
..          ...       ...
341           0   JCR0289
342           0   JCR0289
343           0   JCR0289
344           0   JCR0289
345           0   JCR0289

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1        0
342  12-30-2010       1.0      0.0       2.0       1      1        0
343  01-31-2011       0.0      0.0       0.0       1      1        0
344  03-08-2010       0.0      0.0       0.0       1      1        0
345  03-15-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JCR0770
1             0   JCR0770
2             0   JCR0770
3             0   JCR0770
4             0   JCR0770
..          ...       ...
341           0   JCR0770
342           0   JCR0770
343           0   JCR0770
344           0   JCR0770
345           0   JCR0770

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       2.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       4.0      1.0       4.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   JCR0921
1             0   JCR0921
2             0   JCR0921
3             0   JCR0921
4             0   JCR0921
..          ...       ...
341           0   JCR0921
342           0   JCR0921
343           0   JCR0921
344           0   JCR0921
345           0   JCR0921

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  01-14-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JCV0245
1             0   JCV0245
2             0   JCV0245
3             0   JCV0245
4             0   JCV0245
..          ...       ...
341           0   JCV0245
342           0   JCV0245
343           0   JCV0245
344           0   JCV0245
345           0   JCV0245

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010       6.0      1.0       8.0       1      1        0
2    01-04-2011       5.0      1.0       9.0       1      1        0
3    01-05-2010       2.0      0.0      13.0       1      1        0
4    01-05-2011       6.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      0.0       7.0       1      1        0
342  12-28-2010       3.0      0.0      12.0       1      1        0
343  12-29-2010       0.0      0.0       1.0       1      1        0
344  12-30-2010       6.0      0.0       7.0       1      1        0
345  01-10-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JCW0858
1             0   JCW0858
2             0   JCW0858
3             0   JCW0858
4             0   JCW0858
..          ...       ...
341           0   JCW0858
342           0   JCW0858
343           0   JCW0858
344           0   JCW0858
345           0   JCW0858

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       7.0       1      2        7
1    01-04-2010       6.0      0.0       8.0       1      2        8
2    01-04-2011       6.0      0.0       7.0       1      2        7
3    01-05-2010       5.0      1.0       8.0       1      2        6
4    01-05-2011      11.0      0.0       3.0       1      2        7
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       9.0      0.0       5.0       1      2        9
342  12-28-2010       5.0      2.0       7.0       1      1        9
343  12-29-2010       6.0      0.0       8.0       1      2        6
344  12-30-2010       3.0      2.0       9.0       1      2        6
345  09-23-2010       0.0      0.0       0.0       1      2        8

     Disconnect user_name
0             7   JDB0169
1             8   JDB0169
2             7   JDB0169
3             6   JDB0169
4             7   JDB0169
..          ...       ...
341           9   JDB0169
342           9   JDB0169
343           6   JDB0169
344           6   JDB0169
345           8   JDB0169

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      1.0       6.0       1      2      1.0
1    01-02-2011       7.0      0.0       4.0       1      2      1.0
2    01-03-2010       6.0      0.0       4.0       1      2      0.0
3    01-03-2011       4.0      0.0       7.0       1      1      1.0
4    01-04-2010       5.0      0.0       5.0       2      3      0.0
..          ...       ...      ...       ...     ...    ...      ...
472  12-28-2010       6.0      0.0       5.0       1      2      0.0
473  12-29-2010       3.0      0.0       8.0       1      2      0.0
474  12-30-2010       3.0      2.0       6.0       1      2      0.0
475  12-31-2010       3.0      1.0       7.0       1      2      0.0
476  01-11-2011       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   JDC0030
1           1.0   JDC0030
2           0.0   JDC0030
3           1.0   JDC0030
4           0.0   JDC0030
..          ...       ...
472         0.0   JDC0030
473         0.0   JDC0030
474         0.0   JDC0030
475         0.0   JDC0030
476         0.0   JDC0030

[477 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0     1.0    2.0      9.0
1    01-03-2011       0.0      0.0       1.0     2.0    3.0      9.0
2    01-04-2010       0.0      0.0       1.0     1.0    2.0      9.0
3    01-04-2011       0.0      0.0       1.0     2.0    2.0      9.0
4    01-05-2010       0.0      0.0       1.0     1.0    2.0      9.0
..          ...       ...      ...       ...     ...    ...      ...
376  09-18-2010       0.0      0.0       0.0     1.0    1.0      0.0
377  10-07-2010       0.0      0.0       0.0     1.0    2.0      8.0
378  11-24-2010       0.0      0.0       0.0     3.0    3.0      9.0
379  11-26-2010       0.0      0.0       0.0     1.0    1.0      0.0
380  12-11-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           9.0   JDF0593
1           9.0   JDF0593
2           9.0   JDF0593
3           9.0   JDF0593
4           9.0   JDF0593
..          ...       ...
376         0.0   JDF0593
377         8.0   JDF0593
378         9.0   JDF0593
379         0.0   JDF0593
380         0.0   JDF0593

[381 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       5.0       1      1        0
1    01-04-2010       7.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  01-19-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JER0404
1             0   JER0404
2             0   JER0404
3             0   JER0404
4             0   JER0404
..          ...       ...
341           0   JER0404
342           0   JER0404
343           0   JER0404
344           0   JER0404
345           0   JER0404

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       1.0       1      1        3
1    01-04-2010       4.0      0.0       5.0       1      2        3
2    01-04-2011       6.0      0.0       3.0       1      2        5
3    01-05-2010       2.0      1.0       5.0       1      2        2
4    01-05-2011       1.0      1.0       7.0       1      2        3
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        3
342  12-28-2010       3.0      0.0       6.0       1      2        5
343  12-29-2010       6.0      1.0       2.0       1      2        5
344  12-30-2010       5.0      0.0       1.0       1      2        5
345  06-09-2010       0.0      0.0       0.0       1      2        6

     Disconnect user_name
0             3   JFC0557
1             3   JFC0557
2             5   JFC0557
3             2   JFC0557
4             3   JFC0557
..          ...       ...
341           3   JFC0557
342           5   JFC0557
343           5   JFC0557
344           5   JFC0557
345           6   JFC0557

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       1.0       1      1        0
3    01-05-2010       3.0      0.0       0.0       1      1        0
4    01-05-2011       2.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-11-2011       0.0      0.0       0.0       1      1        0
342  01-12-2010       0.0      0.0       0.0       1      1        0
343  03-04-2010       0.0      0.0       0.0       1      1        0
344  03-08-2010       0.0      0.0       0.0       1      1        0
345  07-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JFC0757
1             0   JFC0757
2             0   JFC0757
3             0   JFC0757
4             0   JFC0757
..          ...       ...
341           0   JFC0757
342           0   JFC0757
343           0   JFC0757
344           0   JFC0757
345           0   JFC0757

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      2        0
2    01-04-2011       6.0      0.0       3.0       1      2        0
3    01-05-2010       6.0      0.0       3.0       1      2        0
4    01-05-2011       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      2        0
342  12-27-2010       4.0      0.0       5.0       1      2        0
343  12-28-2010       6.0      1.0       2.0       1      2        0
344  12-29-2010       4.0      0.0       5.0       1      2        0
345  12-30-2010       5.0      1.0       3.0       1      2        0

     Disconnect user_name
0             0   JGM0934
1             0   JGM0934
2             0   JGM0934
3             0   JGM0934
4             0   JGM0934
..          ...       ...
341           0   JGM0934
342           0   JGM0934
343           0   JGM0934
344           0   JGM0934
345           0   JGM0934

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       6.0       6      6      0.0
1    01-05-2010       7.0      0.0       4.0       5      5      0.0
2    01-06-2010       4.0      0.0       7.0       3      3      0.0
3    01-07-2010       5.0      1.0       3.0       5      5      0.0
4    01-08-2010       4.0      2.0       5.0       4      4      0.0
..          ...       ...      ...       ...     ...    ...      ...
132  07-13-2010       5.0      0.0       6.0       6      6      0.0
133  07-14-2010       7.0      0.0       4.0       5      5      0.0
134  07-15-2010       8.0      0.0       5.0       7      7      2.0
135  07-16-2010       5.0      0.0       6.0       7      7      0.0
136  06-29-2010       0.0      0.0       0.0       2      2      0.0

     Disconnect user_name
0           0.0   JGT0221
1           0.0   JGT0221
2           0.0   JGT0221
3           0.0   JGT0221
4           0.0   JGT0221
..          ...       ...
132         0.0   JGT0221
133         0.0   JGT0221
134         2.0   JGT0221
135         0.0   JGT0221
136         0.0   JGT0221

[137 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       1.0      0.0       0.0     1.0    2.0      1.0
1    01-02-2010       0.0      0.0       1.0     1.0    2.0      0.0
2    01-03-2011       1.0      0.0       0.0     1.0    2.0      2.0
3    01-04-2010       0.0      0.0       1.0     1.0    2.0      1.0
4    01-04-2011       0.0      0.0       1.0     1.0    3.0      3.0
..          ...       ...      ...       ...     ...    ...      ...
401  08-21-2010       0.0      0.0       0.0     1.0    0.0      0.0
402  09-28-2010       0.0      0.0       0.0     1.0    2.0      1.0
403  10-20-2010       0.0      0.0       0.0     1.0    1.0      2.0
404  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0
405  11-26-2010       0.0      0.0       0.0     1.0    2.0      3.0

     Disconnect user_name
0           1.0   JHP0583
1           0.0   JHP0583
2           2.0   JHP0583
3           1.0   JHP0583
4           3.0   JHP0583
..          ...       ...
401         0.0   JHP0583
402         1.0   JHP0583
403         2.0   JHP0583
404         0.0   JHP0583
405         3.0   JHP0583

[406 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      4.0       3.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       2.0      3.0       4.0       1      1        0
3    01-05-2010       0.0      4.0       5.0       1      1        0
4    01-05-2011       1.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      7.0       0.0       1      1        0
342  12-30-2010       0.0      8.0       1.0       1      1        0
343  02-01-2010       0.0      0.0       0.0       1      1        0
344  08-18-2010       0.0      0.0       0.0       1      1        0
345  12-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JIG0128
1             0   JIG0128
2             0   JIG0128
3             0   JIG0128
4             0   JIG0128
..          ...       ...
341           0   JIG0128
342           0   JIG0128
343           0   JIG0128
344           0   JIG0128
345           0   JIG0128

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       6.0       1      1        0
2    01-04-2011       6.0      2.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       7.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       7.0      0.0       4.0       1      1        0
343  12-29-2010       7.0      0.0       4.0       1      1        0
344  12-30-2010       4.0      0.0       7.0       1      1        0
345  01-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JIM0095
1             0   JIM0095
2             0   JIM0095
3             0   JIM0095
4             0   JIM0095
..          ...       ...
341           0   JIM0095
342           0   JIM0095
343           0   JIM0095
344           0   JIM0095
345           0   JIM0095

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      5.0       0.0       1      1        0
1    01-04-2010       2.0      2.0       5.0       1      1        0
2    01-04-2011       2.0      3.0       3.0       1      1        0
3    01-05-2010       0.0      3.0       0.0       1      1        0
4    01-05-2011       2.0      2.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      1.0       6.0       1      1        0
342  12-30-2010       0.0      7.0       1.0       1      1        0
343  03-10-2011       0.0      0.0       0.0       1      1        0
344  04-22-2010       0.0      0.0       0.0       1      1        0
345  09-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JJB0127
1             0   JJB0127
2             0   JJB0127
3             0   JJB0127
4             0   JJB0127
..          ...       ...
341           0   JJB0127
342           0   JJB0127
343           0   JJB0127
344           0   JJB0127
345           0   JJB0127

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-12-2010       0.0      0.0       0.0       2      2        0
342  09-03-2010       0.0      0.0       0.0       1      1        0
343  09-23-2010       0.0      0.0       0.0       1      1        0
344  10-01-2010       0.0      0.0       0.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JJB0700
1             0   JJB0700
2             0   JJB0700
3             0   JJB0700
4             0   JJB0700
..          ...       ...
341           0   JJB0700
342           0   JJB0700
343           0   JJB0700
344           0   JJB0700
345           0   JJB0700

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       0.0       2      3        0
..          ...       ...      ...       ...     ...    ...      ...
347  05-20-2010       0.0      0.0       0.0       1      2        0
348  06-11-2010       0.0      0.0       0.0       1      2        0
349  08-03-2010       0.0      0.0       0.0       1      2        0
350  10-15-2010       0.0      0.0       0.0       1      1        0
351  12-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JJH0292
1             0   JJH0292
2             0   JJH0292
3             0   JJH0292
4             0   JJH0292
..          ...       ...
347           0   JJH0292
348           0   JJH0292
349           0   JJH0292
350           0   JJH0292
351           0   JJH0292

[352 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0       2      3      4.0
1    01-04-2010      11.0      2.0       2.0       2      2      4.0
2    01-04-2011       6.0      1.0       8.0       1      2      2.0
3    01-05-2010       7.0      1.0       7.0       1      2      3.0
4    01-05-2011      10.0      1.0       3.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       9.0       1      2      4.0
342  12-28-2010      13.0      0.0       2.0       2      3      2.0
343  12-29-2010       5.0      1.0       8.0       1      2      5.0
344  12-30-2010       7.0      1.0       7.0       1      2      3.0
345  03-18-2011       0.0      0.0       0.0       1      2      4.0

     Disconnect user_name
0           4.0   JJH0613
1           4.0   JJH0613
2           2.0   JJH0613
3           3.0   JJH0613
4           3.0   JJH0613
..          ...       ...
341         4.0   JJH0613
342         2.0   JJH0613
343         5.0   JJH0613
344         3.0   JJH0613
345         4.0   JJH0613

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      1.0       1.0       1      1      2.0
1    01-05-2010       4.0      0.0       5.0       1      2      2.0
2    01-06-2010       4.0      0.0       5.0       2      2      3.0
3    01-07-2010       5.0      0.0       4.0       1      2      0.0
4    01-08-2010       4.0      0.0       5.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
206  10-26-2010       0.0      0.0       9.0       1      2      1.0
207  10-27-2010       3.0      1.0       5.0       1      1      0.0
208  10-28-2010       2.0      0.0       7.0       2      3      1.0
209  10-29-2010       5.0      0.0       4.0       1      2      1.0
210  06-14-2010       0.0      0.0       0.0       2      2      2.0

     Disconnect user_name
0           2.0   JJM0203
1           2.0   JJM0203
2           3.0   JJM0203
3           0.0   JJM0203
4           2.0   JJM0203
..          ...       ...
206         1.0   JJM0203
207         0.0   JJM0203
208         1.0   JJM0203
209         1.0   JJM0203
210         2.0   JJM0203

[211 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       3.0     1.0    1.0        0
1    01-04-2010       1.0      4.0       1.0     1.0    1.0        0
2    01-04-2011       0.0      7.0       2.0     1.0    1.0        0
3    01-05-2010       4.0      0.0       5.0     1.0    1.0        0
4    01-05-2011       4.0      2.0       3.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0     1.0    1.0        0
342  12-27-2010       2.0      6.0       1.0     1.0    1.0        0
343  12-28-2010       5.0      0.0       4.0     1.0    1.0        0
344  12-29-2010       1.0      7.0       1.0     1.0    1.0        0
345  12-30-2010       3.0      1.0       5.0     1.0    1.0        0

     Disconnect user_name
0             0   JKB0126
1             0   JKB0126
2             0   JKB0126
3             0   JKB0126
4             0   JKB0126
..          ...       ...
341           0   JKB0126
342           0   JKB0126
343           0   JKB0126
344           0   JKB0126
345           0   JKB0126

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       1      1        0
1    01-02-2010       0.0      0.0       1.0       1      1        0
2    01-03-2011       0.0      0.0       1.0       1      1        0
3    01-04-2010       0.0      0.0       1.0       1      1        0
4    01-04-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
415  05-13-2010       0.0      0.0       0.0       1      1        0
416  05-19-2010       0.0      0.0       0.0       1      1        0
417  08-31-2010       0.0      0.0       0.0       1      1        0
418  11-01-2010       0.0      0.0       0.0       1      1        0
419  11-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JKF0465
1             0   JKF0465
2             0   JKF0465
3             0   JKF0465
4             0   JKF0465
..          ...       ...
415           0   JKF0465
416           0   JKF0465
417           0   JKF0465
418           0   JKF0465
419           0   JKF0465

[420 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       1.0      0.0       0.0     1.0    1.0        0
1    01-03-2010       1.0      0.0       0.0     1.0    1.0        0
2    01-03-2011       0.0      0.0       1.0     1.0    1.0        0
3    01-04-2010       0.0      0.0       1.0     1.0    1.0        0
4    01-04-2011       1.0      0.0       0.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
437  06-03-2010       0.0      0.0       0.0     1.0    1.0        0
438  06-16-2010       0.0      0.0       0.0     1.0    1.0        0
439  08-06-2010       0.0      0.0       0.0     1.0    1.0        0
440  10-22-2010       0.0      0.0       0.0     1.0    1.0        0
441  11-22-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   JKJ0698
1             0   JKJ0698
2             0   JKJ0698
3             0   JKJ0698
4             0   JKJ0698
..          ...       ...
437           0   JKJ0698
438           0   JKJ0698
439           0   JKJ0698
440           0   JKJ0698
441           0   JKJ0698

[442 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      1.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-07-2010       0.0      0.0       0.0       1      1        0
342  08-09-2010       0.0      0.0       0.0       1      1        0
343  11-12-2010       0.0      0.0       0.0       1      1        0
344  12-22-2010       0.0      0.0       0.0       1      1        0
345  12-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JKM0303
1             0   JKM0303
2             0   JKM0303
3             0   JKM0303
4             0   JKM0303
..          ...       ...
341           0   JKM0303
342           0   JKM0303
343           0   JKM0303
344           0   JKM0303
345           0   JKM0303

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      2.0       5.0       6      6      0.0
1    01-04-2010       3.0      0.0       7.0       2      2      0.0
2    01-04-2011       7.0      1.0       3.0       5      5      0.0
3    01-05-2010       7.0      1.0       3.0       6      6      0.0
4    01-05-2011       5.0      0.0       6.0       2      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
330  12-28-2010       7.0      1.0       3.0       6      6      0.0
331  12-29-2010       1.0      1.0       9.0       3      3      0.0
332  12-30-2010       6.0      0.0       5.0       2      2      0.0
333  01-07-2010       0.0      0.0       0.0       5      5      0.0
334  02-17-2010       0.0      0.0       0.0       4      4      0.0

     Disconnect user_name
0           0.0   JLM0364
1           0.0   JLM0364
2           0.0   JLM0364
3           0.0   JLM0364
4           0.0   JLM0364
..          ...       ...
330         0.0   JLM0364
331         0.0   JLM0364
332         0.0   JLM0364
333         0.0   JLM0364
334         0.0   JLM0364

[335 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      2.0       8.0       1      1        0
1    01-04-2010       5.0      0.0       9.0       1      1        0
2    01-04-2011       5.0      2.0       7.0       1      1        0
3    01-05-2010       6.0      0.0       8.0       1      1        0
4    01-05-2011       5.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       9.0      1.0       4.0       1      1        0
342  12-27-2010       8.0      0.0       6.0       1      1        0
343  12-28-2010       6.0      0.0       8.0       1      1        0
344  12-29-2010       5.0      1.0       8.0       1      1        0
345  12-30-2010       6.0      1.0       7.0       1      1        0

     Disconnect user_name
0             0   JLW0053
1             0   JLW0053
2             0   JLW0053
3             0   JLW0053
4             0   JLW0053
..          ...       ...
341           0   JLW0053
342           0   JLW0053
343           0   JLW0053
344           0   JLW0053
345           0   JLW0053

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       6.0      0.0       8.0       1      1      0.0
1    01-05-2010      10.0      1.0       4.0       1      1      0.0
2    01-06-2010       8.0      0.0       7.0       1      1      0.0
3    01-07-2010      10.0      1.0       4.0       1      1      0.0
4    01-08-2010       8.0      0.0       7.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
148  08-03-2010       5.0      0.0      10.0       1      1      0.0
149  08-04-2010       9.0      0.0       6.0       1      1      0.0
150  08-05-2010       9.0      2.0       4.0       1      1      0.0
151  08-06-2010       9.0      0.0       6.0       1      1      0.0
152  08-09-2010       4.0      0.0      10.0       1      1      0.0

     Disconnect user_name
0           0.0   JMB0308
1           0.0   JMB0308
2           0.0   JMB0308
3           0.0   JMB0308
4           0.0   JMB0308
..          ...       ...
148         0.0   JMB0308
149         0.0   JMB0308
150         0.0   JMB0308
151         0.0   JMB0308
152         0.0   JMB0308

[153 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       4.0     2.0    3.0        0
1    01-04-2010       6.0      1.0       3.0     2.0    3.0        0
2    01-04-2011       1.0      1.0       8.0     2.0    3.0        0
3    01-05-2010       3.0      0.0       7.0     1.0    2.0        0
4    01-05-2011       5.0      0.0       5.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
347  05-01-2010       0.0      0.0       0.0     1.0    0.0        0
348  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
349  09-30-2010       0.0      0.0       0.0     2.0    3.0        0
350  10-02-2010       0.0      0.0       0.0     1.0    1.0        0
351  11-06-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   JMC0925
1             0   JMC0925
2             0   JMC0925
3             0   JMC0925
4             0   JMC0925
..          ...       ...
347           0   JMC0925
348           0   JMC0925
349           0   JMC0925
350           0   JMC0925
351           0   JMC0925

[352 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0       1      1      2.0
1    01-04-2010       1.0      0.0       2.0       1      1      1.0
2    01-04-2011       1.0      0.0       1.0       2      3      3.0
3    01-05-2010       2.0      0.0       1.0       1      2      2.0
4    01-05-2011       1.0      0.0       2.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
343  01-26-2010       0.0      0.0       0.0       1      2      3.0
344  03-06-2010       0.0      0.0       0.0       1      1      0.0
345  07-03-2010       0.0      0.0       0.0       1      1      0.0
346  08-11-2010       0.0      0.0       0.0       1      2      2.0
347  10-07-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           2.0   JMD0520
1           1.0   JMD0520
2           3.0   JMD0520
3           2.0   JMD0520
4           1.0   JMD0520
..          ...       ...
343         3.0   JMD0520
344         0.0   JMD0520
345         0.0   JMD0520
346         2.0   JMD0520
347         0.0   JMD0520

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       4.0       1      2        0
1    01-05-2010       2.0      0.0       7.0       1      2        0
2    01-06-2010       2.0      0.0       7.0       1      2        0
3    01-07-2010       4.0      1.0       4.0       1      2        0
4    01-08-2010       2.0      0.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
223  11-17-2010       0.0      1.0       8.0       1      1        0
224  11-18-2010       5.0      0.0       4.0       1      1        0
225  11-19-2010       4.0      1.0       3.0       1      2        0
226  11-22-2010       4.0      0.0       5.0       1      1        0
227  11-23-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   JMH0543
1             0   JMH0543
2             0   JMH0543
3             0   JMH0543
4             0   JMH0543
..          ...       ...
223           0   JMH0543
224           0   JMH0543
225           0   JMH0543
226           0   JMH0543
227           0   JMH0543

[228 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      2.0       4.0       2      3      1.0
1    01-04-2010       4.0      1.0       4.0       2      2      2.0
2    01-04-2011       1.0      0.0       8.0       1      2      0.0
3    01-05-2010       5.0      0.0       4.0       1      2      0.0
4    01-05-2011       3.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       2.0       1      2      0.0
342  12-28-2010       2.0      1.0       5.0       2      2      0.0
343  12-29-2010       8.0      0.0       1.0       1      2      0.0
344  12-30-2010       3.0      0.0       6.0       1      2      0.0
345  04-26-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   JMK0099
1           2.0   JMK0099
2           0.0   JMK0099
3           0.0   JMK0099
4           0.0   JMK0099
..          ...       ...
341         0.0   JMK0099
342         0.0   JMK0099
343         0.0   JMK0099
344         0.0   JMK0099
345         0.0   JMK0099

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      1.0       1.0       1      2        0
2    01-04-2011       2.0      0.0       1.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       1.0       1      2        0
342  12-28-2010       1.0      0.0       2.0       1      1        0
343  12-29-2010       0.0      0.0       2.0       1      2        0
344  12-30-2010       0.0      1.0       2.0       1      2        0
345  12-20-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   JML0909
1             0   JML0909
2             0   JML0909
3             0   JML0909
4             0   JML0909
..          ...       ...
341           0   JML0909
342           0   JML0909
343           0   JML0909
344           0   JML0909
345           0   JML0909

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1        0
342  12-30-2010       0.0      0.0       3.0       1      1        0
343  02-14-2011       0.0      0.0       0.0       1      1        0
344  04-13-2010       0.0      0.0       0.0       1      1        0
345  05-06-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JMW0638
1             0   JMW0638
2             0   JMW0638
3             0   JMW0638
4             0   JMW0638
..          ...       ...
341           0   JMW0638
342           0   JMW0638
343           0   JMW0638
344           0   JMW0638
345           0   JMW0638

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0     1.0    1.0        0
1    01-04-2010       5.0      0.0       3.0     1.0    1.0        0
2    01-04-2011       2.0      0.0       7.0     1.0    1.0        0
3    01-05-2010       5.0      0.0       1.0     1.0    1.0        0
4    01-05-2011       0.0      0.0       2.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0     1.0    1.0        0
342  12-28-2010       1.0      1.0       6.0     1.0    1.0        0
343  12-29-2010       3.0      1.0       5.0     1.0    1.0        0
344  12-30-2010       3.0      0.0       5.0     1.0    1.0        0
345  04-12-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   JNA0559
1             0   JNA0559
2             0   JNA0559
3             0   JNA0559
4             0   JNA0559
..          ...       ...
341           0   JNA0559
342           0   JNA0559
343           0   JNA0559
344           0   JNA0559
345           0   JNA0559

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0     1.0    1.0        9
1    01-04-2010       3.0      0.0       1.0     1.0    1.0        9
2    01-04-2011       2.0      0.0       7.0     1.0    1.0        9
3    01-05-2010       4.0      0.0       5.0     1.0    1.0        9
4    01-05-2011       1.0      0.0       8.0     1.0    1.0        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       7.0     1.0    1.0        9
342  12-28-2010       5.0      0.0       3.0     1.0    1.0        9
343  12-29-2010       5.0      0.0       4.0     1.0    1.0        8
344  12-30-2010       6.0      1.0       2.0     1.0    1.0        7
345  01-11-2011       0.0      0.0       0.0     1.0    1.0        9

     Disconnect user_name
0             9   JNJ0556
1             9   JNJ0556
2             9   JNJ0556
3             9   JNJ0556
4             9   JNJ0556
..          ...       ...
341           9   JNJ0556
342           9   JNJ0556
343           8   JNJ0556
344           7   JNJ0556
345           9   JNJ0556

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       6.0       1      1        0
1    01-04-2010       2.0      2.0       7.0       1      1        0
2    01-04-2011       8.0      0.0       3.0       1      1        0
3    01-05-2010       3.0      1.0       7.0       1      1        0
4    01-05-2011       5.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       6.0      0.0       5.0       1      1        0
342  12-30-2010       3.0      0.0       8.0       1      1        0
343  04-08-2010       0.0      0.0       0.0       1      1        0
344  05-09-2011       0.0      0.0       0.0       1      1        0
345  08-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JOL0024
1             0   JOL0024
2             0   JOL0024
3             0   JOL0024
4             0   JOL0024
..          ...       ...
341           0   JOL0024
342           0   JOL0024
343           0   JOL0024
344           0   JOL0024
345           0   JOL0024

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      11.0       1      1        0
1    01-04-2010       2.0      3.0      10.0       1      1        0
2    01-04-2011       6.0      6.0       3.0       1      1        0
3    01-05-2010       1.0      7.0       6.0       1      1        0
4    01-05-2011       7.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      3.0       5.0       1      1        0
342  12-27-2010       0.0     14.0       1.0       1      1        0
343  12-28-2010       5.0      4.0       6.0       1      1        0
344  12-29-2010       1.0     11.0       3.0       1      1        0
345  12-30-2010       5.0      6.0       4.0       1      1        0

     Disconnect user_name
0             0   JOM0750
1             0   JOM0750
2             0   JOM0750
3             0   JOM0750
4             0   JOM0750
..          ...       ...
341           0   JOM0750
342           0   JOM0750
343           0   JOM0750
344           0   JOM0750
345           0   JOM0750

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       5.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       8.0      0.0       1.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      1.0       5.0       1      1        0
342  12-30-2010       5.0      1.0       3.0       1      1        0
343  03-22-2011       0.0      0.0       0.0       1      1        0
344  05-10-2010       0.0      0.0       0.0       1      1        0
345  05-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JPA0667
1             0   JPA0667
2             0   JPA0667
3             0   JPA0667
4             0   JPA0667
..          ...       ...
341           0   JPA0667
342           0   JPA0667
343           0   JPA0667
344           0   JPA0667
345           0   JPA0667

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0     11.0       1.0       1      1        0
1    01-04-2010       5.0      7.0       3.0       1      1        0
2    01-04-2011       7.0      5.0       3.0       1      1        0
3    01-05-2010       6.0      1.0       8.0       1      1        0
4    01-05-2011       7.0      2.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       7.0      1.0       7.0       1      1        0
342  12-30-2010       0.0      1.0      14.0       1      1        0
343  04-27-2010       0.0      0.0       0.0       1      1        0
344  08-03-2010       0.0      0.0       0.0       1      1        0
345  11-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JPW0741
1             0   JPW0741
2             0   JPW0741
3             0   JPW0741
4             0   JPW0741
..          ...       ...
341           0   JPW0741
342           0   JPW0741
343           0   JPW0741
344           0   JPW0741
345           0   JPW0741

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-19-2010       0.0      0.0       0.0       1      1        0
342  04-20-2010       0.0      0.0       0.0       1      1        0
343  07-13-2010       0.0      0.0       0.0       1      1        0
344  11-11-2010       0.0      0.0       0.0       1      1        0
345  12-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JRF0835
1             0   JRF0835
2             0   JRF0835
3             0   JRF0835
4             0   JRF0835
..          ...       ...
341           0   JRF0835
342           0   JRF0835
343           0   JRF0835
344           0   JRF0835
345           0   JRF0835

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       7.0     1.0    1.0      0.0
1    01-04-2010       7.0      1.0       6.0     1.0    1.0      0.0
2    01-04-2011       6.0      0.0       8.0     1.0    1.0      0.0
3    01-05-2010       7.0      0.0       7.0     1.0    1.0      0.0
4    01-05-2011       9.0      0.0       5.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
278  12-28-2010       5.0      0.0       9.0     1.0    1.0      0.0
279  12-29-2010       6.0      1.0       7.0     1.0    1.0      0.0
280  12-30-2010       2.0      0.0      12.0     1.0    1.0      0.0
281  01-29-2011       0.0      0.0       0.0     1.0    0.0      0.0
282  12-17-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   JRG0207
1           0.0   JRG0207
2           0.0   JRG0207
3           0.0   JRG0207
4           0.0   JRG0207
..          ...       ...
278         0.0   JRG0207
279         0.0   JRG0207
280         0.0   JRG0207
281         0.0   JRG0207
282         0.0   JRG0207

[283 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       1.0      0.0       0.0       1      1        0
1   01-05-2010       1.0      0.0       0.0       1      1        0
2   01-06-2010       1.0      0.0       0.0       1      1        0
3   01-07-2010       1.0      0.0       0.0       1      1        0
4   01-11-2010       1.0      0.0       0.0       1      1        0
5   01-12-2010       1.0      0.0       0.0       1      1        0
6   01-13-2010       1.0      0.0       0.0       1      1        0
7   01-14-2010       1.0      0.0       0.0       1      1        0
8   01-18-2010       1.0      0.0       0.0       1      1        0
9   01-20-2010       0.0      0.0       1.0       1      1        0
10  01-21-2010       0.0      0.0       1.0       1      1        0
11  01-22-2010       1.0      0.0       0.0       1      1        0
12  01-25-2010       1.0      0.0       0.0       1      1        0
13  01-26-2010       1.0      0.0       0.0       1      1        0
14  01-27-2010       0.0      0.0       1.0       1      1        0
15  01-28-2010       1.0      0.0       0.0       1      1        0
16  01-29-2010       0.0      0.0       1.0       1      1        0
17  02-01-2010       1.0      0.0       0.0       1      1        0
18  02-02-2010       1.0      0.0       0.0       1      1        0
19  02-03-2010       0.0      0.0       1.0       1      1        0
20  02-04-2010       1.0      0.0       0.0       1      1        0
21  02-05-2010       0.0      0.0       1.0       1      1        0
22  02-08-2010       1.0      0.0       0.0       1      1        0
23  02-09-2010       0.0      0.0       1.0       1      1        0
24  02-10-2010       1.0      0.0       0.0       1      1        0
25  02-11-2010       0.0      0.0       1.0       1      1        0
26  02-12-2010       1.0      0.0       0.0       1      1        0
27  02-15-2010       0.0      0.0       1.0       1      1        0
28  02-16-2010       0.0      0.0       1.0       1      1        0
29  02-17-2010       0.0      0.0       1.0       1      1        0
30  02-18-2010       0.0      0.0       1.0       1      1        0
31  02-19-2010       0.0      0.0       1.0       1      1        0
32  02-22-2010       0.0      0.0       1.0       1      1        0
33  02-23-2010       0.0      0.0       1.0       1      1        0
34  02-24-2010       0.0      1.0       0.0       1      1        0
35  02-25-2010       0.0      0.0       1.0       1      1        0
36  02-26-2010       0.0      0.0       1.0       1      1        0
37  03-01-2010       0.0      0.0       1.0       1      1        0
38  03-02-2010       0.0      0.0       1.0       1      1        0
39  03-03-2010       0.0      0.0       1.0       1      1        0
40  03-04-2010       1.0      0.0       0.0       1      1        0
41  03-05-2010       0.0      0.0       1.0       1      1        0
42  03-08-2010       0.0      0.0       1.0       1      1        0
43  03-09-2010       0.0      0.0       1.0       1      1        0
44  03-10-2010       0.0      0.0       1.0       1      1        0
45  03-11-2010       0.0      0.0       1.0       1      1        0
46  03-12-2010       1.0      0.0       0.0       1      1        0
47  03-16-2010       0.0      0.0       1.0       1      1        0
48  03-17-2010       0.0      0.0       1.0       1      1        0
49  03-18-2010       1.0      0.0       0.0       1      1        0
50  03-19-2010       0.0      0.0       1.0       1      1        0
51  01-08-2010       0.0      0.0       0.0       1      1        0
52  01-15-2010       0.0      0.0       0.0       1      1        0
53  01-19-2010       0.0      0.0       0.0       1      1        0
54  03-15-2010       0.0      0.0       0.0       1      1        0

    Disconnect user_name
0            0   JRH0455
1            0   JRH0455
2            0   JRH0455
3            0   JRH0455
4            0   JRH0455
5            0   JRH0455
6            0   JRH0455
7            0   JRH0455
8            0   JRH0455
9            0   JRH0455
10           0   JRH0455
11           0   JRH0455
12           0   JRH0455
13           0   JRH0455
14           0   JRH0455
15           0   JRH0455
16           0   JRH0455
17           0   JRH0455
18           0   JRH0455
19           0   JRH0455
20           0   JRH0455
21           0   JRH0455
22           0   JRH0455
23           0   JRH0455
24           0   JRH0455
25           0   JRH0455
26           0   JRH0455
27           0   JRH0455
28           0   JRH0455
29           0   JRH0455
30           0   JRH0455
31           0   JRH0455
32           0   JRH0455
33           0   JRH0455
34           0   JRH0455
35           0   JRH0455
36           0   JRH0455
37           0   JRH0455
38           0   JRH0455
39           0   JRH0455
40           0   JRH0455
41           0   JRH0455
42           0   JRH0455
43           0   JRH0455
44           0   JRH0455
45           0   JRH0455
46           0   JRH0455
47           0   JRH0455
48           0   JRH0455
49           0   JRH0455
50           0   JRH0455
51           0   JRH0455
52           0   JRH0455
53           0   JRH0455
54           0   JRH0455
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-14-2010       0.0      0.0       0.0       1      1        0
342  09-29-2010       0.0      0.0       0.0       1      1        0
343  10-15-2010       0.0      0.0       0.0       1      1        0
344  11-18-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JRL0574
1             0   JRL0574
2             0   JRL0574
3             0   JRL0574
4             0   JRL0574
..          ...       ...
341           0   JRL0574
342           0   JRL0574
343           0   JRL0574
344           0   JRL0574
345           0   JRL0574

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       2.0       3      3        0
1    01-04-2010       8.0      0.0       3.0       6      6        0
2    01-04-2011       5.0      0.0       6.0       5      5        0
3    01-05-2010       2.0      2.0       7.0       3      3        0
4    01-05-2011       6.0      1.0       4.0       4      4        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       9.0       5      5        0
342  12-27-2010       4.0      0.0       7.0       2      2        0
343  12-28-2010       6.0      0.0       5.0       3      3        0
344  12-29-2010       4.0      0.0       7.0       3      3        0
345  12-30-2010       7.0      0.0       4.0       4      4        0

     Disconnect user_name
0             0   JRS0362
1             0   JRS0362
2             0   JRS0362
3             0   JRS0362
4             0   JRS0362
..          ...       ...
341           0   JRS0362
342           0   JRS0362
343           0   JRS0362
344           0   JRS0362
345           0   JRS0362

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  04-16-2010       0.0      0.0       0.0       1      1        0
343  05-09-2011       0.0      0.0       0.0       1      1        0
344  09-09-2010       0.0      0.0       0.0       1      1        0
345  10-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JSA0775
1             0   JSA0775
2             0   JSA0775
3             0   JSA0775
4             0   JSA0775
..          ...       ...
341           0   JSA0775
342           0   JSA0775
343           0   JSA0775
344           0   JSA0775
345           0   JSA0775

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      0.0       4.0       1      1        0
342  12-30-2010       1.0      0.0       2.0       1      1        0
343  03-01-2011       0.0      0.0       0.0       1      1        0
344  04-09-2010       0.0      0.0       0.0       1      1        0
345  05-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JSH0330
1             0   JSH0330
2             0   JSH0330
3             0   JSH0330
4             0   JSH0330
..          ...       ...
341           0   JSH0330
342           0   JSH0330
343           0   JSH0330
344           0   JSH0330
345           0   JSH0330

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      1.0       8.0       5      6      0.0
1    01-05-2010       5.0      0.0       6.0       3      4      0.0
2    01-06-2010       7.0      0.0       4.0       4      5      0.0
3    01-07-2010       4.0      0.0       7.0       6      7      0.0
4    01-08-2010       3.0      1.0       7.0       5      6      0.0
..          ...       ...      ...       ...     ...    ...      ...
137  07-21-2010       3.0      0.0       8.0       2      3      0.0
138  07-22-2010       7.0      0.0       6.0       6      7      2.0
139  07-23-2010       2.0      0.0       1.0       7      8      0.0
140  01-15-2010       0.0      0.0       0.0       5      6      0.0
141  03-23-2010       0.0      0.0       0.0       7      8      0.0

     Disconnect user_name
0           0.0   JTM0223
1           0.0   JTM0223
2           0.0   JTM0223
3           0.0   JTM0223
4           0.0   JTM0223
..          ...       ...
137         0.0   JTM0223
138         2.0   JTM0223
139         0.0   JTM0223
140         0.0   JTM0223
141         0.0   JTM0223

[142 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       5.0       1      1      1.0
1    01-04-2010       3.0      1.0       6.0       1      1      0.0
2    01-04-2011       2.0      0.0       5.0       1      1      1.0
3    01-05-2010       4.0      0.0       6.0       1      1      0.0
4    01-05-2011       5.0      0.0       5.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1      0.0
342  12-28-2010       3.0      1.0       6.0       1      1      0.0
343  12-29-2010       4.0      1.0       5.0       1      1      0.0
344  12-30-2010       4.0      0.0       6.0       1      1      0.0
345  04-08-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   JTS0389
1           0.0   JTS0389
2           1.0   JTS0389
3           0.0   JTS0389
4           0.0   JTS0389
..          ...       ...
341         0.0   JTS0389
342         0.0   JTS0389
343         0.0   JTS0389
344         0.0   JTS0389
345         0.0   JTS0389

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       9.0       1      1        0
1    01-04-2010       8.0      0.0       6.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010       4.0      0.0       6.0       1      1        0
4    01-05-2011       3.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       9.0      1.0       5.0       1      1        0
342  12-28-2010       9.0      0.0       6.0       1      1        0
343  12-29-2010       6.0      1.0       8.0       1      1        0
344  12-30-2010       6.0      1.0       3.0       1      1        0
345  11-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JXH0493
1             0   JXH0493
2             0   JXH0493
3             0   JXH0493
4             0   JXH0493
..          ...       ...
341           0   JXH0493
342           0   JXH0493
343           0   JXH0493
344           0   JXH0493
345           0   JXH0493

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      2.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-08-2010       0.0      0.0       0.0       1      1        0
342  04-14-2011       0.0      0.0       0.0       1      1        0
343  04-19-2010       0.0      0.0       0.0       1      1        0
344  08-25-2010       0.0      0.0       0.0       1      1        0
345  08-31-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   JZD0888
1             0   JZD0888
2             0   JZD0888
3             0   JZD0888
4             0   JZD0888
..          ...       ...
341           0   JZD0888
342           0   JZD0888
343           0   JZD0888
344           0   JZD0888
345           0   JZD0888

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      5.0       1.0       1      1        0
1    01-04-2010       2.0      5.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       2.0      4.0       3.0       1      1        0
4    01-05-2011       2.0      3.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      2.0       2.0       1      1        0
342  12-27-2010       3.0      0.0       5.0       1      1        0
343  12-28-2010       0.0      7.0       2.0       1      1        0
344  12-29-2010       2.0      7.0       0.0       1      1        0
345  12-30-2010       3.0      3.0       3.0       1      1        0

     Disconnect user_name
0             0   KAC0124
1             0   KAC0124
2             0   KAC0124
3             0   KAC0124
4             0   KAC0124
..          ...       ...
341           0   KAC0124
342           0   KAC0124
343           0   KAC0124
344           0   KAC0124
345           0   KAC0124

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       3.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       5.0      0.0       4.0       1      1        0
342  12-30-2010       5.0      0.0       4.0       1      1        0
343  01-18-2010       0.0      0.0       0.0       1      1        0
344  04-16-2010       0.0      0.0       0.0       1      1        0
345  05-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KAL0395
1             0   KAL0395
2             0   KAL0395
3             0   KAL0395
4             0   KAL0395
..          ...       ...
341           0   KAL0395
342           0   KAL0395
343           0   KAL0395
344           0   KAL0395
345           0   KAL0395

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       1.0      0.0       7.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       5.0      0.0       4.0       1      1        0
343  12-29-2010       4.0      2.0       3.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  05-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KAT0270
1             0   KAT0270
2             0   KAT0270
3             0   KAT0270
4             0   KAT0270
..          ...       ...
341           0   KAT0270
342           0   KAT0270
343           0   KAT0270
344           0   KAT0270
345           0   KAT0270

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010      11.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      0.0      12.0       1      1        0
3    01-05-2010      12.0      0.0       2.0       1      1        0
4    01-05-2011       7.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       8.0       1      1        0
342  12-27-2010       9.0      0.0       5.0       1      1        0
343  12-28-2010       8.0      1.0       6.0       1      1        0
344  12-29-2010       5.0      1.0       9.0       1      1        0
345  12-30-2010      11.0      1.0       3.0       1      1        0

     Disconnect user_name
0             0   KAT0489
1             0   KAT0489
2             0   KAT0489
3             0   KAT0489
4             0   KAT0489
..          ...       ...
341           0   KAT0489
342           0   KAT0489
343           0   KAT0489
344           0   KAT0489
345           0   KAT0489

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      3.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      1.0       7.0       1      1        0
3    01-05-2010       6.0      2.0       3.0       1      1        0
4    01-05-2011       4.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       6.0       1      1        0
342  12-27-2010       5.0      1.0       5.0       1      1        0
343  12-28-2010       5.0      0.0       6.0       1      1        0
344  12-29-2010       2.0      1.0       8.0       1      1        0
345  12-30-2010       6.0      1.0       4.0       1      1        0

     Disconnect user_name
0             0   KBB0189
1             0   KBB0189
2             0   KBB0189
3             0   KBB0189
4             0   KBB0189
..          ...       ...
341           0   KBB0189
342           0   KBB0189
343           0   KBB0189
344           0   KBB0189
345           0   KBB0189

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      2.0       4.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       7.0      0.0       2.0       1      1        0
342  12-30-2010       4.0      0.0       5.0       1      1        0
343  03-09-2011       0.0      0.0       0.0       1      1        0
344  04-01-2010       0.0      0.0       0.0       1      1        0
345  07-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KBC0054
1             0   KBC0054
2             0   KBC0054
3             0   KBC0054
4             0   KBC0054
..          ...       ...
341           0   KBC0054
342           0   KBC0054
343           0   KBC0054
344           0   KBC0054
345           0   KBC0054

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       8.0       2      2      0.0
1    01-04-2010       1.0      0.0       6.0       1      2      0.0
2    01-04-2011       3.0      0.0       5.0       1      2      0.0
3    01-05-2010       2.0      0.0       8.0       1      2      0.0
4    01-05-2011       1.0      1.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       3.0       1      2      0.0
342  12-28-2010       3.0      0.0       7.0       1      2      0.0
343  12-29-2010       1.0      0.0       9.0       1      2      0.0
344  12-30-2010       2.0      0.0       8.0       1      2      0.0
345  03-17-2011       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   KBG0549
1           0.0   KBG0549
2           0.0   KBG0549
3           0.0   KBG0549
4           0.0   KBG0549
..          ...       ...
341         0.0   KBG0549
342         0.0   KBG0549
343         0.0   KBG0549
344         0.0   KBG0549
345         0.0   KBG0549

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       6.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       1.0      0.0       1.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  01-25-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KBL0260
1             0   KBL0260
2             0   KBL0260
3             0   KBL0260
4             0   KBL0260
..          ...       ...
341           0   KBL0260
342           0   KBL0260
343           0   KBL0260
344           0   KBL0260
345           0   KBL0260

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      12.0      1.0      14.0       2      2        0
1    01-04-2010       8.0      1.0      17.0       2      3        0
2    01-04-2011      11.0      2.0      14.0       1      2        0
3    01-05-2010       3.0      1.0      22.0       1      2        0
4    01-05-2011      11.0      1.0      12.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      15.0      1.0      11.0       1      2        0
342  12-27-2010       9.0      4.0      14.0       1      2        0
343  12-28-2010       2.0      0.0      25.0       2      2        0
344  12-29-2010       8.0      2.0      17.0       1      2        0
345  12-30-2010       4.0      3.0      20.0       1      2        0

     Disconnect user_name
0             0   KBP0008
1             0   KBP0008
2             0   KBP0008
3             0   KBP0008
4             0   KBP0008
..          ...       ...
341           0   KBP0008
342           0   KBP0008
343           0   KBP0008
344           0   KBP0008
345           0   KBP0008

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       7.0       1      1        0
1    01-04-2010       2.0      2.0      11.0       1      2        0
2    01-04-2011       4.0      0.0      11.0       1      2        0
3    01-05-2010       9.0      2.0       4.0       1      2        0
4    01-05-2011       6.0      1.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0      11.0       1      2        0
342  12-27-2010       7.0      0.0       8.0       1      2        0
343  12-28-2010       5.0      2.0       8.0       1      1        0
344  12-29-2010       8.0      2.0       5.0       1      2        0
345  12-30-2010       8.0      0.0       7.0       1      2        0

     Disconnect user_name
0             0   KBS0874
1             0   KBS0874
2             0   KBS0874
3             0   KBS0874
4             0   KBS0874
..          ...       ...
341           0   KBS0874
342           0   KBS0874
343           0   KBS0874
344           0   KBS0874
345           0   KBS0874

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       5.0      0.0       4.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       5.0      0.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       0.0      1.0       7.0       1      2        0
342  12-27-2010       5.0      0.0       4.0       1      2        0
343  12-28-2010       7.0      0.0       2.0       1      2        0
344  12-29-2010       2.0      0.0       7.0       1      2        0
345  12-30-2010       3.0      1.0       4.0       1      2        0

     Disconnect user_name
0             0   KCB0815
1             0   KCB0815
2             0   KCB0815
3             0   KCB0815
4             0   KCB0815
..          ...       ...
341           0   KCB0815
342           0   KCB0815
343           0   KCB0815
344           0   KCB0815
345           0   KCB0815

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       3      3        0
1    01-04-2010       2.0      0.0       9.0       3      3        0
2    01-04-2011       4.0      0.0       7.0       5      5        0
3    01-05-2010       3.0      1.0       5.0       6      6        0
4    01-05-2011       3.0      1.0       7.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       5.0       2      2        0
342  12-29-2010       3.0      0.0       8.0       5      5        0
343  12-30-2010       1.0      0.0       1.0       5      5        0
344  03-23-2010       0.0      0.0       0.0       2      2        0
345  04-04-2011       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   KCF0045
1             0   KCF0045
2             0   KCF0045
3             0   KCF0045
4             0   KCF0045
..          ...       ...
341           0   KCF0045
342           0   KCF0045
343           0   KCF0045
344           0   KCF0045
345           0   KCF0045

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0     1.0    3.0      2.0
1    01-04-2010       5.0      0.0       4.0     1.0    2.0      2.0
2    01-04-2011       1.0      2.0       6.0     2.0    2.0      2.0
3    01-05-2010       3.0      4.0       2.0     1.0    2.0      2.0
4    01-05-2011       3.0      2.0       4.0     1.0    2.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
350  05-01-2010       0.0      0.0       0.0     1.0    0.0      0.0
351  05-14-2011       0.0      0.0       0.0     1.0    0.0      0.0
352  07-03-2010       0.0      0.0       0.0     1.0    0.0      0.0
353  10-02-2010       0.0      0.0       0.0     1.0    1.0      0.0
354  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           2.0   KCO0122
1           2.0   KCO0122
2           2.0   KCO0122
3           2.0   KCO0122
4           2.0   KCO0122
..          ...       ...
350         0.0   KCO0122
351         0.0   KCO0122
352         0.0   KCO0122
353         0.0   KCO0122
354         0.0   KCO0122

[355 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       2      2      1.0
1    01-04-2010       5.0      2.0       6.0       1      2      0.0
2    01-04-2011       8.0      1.0       5.0       1      2      2.0
3    01-05-2010       6.0      1.0       7.0       1      2      1.0
4    01-05-2011       7.0      1.0       6.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      1.0      12.0       1      2      1.0
342  12-28-2010       7.0      1.0       6.0       1      2      1.0
343  12-29-2010       8.0      0.0       6.0       1      2      2.0
344  12-30-2010       8.0      0.0       6.0       1      2      1.0
345  03-18-2010       0.0      0.0       0.0       2      2      3.0

     Disconnect user_name
0           1.0   KCS0173
1           0.0   KCS0173
2           2.0   KCS0173
3           1.0   KCS0173
4           1.0   KCS0173
..          ...       ...
341         1.0   KCS0173
342         1.0   KCS0173
343         2.0   KCS0173
344         1.0   KCS0173
345         3.0   KCS0173

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       6.0       1      1        0
1    01-04-2010       9.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      0.0       8.0       1      1        0
3    01-05-2010       6.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       6.0       1      1        0
342  12-27-2010       6.0      1.0       7.0       1      1        0
343  12-28-2010       5.0      1.0       7.0       1      1        0
344  12-29-2010       6.0      0.0       8.0       1      1        0
345  12-30-2010       7.0      1.0       6.0       1      1        0

     Disconnect user_name
0             0   KDS0349
1             0   KDS0349
2             0   KDS0349
3             0   KDS0349
4             0   KDS0349
..          ...       ...
341           0   KDS0349
342           0   KDS0349
343           0   KDS0349
344           0   KDS0349
345           0   KDS0349

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       2.0       1      2        0
2    01-04-2011       0.0      1.0       2.0       1      2        0
3    01-05-2010       0.0      0.0       2.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-26-2011       0.0      0.0       0.0       1      2        0
342  03-18-2010       0.0      0.0       0.0       1      1        0
343  06-04-2010       0.0      0.0       0.0       1      2        0
344  07-06-2010       0.0      0.0       0.0       1      2        0
345  10-05-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   KDT0346
1             0   KDT0346
2             0   KDT0346
3             0   KDT0346
4             0   KDT0346
..          ...       ...
341           0   KDT0346
342           0   KDT0346
343           0   KDT0346
344           0   KDT0346
345           0   KDT0346

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      8.0       4.0       1      1        0
1    01-04-2010       3.0      4.0       7.0       1      2        0
2    01-04-2011       2.0      4.0       9.0       1      2        0
3    01-05-2010       2.0      6.0       7.0       1      2        0
4    01-05-2011       7.0      0.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       5.0      3.0       7.0       1      2        0
342  12-30-2010       1.0      9.0       5.0       1      2        0
343  03-24-2010       0.0      0.0       0.0       1      1        0
344  04-08-2010       0.0      0.0       0.0       1      2        0
345  04-22-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   KES0729
1             0   KES0729
2             0   KES0729
3             0   KES0729
4             0   KES0729
..          ...       ...
341           0   KES0729
342           0   KES0729
343           0   KES0729
344           0   KES0729
345           0   KES0729

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       6.0       1      1        0
1    01-04-2010       6.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      3.0       3.0       1      1        0
3    01-05-2010       5.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       5.0       1      1        0
342  12-28-2010       5.0      1.0       5.0       1      1        0
343  12-29-2010       4.0      0.0       7.0       1      1        0
344  12-30-2010       4.0      0.0       7.0       1      1        0
345  04-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KJA0152
1             0   KJA0152
2             0   KJA0152
3             0   KJA0152
4             0   KJA0152
..          ...       ...
341           0   KJA0152
342           0   KJA0152
343           0   KJA0152
344           0   KJA0152
345           0   KJA0152

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-30-2011       0.0      0.0       0.0       1      1        0
342  05-13-2011       0.0      0.0       0.0       1      1        0
343  08-26-2010       0.0      0.0       0.0       1      1        0
344  10-14-2010       0.0      0.0       0.0       1      1        0
345  11-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KJG0910
1             0   KJG0910
2             0   KJG0910
3             0   KJG0910
4             0   KJG0910
..          ...       ...
341           0   KJG0910
342           0   KJG0910
343           0   KJG0910
344           0   KJG0910
345           0   KJG0910

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2      1.0
1    01-04-2010       0.0      0.0       1.0       2      3      0.0
2    01-04-2011       0.0      0.0       1.0       1      2      0.0
3    01-05-2010       0.0      0.0       1.0       1      2      2.0
4    01-05-2011       1.0      0.0       0.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  08-05-2010       0.0      0.0       0.0       1      2      1.0
342  09-17-2010       0.0      0.0       0.0       1      2      2.0
343  09-20-2010       0.0      0.0       0.0       1      2      0.0
344  10-04-2010       0.0      0.0       0.0       1      2      2.0
345  11-30-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           1.0   KJJ0293
1           0.0   KJJ0293
2           0.0   KJJ0293
3           2.0   KJJ0293
4           0.0   KJJ0293
..          ...       ...
341         1.0   KJJ0293
342         2.0   KJJ0293
343         0.0   KJJ0293
344         2.0   KJJ0293
345         1.0   KJJ0293

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      1.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      1.0       0.0       1      1        0
342  12-28-2010       1.0      1.0       1.0       1      1        0
343  12-29-2010       3.0      0.0       0.0       1      1        0
344  12-30-2010       2.0      0.0       1.0       1      1        0
345  09-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KJM0887
1             0   KJM0887
2             0   KJM0887
3             0   KJM0887
4             0   KJM0887
..          ...       ...
341           0   KJM0887
342           0   KJM0887
343           0   KJM0887
344           0   KJM0887
345           0   KJM0887

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       4.0       5      5        0
1    01-04-2010       2.0      0.0       9.0       2      2        0
2    01-04-2011       6.0      0.0       5.0       6      6        0
3    01-05-2010       5.0      1.0       2.0       5      5        0
4    01-05-2011       2.0      0.0       9.0       4      4        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       7.0       3      3        0
342  12-27-2010       4.0      0.0       7.0       5      5        0
343  12-28-2010       6.0      1.0       4.0       3      3        0
344  12-29-2010       4.0      0.0       7.0       4      4        0
345  12-30-2010       2.0      1.0       7.0       2      2        0

     Disconnect user_name
0             0   KJP0371
1             0   KJP0371
2             0   KJP0371
3             0   KJP0371
4             0   KJP0371
..          ...       ...
341           0   KJP0371
342           0   KJP0371
343           0   KJP0371
344           0   KJP0371
345           0   KJP0371

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      1        0
1    01-04-2010      10.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      1.0       8.0       1      1        0
3    01-05-2010       6.0      0.0       8.0       1      1        0
4    01-05-2011       9.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0       7.0       1      1        0
342  12-27-2010       7.0      1.0       7.0       1      1        0
343  12-28-2010      10.0      0.0       5.0       1      1        0
344  12-29-2010      11.0      0.0       4.0       1      1        0
345  12-30-2010       8.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   KJS0618
1             0   KJS0618
2             0   KJS0618
3             0   KJS0618
4             0   KJS0618
..          ...       ...
341           0   KJS0618
342           0   KJS0618
343           0   KJS0618
344           0   KJS0618
345           0   KJS0618

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       5.0      1.0       3.0       1      1        0
3    01-05-2010       5.0      0.0       3.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       7.0      0.0       2.0       1      1        0
343  12-30-2010       4.0      0.0       5.0       1      1        0
344  01-13-2011       0.0      0.0       0.0       1      1        0
345  04-12-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KJW0416
1             0   KJW0416
2             0   KJW0416
3             0   KJW0416
4             0   KJW0416
..          ...       ...
341           0   KJW0416
342           0   KJW0416
343           0   KJW0416
344           0   KJW0416
345           0   KJW0416

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       2.0      1.0       5.0       1      1        0
2    01-04-2011       3.0      2.0       4.0       1      1        0
3    01-05-2010       4.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      2.0       4.0       1      1        0
342  12-27-2010       2.0      0.0       7.0       1      1        0
343  12-28-2010       1.0      1.0       7.0       1      1        0
344  12-29-2010       5.0      1.0       3.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   KKC0683
1             0   KKC0683
2             0   KKC0683
3             0   KKC0683
4             0   KKC0683
..          ...       ...
341           0   KKC0683
342           0   KKC0683
343           0   KKC0683
344           0   KKC0683
345           0   KKC0683

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      2.0       6.0       1      2        0
1    01-04-2010       4.0      1.0       8.0       1      2        0
2    01-04-2011       7.0      0.0       7.0       1      2        0
3    01-05-2010       6.0      1.0       7.0       1      2        0
4    01-05-2011       8.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       6.0       1      2        0
342  12-27-2010       8.0      2.0       4.0       1      2        0
343  12-28-2010       7.0      0.0       6.0       1      2        0
344  12-29-2010       7.0      1.0       6.0       1      2        0
345  12-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   KKS0119
1             0   KKS0119
2             0   KKS0119
3             0   KKS0119
4             0   KKS0119
..          ...       ...
341           0   KKS0119
342           0   KKS0119
343           0   KKS0119
344           0   KKS0119
345           0   KKS0119

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       8.0      0.0       6.0     1.0    1.0      8.0
1    01-03-2011       5.0      1.0       8.0     1.0    1.0      9.0
2    01-04-2010       7.0      1.0       6.0     1.0    1.0      9.0
3    01-04-2011       8.0      0.0       6.0     1.0    1.0      9.0
4    01-05-2010       7.0      1.0       6.0     1.0    1.0      9.0
..          ...       ...      ...       ...     ...    ...      ...
379  01-29-2011       0.0      0.0       0.0     1.0    1.0      0.0
380  02-07-2011       0.0      0.0       0.0     1.0    1.0      7.0
381  03-27-2011       0.0      0.0       0.0     1.0    0.0      0.0
382  04-05-2010       0.0      0.0       0.0     1.0    1.0      9.0
383  12-11-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           8.0   KKW0879
1           9.0   KKW0879
2           9.0   KKW0879
3           9.0   KKW0879
4           9.0   KKW0879
..          ...       ...
379         0.0   KKW0879
380         7.0   KKW0879
381         0.0   KKW0879
382         9.0   KKW0879
383         0.0   KKW0879

[384 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1      0.0
1    01-04-2010       1.0      0.0       0.0       1      1      0.0
2    01-04-2011       1.0      0.0       0.0       1      1      0.0
3    01-05-2010       0.0      0.0       1.0       1      1      0.0
4    01-05-2011       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
287  08-31-2010       0.0      0.0       0.0       1      1      0.0
288  09-22-2010       0.0      0.0       0.0       1      1      0.0
289  11-10-2010       0.0      0.0       0.0       1      1      0.0
290  11-12-2010       0.0      0.0       0.0       1      1      0.0
291  12-21-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   KLH0596
1           0.0   KLH0596
2           0.0   KLH0596
3           0.0   KLH0596
4           0.0   KLH0596
..          ...       ...
287         0.0   KLH0596
288         0.0   KLH0596
289         0.0   KLH0596
290         0.0   KLH0596
291         0.0   KLH0596

[292 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      0.0       3.0       1      1        0
342  12-28-2010       0.0      0.0       3.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      1        0
344  12-30-2010       2.0      1.0       0.0       1      1        0
345  12-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KLM0639
1             0   KLM0639
2             0   KLM0639
3             0   KLM0639
4             0   KLM0639
..          ...       ...
341           0   KLM0639
342           0   KLM0639
343           0   KLM0639
344           0   KLM0639
345           0   KLM0639

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0     1.0    1.0      2.0
1    01-04-2010       6.0      0.0       3.0     1.0    2.0      3.0
2    01-04-2011       4.0      3.0       2.0     2.0    3.0      2.0
3    01-05-2010       3.0      0.0       6.0     1.0    2.0      1.0
4    01-05-2011       8.0      0.0       1.0     1.0    2.0      4.0
..          ...       ...      ...       ...     ...    ...      ...
348  03-19-2011       0.0      0.0       0.0     1.0    1.0      0.0
349  04-17-2010       0.0      0.0       0.0     1.0    1.0      0.0
350  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
351  10-02-2010       0.0      0.0       0.0     1.0    0.0      0.0
352  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           2.0   KMB0922
1           3.0   KMB0922
2           2.0   KMB0922
3           1.0   KMB0922
4           4.0   KMB0922
..          ...       ...
348         0.0   KMB0922
349         0.0   KMB0922
350         0.0   KMB0922
351         0.0   KMB0922
352         0.0   KMB0922

[353 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      1.0       2.0       1      1        0
342  12-30-2010       0.0      0.0       3.0       1      1        0
343  02-22-2010       0.0      0.0       0.0       1      1        0
344  06-15-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KMS0657
1             0   KMS0657
2             0   KMS0657
3             0   KMS0657
4             0   KMS0657
..          ...       ...
341           0   KMS0657
342           0   KMS0657
343           0   KMS0657
344           0   KMS0657
345           0   KMS0657

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1      1.0
1    01-04-2010       3.0      0.0       6.0       1      2      0.0
2    01-04-2011       5.0      0.0       4.0       1      2      1.0
3    01-05-2010       3.0      0.0       6.0       1      2      0.0
4    01-05-2011       5.0      0.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1      0.0
342  12-29-2010       4.0      1.0       4.0       1      2      1.0
343  12-30-2010       2.0      0.0       7.0       1      2      0.0
344  01-19-2010       0.0      0.0       0.0       1      2      0.0
345  04-01-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   KMW0545
1           0.0   KMW0545
2           1.0   KMW0545
3           0.0   KMW0545
4           0.0   KMW0545
..          ...       ...
341         0.0   KMW0545
342         1.0   KMW0545
343         0.0   KMW0545
344         0.0   KMW0545
345         0.0   KMW0545

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       7.0       1      1        0
1    01-04-2010       7.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      2.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       5.0       1      1        0
342  12-28-2010       5.0      0.0       6.0       1      1        0
343  12-29-2010       2.0      0.0       9.0       1      1        0
344  12-30-2010       5.0      0.0       6.0       1      1        0
345  05-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KNB0022
1             0   KNB0022
2             0   KNB0022
3             0   KNB0022
4             0   KNB0022
..          ...       ...
341           0   KNB0022
342           0   KNB0022
343           0   KNB0022
344           0   KNB0022
345           0   KNB0022

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       1.0      0.0       8.0       1      1        0
4    01-05-2011       3.0      4.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
296  12-30-2010       4.0      1.0       4.0       1      1        0
297  03-04-2010       0.0      0.0       0.0       1      1        0
298  04-22-2010       0.0      0.0       0.0       1      1        0
299  06-01-2010       0.0      0.0       0.0       1      1        0
300  06-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KNG0672
1             0   KNG0672
2             0   KNG0672
3             0   KNG0672
4             0   KNG0672
..          ...       ...
296           0   KNG0672
297           0   KNG0672
298           0   KNG0672
299           0   KNG0672
300           0   KNG0672

[301 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0       1      1        0
1    01-04-2011       0.0      1.0       2.0       1      1        0
2    01-05-2010       2.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       2.0       1      1        0
4    01-06-2010       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  01-04-2010       0.0      0.0       0.0       1      1        0
345  08-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KNW0644
1             0   KNW0644
2             0   KNW0644
3             0   KNW0644
4             0   KNW0644
..          ...       ...
341           0   KNW0644
342           0   KNW0644
343           0   KNW0644
344           0   KNW0644
345           0   KNW0644

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      1.0       4.0       1      1      0.0
1    01-05-2010       5.0      0.0       4.0       1      1      0.0
2    01-06-2010       3.0      0.0       6.0       1      1      0.0
3    01-07-2010       2.0      0.0       7.0       1      1      0.0
4    01-08-2010       2.0      0.0       7.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
144  07-28-2010       4.0      1.0       4.0       1      1      0.0
145  07-29-2010       3.0      2.0       4.0       1      1      0.0
146  07-30-2010       4.0      0.0       5.0       1      1      0.0
147  08-02-2010       4.0      0.0       5.0       1      1      0.0
148  08-03-2010       5.0      1.0       3.0       1      1      0.0

     Disconnect user_name
0           0.0   KPC0073
1           0.0   KPC0073
2           0.0   KPC0073
3           0.0   KPC0073
4           0.0   KPC0073
..          ...       ...
144         0.0   KPC0073
145         0.0   KPC0073
146         0.0   KPC0073
147         0.0   KPC0073
148         0.0   KPC0073

[149 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-07-2011       0.0      0.0       0.0       1      1        0
342  07-21-2010       0.0      0.0       0.0       1      1        0
343  08-16-2010       0.0      0.0       0.0       1      1        0
344  08-27-2010       0.0      0.0       0.0       1      1        0
345  09-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KPP0452
1             0   KPP0452
2             0   KPP0452
3             0   KPP0452
4             0   KPP0452
..          ...       ...
341           0   KPP0452
342           0   KPP0452
343           0   KPP0452
344           0   KPP0452
345           0   KPP0452

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       9.0       1      2        0
1    01-04-2010       7.0      0.0       8.0       2      3        0
2    01-04-2011       5.0      0.0      10.0       1      2        0
3    01-05-2010       3.0      0.0      11.0       1      2        0
4    01-05-2011       9.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0      12.0       1      2        0
342  12-27-2010       7.0      0.0       8.0       1      2        0
343  12-28-2010       6.0      1.0       8.0       2      3        0
344  12-29-2010       4.0      0.0      11.0       1      2        0
345  12-30-2010       4.0      1.0      10.0       1      2        0

     Disconnect user_name
0             0   KPR0497
1             0   KPR0497
2             0   KPR0497
3             0   KPR0497
4             0   KPR0497
..          ...       ...
341           0   KPR0497
342           0   KPR0497
343           0   KPR0497
344           0   KPR0497
345           0   KPR0497

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-03-2011       0.0      0.0       0.0       1      1        0
342  07-19-2010       0.0      0.0       0.0       1      1        0
343  09-09-2010       0.0      0.0       0.0       1      1        0
344  10-25-2010       0.0      0.0       0.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KQC0708
1             0   KQC0708
2             0   KQC0708
3             0   KQC0708
4             0   KQC0708
..          ...       ...
341           0   KQC0708
342           0   KQC0708
343           0   KQC0708
344           0   KQC0708
345           0   KQC0708

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       2.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      4.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       6.0      0.0       3.0       1      1        0
343  12-29-2010       3.0      2.0       4.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  05-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KQS0415
1             0   KQS0415
2             0   KQS0415
3             0   KQS0415
4             0   KQS0415
..          ...       ...
341           0   KQS0415
342           0   KQS0415
343           0   KQS0415
344           0   KQS0415
345           0   KQS0415

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0       7.0       1      1        0
2    01-04-2011       5.0      0.0       6.0       1      1        0
3    01-05-2010       3.0      2.0       6.0       1      1        0
4    01-05-2011       6.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       6.0       1      1        0
342  12-29-2010       5.0      0.0       6.0       1      1        0
343  12-30-2010       4.0      0.0       7.0       1      1        0
344  02-23-2011       0.0      0.0       0.0       1      1        0
345  06-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KRG0158
1             0   KRG0158
2             0   KRG0158
3             0   KRG0158
4             0   KRG0158
..          ...       ...
341           0   KRG0158
342           0   KRG0158
343           0   KRG0158
344           0   KRG0158
345           0   KRG0158

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       1      1        0
1    01-04-2010       4.0      1.0       6.0       1      1        0
2    01-04-2011       6.0      0.0       5.0       1      1        0
3    01-05-2010       6.0      0.0       5.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       5.0       1      1        0
342  12-27-2010       3.0      0.0       8.0       1      1        0
343  12-28-2010       2.0      1.0       8.0       1      1        0
344  12-29-2010       3.0      2.0       5.0       1      1        0
345  12-30-2010       4.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   KRL0062
1             0   KRL0062
2             0   KRL0062
3             0   KRL0062
4             0   KRL0062
..          ...       ...
341           0   KRL0062
342           0   KRL0062
343           0   KRL0062
344           0   KRL0062
345           0   KRL0062

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0      10.0       1      1      4.0
1    01-04-2010       5.0      0.0      10.0       1      1      2.0
2    01-04-2011       6.0      3.0       6.0       1      1      1.0
3    01-05-2010       5.0      1.0       9.0       1      1      3.0
4    01-05-2011       8.0      1.0       6.0       1      1      7.0
..          ...       ...      ...       ...     ...    ...      ...
260  12-22-2010      11.0      0.0       4.0       1      1      7.0
261  12-27-2010      11.0      1.0       3.0       1      1      6.0
262  12-28-2010       6.0      0.0       5.0       1      1      5.0
263  12-29-2010       8.0      0.0       7.0       1      1      2.0
264  12-30-2010       6.0      2.0       7.0       1      1      6.0

     Disconnect user_name
0           4.0   KRL0501
1           2.0   KRL0501
2           1.0   KRL0501
3           3.0   KRL0501
4           7.0   KRL0501
..          ...       ...
260         7.0   KRL0501
261         6.0   KRL0501
262         5.0   KRL0501
263         2.0   KRL0501
264         6.0   KRL0501

[265 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       2      2        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-29-2010       5.0      0.0       4.0       1      1        0
343  12-30-2010       3.0      1.0       5.0       1      1        0
344  05-03-2010       0.0      0.0       0.0       1      1        0
345  12-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KRM0541
1             0   KRM0541
2             0   KRM0541
3             0   KRM0541
4             0   KRM0541
..          ...       ...
341           0   KRM0541
342           0   KRM0541
343           0   KRM0541
344           0   KRM0541
345           0   KRM0541

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       4.0       5      5        0
1    01-04-2010       0.0      2.0       8.0       4      4        0
2    01-04-2011       2.0      1.0       6.0       3      3        0
3    01-05-2010       2.0      0.0       9.0       3      3        0
4    01-05-2011       2.0      0.0       9.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0       9.0       5      5        0
342  12-27-2010       2.0      0.0       9.0       5      5        0
343  12-28-2010       3.0      0.0       8.0       4      4        0
344  12-29-2010       5.0      0.0       5.0       5      5        0
345  12-30-2010       3.0      0.0       7.0       4      4        0

     Disconnect user_name
0             0   KRV0372
1             0   KRV0372
2             0   KRV0372
3             0   KRV0372
4             0   KRV0372
..          ...       ...
341           0   KRV0372
342           0   KRV0372
343           0   KRV0372
344           0   KRV0372
345           0   KRV0372

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       1.0      0.0       8.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       3.0       1      1        0
343  12-29-2010       2.0      3.0       4.0       1      1        0
344  12-30-2010       4.0      0.0       4.0       1      1        0
345  02-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KSH0569
1             0   KSH0569
2             0   KSH0569
3             0   KSH0569
4             0   KSH0569
..          ...       ...
341           0   KSH0569
342           0   KSH0569
343           0   KSH0569
344           0   KSH0569
345           0   KSH0569

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       7.0       6      6        0
1    01-05-2010       4.0      0.0       7.0       5      5        0
2    01-06-2010       5.0      0.0       6.0       2      2        0
3    01-07-2010       4.0      0.0       7.0       6      6        0
4    01-08-2010       6.0      1.0       4.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
232  12-02-2010       3.0      1.0       7.0       6      6        0
233  12-03-2010       2.0      1.0       8.0       5      5        0
234  12-06-2010       6.0      1.0       4.0       5      5        0
235  12-07-2010       5.0      0.0       6.0       5      5        0
236  12-08-2010       3.0      1.0       7.0       5      5        0

     Disconnect user_name
0             0   KSP0357
1             0   KSP0357
2             0   KSP0357
3             0   KSP0357
4             0   KSP0357
..          ...       ...
232           0   KSP0357
233           0   KSP0357
234           0   KSP0357
235           0   KSP0357
236           0   KSP0357

[237 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-14-2010       0.0      0.0       0.0       1      1        0
342  04-26-2010       0.0      0.0       0.0       1      1        0
343  05-04-2010       0.0      0.0       0.0       1      1        0
344  06-04-2010       0.0      0.0       0.0       1      1        0
345  12-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KSP0966
1             0   KSP0966
2             0   KSP0966
3             0   KSP0966
4             0   KSP0966
..          ...       ...
341           0   KSP0966
342           0   KSP0966
343           0   KSP0966
344           0   KSP0966
345           0   KSP0966

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       7.0      1.0       1.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       1.0      0.0       4.0       1      1        0
343  12-29-2010       6.0      2.0       1.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  06-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KTG0091
1             0   KTG0091
2             0   KTG0091
3             0   KTG0091
4             0   KTG0091
..          ...       ...
341           0   KTG0091
342           0   KTG0091
343           0   KTG0091
344           0   KTG0091
345           0   KTG0091

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       3.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       9.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       1.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       2.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  02-07-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KVS0425
1             0   KVS0425
2             0   KVS0425
3             0   KVS0425
4             0   KVS0425
..          ...       ...
341           0   KVS0425
342           0   KVS0425
343           0   KVS0425
344           0   KVS0425
345           0   KVS0425

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       3.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       3.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       0.0      0.0       9.0       1      1        0
343  12-30-2010       5.0      0.0       4.0       1      1        0
344  04-16-2010       0.0      0.0       0.0       1      1        0
345  07-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   KVT0028
1             0   KVT0028
2             0   KVT0028
3             0   KVT0028
4             0   KVT0028
..          ...       ...
341           0   KVT0028
342           0   KVT0028
343           0   KVT0028
344           0   KVT0028
345           0   KVT0028

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      14.0      1.0      11.0       1      1        0
1    01-04-2010       7.0      2.0      17.0       1      1        0
2    01-04-2011      10.0      2.0      12.0       1      1        0
3    01-05-2010      12.0      2.0      13.0       1      1        0
4    01-05-2011      10.0      2.0      15.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      11.0      1.0      15.0       1      1        0
342  12-27-2010      11.0      0.0      16.0       1      1        0
343  12-28-2010       8.0      1.0      18.0       1      1        0
344  12-29-2010      13.0      1.0      12.0       1      1        0
345  12-30-2010       6.0      2.0      19.0       1      1        0

     Disconnect user_name
0             0   KWC0004
1             0   KWC0004
2             0   KWC0004
3             0   KWC0004
4             0   KWC0004
..          ...       ...
341           0   KWC0004
342           0   KWC0004
343           0   KWC0004
344           0   KWC0004
345           0   KWC0004

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      2      3.0
1    01-04-2010       5.0      0.0       4.0       1      2      3.0
2    01-04-2011       2.0      0.0       7.0       1      2      1.0
3    01-05-2010       2.0      0.0       7.0       1      2      2.0
4    01-05-2011       5.0      0.0       4.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       5.0       1      1      4.0
342  12-29-2010       5.0      0.0       4.0       1      2      3.0
343  12-30-2010       2.0      2.0       5.0       1      2      2.0
344  02-22-2010       0.0      0.0       0.0       1      2      2.0
345  10-13-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           3.0   KWE0082
1           3.0   KWE0082
2           1.0   KWE0082
3           2.0   KWE0082
4           2.0   KWE0082
..          ...       ...
341         4.0   KWE0082
342         3.0   KWE0082
343         2.0   KWE0082
344         2.0   KWE0082
345         2.0   KWE0082

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      2.0       6.0       1      1        0
1    01-04-2010       0.0      6.0       3.0       1      1        0
2    01-04-2011       2.0      5.0       2.0       1      2        0
3    01-05-2010       2.0      2.0       5.0       1      2        0
4    01-05-2011       2.0      1.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1        0
342  12-29-2010       7.0      1.0       1.0       1      2        0
343  12-30-2010       2.0      6.0       1.0       1      2        0
344  08-18-2010       0.0      0.0       0.0       1      2        0
345  12-22-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   LAF0991
1             0   LAF0991
2             0   LAF0991
3             0   LAF0991
4             0   LAF0991
..          ...       ...
341           0   LAF0991
342           0   LAF0991
343           0   LAF0991
344           0   LAF0991
345           0   LAF0991

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      3.0       6.0       1      1        0
1    01-04-2010       4.0      0.0      10.0       1      2        0
2    01-04-2011       6.0      1.0       7.0       1      2        0
3    01-05-2010       5.0      3.0       6.0       1      2        0
4    01-05-2011       7.0      0.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       8.0       1      2        0
342  12-28-2010       9.0      3.0       2.0       1      1        0
343  12-29-2010       6.0      0.0       8.0       1      2        0
344  12-30-2010       7.0      1.0       6.0       1      2        0
345  09-23-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   LAM0911
1             0   LAM0911
2             0   LAM0911
3             0   LAM0911
4             0   LAM0911
..          ...       ...
341           0   LAM0911
342           0   LAM0911
343           0   LAM0911
344           0   LAM0911
345           0   LAM0911

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       0.0      0.0       3.0       1      1        0
1    01-03-2010       1.0      0.0       2.0       1      2        0
2    01-03-2011       1.0      0.0       2.0       1      2        0
3    01-04-2010       2.0      1.0       0.0       1      1        0
4    01-04-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
483  01-15-2010       0.0      0.0       0.0       1      2        0
484  02-01-2010       0.0      0.0       0.0       1      1        0
485  06-11-2010       0.0      0.0       0.0       1      1        0
486  07-18-2010       0.0      0.0       0.0       1      2        0
487  12-07-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   LAP0338
1             0   LAP0338
2             0   LAP0338
3             0   LAP0338
4             0   LAP0338
..          ...       ...
483           0   LAP0338
484           0   LAP0338
485           0   LAP0338
486           0   LAP0338
487           0   LAP0338

[488 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       5.0       6      7        0
1    01-04-2010       4.0      0.0       7.0       2      3        0
2    01-04-2011       5.0      0.0       6.0       2      3        0
3    01-05-2010       3.0      2.0       6.0       2      3        0
4    01-05-2011       2.0      0.0       9.0       3      4        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       6.0       4      5        0
342  12-29-2010       3.0      2.0       6.0       5      6        0
343  12-30-2010       4.0      1.0       6.0       4      5        0
344  04-15-2010       0.0      0.0       0.0       2      3        0
345  08-11-2010       0.0      0.0       0.0       6      7        0

     Disconnect user_name
0             0   LBC0356
1             0   LBC0356
2             0   LBC0356
3             0   LBC0356
4             0   LBC0356
..          ...       ...
341           0   LBC0356
342           0   LBC0356
343           0   LBC0356
344           0   LBC0356
345           0   LBC0356

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       6.0      2.0       6.0     2.0    3.0      1.0
1    01-03-2010       3.0      2.0       9.0     2.0    2.0      2.0
2    01-03-2011       6.0      1.0       5.0     1.0    2.0      1.0
3    01-04-2010       3.0      0.0      11.0     1.0    2.0      0.0
4    01-04-2011       1.0      0.0       1.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
457  02-06-2010       0.0      0.0       0.0     1.0    1.0      0.0
458  02-09-2010       0.0      0.0       0.0     1.0    1.0      0.0
459  05-01-2010       0.0      0.0       0.0     1.0    0.0      0.0
460  07-31-2010       0.0      0.0       0.0     1.0    0.0      0.0
461  09-12-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           1.0   LBF0214
1           2.0   LBF0214
2           1.0   LBF0214
3           0.0   LBF0214
4           0.0   LBF0214
..          ...       ...
457         0.0   LBF0214
458         0.0   LBF0214
459         0.0   LBF0214
460         0.0   LBF0214
461         0.0   LBF0214

[462 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       4.0      0.0       5.0       1      2        8
1    01-03-2011       4.0      0.0       5.0       1      2        9
2    01-04-2010       4.0      1.0       3.0       1      2        9
3    01-04-2011       5.0      0.0       4.0       1      2        9
4    01-05-2010       4.0      1.0       4.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
448  12-28-2010       3.0      1.0       4.0       1      2        9
449  12-29-2010       3.0      0.0       6.0       1      2        9
450  12-30-2010       3.0      0.0       6.0       1      2        9
451  12-31-2010       3.0      1.0       5.0       1      2        9
452  05-21-2010       0.0      0.0       0.0       1      2        9

     Disconnect user_name
0             8   LBH0942
1             9   LBH0942
2             9   LBH0942
3             9   LBH0942
4             9   LBH0942
..          ...       ...
448           9   LBH0942
449           9   LBH0942
450           9   LBH0942
451           9   LBH0942
452           9   LBH0942

[453 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0      10.0       2      2        9
1    01-04-2010       4.0      3.0       7.0       1      2        9
2    01-04-2011       2.0      3.0       9.0       1      2        8
3    01-05-2010       1.0     12.0       1.0       1      2        9
4    01-05-2011       5.0      2.0       7.0       1      2        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      3.0      10.0       1      2        9
342  12-27-2010       2.0      1.0      11.0       1      2        8
343  12-28-2010       4.0      0.0      10.0       2      3        8
344  12-29-2010       5.0      2.0       7.0       1      2        9
345  12-30-2010       5.0      4.0       5.0       1      2        9

     Disconnect user_name
0             9   LCB0664
1             9   LCB0664
2             8   LCB0664
3             9   LCB0664
4             9   LCB0664
..          ...       ...
341           9   LCB0664
342           8   LCB0664
343           8   LCB0664
344           9   LCB0664
345           9   LCB0664

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      1.0       2.0       1      1      1.0
1    01-05-2010       2.0      1.0       6.0       1      1      1.0
2    01-06-2010       1.0      0.0       8.0       1      1      3.0
3    01-07-2010       6.0      0.0       3.0       1      1      2.0
4    01-08-2010       2.0      0.0       7.0       1      1      4.0
..          ...       ...      ...       ...     ...    ...      ...
152  08-09-2010       5.0      0.0       3.0       1      1      2.0
153  08-10-2010       4.0      0.0       4.0       1      1      6.0
154  08-11-2010       2.0      1.0       6.0       1      1      2.0
155  08-12-2010       2.0      0.0       7.0       1      1      2.0
156  08-13-2010       4.0      0.0       5.0       1      1      1.0

     Disconnect user_name
0           1.0   LCC0819
1           1.0   LCC0819
2           3.0   LCC0819
3           2.0   LCC0819
4           4.0   LCC0819
..          ...       ...
152         2.0   LCC0819
153         6.0   LCC0819
154         2.0   LCC0819
155         2.0   LCC0819
156         1.0   LCC0819

[157 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       5.0       1      1        0
1    01-04-2010      10.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      2.0       7.0       1      1        0
3    01-05-2010       9.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      2.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0      10.0       1      1        0
342  12-28-2010      12.0      1.0       2.0       1      1        0
343  12-29-2010      10.0      0.0       5.0       1      1        0
344  12-30-2010       6.0      0.0       9.0       1      1        0
345  03-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LCD0622
1             0   LCD0622
2             0   LCD0622
3             0   LCD0622
4             0   LCD0622
..          ...       ...
341           0   LCD0622
342           0   LCD0622
343           0   LCD0622
344           0   LCD0622
345           0   LCD0622

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       1      1        0
1    01-04-2010       3.0      1.0       7.0       1      1        0
2    01-04-2011       2.0      1.0       8.0       1      1        0
3    01-05-2010       0.0      1.0      10.0       1      1        0
4    01-05-2011       4.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       7.0       1      1        0
342  12-28-2010       4.0      0.0       7.0       1      1        0
343  12-29-2010       4.0      1.0       6.0       1      1        0
344  12-30-2010       6.0      0.0       4.0       1      1        0
345  02-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LDB0090
1             0   LDB0090
2             0   LDB0090
3             0   LDB0090
4             0   LDB0090
..          ...       ...
341           0   LDB0090
342           0   LDB0090
343           0   LDB0090
344           0   LDB0090
345           0   LDB0090

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-03-2010       3.0      1.0       6.0       1      1        0
1   01-04-2010       5.0      0.0       5.0       1      1        0
2   01-05-2010       3.0      0.0       7.0       1      1        0
3   01-06-2010       3.0      0.0       7.0       1      1        0
4   01-07-2010       6.0      0.0       4.0       1      1        0
5   01-08-2010       3.0      0.0       7.0       1      1        0
6   01-10-2010       3.0      1.0       6.0       1      1        0
7   01-11-2010       6.0      0.0       4.0       1      1        0
8   01-12-2010       4.0      0.0       6.0       1      1        0
9   01-13-2010       4.0      0.0       6.0       1      1        0
10  01-14-2010       8.0      0.0       2.0       1      1        0
11  01-15-2010       3.0      2.0       5.0       2      2        0
12  01-16-2010       3.0      1.0       6.0       1      1        0
13  01-18-2010       6.0      0.0       4.0       1      1        0
14  01-19-2010       2.0      0.0       8.0       1      1        0
15  01-20-2010       3.0      2.0       5.0       1      1        0
16  01-21-2010       6.0      0.0       4.0       1      1        0
17  01-22-2010       4.0      0.0       5.0       1      1        0
18  01-24-2010       8.0      0.0       2.0       2      2        0
19  01-25-2010       4.0      0.0       6.0       1      1        0
20  01-26-2010       5.0      0.0       5.0       1      1        0
21  01-27-2010       3.0      0.0       7.0       2      2        0
22  01-28-2010       4.0      1.0       5.0       1      1        0
23  01-29-2010       4.0      0.0       6.0       1      1        0
24  01-31-2010       5.0      1.0       4.0       1      1        0
25  02-01-2010       3.0      0.0       7.0       2      2        0
26  02-02-2010       2.0      1.0       7.0       1      1        0
27  02-03-2010       4.0      1.0       5.0       1      1        0
28  02-04-2010       2.0      1.0       6.0       1      1        0
29  02-05-2010       5.0      0.0       5.0       2      2        0
30  02-08-2010       6.0      0.0       5.0       2      3        0
31  02-09-2010       6.0      1.0       3.0       2      1        0
32  02-10-2010       6.0      0.0       4.0       1      1        0
33  02-11-2010       4.0      1.0       5.0       2      2        0
34  02-12-2010       5.0      0.0       5.0       1      1        0
35  02-13-2010       2.0      2.0       6.0       1      1        0
36  02-14-2010       3.0      0.0       8.0       2      3        0
37  02-15-2010       4.0      0.0       6.0       2      1        0
38  02-16-2010       4.0      0.0       6.0       1      1        0
39  02-17-2010       6.0      0.0       4.0       1      1        0

    Disconnect user_name
0            0   LDD0560
1            0   LDD0560
2            0   LDD0560
3            0   LDD0560
4            0   LDD0560
5            0   LDD0560
6            0   LDD0560
7            0   LDD0560
8            0   LDD0560
9            0   LDD0560
10           0   LDD0560
11           0   LDD0560
12           0   LDD0560
13           0   LDD0560
14           0   LDD0560
15           0   LDD0560
16           0   LDD0560
17           0   LDD0560
18           0   LDD0560
19           0   LDD0560
20           0   LDD0560
21           0   LDD0560
22           0   LDD0560
23           0   LDD0560
24           0   LDD0560
25           0   LDD0560
26           0   LDD0560
27           0   LDD0560
28           0   LDD0560
29           0   LDD0560
30           0   LDD0560
31           0   LDD0560
32           0   LDD0560
33           0   LDD0560
34           0   LDD0560
35           0   LDD0560
36           0   LDD0560
37           0   LDD0560
38           0   LDD0560
39           0   LDD0560
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       2      2      2.0
1    01-04-2011       0.0      0.0       1.0       1      2      0.0
2    01-05-2010       1.0      0.0       0.0       1      2      0.0
3    01-05-2011       1.0      0.0       0.0       1      2      0.0
4    01-06-2011       1.0      0.0       0.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  05-24-2010       0.0      0.0       0.0       1      2      0.0
342  08-02-2010       0.0      0.0       0.0       1      1      0.0
343  08-06-2010       0.0      0.0       0.0       1      2      0.0
344  08-18-2010       0.0      0.0       0.0       1      1      1.0
345  10-15-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           2.0   LDG0459
1           0.0   LDG0459
2           0.0   LDG0459
3           0.0   LDG0459
4           1.0   LDG0459
..          ...       ...
341         0.0   LDG0459
342         0.0   LDG0459
343         0.0   LDG0459
344         1.0   LDG0459
345         0.0   LDG0459

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-02-2011       0.0      0.0       0.0       1      1        0
342  05-03-2010       0.0      0.0       0.0       1      1        0
343  07-20-2010       0.0      0.0       0.0       1      1        0
344  09-13-2010       0.0      0.0       0.0       1      1        0
345  10-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LDM0587
1             0   LDM0587
2             0   LDM0587
3             0   LDM0587
4             0   LDM0587
..          ...       ...
341           0   LDM0587
342           0   LDM0587
343           0   LDM0587
344           0   LDM0587
345           0   LDM0587

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0      11.0       1      1        0
1    01-04-2010       8.0      1.0       6.0       1      1        0
2    01-04-2011       9.0      0.0       6.0       1      1        0
3    01-05-2010       7.0      1.0       7.0       1      1        0
4    01-05-2011       4.0      2.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       8.0      1.0       6.0       1      1        0
342  12-30-2010       5.0      1.0       9.0       1      1        0
343  03-03-2010       0.0      0.0       0.0       1      1        0
344  08-18-2010       0.0      0.0       0.0       1      1        0
345  10-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LEM0605
1             0   LEM0605
2             0   LEM0605
3             0   LEM0605
4             0   LEM0605
..          ...       ...
341           0   LEM0605
342           0   LEM0605
343           0   LEM0605
344           0   LEM0605
345           0   LEM0605

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       4.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       1.0      0.0       4.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       2.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   LFS0071
1             0   LFS0071
2             0   LFS0071
3             0   LFS0071
4             0   LFS0071
..          ...       ...
341           0   LFS0071
342           0   LFS0071
343           0   LFS0071
344           0   LFS0071
345           0   LFS0071

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       7.0      1.0       7.0       1      1        0
1   01-05-2010      11.0      0.0       4.0       1      1        0
2   01-06-2010       8.0      2.0       5.0       1      1        0
3   01-07-2010       9.0      0.0       6.0       1      1        0
4   01-08-2010       5.0      3.0       6.0       1      1        0
..         ...       ...      ...       ...     ...    ...      ...
77  04-22-2010       1.0      0.0       7.0       1      1        0
78  04-23-2010      10.0      0.0       5.0       1      1        0
79  04-26-2010       9.0      1.0       4.0       1      1        0
80  04-27-2010      12.0      0.0       3.0       1      1        0
81  04-28-2010       6.0      0.0       8.0       1      1        0

    Disconnect user_name
0            0   LHB0606
1            0   LHB0606
2            0   LHB0606
3            0   LHB0606
4            0   LHB0606
..         ...       ...
77           0   LHB0606
78           0   LHB0606
79           0   LHB0606
80           0   LHB0606
81           0   LHB0606

[82 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-04-2011       1.0      0.0       0.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       0.0      0.0       1.0       1      1        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-11-2010       0.0      0.0       0.0       1      1        0
342  10-12-2010       0.0      0.0       0.0       1      1        0
343  11-12-2010       0.0      0.0       0.0       1      1        0
344  12-13-2010       0.0      0.0       0.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LHB0967
1             0   LHB0967
2             0   LHB0967
3             0   LHB0967
4             0   LHB0967
..          ...       ...
341           0   LHB0967
342           0   LHB0967
343           0   LHB0967
344           0   LHB0967
345           0   LHB0967

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      2.0       6.0       1      1        0
1    01-04-2010      10.0      1.0       4.0       1      1        0
2    01-04-2011      10.0      1.0       4.0       1      1        0
3    01-05-2010       4.0      2.0       8.0       1      1        0
4    01-05-2011       4.0      1.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       8.0      0.0       7.0       1      1        0
342  01-07-2011       0.0      0.0       0.0       1      1        0
343  04-27-2010       0.0      0.0       0.0       1      1        0
344  06-21-2010       0.0      0.0       0.0       1      1        0
345  11-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LHL0309
1             0   LHL0309
2             0   LHL0309
3             0   LHL0309
4             0   LHL0309
..          ...       ...
341           0   LHL0309
342           0   LHL0309
343           0   LHL0309
344           0   LHL0309
345           0   LHL0309

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       5.0       1      1        0
1    01-04-2010       1.0      0.0       4.0       1      1        0
2    01-04-2011       1.0      1.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       4.0       1      1        0
4    01-05-2011       2.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       0.0      0.0       5.0       1      1        0
342  12-27-2010       4.0      0.0       1.0       1      1        0
343  12-28-2010       1.0      1.0       3.0       1      1        0
344  12-29-2010       2.0      0.0       3.0       1      1        0
345  12-30-2010       3.0      0.0       1.0       1      1        0

     Disconnect user_name
0             0   LHN0151
1             0   LHN0151
2             0   LHN0151
3             0   LHN0151
4             0   LHN0151
..          ...       ...
341           0   LHN0151
342           0   LHN0151
343           0   LHN0151
344           0   LHN0151
345           0   LHN0151

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0     1.0    2.0      0.0
1    01-04-2010       3.0      0.0       6.0     1.0    2.0      0.0
2    01-04-2011       4.0      0.0       5.0     1.0    2.0      0.0
3    01-05-2010       5.0      1.0       3.0     1.0    2.0      0.0
4    01-05-2011       4.0      0.0       5.0     1.0    3.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
352  02-15-2011       0.0      0.0       0.0     2.0    3.0      0.0
353  02-19-2011       0.0      0.0       0.0     1.0    1.0      0.0
354  05-15-2010       0.0      0.0       0.0     1.0    0.0      0.0
355  08-03-2010       0.0      0.0       0.0     2.0    3.0      2.0
356  10-30-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   LIM0674
1           0.0   LIM0674
2           0.0   LIM0674
3           0.0   LIM0674
4           1.0   LIM0674
..          ...       ...
352         0.0   LIM0674
353         0.0   LIM0674
354         0.0   LIM0674
355         2.0   LIM0674
356         0.0   LIM0674

[357 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-10-2010       0.0      0.0       0.0       1      1        0
342  06-29-2010       0.0      0.0       0.0       1      1        0
343  07-16-2010       0.0      0.0       0.0       1      1        0
344  08-02-2010       0.0      0.0       0.0       1      1        0
345  09-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LJB0826
1             0   LJB0826
2             0   LJB0826
3             0   LJB0826
4             0   LJB0826
..          ...       ...
341           0   LJB0826
342           0   LJB0826
343           0   LJB0826
344           0   LJB0826
345           0   LJB0826

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       3.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       3.0       1      1        0
342  01-24-2011       0.0      0.0       0.0       1      1        0
343  04-07-2011       0.0      0.0       0.0       1      1        0
344  05-13-2011       0.0      0.0       0.0       2      2        0
345  11-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LJJ0905
1             0   LJJ0905
2             0   LJJ0905
3             0   LJJ0905
4             0   LJJ0905
..          ...       ...
341           0   LJJ0905
342           0   LJJ0905
343           0   LJJ0905
344           0   LJJ0905
345           0   LJJ0905

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0     1.0    1.0      0.0
1    01-05-2010       0.0      0.0       3.0     1.0    1.0      0.0
2    01-06-2010       2.0      0.0       1.0     1.0    1.0      0.0
3    01-07-2010       1.0      0.0       2.0     1.0    1.0      0.0
4    01-08-2010       1.0      0.0       2.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
163  08-26-2010       0.0      1.0       2.0     1.0    1.0      0.0
164  06-24-2010       0.0      0.0       0.0     1.0    1.0      0.0
165  07-31-2010       0.0      0.0       0.0     1.0    1.0      1.0
166  08-07-2010       0.0      0.0       0.0     1.0    1.0      1.0
167  08-11-2010       0.0      0.0       0.0     2.0    2.0      1.0

     Disconnect user_name
0           0.0   LJR0523
1           0.0   LJR0523
2           0.0   LJR0523
3           0.0   LJR0523
4           0.0   LJR0523
..          ...       ...
163         0.0   LJR0523
164         0.0   LJR0523
165         1.0   LJR0523
166         1.0   LJR0523
167         1.0   LJR0523

[168 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       2      3      3.0
1    01-04-2010       6.0      0.0       3.0       1      1      2.0
2    01-04-2011       5.0      1.0       3.0       1      2      4.0
3    01-05-2010       3.0      0.0       6.0       1      2      1.0
4    01-05-2011       4.0      0.0       4.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       3.0       1      2      1.0
342  12-28-2010       3.0      0.0       6.0       1      2      1.0
343  12-29-2010       3.0      2.0       3.0       1      2      2.0
344  12-30-2010       5.0      0.0       4.0       1      2      2.0
345  01-10-2011       0.0      0.0       0.0       1      2      3.0

     Disconnect user_name
0           3.0   LJT0817
1           2.0   LJT0817
2           4.0   LJT0817
3           1.0   LJT0817
4           2.0   LJT0817
..          ...       ...
341         1.0   LJT0817
342         1.0   LJT0817
343         2.0   LJT0817
344         2.0   LJT0817
345         3.0   LJT0817

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      2.0       7.0       1      1        0
2    01-04-2011       4.0      0.0      11.0       1      1        0
3    01-05-2010       6.0      0.0       9.0       1      1        0
4    01-05-2011       4.0      0.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       9.0       1      1        0
342  12-27-2010       1.0      0.0      14.0       1      1        0
343  12-28-2010       7.0      1.0       7.0       1      1        0
344  12-29-2010      10.0      1.0       3.0       1      1        0
345  12-30-2010       7.0      1.0       7.0       1      1        0

     Disconnect user_name
0             0   LLV0602
1             0   LLV0602
2             0   LLV0602
3             0   LLV0602
4             0   LLV0602
..          ...       ...
341           0   LLV0602
342           0   LLV0602
343           0   LLV0602
344           0   LLV0602
345           0   LLV0602

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       8.0       1      2        0
1    01-04-2010       4.0      2.0       5.0       1      1        0
2    01-04-2011       3.0      1.0       7.0       1      2        0
3    01-05-2010       3.0      1.0       7.0       1      2        0
4    01-05-2011       2.0      2.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       5.0       1      2        0
342  12-27-2010       5.0      2.0       4.0       1      2        0
343  12-28-2010       2.0      0.0       9.0       1      1        0
344  12-29-2010       3.0      1.0       7.0       1      2        0
345  12-30-2010       3.0      0.0       8.0       1      2        0

     Disconnect user_name
0             0   LMF0980
1             0   LMF0980
2             0   LMF0980
3             0   LMF0980
4             0   LMF0980
..          ...       ...
341           0   LMF0980
342           0   LMF0980
343           0   LMF0980
344           0   LMF0980
345           0   LMF0980

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       2.0      1.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       1.0      0.0       1.0       1      1        0
344  01-10-2011       0.0      0.0       0.0       1      1        0
345  03-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LNR0656
1             0   LNR0656
2             0   LNR0656
3             0   LNR0656
4             0   LNR0656
..          ...       ...
341           0   LNR0656
342           0   LNR0656
343           0   LNR0656
344           0   LNR0656
345           0   LNR0656

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       2      3        0
1    01-04-2010       1.0      0.0       4.0       1      2        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-05-2011       5.0      2.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        0
342  12-28-2010       1.0      0.0       8.0       1      1        0
343  12-29-2010       2.0      0.0       7.0       1      2        0
344  12-30-2010       5.0      0.0       3.0       1      2        0
345  01-26-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   LNS0989
1             0   LNS0989
2             0   LNS0989
3             0   LNS0989
4             0   LNS0989
..          ...       ...
341           0   LNS0989
342           0   LNS0989
343           0   LNS0989
344           0   LNS0989
345           0   LNS0989

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      1.0       5.0       1      1        0
1    01-04-2010       7.0      1.0       7.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010       8.0      2.0       5.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      2.0       3.0       1      1        0
342  12-28-2010       4.0      1.0      10.0       1      1        0
343  12-29-2010       8.0      1.0       6.0       1      1        0
344  12-30-2010       6.0      2.0       7.0       1      1        0
345  10-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LOF0311
1             0   LOF0311
2             0   LOF0311
3             0   LOF0311
4             0   LOF0311
..          ...       ...
341           0   LOF0311
342           0   LOF0311
343           0   LOF0311
344           0   LOF0311
345           0   LOF0311

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       3.0       1      2      3.0
1    01-05-2010       4.0      0.0       5.0       1      2      1.0
2    01-06-2010       5.0      0.0       4.0       1      2      2.0
3    01-07-2010       4.0      1.0       4.0       1      2      2.0
4    01-08-2010       3.0      0.0       6.0       1      2      4.0
..          ...       ...      ...       ...     ...    ...      ...
137  07-19-2010       4.0      2.0       3.0       1      2      3.0
138  07-20-2010       3.0      0.0       6.0       1      2      1.0
139  07-21-2010       4.0      2.0       3.0       1      2      5.0
140  07-22-2010       5.0      0.0       4.0       1      1      3.0
141  07-23-2010       7.0      0.0       2.0       1      2      2.0

     Disconnect user_name
0           3.0   LOM0086
1           1.0   LOM0086
2           2.0   LOM0086
3           2.0   LOM0086
4           4.0   LOM0086
..          ...       ...
137         3.0   LOM0086
138         1.0   LOM0086
139         5.0   LOM0086
140         3.0   LOM0086
141         2.0   LOM0086

[142 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0       1      1        0
1    01-04-2010       3.0      0.0      12.0       1      1        0
2    01-04-2011       4.0      1.0      10.0       1      1        0
3    01-05-2010      11.0      0.0       4.0       1      1        0
4    01-05-2011       7.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       8.0       1      1        0
342  12-28-2010       6.0      1.0       7.0       1      1        0
343  12-29-2010       5.0      1.0       9.0       1      1        0
344  12-30-2010       7.0      0.0       8.0       1      1        0
345  06-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LPC0492
1             0   LPC0492
2             0   LPC0492
3             0   LPC0492
4             0   LPC0492
..          ...       ...
341           0   LPC0492
342           0   LPC0492
343           0   LPC0492
344           0   LPC0492
345           0   LPC0492

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       0.0      0.0       1.0       1      1        0
1   01-05-2010       0.0      0.0       1.0       1      1        0
2   01-06-2010       1.0      0.0       0.0       1      1        0
3   01-07-2010       0.0      0.0       1.0       1      1        0
4   01-08-2010       0.0      0.0       1.0       1      1        0
5   01-11-2010       0.0      0.0       1.0       1      1        0
6   01-12-2010       1.0      0.0       0.0       1      1        0
7   01-13-2010       0.0      1.0       0.0       1      1        0
8   01-14-2010       1.0      0.0       0.0       1      1        0
9   01-15-2010       1.0      0.0       0.0       1      1        0
10  01-18-2010       1.0      0.0       0.0       1      1        0
11  01-19-2010       0.0      0.0       1.0       1      1        0
12  01-20-2010       0.0      0.0       1.0       1      1        0
13  01-21-2010       1.0      0.0       0.0       1      1        0
14  01-22-2010       1.0      0.0       0.0       1      1        0
15  01-25-2010       0.0      0.0       1.0       1      1        0
16  01-26-2010       0.0      1.0       0.0       1      1        0
17  01-27-2010       0.0      0.0       1.0       1      1        0
18  01-28-2010       1.0      0.0       0.0       1      1        0
19  01-29-2010       0.0      0.0       1.0       1      1        0
20  02-01-2010       1.0      0.0       0.0       1      1        0
21  02-02-2010       0.0      0.0       1.0       1      1        0
22  02-03-2010       0.0      0.0       1.0       1      1        0
23  02-05-2010       0.0      0.0       1.0       1      1        0
24  02-08-2010       0.0      0.0       1.0       1      1        0
25  02-09-2010       0.0      0.0       1.0       1      1        0
26  02-10-2010       0.0      0.0       1.0       1      1        0
27  02-11-2010       1.0      0.0       0.0       1      1        0
28  02-12-2010       1.0      0.0       0.0       1      1        0
29  02-15-2010       1.0      0.0       0.0       1      1        0
30  02-16-2010       1.0      0.0       0.0       1      1        0
31  02-17-2010       0.0      0.0       1.0       1      1        0
32  02-18-2010       1.0      0.0       0.0       1      1        0
33  02-19-2010       0.0      0.0       1.0       1      1        0
34  02-22-2010       1.0      0.0       0.0       1      1        0
35  02-23-2010       0.0      0.0       1.0       1      1        0
36  02-04-2010       0.0      0.0       0.0       1      1        0

    Disconnect user_name
0            0   LPH0572
1            0   LPH0572
2            0   LPH0572
3            0   LPH0572
4            0   LPH0572
5            0   LPH0572
6            0   LPH0572
7            0   LPH0572
8            0   LPH0572
9            0   LPH0572
10           0   LPH0572
11           0   LPH0572
12           0   LPH0572
13           0   LPH0572
14           0   LPH0572
15           0   LPH0572
16           0   LPH0572
17           0   LPH0572
18           0   LPH0572
19           0   LPH0572
20           0   LPH0572
21           0   LPH0572
22           0   LPH0572
23           0   LPH0572
24           0   LPH0572
25           0   LPH0572
26           0   LPH0572
27           0   LPH0572
28           0   LPH0572
29           0   LPH0572
30           0   LPH0572
31           0   LPH0572
32           0   LPH0572
33           0   LPH0572
34           0   LPH0572
35           0   LPH0572
36           0   LPH0572
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      2.0       6.0       1      1      0.0
1    01-05-2010       5.0      1.0       9.0       1      1      0.0
2    01-06-2010       7.0      0.0       8.0       1      1      0.0
3    01-07-2010       5.0      0.0      10.0       1      1      0.0
4    01-08-2010      11.0      0.0       4.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
192  10-06-2010       9.0      0.0       6.0       1      1      0.0
193  10-07-2010       6.0      1.0       8.0       1      1      0.0
194  10-08-2010       8.0      0.0       6.0       1      1      0.0
195  10-11-2010       5.0      0.0       9.0       1      1      0.0
196  06-23-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   LQC0479
1           0.0   LQC0479
2           0.0   LQC0479
3           0.0   LQC0479
4           0.0   LQC0479
..          ...       ...
192         0.0   LQC0479
193         0.0   LQC0479
194         0.0   LQC0479
195         0.0   LQC0479
196         0.0   LQC0479

[197 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      2        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-06-2010       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-05-2011       0.0      0.0       0.0       1      2        0
342  01-07-2011       0.0      0.0       0.0       2      3        0
343  01-20-2011       0.0      0.0       0.0       1      2        0
344  02-09-2010       0.0      0.0       0.0       1      2        0
345  08-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LQP0508
1             0   LQP0508
2             0   LQP0508
3             0   LQP0508
4             0   LQP0508
..          ...       ...
341           0   LQP0508
342           0   LQP0508
343           0   LQP0508
344           0   LQP0508
345           0   LQP0508

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       1.0      0.0      13.0       2      3      3.0
1    01-03-2011       1.0      0.0       3.0       1      2      2.0
2    01-04-2010       7.0      1.0       6.0       1      2      3.0
3    01-04-2011       6.0      1.0       6.0       1      2      2.0
4    01-05-2010       6.0      2.0       6.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
395  12-27-2010       2.0      0.0      12.0       1      1      1.0
396  12-28-2010       4.0      0.0      10.0       1      2      2.0
397  12-29-2010       6.0      1.0       7.0       1      2      3.0
398  12-30-2010       5.0      0.0       9.0       1      2      4.0
399  12-31-2010       8.0      1.0       5.0       2      2      2.0

     Disconnect user_name
0           3.0   LRR0148
1           2.0   LRR0148
2           3.0   LRR0148
3           2.0   LRR0148
4           0.0   LRR0148
..          ...       ...
395         1.0   LRR0148
396         2.0   LRR0148
397         3.0   LRR0148
398         4.0   LRR0148
399         2.0   LRR0148

[400 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-31-2011       0.0      0.0       0.0       1      1        0
342  06-04-2010       0.0      0.0       0.0       1      1        0
343  06-17-2010       0.0      0.0       0.0       1      1        0
344  08-04-2010       0.0      0.0       0.0       1      1        0
345  08-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   LRW0970
1             0   LRW0970
2             0   LRW0970
3             0   LRW0970
4             0   LRW0970
..          ...       ...
341           0   LRW0970
342           0   LRW0970
343           0   LRW0970
344           0   LRW0970
345           0   LRW0970

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0       1      1        0
1    01-04-2010      10.0      1.0       4.0       1      1        0
2    01-04-2011       4.0      1.0      10.0       1      1        0
3    01-05-2010       6.0      1.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       9.0      0.0       5.0       1      1        0
342  12-27-2010       6.0      0.0       9.0       1      1        0
343  12-28-2010       7.0      0.0       8.0       1      1        0
344  12-29-2010       3.0      0.0      11.0       1      1        0
345  12-30-2010      10.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   LTS0860
1             0   LTS0860
2             0   LTS0860
3             0   LTS0860
4             0   LTS0860
..          ...       ...
341           0   LTS0860
342           0   LTS0860
343           0   LTS0860
344           0   LTS0860
345           0   LTS0860

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0     1.0    1.0        0
1    01-04-2010       0.0      0.0       3.0     1.0    1.0        0
2    01-04-2011       2.0      0.0       1.0     1.0    1.0        0
3    01-05-2010       1.0      0.0       2.0     1.0    1.0        0
4    01-05-2011       0.0      0.0       3.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
298  04-22-2010       0.0      0.0       0.0     1.0    1.0        0
299  05-08-2010       0.0      0.0       0.0     1.0    1.0        0
300  05-20-2010       0.0      0.0       0.0     2.0    2.0        0
301  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
302  11-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   LUR0896
1             0   LUR0896
2             0   LUR0896
3             0   LUR0896
4             0   LUR0896
..          ...       ...
298           0   LUR0896
299           0   LUR0896
300           0   LUR0896
301           0   LUR0896
302           0   LUR0896

[303 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       4.0      0.0      11.0       1      1        0
1    01-04-2010       2.0      0.0      12.0       1      1        0
2    01-05-2010       7.0      1.0       7.0       1      1        0
3    01-06-2010       6.0      0.0       9.0       1      1        0
4    01-07-2010       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
113  05-10-2010       8.0      0.0       7.0       1      1        0
114  05-11-2010       6.0      0.0       9.0       1      1        0
115  05-12-2010       8.0      0.0       7.0       1      1        0
116  05-13-2010       7.0      2.0       6.0       1      1        0
117  05-14-2010      12.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   MAD0496
1             0   MAD0496
2             0   MAD0496
3             0   MAD0496
4             0   MAD0496
..          ...       ...
113           0   MAD0496
114           0   MAD0496
115           0   MAD0496
116           0   MAD0496
117           0   MAD0496

[118 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      5.0       7.0       1      1        0
1    01-04-2010       1.0     12.0       2.0       1      1        0
2    01-04-2011       8.0      6.0       1.0       1      1        0
3    01-05-2010       3.0      7.0       5.0       1      1        0
4    01-05-2011       4.0      3.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       8.0       1      1        0
342  12-27-2010       6.0      2.0       7.0       1      1        0
343  12-28-2010       5.0      8.0       2.0       1      1        0
344  12-29-2010       5.0      3.0       7.0       1      1        0
345  12-30-2010       2.0      3.0      10.0       1      1        0

     Disconnect user_name
0             0   MAD0753
1             0   MAD0753
2             0   MAD0753
3             0   MAD0753
4             0   MAD0753
..          ...       ...
341           0   MAD0753
342           0   MAD0753
343           0   MAD0753
344           0   MAD0753
345           0   MAD0753

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       2.0      1.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      1.0       1.0       1      1        0
342  12-29-2010       2.0      0.0       1.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  01-21-2011       0.0      0.0       0.0       1      1        0
345  08-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MAE0331
1             0   MAE0331
2             0   MAE0331
3             0   MAE0331
4             0   MAE0331
..          ...       ...
341           0   MAE0331
342           0   MAE0331
343           0   MAE0331
344           0   MAE0331
345           0   MAE0331

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       1      2        0
1    01-04-2010       4.0      0.0       7.0       1      2        0
2    01-04-2011       3.0      0.0       8.0       1      2        0
3    01-05-2010       4.0      1.0       6.0       1      2        0
4    01-05-2011       3.0      1.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       8.0       1      2        0
342  12-27-2010       5.0      0.0       6.0       1      2        0
343  12-28-2010       5.0      1.0       5.0       1      2        0
344  12-29-2010       4.0      2.0       5.0       1      2        0
345  12-30-2010       4.0      1.0       5.0       1      2        0

     Disconnect user_name
0             0   MAH0149
1             0   MAH0149
2             0   MAH0149
3             0   MAH0149
4             0   MAH0149
..          ...       ...
341           0   MAH0149
342           0   MAH0149
343           0   MAH0149
344           0   MAH0149
345           0   MAH0149

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0       1      1        0
1    01-04-2010       7.0      1.0       7.0       1      1        0
2    01-04-2011       6.0      0.0       9.0       1      1        0
3    01-05-2010       6.0      1.0       7.0       1      1        0
4    01-05-2011       6.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       9.0       1      1        0
342  12-27-2010       7.0      0.0       8.0       1      1        0
343  12-28-2010      10.0      1.0       4.0       1      1        0
344  12-29-2010       6.0      0.0       9.0       1      1        0
345  12-30-2010       8.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   MAH0864
1             0   MAH0864
2             0   MAH0864
3             0   MAH0864
4             0   MAH0864
..          ...       ...
341           0   MAH0864
342           0   MAH0864
343           0   MAH0864
344           0   MAH0864
345           0   MAH0864

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1      0.0
1    01-04-2010       0.0      0.0       1.0       1      1      0.0
2    01-04-2011       0.0      0.0       1.0       1      1      0.0
3    01-05-2011       0.0      0.0       1.0       1      1      0.0
4    01-06-2010       0.0      0.0       1.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
292  07-26-2010       0.0      0.0       0.0       1      1      0.0
293  10-15-2010       0.0      0.0       0.0       1      1      0.0
294  11-04-2010       0.0      0.0       0.0       1      1      0.0
295  11-19-2010       0.0      0.0       0.0       1      1      0.0
296  12-03-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   MAR0955
1           0.0   MAR0955
2           0.0   MAR0955
3           0.0   MAR0955
4           0.0   MAR0955
..          ...       ...
292         0.0   MAR0955
293         0.0   MAR0955
294         0.0   MAR0955
295         0.0   MAR0955
296         0.0   MAR0955

[297 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       8.0      0.0       6.0       1      1      0.0
1    01-05-2010       5.0      1.0       7.0       1      1      0.0
2    01-06-2010       5.0      0.0       9.0       1      1      0.0
3    01-07-2010       6.0      0.0       7.0       1      1      0.0
4    01-08-2010       5.0      2.0       7.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
196  10-12-2010       5.0      2.0       7.0       1      1      0.0
197  10-13-2010       7.0      0.0       7.0       1      1      0.0
198  10-14-2010       9.0      0.0       5.0       1      1      0.0
199  10-15-2010      11.0      0.0       3.0       1      1      0.0
200  04-30-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   MAS0025
1           0.0   MAS0025
2           0.0   MAS0025
3           0.0   MAS0025
4           0.0   MAS0025
..          ...       ...
196         0.0   MAS0025
197         0.0   MAS0025
198         0.0   MAS0025
199         0.0   MAS0025
200         0.0   MAS0025

[201 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       7.0       1      1        0
1    01-04-2010       5.0      1.0       7.0       1      1        0
2    01-04-2011       3.0      1.0      10.0       1      1        0
3    01-05-2010       9.0      0.0       5.0       1      1        0
4    01-05-2011       7.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       8.0       1      1        0
342  12-27-2010       6.0      0.0       8.0       1      1        0
343  12-28-2010       6.0      0.0       8.0       1      1        0
344  12-29-2010       6.0      0.0       8.0       1      1        0
345  12-30-2010       9.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   MAW0166
1             0   MAW0166
2             0   MAW0166
3             0   MAW0166
4             0   MAW0166
..          ...       ...
341           0   MAW0166
342           0   MAW0166
343           0   MAW0166
344           0   MAW0166
345           0   MAW0166

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      0.0       6.0       1      1        0
1    01-05-2010       1.0      1.0       7.0       1      1        0
2    01-06-2010       4.0      2.0       3.0       1      1        0
3    01-07-2010       1.0      2.0       6.0       1      1        0
4    01-08-2010       5.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
230  12-06-2010       2.0      0.0       7.0       1      1        0
231  01-21-2010       0.0      0.0       0.0       1      1        0
232  02-26-2010       0.0      0.0       0.0       1      1        0
233  04-16-2010       0.0      0.0       0.0       1      1        0
234  09-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MBG0438
1             0   MBG0438
2             0   MBG0438
3             0   MBG0438
4             0   MBG0438
..          ...       ...
230           0   MBG0438
231           0   MBG0438
232           0   MBG0438
233           0   MBG0438
234           0   MBG0438

[235 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      3.0       8.0       2      2      4.0
1    01-04-2010       9.0      0.0       6.0       1      2      1.0
2    01-04-2011       4.0      1.0       9.0       1      2      1.0
3    01-05-2010       6.0      0.0       9.0       1      2      3.0
4    01-05-2011      10.0      0.0       5.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       8.0       1      2      3.0
342  12-27-2010       4.0      0.0      11.0       1      2      2.0
343  12-28-2010       8.0      0.0       7.0       1      2      4.0
344  12-29-2010      10.0      0.0       5.0       1      2      5.0
345  12-30-2010       2.0      0.0      13.0       1      2      2.0

     Disconnect user_name
0           4.0   MBJ0312
1           1.0   MBJ0312
2           1.0   MBJ0312
3           3.0   MBJ0312
4           2.0   MBJ0312
..          ...       ...
341         2.0   MBJ0312
342         2.0   MBJ0312
343         4.0   MBJ0312
344         5.0   MBJ0312
345         2.0   MBJ0312

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-10-2011       0.0      0.0       0.0       1      1        0
342  05-17-2010       0.0      0.0       0.0       1      1        0
343  08-19-2010       0.0      0.0       0.0       1      1        0
344  09-29-2010       0.0      0.0       0.0       1      1        0
345  12-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MBR0724
1             0   MBR0724
2             0   MBR0724
3             0   MBR0724
4             0   MBR0724
..          ...       ...
341           0   MBR0724
342           0   MBR0724
343           0   MBR0724
344           0   MBR0724
345           0   MBR0724

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       4.0      0.0       5.0       1      1        0
1   01-05-2010       5.0      0.0       4.0       1      1        0
2   01-06-2010       4.0      0.0       1.0       1      1        0
3   01-07-2010       3.0      1.0       5.0       1      1        0
4   01-08-2010       4.0      1.0       3.0       1      1        0
5   01-11-2010       4.0      0.0       5.0       1      1        0
6   01-12-2010       4.0      2.0       3.0       1      1        0
7   01-13-2010       5.0      0.0       4.0       1      1        0
8   01-14-2010       3.0      1.0       5.0       1      1        0
9   01-15-2010       1.0      0.0       4.0       1      1        0
10  01-18-2010       3.0      1.0       5.0       1      1        0
11  01-19-2010       4.0      0.0       5.0       1      1        0
12  01-20-2010       1.0      0.0       8.0       1      1        0
13  01-21-2010       1.0      1.0       7.0       1      1        0
14  01-22-2010       4.0      1.0       4.0       1      1        0
15  01-25-2010       6.0      0.0       2.0       1      1        0
16  01-26-2010       2.0      0.0       7.0       1      1        0
17  01-27-2010       3.0      1.0       5.0       1      1        0
18  01-28-2010       0.0      0.0       9.0       1      1        0
19  01-29-2010       1.0      0.0       7.0       1      1        0
20  02-01-2010       5.0      0.0       4.0       1      1        0
21  02-02-2010       4.0      0.0       5.0       1      1        0
22  02-03-2010       4.0      1.0       4.0       1      1        0
23  02-04-2010       3.0      0.0       6.0       1      1        0
24  02-05-2010       3.0      0.0       6.0       1      1        0
25  02-08-2010       1.0      0.0       8.0       1      1        0
26  02-09-2010       2.0      0.0       6.0       1      1        0
27  02-10-2010       6.0      1.0       2.0       1      1        0
28  02-11-2010       7.0      0.0       2.0       1      1        0
29  02-12-2010       3.0      2.0       4.0       1      1        0

    Disconnect user_name
0            0   MBW0809
1            0   MBW0809
2            0   MBW0809
3            0   MBW0809
4            0   MBW0809
5            0   MBW0809
6            0   MBW0809
7            0   MBW0809
8            0   MBW0809
9            0   MBW0809
10           0   MBW0809
11           0   MBW0809
12           0   MBW0809
13           0   MBW0809
14           0   MBW0809
15           0   MBW0809
16           0   MBW0809
17           0   MBW0809
18           0   MBW0809
19           0   MBW0809
20           0   MBW0809
21           0   MBW0809
22           0   MBW0809
23           0   MBW0809
24           0   MBW0809
25           0   MBW0809
26           0   MBW0809
27           0   MBW0809
28           0   MBW0809
29           0   MBW0809
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       4.0      0.0       5.0       1      2      0.0
1    01-04-2010       6.0      1.0       2.0       1      2      0.0
2    01-05-2010       0.0      4.0       5.0       2      2      0.0
3    01-06-2010       1.0      6.0       1.0       1      2      0.0
4    01-07-2010       4.0      0.0       5.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
171  07-13-2010       2.0      1.0       6.0       1      2      1.0
172  07-14-2010       3.0      1.0       5.0       2      3      1.0
173  07-15-2010       2.0      1.0       6.0       1      2      0.0
174  07-16-2010       4.0      1.0       4.0       1      2      0.0
175  07-19-2010       5.0      0.0       4.0       1      2      0.0

     Disconnect user_name
0           0.0   MCD0125
1           0.0   MCD0125
2           0.0   MCD0125
3           0.0   MCD0125
4           1.0   MCD0125
..          ...       ...
171         1.0   MCD0125
172         1.0   MCD0125
173         0.0   MCD0125
174         0.0   MCD0125
175         0.0   MCD0125

[176 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0      13.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011       7.0      0.0       8.0       1      1        0
3    01-05-2010       6.0      1.0       8.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0       7.0       1      1        0
342  12-27-2010       7.0      0.0       7.0       1      1        0
343  12-28-2010       5.0      1.0       5.0       1      1        0
344  12-29-2010       5.0      1.0       8.0       1      1        0
345  12-30-2010       8.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   MCF0327
1             0   MCF0327
2             0   MCF0327
3             0   MCF0327
4             0   MCF0327
..          ...       ...
341           0   MCF0327
342           0   MCF0327
343           0   MCF0327
344           0   MCF0327
345           0   MCF0327

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       0.0      0.0       1.0     1.0    1.0      0.0
1    01-04-2010       0.0      0.0       1.0     1.0    1.0      0.0
2    01-05-2010       1.0      0.0       0.0     1.0    1.0      0.0
3    01-06-2010       1.0      0.0       0.0     1.0    1.0      0.0
4    01-07-2010       0.0      0.0       1.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
241  06-05-2010       0.0      0.0       0.0     1.0    1.0      0.0
242  07-13-2010       0.0      0.0       0.0     2.0    2.0      0.0
243  07-28-2010       0.0      0.0       0.0     1.0    1.0      0.0
244  09-01-2010       0.0      0.0       0.0     2.0    2.0      0.0
245  09-25-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   MCF0600
1           0.0   MCF0600
2           0.0   MCF0600
3           0.0   MCF0600
4           0.0   MCF0600
..          ...       ...
241         0.0   MCF0600
242         0.0   MCF0600
243         0.0   MCF0600
244         0.0   MCF0600
245         0.0   MCF0600

[246 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       6.0       1      1        0
1    01-04-2010       7.0      1.0       7.0       1      1        0
2    01-04-2011       5.0      2.0       8.0       1      1        0
3    01-05-2010      11.0      0.0       4.0       1      1        0
4    01-05-2011       8.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       8.0       1      1        0
342  12-28-2010       8.0      0.0       7.0       1      1        0
343  12-29-2010       2.0      1.0      12.0       1      1        0
344  12-30-2010       8.0      0.0       7.0       1      1        0
345  11-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MCJ0324
1             0   MCJ0324
2             0   MCJ0324
3             0   MCJ0324
4             0   MCJ0324
..          ...       ...
341           0   MCJ0324
342           0   MCJ0324
343           0   MCJ0324
344           0   MCJ0324
345           0   MCJ0324

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       5.0       1      1        0
1    01-04-2010       2.0      1.0      11.0       1      1        0
2    01-04-2011       4.0      0.0      10.0       1      1        0
3    01-05-2010       9.0      0.0       3.0       1      1        0
4    01-05-2011       5.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       7.0       1      1        0
342  12-27-2010       6.0      0.0       8.0       1      1        0
343  12-28-2010       7.0      0.0       7.0       1      1        0
344  12-29-2010       6.0      0.0       8.0       1      1        0
345  12-30-2010       4.0      0.0       9.0       1      1        0

     Disconnect user_name
0             0   MCS0035
1             0   MCS0035
2             0   MCS0035
3             0   MCS0035
4             0   MCS0035
..          ...       ...
341           0   MCS0035
342           0   MCS0035
343           0   MCS0035
344           0   MCS0035
345           0   MCS0035

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-05-2011       1.0      0.0       0.0       1      1        0
3    01-06-2010       0.0      0.0       1.0       1      1        0
4    01-06-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-22-2011       0.0      0.0       0.0       1      1        0
342  04-18-2011       0.0      0.0       0.0       1      1        0
343  04-30-2010       0.0      0.0       0.0       1      1        0
344  05-25-2010       0.0      0.0       0.0       1      1        0
345  07-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MCT0720
1             0   MCT0720
2             0   MCT0720
3             0   MCT0720
4             0   MCT0720
..          ...       ...
341           0   MCT0720
342           0   MCT0720
343           0   MCT0720
344           0   MCT0720
345           0   MCT0720

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1      2.0
1    01-04-2010       1.0      0.0       0.0       1      1      0.0
2    01-04-2011       1.0      0.0       0.0       1      1      1.0
3    01-05-2010       0.0      0.0       1.0       1      1      1.0
4    01-05-2011       1.0      0.0       0.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
291  06-17-2010       0.0      0.0       0.0       1      1      1.0
292  07-01-2010       0.0      0.0       0.0       1      1      4.0
293  07-12-2010       0.0      0.0       0.0       1      1      2.0
294  07-27-2010       0.0      0.0       0.0       1      1      3.0
295  11-17-2010       0.0      0.0       0.0       1      1      2.0

     Disconnect user_name
0           2.0   MDH0580
1           0.0   MDH0580
2           1.0   MDH0580
3           1.0   MDH0580
4           2.0   MDH0580
..          ...       ...
291         1.0   MDH0580
292         4.0   MDH0580
293         2.0   MDH0580
294         3.0   MDH0580
295         2.0   MDH0580

[296 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       6.0      0.0       3.0       1      1        0
1    01-03-2011       5.0      1.0       3.0       1      2        0
2    01-04-2010       1.0      1.0       7.0       1      2        0
3    01-04-2011       4.0      1.0       4.0       1      1        0
4    01-05-2010       3.0      0.0       6.0       2      3        0
..          ...       ...      ...       ...     ...    ...      ...
454  12-29-2010       2.0      0.0       7.0       1      2        0
455  12-30-2010       6.0      0.0       3.0       1      2        0
456  12-31-2010       6.0      0.0       3.0       1      2        0
457  02-26-2010       0.0      0.0       0.0       1      2        0
458  09-28-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MDH0686
1             0   MDH0686
2             0   MDH0686
3             0   MDH0686
4             0   MDH0686
..          ...       ...
454           0   MDH0686
455           0   MDH0686
456           0   MDH0686
457           0   MDH0686
458           0   MDH0686

[459 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       8.0       2      3      8.0
1    01-04-2010       2.0      0.0       2.0       1      2      8.0
2    01-04-2011      12.0      0.0       4.0       1      2      9.0
3    01-05-2010       8.0      0.0       8.0       1      2      8.0
4    01-05-2011      10.0      0.0       6.0       1      2      9.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      1.0       9.0       1      2      8.0
342  12-29-2010       5.0      1.0      10.0       1      2      9.0
343  12-30-2010      11.0      0.0       5.0       1      2      8.0
344  01-07-2011       0.0      0.0       0.0       2      2      0.0
345  03-24-2011       0.0      0.0       0.0       1      2      8.0

     Disconnect user_name
0           8.0   MDM0625
1           8.0   MDM0625
2           9.0   MDM0625
3           8.0   MDM0625
4           9.0   MDM0625
..          ...       ...
341         8.0   MDM0625
342         9.0   MDM0625
343         8.0   MDM0625
344         0.0   MDM0625
345         8.0   MDM0625

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       3.0      0.0       8.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      0.0       7.0       1      1        0
4    01-05-2011       4.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       9.0       1      1        0
342  12-28-2010       6.0      1.0       4.0       1      1        0
343  12-29-2010       3.0      0.0       7.0       1      1        0
344  12-30-2010       0.0      0.0      11.0       1      1        0
345  03-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MDM0976
1             0   MDM0976
2             0   MDM0976
3             0   MDM0976
4             0   MDM0976
..          ...       ...
341           0   MDM0976
342           0   MDM0976
343           0   MDM0976
344           0   MDM0976
345           0   MDM0976

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       1.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       5.0      1.0       3.0       1      1        0
343  12-30-2010       2.0      1.0       6.0       1      1        0
344  03-14-2011       0.0      0.0       0.0       1      1        0
345  08-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MES0407
1             0   MES0407
2             0   MES0407
3             0   MES0407
4             0   MES0407
..          ...       ...
341           0   MES0407
342           0   MES0407
343           0   MES0407
344           0   MES0407
345           0   MES0407

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-08-2011       0.0      0.0       0.0       1      1        0
342  04-14-2011       0.0      0.0       0.0       1      1        0
343  04-15-2011       0.0      0.0       0.0       1      1        0
344  05-10-2011       0.0      0.0       0.0       1      1        0
345  10-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MFV0897
1             0   MFV0897
2             0   MFV0897
3             0   MFV0897
4             0   MFV0897
..          ...       ...
341           0   MFV0897
342           0   MFV0897
343           0   MFV0897
344           0   MFV0897
345           0   MFV0897

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       1      1      0.0
1    01-04-2010       6.0      0.0       5.0       1      1      1.0
2    01-04-2011       3.0      1.0       6.0       2      2      1.0
3    01-05-2010       2.0      0.0       9.0       1      1      0.0
4    01-05-2011       6.0      1.0       4.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
375  12-28-2010       5.0      0.0       6.0       2      2      1.0
376  12-29-2010       1.0      0.0      10.0       1      1      0.0
377  12-30-2010       4.0      0.0       7.0       2      2      0.0
378  01-07-2010       0.0      0.0       0.0       1      1      0.0
379  05-27-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   MGS0974
1           1.0   MGS0974
2           1.0   MGS0974
3           0.0   MGS0974
4           1.0   MGS0974
..          ...       ...
375         1.0   MGS0974
376         0.0   MGS0974
377         0.0   MGS0974
378         0.0   MGS0974
379         0.0   MGS0974

[380 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      2.0       6.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      1.0       3.0       1      1        0
342  12-27-2010       2.0      0.0       7.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       7.0      0.0       2.0       1      1        0
345  12-30-2010       3.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   MHA0798
1             0   MHA0798
2             0   MHA0798
3             0   MHA0798
4             0   MHA0798
..          ...       ...
341           0   MHA0798
342           0   MHA0798
343           0   MHA0798
344           0   MHA0798
345           0   MHA0798

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       2.0      0.0       6.0       1      1        0
2    01-04-2011       1.0      1.0       4.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       3.0       1      1        0
342  12-29-2010       3.0      1.0       5.0       1      1        0
343  12-30-2010       4.0      0.0       5.0       1      1        0
344  03-18-2011       0.0      0.0       0.0       1      1        0
345  06-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MHG0244
1             0   MHG0244
2             0   MHG0244
3             0   MHG0244
4             0   MHG0244
..          ...       ...
341           0   MHG0244
342           0   MHG0244
343           0   MHG0244
344           0   MHG0244
345           0   MHG0244

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      3.0       7.0       1      1        0
1    01-04-2010       5.0      5.0       5.0       1      1        0
2    01-04-2011       4.0      3.0       8.0       1      1        0
3    01-05-2010       5.0      3.0       7.0       1      1        0
4    01-05-2011       2.0      2.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      1.0       8.0       1      1        0
342  12-27-2010       7.0      0.0       8.0       1      1        0
343  12-28-2010       3.0      2.0       3.0       1      1        0
344  12-29-2010       6.0      5.0       3.0       1      1        0
345  12-30-2010       5.0      3.0       7.0       1      1        0

     Disconnect user_name
0             0   MHG0733
1             0   MHG0733
2             0   MHG0733
3             0   MHG0733
4             0   MHG0733
..          ...       ...
341           0   MHG0733
342           0   MHG0733
343           0   MHG0733
344           0   MHG0733
345           0   MHG0733

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       0.0      1.0       2.0       1      2        0
1    01-04-2010       0.0      0.0       3.0       1      2        0
2    01-05-2010       1.0      0.0       2.0       1      1        0
3    01-06-2010       1.0      0.0       2.0       1      2        0
4    01-07-2010       0.0      1.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
269  11-30-2010       2.0      0.0       1.0       1      2        0
270  12-01-2010       2.0      0.0       1.0       1      1        0
271  12-02-2010       2.0      0.0       1.0       1      1        0
272  03-23-2010       0.0      0.0       0.0       1      2        0
273  06-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MHH0180
1             0   MHH0180
2             0   MHH0180
3             0   MHH0180
4             0   MHH0180
..          ...       ...
269           0   MHH0180
270           0   MHH0180
271           0   MHH0180
272           0   MHH0180
273           0   MHH0180

[274 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       0.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       2.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      2        0
342  12-28-2010       2.0      0.0       1.0       1      1        0
343  12-29-2010       0.0      0.0       3.0       1      2        0
344  12-30-2010       1.0      0.0       2.0       1      2        0
345  09-16-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MIB0904
1             0   MIB0904
2             0   MIB0904
3             0   MIB0904
4             0   MIB0904
..          ...       ...
341           0   MIB0904
342           0   MIB0904
343           0   MIB0904
344           0   MIB0904
345           0   MIB0904

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      5.0       6.0       1      1        0
1    01-04-2010       5.0      2.0       8.0       1      1        0
2    01-04-2011       5.0      2.0       8.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011       0.0      2.0      13.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      4.0       7.0       1      1        0
342  12-29-2010       2.0      2.0      10.0       1      1        0
343  12-30-2010       5.0      3.0       7.0       1      1        0
344  01-25-2011       0.0      0.0       0.0       1      1        0
345  04-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MIC0726
1             0   MIC0726
2             0   MIC0726
3             0   MIC0726
4             0   MIC0726
..          ...       ...
341           0   MIC0726
342           0   MIC0726
343           0   MIC0726
344           0   MIC0726
345           0   MIC0726

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       4.0      0.0       5.0       1      1        0
343  12-30-2010       3.0      0.0       6.0       1      1        0
344  03-18-2011       0.0      0.0       0.0       1      1        0
345  12-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MIL0255
1             0   MIL0255
2             0   MIL0255
3             0   MIL0255
4             0   MIL0255
..          ...       ...
341           0   MIL0255
342           0   MIL0255
343           0   MIL0255
344           0   MIL0255
345           0   MIL0255

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-31-2011       0.0      0.0       0.0       1      1        0
342  04-21-2010       0.0      0.0       0.0       1      1        0
343  08-13-2010       0.0      0.0       0.0       1      1        0
344  09-23-2010       0.0      0.0       0.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MIM0712
1             0   MIM0712
2             0   MIM0712
3             0   MIM0712
4             0   MIM0712
..          ...       ...
341           0   MIM0712
342           0   MIM0712
343           0   MIM0712
344           0   MIM0712
345           0   MIM0712

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-04-2010       0.0      0.0       0.0       1      1        0
342  02-15-2011       0.0      0.0       0.0       1      1        0
343  05-11-2010       0.0      0.0       0.0       1      1        0
344  09-30-2010       0.0      0.0       0.0       1      1        0
345  11-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MJB0588
1             0   MJB0588
2             0   MJB0588
3             0   MJB0588
4             0   MJB0588
..          ...       ...
341           0   MJB0588
342           0   MJB0588
343           0   MJB0588
344           0   MJB0588
345           0   MJB0588

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       2      2        0
1    01-04-2010       0.0      0.0       2.0       2      3        0
2    01-04-2011       0.0      0.0       3.0       1      2        0
3    01-05-2010       0.0      0.0       3.0       1      2        0
4    01-05-2011       0.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       1.0       1      2        0
342  12-30-2010       0.0      0.0       3.0       1      2        0
343  03-30-2010       0.0      0.0       0.0       2      2        0
344  06-10-2010       0.0      0.0       0.0       2      2        0
345  12-10-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MJM0510
1             0   MJM0510
2             0   MJM0510
3             0   MJM0510
4             0   MJM0510
..          ...       ...
341           0   MJM0510
342           0   MJM0510
343           0   MJM0510
344           0   MJM0510
345           0   MJM0510

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      1.0       1.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       1.0       1      1        0
342  12-28-2010       0.0      0.0       3.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      1        0
344  12-30-2010       1.0      0.0       2.0       1      1        0
345  02-21-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MJS0890
1             0   MJS0890
2             0   MJS0890
3             0   MJS0890
4             0   MJS0890
..          ...       ...
341           0   MJS0890
342           0   MJS0890
343           0   MJS0890
344           0   MJS0890
345           0   MJS0890

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-15-2010       0.0      0.0       0.0       1      1        0
342  04-29-2011       0.0      0.0       0.0       1      1        0
343  06-22-2010       0.0      0.0       0.0       1      1        0
344  07-09-2010       0.0      0.0       0.0       1      1        0
345  12-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MKG0711
1             0   MKG0711
2             0   MKG0711
3             0   MKG0711
4             0   MKG0711
..          ...       ...
341           0   MKG0711
342           0   MKG0711
343           0   MKG0711
344           0   MKG0711
345           0   MKG0711

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       5.0      1.0       3.0       1      1        0
4    01-05-2011       2.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       7.0      0.0       2.0       1      1        0
343  12-28-2010       0.0      1.0       8.0       1      1        0
344  12-29-2010       5.0      0.0       4.0       1      1        0
345  12-30-2010       4.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   MKL0941
1             0   MKL0941
2             0   MKL0941
3             0   MKL0941
4             0   MKL0941
..          ...       ...
341           0   MKL0941
342           0   MKL0941
343           0   MKL0941
344           0   MKL0941
345           0   MKL0941

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       1      2        0
1    01-04-2010       7.0      0.0       8.0       1      2        0
2    01-04-2011       5.0      1.0       9.0       1      2        0
3    01-05-2010       4.0      0.0      11.0       1      2        0
4    01-05-2011       5.0      2.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      1.0       6.0       1      2        0
342  12-28-2010       8.0      0.0       6.0       1      1        0
343  12-29-2010       7.0      0.0       8.0       1      2        0
344  12-30-2010       6.0      0.0       9.0       1      2        0
345  08-04-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MKP0861
1             0   MKP0861
2             0   MKP0861
3             0   MKP0861
4             0   MKP0861
..          ...       ...
341           0   MKP0861
342           0   MKP0861
343           0   MKP0861
344           0   MKP0861
345           0   MKP0861

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      1.0       5.0       1      1        0
2    01-04-2011       1.0      2.0       8.0       1      1        0
3    01-05-2010       7.0      0.0       4.0       1      1        0
4    01-05-2011       1.0      1.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       9.0       1      1        0
342  12-27-2010       8.0      0.0       3.0       1      1        0
343  12-28-2010       4.0      0.0       7.0       1      1        0
344  12-29-2010       2.0      1.0       8.0       1      1        0
345  12-30-2010       5.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   MKS0204
1             0   MKS0204
2             0   MKS0204
3             0   MKS0204
4             0   MKS0204
..          ...       ...
341           0   MKS0204
342           0   MKS0204
343           0   MKS0204
344           0   MKS0204
345           0   MKS0204

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1      2.0
1    01-04-2010       1.0      0.0       2.0       1      2      3.0
2    01-04-2011       1.0      0.0       2.0       1      2      4.0
3    01-05-2010       0.0      0.0       3.0       1      2      2.0
4    01-05-2011       1.0      0.0       2.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
342  12-30-2010       1.0      0.0       2.0       1      2      1.0
343  01-15-2011       0.0      0.0       0.0       1      1      0.0
344  02-05-2010       0.0      0.0       0.0       2      2      2.0
345  03-16-2010       0.0      0.0       0.0       1      2      3.0
346  10-05-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           2.0   MKW0441
1           3.0   MKW0441
2           4.0   MKW0441
3           2.0   MKW0441
4           2.0   MKW0441
..          ...       ...
342         1.0   MKW0441
343         0.0   MKW0441
344         2.0   MKW0441
345         3.0   MKW0441
346         2.0   MKW0441

[347 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0     11.0       3.0       1      1        0
1    01-04-2010       8.0      4.0       3.0       1      2        0
2    01-04-2011       4.0      1.0      10.0       1      2        0
3    01-05-2010       6.0      3.0       5.0       1      2        0
4    01-05-2011       9.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      3.0       7.0       1      2        0
342  12-28-2010       6.0      3.0       6.0       1      2        0
343  12-29-2010       6.0      5.0       4.0       1      2        0
344  12-30-2010       7.0      3.0       5.0       1      2        0
345  01-10-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MLD0755
1             0   MLD0755
2             0   MLD0755
3             0   MLD0755
4             0   MLD0755
..          ...       ...
341           0   MLD0755
342           0   MLD0755
343           0   MLD0755
344           0   MLD0755
345           0   MLD0755

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-07-2010       0.0      0.0       0.0       1      1        0
342  08-17-2010       0.0      0.0       0.0       1      1        0
343  11-11-2010       0.0      0.0       0.0       1      1        0
344  11-18-2010       0.0      0.0       0.0       1      1        0
345  11-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MLG0475
1             0   MLG0475
2             0   MLG0475
3             0   MLG0475
4             0   MLG0475
..          ...       ...
341           0   MLG0475
342           0   MLG0475
343           0   MLG0475
344           0   MLG0475
345           0   MLG0475

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1      9.0
1    01-04-2010       0.0      0.0       1.0       1      1      7.0
2    01-04-2011       0.0      0.0       1.0       1      1      9.0
3    01-05-2010       0.0      0.0       1.0       1      1      8.0
4    01-05-2011       0.0      0.0       1.0       1      1      8.0
..          ...       ...      ...       ...     ...    ...      ...
341  05-06-2011       0.0      0.0       0.0       1      1      7.0
342  07-16-2010       0.0      0.0       0.0       1      1      9.0
343  10-05-2010       0.0      0.0       0.0       1      1      9.0
344  11-09-2010       0.0      0.0       0.0       1      1      8.0
345  12-01-2010       0.0      0.0       0.0       1      1      8.0

     Disconnect user_name
0           9.0   MLL0598
1           7.0   MLL0598
2           9.0   MLL0598
3           8.0   MLL0598
4           8.0   MLL0598
..          ...       ...
341         6.0   MLL0598
342         9.0   MLL0598
343         9.0   MLL0598
344         8.0   MLL0598
345         8.0   MLL0598

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       1      2      2.0
1    01-02-2011       0.0      0.0       1.0       1      2      3.0
2    01-03-2010       0.0      0.0       1.0       1      2      2.0
3    01-03-2011       1.0      0.0       0.0       1      2      1.0
4    01-04-2010       1.0      0.0       0.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
418  11-09-2010       0.0      0.0       0.0       2      2      2.0
419  11-23-2010       0.0      0.0       0.0       1      2      1.0
420  12-08-2010       0.0      0.0       0.0       1      2      2.0
421  12-11-2010       0.0      0.0       0.0       1      1      0.0
422  12-13-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           2.0   MLM0950
1           3.0   MLM0950
2           2.0   MLM0950
3           1.0   MLM0950
4           0.0   MLM0950
..          ...       ...
418         2.0   MLM0950
419         1.0   MLM0950
420         2.0   MLM0950
421         0.0   MLM0950
422         2.0   MLM0950

[423 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      1.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      1        0
342  12-28-2010       5.0      0.0       4.0       1      1        0
343  12-29-2010       4.0      1.0       4.0       1      1        0
344  12-30-2010       2.0      1.0       6.0       1      1        0
345  03-23-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MLP0668
1             0   MLP0668
2             0   MLP0668
3             0   MLP0668
4             0   MLP0668
..          ...       ...
341           0   MLP0668
342           0   MLP0668
343           0   MLP0668
344           0   MLP0668
345           0   MLP0668

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0       1      1        0
1    01-04-2010       5.0      0.0       8.0       1      1        0
2    01-04-2011       1.0      0.0      13.0       1      1        0
3    01-05-2010       4.0      0.0      10.0       1      1        0
4    01-05-2011       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
305  12-27-2010       6.0      2.0       7.0       1      1        0
306  12-28-2010       2.0      0.0      13.0       1      1        0
307  12-29-2010       4.0      0.0      11.0       1      1        0
308  12-30-2010       3.0      0.0      12.0       1      1        0
309  04-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MMB0488
1             0   MMB0488
2             0   MMB0488
3             0   MMB0488
4             0   MMB0488
..          ...       ...
305           0   MMB0488
306           0   MMB0488
307           0   MMB0488
308           0   MMB0488
309           0   MMB0488

[310 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       2      2        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       2.0      2.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       4.0      0.0       5.0       1      1        0
342  12-30-2010       2.0      0.0       7.0       1      1        0
343  04-08-2010       0.0      0.0       0.0       1      1        0
344  05-05-2010       0.0      0.0       0.0       1      1        0
345  08-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MMG0943
1             0   MMG0943
2             0   MMG0943
3             0   MMG0943
4             0   MMG0943
..          ...       ...
341           0   MMG0943
342           0   MMG0943
343           0   MMG0943
344           0   MMG0943
345           0   MMG0943

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      2        0
1    01-04-2010       1.0      0.0       0.0       2      3        0
2    01-04-2011       1.0      0.0       0.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-12-2010       0.0      0.0       0.0       2      2        0
342  04-01-2010       0.0      0.0       0.0       1      2        0
343  04-08-2010       0.0      0.0       0.0       1      2        0
344  11-02-2010       0.0      0.0       0.0       2      3        0
345  11-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MNC0717
1             0   MNC0717
2             0   MNC0717
3             0   MNC0717
4             0   MNC0717
..          ...       ...
341           0   MNC0717
342           0   MNC0717
343           0   MNC0717
344           0   MNC0717
345           0   MNC0717

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      1        0
2    01-05-2011       0.0      1.0       0.0       1      1        0
3    01-06-2010       0.0      0.0       1.0       1      1        0
4    01-06-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-26-2010       0.0      0.0       0.0       1      1        0
342  07-16-2010       0.0      0.0       0.0       1      1        0
343  10-25-2010       0.0      0.0       0.0       1      1        0
344  11-12-2010       0.0      0.0       0.0       1      1        0
345  11-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MNR0829
1             0   MNR0829
2             0   MNR0829
3             0   MNR0829
4             0   MNR0829
..          ...       ...
341           0   MNR0829
342           0   MNR0829
343           0   MNR0829
344           0   MNR0829
345           0   MNR0829

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0      10.0       5      5        0
1    01-04-2010       6.0      0.0       5.0       3      3        0
2    01-04-2011       2.0      1.0       8.0       6      6        0
3    01-05-2010       3.0      0.0       8.0       4      4        0
4    01-05-2011       4.0      2.0       5.0       6      6        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       5.0       3      3        0
342  12-29-2010       8.0      0.0       3.0       3      3        0
343  12-30-2010       1.0      1.0       9.0       2      2        0
344  04-13-2010       0.0      0.0       0.0       5      5        0
345  11-19-2010       0.0      0.0       0.0       5      5        0

     Disconnect user_name
0             0   MNS0224
1             0   MNS0224
2             0   MNS0224
3             0   MNS0224
4             0   MNS0224
..          ...       ...
341           0   MNS0224
342           0   MNS0224
343           0   MNS0224
344           0   MNS0224
345           0   MNS0224

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       3.0      0.0       0.0       1      1        0
342  02-03-2011       0.0      0.0       0.0       1      1        0
343  07-01-2010       0.0      0.0       0.0       1      1        0
344  08-20-2010       0.0      0.0       0.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MOP0763
1             0   MOP0763
2             0   MOP0763
3             0   MOP0763
4             0   MOP0763
..          ...       ...
341           0   MOP0763
342           0   MOP0763
343           0   MOP0763
344           0   MOP0763
345           0   MOP0763

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       5.0       7      8        7
1    01-05-2010       2.0      1.0       8.0       6      7        7
2    01-06-2010       5.0      1.0       5.0       3      3        2
3    01-07-2010       4.0      0.0       7.0       5      6        6
4    01-08-2010       2.0      1.0       4.0       4      5        5
..          ...       ...      ...       ...     ...    ...      ...
171  09-03-2010       3.0      0.0       5.0       6      7       11
172  09-07-2010       2.0      1.0       8.0       7      7        7
173  09-08-2010       6.0      0.0       4.0       3      4        3
174  09-09-2010       3.0      2.0       6.0       6      7        7
175  09-10-2010       4.0      1.0       6.0       5      6        6

     Disconnect user_name
0             7   MOS0047
1             7   MOS0047
2             2   MOS0047
3             6   MOS0047
4             5   MOS0047
..          ...       ...
171          11   MOS0047
172           7   MOS0047
173           3   MOS0047
174           7   MOS0047
175           6   MOS0047

[176 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       7.0     4.0    5.0     12.0
1    01-05-2010       3.0      0.0       7.0     2.0    3.0     10.0
2    01-06-2010       3.0      0.0       8.0     5.0    5.0     13.0
3    01-07-2010       3.0      0.0       8.0     6.0    7.0     13.0
4    01-08-2010       6.0      0.0       5.0     4.0    5.0     10.0
..          ...       ...      ...       ...     ...    ...      ...
213  11-03-2010       5.0      0.0       5.0     6.0    7.0     12.0
214  11-04-2010       7.0      0.0       6.0     5.0    6.0     12.0
215  11-05-2010       5.0      1.0       5.0     5.0    6.0     11.0
216  04-17-2010       0.0      0.0       0.0     1.0    1.0      0.0
217  05-08-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0          12.0   MPM0220
1          10.0   MPM0220
2          13.0   MPM0220
3          13.0   MPM0220
4          10.0   MPM0220
..          ...       ...
213        12.0   MPM0220
214        12.0   MPM0220
215        11.0   MPM0220
216         0.0   MPM0220
217         0.0   MPM0220

[218 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      2      0.0
1    01-04-2010       4.0      1.0       4.0       2      3      0.0
2    01-04-2011       2.0      0.0       7.0       1      1      0.0
3    01-05-2010       6.0      0.0       3.0       1      2      0.0
4    01-05-2011       6.0      0.0       3.0       2      3      2.0
..          ...       ...      ...       ...     ...    ...      ...
360  12-27-2010       2.0      0.0       7.0       2      3      3.0
361  12-28-2010       3.0      0.0       6.0       1      2      0.0
362  12-29-2010       5.0      0.0       4.0       1      2      1.0
363  12-30-2010       6.0      0.0       3.0       1      2      1.0
364  12-05-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   MPT0376
1           0.0   MPT0376
2           0.0   MPT0376
3           0.0   MPT0376
4           2.0   MPT0376
..          ...       ...
360         3.0   MPT0376
361         0.0   MPT0376
362         1.0   MPT0376
363         1.0   MPT0376
364         0.0   MPT0376

[365 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       5.0       1      1        0
1    01-04-2010       4.0      2.0       3.0       1      1        0
2    01-04-2011       6.0      1.0       2.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       7.0      1.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1        0
342  12-29-2010       4.0      0.0       5.0       1      1        0
343  12-30-2010       2.0      0.0       7.0       1      1        0
344  05-04-2011       0.0      0.0       0.0       1      1        0
345  06-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MSD0939
1             0   MSD0939
2             0   MSD0939
3             0   MSD0939
4             0   MSD0939
..          ...       ...
341           0   MSD0939
342           0   MSD0939
343           0   MSD0939
344           0   MSD0939
345           0   MSD0939

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  10-05-2010       0.0      0.0       0.0       1      1        0
342  10-08-2010       0.0      0.0       0.0       1      1        0
343  10-22-2010       0.0      0.0       0.0       1      1        0
344  11-17-2010       0.0      0.0       0.0       1      1        0
345  11-30-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MSG0839
1             0   MSG0839
2             0   MSG0839
3             0   MSG0839
4             0   MSG0839
..          ...       ...
341           0   MSG0839
342           0   MSG0839
343           0   MSG0839
344           0   MSG0839
345           0   MSG0839

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       4      4        0
1    01-04-2010       6.0      0.0       4.0       4      4        0
2    01-04-2011       6.0      0.0       5.0       6      6        0
3    01-05-2010       6.0      2.0       3.0       4      4        0
4    01-05-2011       4.0      1.0       5.0       5      5        0
..          ...       ...      ...       ...     ...    ...      ...
250  12-27-2010       5.0      0.0       5.0       2      2        0
251  12-28-2010       5.0      0.0       6.0       2      2        0
252  12-29-2010       3.0      1.0       7.0       5      5        0
253  12-30-2010       5.0      0.0       6.0       5      5        0
254  04-01-2010       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   MSH0040
1             0   MSH0040
2             0   MSH0040
3             0   MSH0040
4             0   MSH0040
..          ...       ...
250           0   MSH0040
251           0   MSH0040
252           0   MSH0040
253           0   MSH0040
254           0   MSH0040

[255 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      1.0       8.0       3      3      0.0
1    01-05-2010       5.0      0.0       6.0       5      5      0.0
2    01-06-2010       5.0      1.0       5.0       3      3      0.0
3    01-07-2010       2.0      1.0       8.0       2      2      0.0
4    01-08-2010       3.0      0.0       8.0       2      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
234  12-06-2010       4.0      0.0       7.0       5      5      0.0
235  12-07-2010       4.0      0.0       7.0       5      5      0.0
236  12-08-2010       4.0      1.0       6.0       2      2      0.0
237  12-09-2010       4.0      0.0       9.0       7      7      2.0
238  12-10-2010       1.0      0.0      10.0       5      5      0.0

     Disconnect user_name
0           0.0   MSO0222
1           0.0   MSO0222
2           0.0   MSO0222
3           0.0   MSO0222
4           0.0   MSO0222
..          ...       ...
234         0.0   MSO0222
235         0.0   MSO0222
236         0.0   MSO0222
237         2.0   MSO0222
238         0.0   MSO0222

[239 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      11.0      2.0      22.0       1      2        0
1    01-04-2010      13.0      0.0      23.0       1      1        0
2    01-04-2011       9.0      3.0      24.0       1      2        0
3    01-05-2010      16.0      4.0      15.0       1      2        0
4    01-05-2011      11.0      2.0      23.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       8.0      0.0      28.0       1      1        0
342  12-29-2010       9.0      0.0      27.0       1      2        0
343  12-30-2010      11.0      2.0      21.0       1      2        0
344  03-15-2011       0.0      0.0       0.0       1      1        0
345  03-31-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   MSS0001
1             0   MSS0001
2             0   MSS0001
3             0   MSS0001
4             0   MSS0001
..          ...       ...
341           0   MSS0001
342           0   MSS0001
343           0   MSS0001
344           0   MSS0001
345           0   MSS0001

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      2.0       5.0       1      1        0
1    01-04-2010       6.0      2.0       7.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010       6.0      0.0       8.0       1      1        0
4    01-05-2011       8.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       8.0       1      1        0
342  12-28-2010       4.0      0.0      11.0       1      1        0
343  12-29-2010       6.0      1.0       8.0       1      1        0
344  12-30-2010       6.0      1.0       8.0       1      1        0
345  03-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MSZ0310
1             0   MSZ0310
2             0   MSZ0310
3             0   MSZ0310
4             0   MSZ0310
..          ...       ...
341           0   MSZ0310
342           0   MSZ0310
343           0   MSZ0310
344           0   MSZ0310
345           0   MSZ0310

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1      4.0
1    01-04-2010       5.0      0.0       9.0       1      1      3.0
2    01-04-2011      11.0      0.0       4.0       1      2      2.0
3    01-05-2010       5.0      2.0       8.0       1      2      2.0
4    01-05-2011       6.0      0.0       9.0       1      2      4.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      3.0       8.0       1      2      5.0
342  12-28-2010       7.0      2.0       6.0       1      1      3.0
343  12-29-2010       6.0      0.0       9.0       1      2      4.0
344  12-30-2010       8.0      2.0       5.0       1      2      4.0
345  06-15-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           4.0   MTB0620
1           3.0   MTB0620
2           2.0   MTB0620
3           2.0   MTB0620
4           4.0   MTB0620
..          ...       ...
341         5.0   MTB0620
342         3.0   MTB0620
343         4.0   MTB0620
344         4.0   MTB0620
345         2.0   MTB0620

[346 rows x 9 columns]

aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       0.0      0.0       3.0       1      2      2.0
1   01-05-2010       1.0      0.0       2.0       1      2      2.0
2   01-06-2010       0.0      0.0       3.0       1      1      3.0
3   01-07-2010       3.0      0.0       0.0       1      2      3.0
4   01-08-2010       1.0      0.0       2.0       1      2      3.0
5   01-11-2010       0.0      0.0       3.0       1      1      3.0
6   01-12-2010       1.0      0.0       2.0       1      2      4.0
7   01-13-2010       1.0      0.0       1.0       1      2      1.0
8   01-14-2010       0.0      1.0       2.0       1      1      4.0
9   01-15-2010       0.0      0.0       2.0       1      2      3.0
10  01-18-2010       0.0      0.0       3.0       1      1      4.0
11  01-19-2010       0.0      0.0       2.0       1      2      3.0
12  01-20-2010       0.0      0.0       3.0       1      2      4.0
13  01-21-2010       1.0      0.0       2.0       1      2      5.0
14  01-22-2010       1.0      1.0       1.0       1      2      6.0
15  01-25-2010       3.0      0.0       0.0       1      1      3.0
16  01-26-2010       2.0      1.0       0.0       1      2      6.0
17  01-27-2010       0.0      0.0       3.0       1      1      2.0
18  01-28-2010       0.0      0.0       3.0       1      1      5.0
19  01-29-2010       1.0      0.0       2.0       1      2      4.0
20  02-01-2010       0.0      0.0       3.0       1      2      2.0
21  02-02-2010       1.0      0.0       2.0       1      2      3.0
22  02-03-2010       1.0      0.0       1.0       1      2      2.0
23  02-04-2010       0.0      0.0       3.0       1      2      3.0
24  02-05-2010       0.0      0.0       3.0       1      1      0.0
25  02-08-2010       1.0      1.0       0.0       1      2      2.0
26  02-09-2010       0.0      1.0       2.0       1      2      4.0
27  02-10-2010       0.0      1.0       2.0       1      2      2.0
28  02-11-2010       1.0      0.0       2.0       1      1      2.0

    Disconnect user_name
0          2.0   MTT0901
1          2.0   MTT0901
2          3.0   MTT0901
3          3.0   MTT0901
4          3.0   MTT0901
5          3.0   MTT0901
6          4.0   MTT0901
7          1.0   MTT0901
8          4.0   MTT0901
9          3.0   MTT0901
10         4.0   MTT0901
11         3.0   MTT0901
12         4.0   MTT0901
13         5.0   MTT0901
14         6.0   MTT0901
15         3.0   MTT0901
16         6.0   MTT0901
17         2.0   MTT0901
18         5.0   MTT0901
19         4.0   MTT0901
20         2.0   MTT0901
21         3.0   MTT0901
22         2.0   MTT0901
23         3.0   MTT0901
24         0.0   MTT0901
25         2.0   MTT0901
26         4.0   MTT0901
27         2.0   MTT0901
28         2.0   MTT0901
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      2      1.0
1    01-04-2010       0.0      0.0       3.0       1      1      1.0
2    01-04-2011       1.0      0.0       2.0       1      2      1.0
3    01-05-2010       0.0      0.0       3.0       1      2      0.0
4    01-05-2011       1.0      0.0       2.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       1.0       1      2      0.0
342  03-09-2011       0.0      0.0       0.0       2      3      1.0
343  10-07-2010       0.0      0.0       0.0       1      1      1.0
344  11-29-2010       0.0      0.0       0.0       1      1      1.0
345  12-09-2010       0.0      0.0       0.0       2      3      1.0

     Disconnect user_name
0           1.0   MVB0515
1           1.0   MVB0515
2           1.0   MVB0515
3           0.0   MVB0515
4           0.0   MVB0515
..          ...       ...
341         0.0   MVB0515
342         1.0   MVB0515
343         1.0   MVB0515
344         1.0   MVB0515
345         1.0   MVB0515

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-03-2010       0.0      0.0       0.0       1      1        0
342  06-17-2010       0.0      0.0       0.0       1      1        0
343  08-10-2010       0.0      0.0       0.0       1      1        0
344  08-25-2010       0.0      0.0       0.0       1      1        0
345  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   MVF0594
1             0   MVF0594
2             0   MVF0594
3             0   MVF0594
4             0   MVF0594
..          ...       ...
341           0   MVF0594
342           0   MVF0594
343           0   MVF0594
344           0   MVF0594
345           0   MVF0594

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       4.0      1.0       6.0       4      4        0
1   01-05-2010       7.0      0.0       4.0       5      5        0
2   01-06-2010       6.0      0.0       4.0       5      5        0
3   01-07-2010       0.0      0.0      11.0       2      2        0
4   01-08-2010       4.0      0.0       5.0       5      5        0
..         ...       ...      ...       ...     ...    ...      ...
61  03-30-2010       6.0      0.0       5.0       4      4        0
62  03-31-2010       3.0      0.0       8.0       6      6        0
63  04-01-2010       5.0      1.0       5.0       4      4        0
64  04-05-2010       6.0      0.0       5.0       2      2        0
65  04-06-2010       6.0      0.0       5.0       3      3        0

    Disconnect user_name
0            0   MVH0373
1            0   MVH0373
2            0   MVH0373
3            0   MVH0373
4            0   MVH0373
..         ...       ...
61           0   MVH0373
62           0   MVH0373
63           0   MVH0373
64           0   MVH0373
65           0   MVH0373

[66 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       7.0       1      1      0.0
1    01-05-2010       6.0      1.0       3.0       1      1      0.0
2    01-06-2010       2.0      0.0       9.0       1      1      0.0
3    01-07-2010       3.0      1.0       7.0       1      1      0.0
4    01-08-2010       5.0      0.0       6.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
247  12-27-2010       4.0      0.0       4.0       1      1      0.0
248  12-28-2010       8.0      0.0       3.0       1      1      0.0
249  12-29-2010       3.0      0.0       8.0       1      1      0.0
250  12-30-2010       3.0      0.0       8.0       1      1      0.0
251  12-18-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           0.0   MYD0978
1           0.0   MYD0978
2           0.0   MYD0978
3           0.0   MYD0978
4           0.0   MYD0978
..          ...       ...
247         0.0   MYD0978
248         0.0   MYD0978
249         0.0   MYD0978
250         0.0   MYD0978
251         1.0   MYD0978

[252 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       0.0      1.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       4.0       1      1        0
342  12-27-2010       0.0      0.0       5.0       1      1        0
343  12-28-2010       3.0      0.0       6.0       1      1        0
344  12-29-2010       2.0      0.0       7.0       1      1        0
345  12-30-2010       1.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   NAB0801
1             0   NAB0801
2             0   NAB0801
3             0   NAB0801
4             0   NAB0801
..          ...       ...
341           0   NAB0801
342           0   NAB0801
343           0   NAB0801
344           0   NAB0801
345           0   NAB0801

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       0.0      1.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      1        0
342  12-28-2010       0.0      1.0       2.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      1        0
344  12-30-2010       0.0      0.0       4.0       1      1        0
345  12-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NAB0903
1             0   NAB0903
2             0   NAB0903
3             0   NAB0903
4             0   NAB0903
..          ...       ...
341           0   NAB0903
342           0   NAB0903
343           0   NAB0903
344           0   NAB0903
345           0   NAB0903

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       1      1        0
1    01-04-2010       8.0      0.0       6.0       1      1        0
2    01-04-2011       8.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      0.0       9.0       1      1        0
4    01-05-2011       5.0      3.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
339  12-22-2010       8.0      0.0       6.0       1      1        0
340  12-27-2010       6.0      0.0       8.0       1      1        0
341  12-28-2010       7.0      0.0       7.0       1      1        0
342  12-29-2010       4.0      1.0       6.0       1      1        0
343  12-30-2010       1.0      0.0      13.0       1      1        0

     Disconnect user_name
0             0   NAF0033
1             0   NAF0033
2             0   NAF0033
3             0   NAF0033
4             0   NAF0033
..          ...       ...
339           0   NAF0033
340           0   NAF0033
341           0   NAF0033
342           0   NAF0033
343           0   NAF0033

[344 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010      12.0      0.0       4.0       1      2      3.0
1    01-03-2011       5.0      2.0       9.0       1      2      2.0
2    01-04-2010       7.0      1.0       8.0       1      2      1.0
3    01-04-2011       8.0      0.0       8.0       1      2      4.0
4    01-05-2010       6.0      0.0      10.0       2      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
453  12-28-2010       7.0      1.0       8.0       1      2      0.0
454  12-29-2010       7.0      0.0       9.0       1      2      0.0
455  12-30-2010       5.0      0.0      11.0       1      2      2.0
456  12-31-2010       7.0      0.0       6.0       1      2      3.0
457  09-08-2010       0.0      0.0       0.0       2      3      0.0

     Disconnect user_name
0           3.0   NAF0326
1           2.0   NAF0326
2           1.0   NAF0326
3           4.0   NAF0326
4           1.0   NAF0326
..          ...       ...
453         0.0   NAF0326
454         0.0   NAF0326
455         2.0   NAF0326
456         3.0   NAF0326
457         0.0   NAF0326

[458 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       8.0      1.0       6.0     1.0    1.0        0
1    01-03-2011       7.0      0.0       8.0     1.0    1.0        0
2    01-04-2010       9.0      2.0       4.0     1.0    1.0        0
3    01-04-2011       2.0      0.0      12.0     1.0    1.0        0
4    01-05-2010       9.0      1.0       5.0     2.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
399  05-15-2010       0.0      0.0       0.0     1.0    1.0        0
400  08-28-2010       0.0      0.0       0.0     1.0    0.0        0
401  10-23-2010       0.0      0.0       0.0     1.0    1.0        0
402  12-04-2010       0.0      0.0       0.0     1.0    1.0        0
403  12-11-2010       0.0      0.0       0.0     1.0    0.0        0

     Disconnect user_name
0             0   NAH0503
1             0   NAH0503
2             0   NAH0503
3             0   NAH0503
4             0   NAH0503
..          ...       ...
399           0   NAH0503
400           0   NAH0503
401           0   NAH0503
402           0   NAH0503
403           0   NAH0503

[404 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       7.0      0.0       2.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      0.0       4.0       1      1        0
342  12-29-2010       1.0      1.0       7.0       1      1        0
343  12-30-2010       5.0      0.0       4.0       1      1        0
344  11-04-2010       0.0      0.0       0.0       1      1        0
345  11-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NAR0981
1             0   NAR0981
2             0   NAR0981
3             0   NAR0981
4             0   NAR0981
..          ...       ...
341           0   NAR0981
342           0   NAR0981
343           0   NAR0981
344           0   NAR0981
345           0   NAR0981

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       6.0       1      1        0
1    01-04-2010       0.0      1.0       9.0       1      1        0
2    01-04-2011       6.0      1.0       3.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       3.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       5.0       1      1        0
342  12-28-2010       4.0      0.0       6.0       1      1        0
343  12-29-2010       6.0      0.0       4.0       1      1        0
344  12-30-2010       6.0      0.0       4.0       1      1        0
345  09-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NBC0412
1             0   NBC0412
2             0   NBC0412
3             0   NBC0412
4             0   NBC0412
..          ...       ...
341           0   NBC0412
342           0   NBC0412
343           0   NBC0412
344           0   NBC0412
345           0   NBC0412

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       7.0      0.0       2.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-28-2010       0.0      3.0       6.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  03-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NBH0256
1             0   NBH0256
2             0   NBH0256
3             0   NBH0256
4             0   NBH0256
..          ...       ...
341           0   NBH0256
342           0   NBH0256
343           0   NBH0256
344           0   NBH0256
345           0   NBH0256

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      1.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       7.0       1      1        0
343  12-29-2010       2.0      0.0       6.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  04-26-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NCE0097
1             0   NCE0097
2             0   NCE0097
3             0   NCE0097
4             0   NCE0097
..          ...       ...
341           0   NCE0097
342           0   NCE0097
343           0   NCE0097
344           0   NCE0097
345           0   NCE0097

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       9.0       1      1        0
1    01-04-2010       2.0      1.0       8.0       1      1        0
2    01-04-2011       1.0      0.0      10.0       1      1        0
3    01-05-2010       2.0      2.0       7.0       1      1        0
4    01-05-2011       5.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0       9.0       1      1        0
342  12-27-2010       3.0      0.0       8.0       1      1        0
343  12-28-2010       5.0      1.0       5.0       1      1        0
344  12-29-2010       8.0      0.0       3.0       1      1        0
345  12-30-2010       4.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   NCH0179
1             0   NCH0179
2             0   NCH0179
3             0   NCH0179
4             0   NCH0179
..          ...       ...
341           0   NCH0179
342           0   NCH0179
343           0   NCH0179
344           0   NCH0179
345           0   NCH0179

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-23-2010       0.0      0.0       0.0       1      1        0
342  10-07-2010       0.0      0.0       0.0       1      1        0
343  10-28-2010       0.0      0.0       0.0       1      1        0
344  11-02-2010       0.0      0.0       0.0       1      1        0
345  11-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NCK0295
1             0   NCK0295
2             0   NCK0295
3             0   NCK0295
4             0   NCK0295
..          ...       ...
341           0   NCK0295
342           0   NCK0295
343           0   NCK0295
344           0   NCK0295
345           0   NCK0295

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       3.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       3.0       1      1        0
4    01-05-2011       5.0      1.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1        0
342  12-29-2010       2.0      1.0       6.0       1      1        0
343  12-30-2010       5.0      0.0       4.0       1      1        0
344  04-20-2011       0.0      0.0       0.0       1      1        0
345  05-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NCK0421
1             0   NCK0421
2             0   NCK0421
3             0   NCK0421
4             0   NCK0421
..          ...       ...
341           0   NCK0421
342           0   NCK0421
343           0   NCK0421
344           0   NCK0421
345           0   NCK0421

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      1.0       3.0       1      2        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       5.0      0.0       4.0       1      2        0
4    01-05-2011       7.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        0
342  12-28-2010       0.0      1.0       5.0       1      1        0
343  12-29-2010       5.0      1.0       3.0       1      2        0
344  12-30-2010       6.0      1.0       2.0       1      2        0
345  03-07-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NCO0666
1             0   NCO0666
2             0   NCO0666
3             0   NCO0666
4             0   NCO0666
..          ...       ...
341           0   NCO0666
342           0   NCO0666
343           0   NCO0666
344           0   NCO0666
345           0   NCO0666

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       2      3      1.0
1    01-04-2010       4.0      0.0       5.0       1      2      2.0
2    01-04-2011       3.0      0.0       6.0       1      2      2.0
3    01-05-2010       6.0      0.0       3.0       1      2      2.0
4    01-05-2011       4.0      0.0       5.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      2      2.0
342  12-28-2010       3.0      0.0       6.0       2      2      1.0
343  12-29-2010       2.0      0.0       5.0       1      2      0.0
344  12-30-2010       5.0      0.0       4.0       1      2      0.0
345  11-15-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           1.0   NDM0417
1           2.0   NDM0417
2           2.0   NDM0417
3           2.0   NDM0417
4           3.0   NDM0417
..          ...       ...
341         2.0   NDM0417
342         1.0   NDM0417
343         0.0   NDM0417
344         0.0   NDM0417
345         1.0   NDM0417

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       2.0      0.0       7.0       1      1      0.0
1    01-03-2011       1.0      0.0       8.0       1      1      0.0
2    01-04-2010       4.0      0.0       5.0       1      1      0.0
3    01-04-2011       4.0      0.0       5.0       1      1      2.0
4    01-05-2010       3.0      0.0       6.0       2      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
423  12-29-2010       0.0      0.0       8.0       1      1      0.0
424  12-30-2010       2.0      0.0       7.0       1      1      0.0
425  12-31-2010       2.0      3.0       4.0       1      1      0.0
426  07-20-2010       0.0      0.0       0.0       1      1      1.0
427  11-05-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   NGC0058
1           0.0   NGC0058
2           0.0   NGC0058
3           2.0   NGC0058
4           1.0   NGC0058
..          ...       ...
423         0.0   NGC0058
424         0.0   NGC0058
425         0.0   NGC0058
426         1.0   NGC0058
427         0.0   NGC0058

[428 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       3.0      1.0       5.0     1.0    2.0      0.0
1    01-02-2010       2.0      0.0       7.0     1.0    2.0      0.0
2    01-03-2011       7.0      0.0       2.0     1.0    2.0      0.0
3    01-04-2010       3.0      2.0       4.0     1.0    2.0      0.0
4    01-04-2011       7.0      0.0       2.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
405  01-02-2011       0.0      0.0       0.0     1.0    1.0      0.0
406  03-26-2011       0.0      0.0       0.0     1.0    1.0      0.0
407  09-11-2010       0.0      0.0       0.0     1.0    0.0      0.0
408  09-19-2010       0.0      0.0       0.0     1.0    0.0      0.0
409  09-25-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   NGF0157
1           0.0   NGF0157
2           0.0   NGF0157
3           0.0   NGF0157
4           0.0   NGF0157
..          ...       ...
405         0.0   NGF0157
406         0.0   NGF0157
407         0.0   NGF0157
408         0.0   NGF0157
409         0.0   NGF0157

[410 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      2        0
1    01-04-2010       1.0      1.0       7.0       1      1        0
2    01-04-2011       3.0      2.0       4.0       1      2        0
3    01-05-2010       4.0      0.0       5.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       8.0       1      2        0
342  12-29-2010       4.0      0.0       5.0       1      2        0
343  12-30-2010       4.0      1.0       4.0       1      2        0
344  03-25-2011       0.0      0.0       0.0       1      2        0
345  04-21-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   NGO0690
1             0   NGO0690
2             0   NGO0690
3             0   NGO0690
4             0   NGO0690
..          ...       ...
341           0   NGO0690
342           0   NGO0690
343           0   NGO0690
344           0   NGO0690
345           0   NGO0690

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       2.0      0.0       6.0       1      2        0
3    01-05-2010       1.0      0.0       8.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      2        0
342  12-27-2010       6.0      0.0       3.0       1      2        0
343  12-28-2010       4.0      1.0       4.0       1      2        0
344  12-29-2010       2.0      0.0       7.0       1      2        0
345  12-30-2010       4.0      1.0       4.0       1      2        0

     Disconnect user_name
0             0   NHE0919
1             0   NHE0919
2             0   NHE0919
3             0   NHE0919
4             0   NHE0919
..          ...       ...
341           0   NHE0919
342           0   NHE0919
343           0   NHE0919
344           0   NHE0919
345           0   NHE0919

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      0.0       3.0       1      1        0
342  12-28-2010       2.0      0.0       1.0       1      1        0
343  12-29-2010       0.0      0.0       3.0       1      1        0
344  12-30-2010       0.0      1.0       2.0       1      1        0
345  06-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NHH0185
1             0   NHH0185
2             0   NHH0185
3             0   NHH0185
4             0   NHH0185
..          ...       ...
341           0   NHH0185
342           0   NHH0185
343           0   NHH0185
344           0   NHH0185
345           0   NHH0185

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-20-2010       0.0      0.0       0.0       1      2        0
342  06-29-2010       0.0      0.0       0.0       1      2        0
343  09-28-2010       0.0      0.0       0.0       1      2        0
344  10-01-2010       0.0      0.0       0.0       1      1        0
345  10-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NIH0969
1             0   NIH0969
2             0   NIH0969
3             0   NIH0969
4             0   NIH0969
..          ...       ...
341           0   NIH0969
342           0   NIH0969
343           0   NIH0969
344           0   NIH0969
345           0   NIH0969

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       1.0      1.0       7.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       4.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       4.0      0.0       5.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   NJB0243
1             0   NJB0243
2             0   NJB0243
3             0   NJB0243
4             0   NJB0243
..          ...       ...
341           0   NJB0243
342           0   NJB0243
343           0   NJB0243
344           0   NJB0243
345           0   NJB0243

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-20-2010       0.0      0.0       0.0       1      1        0
342  06-07-2010       0.0      0.0       0.0       1      1        0
343  08-25-2010       0.0      0.0       0.0       1      1        0
344  11-11-2010       0.0      0.0       0.0       1      1        0
345  11-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NJC0705
1             0   NJC0705
2             0   NJC0705
3             0   NJC0705
4             0   NJC0705
..          ...       ...
341           0   NJC0705
342           0   NJC0705
343           0   NJC0705
344           0   NJC0705
345           0   NJC0705

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       1.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       3.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       3.0      1.0       5.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       5.0      1.0       3.0       1      1        0

     Disconnect user_name
0             0   NKH0807
1             0   NKH0807
2             0   NKH0807
3             0   NKH0807
4             0   NKH0807
..          ...       ...
341           0   NKH0807
342           0   NKH0807
343           0   NKH0807
344           0   NKH0807
345           0   NKH0807

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      1.0       3.0       2      3        0
2    01-04-2011       6.0      0.0       5.0       1      2        0
3    01-05-2010       3.0      0.0       8.0       1      2        0
4    01-05-2011       5.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       5.0       1      2        0
342  12-27-2010       4.0      2.0       5.0       1      2        0
343  12-28-2010       5.0      1.0       4.0       2      3        0
344  12-29-2010       6.0      1.0       4.0       1      2        0
345  12-30-2010       3.0      0.0       8.0       1      2        0

     Disconnect user_name
0             0   NKH0979
1             0   NKH0979
2             0   NKH0979
3             0   NKH0979
4             0   NKH0979
..          ...       ...
341           0   NKH0979
342           0   NKH0979
343           0   NKH0979
344           0   NKH0979
345           0   NKH0979

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1      1.0
1    01-04-2010       6.0      1.0       2.0       1      1      0.0
2    01-04-2011       5.0      0.0       4.0       1      1      0.0
3    01-05-2010       1.0      1.0       6.0       1      1      0.0
4    01-05-2011       4.0      0.0       5.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1      0.0
342  12-29-2010       3.0      0.0       6.0       1      1      0.0
343  12-30-2010       4.0      0.0       5.0       1      1      1.0
344  11-30-2010       0.0      0.0       0.0       1      1      0.0
345  12-16-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   NKP0236
1           0.0   NKP0236
2           0.0   NKP0236
3           0.0   NKP0236
4           1.0   NKP0236
..          ...       ...
341         0.0   NKP0236
342         0.0   NKP0236
343         1.0   NKP0236
344         0.0   NKP0236
345         0.0   NKP0236

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1        0
1    01-04-2011       1.0      0.0       0.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-14-2011       0.0      0.0       0.0       1      1        0
342  05-05-2010       0.0      0.0       0.0       1      1        0
343  06-18-2010       0.0      0.0       0.0       1      1        0
344  07-16-2010       0.0      0.0       0.0       1      1        0
345  10-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NLO0131
1             0   NLO0131
2             0   NLO0131
3             0   NLO0131
4             0   NLO0131
..          ...       ...
341           0   NLO0131
342           0   NLO0131
343           0   NLO0131
344           0   NLO0131
345           0   NLO0131

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-13-2010       0.0      0.0       0.0       1      1        0
342  06-18-2010       0.0      0.0       0.0       1      1        0
343  08-20-2010       0.0      0.0       0.0       1      1        0
344  10-06-2010       0.0      0.0       0.0       1      1        0
345  12-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NMB0972
1             0   NMB0972
2             0   NMB0972
3             0   NMB0972
4             0   NMB0972
..          ...       ...
341           0   NMB0972
342           0   NMB0972
343           0   NMB0972
344           0   NMB0972
345           0   NMB0972

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      1.0       5.0       1      1        0
1    01-04-2010       9.0      0.0       6.0       1      1        0
2    01-04-2011       8.0      1.0       6.0       1      1        0
3    01-05-2010      12.0      0.0       3.0       1      1        0
4    01-05-2011      11.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010      12.0      0.0       3.0       1      1        0
342  12-29-2010       7.0      0.0       7.0       1      1        0
343  12-30-2010       9.0      2.0       2.0       1      1        0
344  01-26-2010       0.0      0.0       0.0       1      1        0
345  02-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NMC0486
1             0   NMC0486
2             0   NMC0486
3             0   NMC0486
4             0   NMC0486
..          ...       ...
341           0   NMC0486
342           0   NMC0486
343           0   NMC0486
344           0   NMC0486
345           0   NMC0486

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      1.0       1.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  01-06-2011       0.0      0.0       0.0       1      1        0
345  03-23-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NMF0780
1             0   NMF0780
2             0   NMF0780
3             0   NMF0780
4             0   NMF0780
..          ...       ...
341           0   NMF0780
342           0   NMF0780
343           0   NMF0780
344           0   NMF0780
345           0   NMF0780

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       1.0       1      1        0
1    01-04-2010       2.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      0.0       3.0       1      1        0
342  02-23-2010       0.0      0.0       0.0       1      1        0
343  10-20-2010       0.0      0.0       0.0       1      1        0
344  10-27-2010       0.0      0.0       0.0       1      1        0
345  12-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NMG0766
1             0   NMG0766
2             0   NMG0766
3             0   NMG0766
4             0   NMG0766
..          ...       ...
341           0   NMG0766
342           0   NMG0766
343           0   NMG0766
344           0   NMG0766
345           0   NMG0766

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       0.0      0.0       2.0       1      1      1.0
1    01-03-2011       1.0      0.0       2.0       1      1      1.0
2    01-04-2010       2.0      0.0       1.0       1      1      1.0
3    01-04-2011       0.0      1.0       2.0       1      1      0.0
4    01-05-2010       3.0      0.0       0.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
431  01-28-2010       0.0      0.0       0.0       1      1      0.0
432  01-31-2010       0.0      0.0       0.0       1      1      0.0
433  02-06-2011       0.0      0.0       0.0       1      1      0.0
434  02-07-2011       0.0      0.0       0.0       1      1      1.0
435  04-13-2011       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           1.0   NMS0280
1           1.0   NMS0280
2           1.0   NMS0280
3           0.0   NMS0280
4           2.0   NMS0280
..          ...       ...
431         0.0   NMS0280
432         0.0   NMS0280
433         0.0   NMS0280
434         1.0   NMS0280
435         0.0   NMS0280

[436 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      11.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011       3.0      1.0      10.0       1      1        0
3    01-05-2010       8.0      0.0       6.0       1      1        0
4    01-05-2011       7.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      0.0       7.0       1      1        0
342  12-28-2010       9.0      1.0       5.0       1      1        0
343  12-29-2010       7.0      0.0       7.0       1      1        0
344  12-30-2010       8.0      0.0       7.0       1      1        0
345  05-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NNA0610
1             0   NNA0610
2             0   NNA0610
3             0   NNA0610
4             0   NNA0610
..          ...       ...
341           0   NNA0610
342           0   NNA0610
343           0   NNA0610
344           0   NNA0610
345           0   NNA0610

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      1.0       7.0       1      1        0
342  12-28-2010       2.0      0.0       7.0       1      1        0
343  12-29-2010       4.0      2.0       3.0       1      1        0
344  12-30-2010       1.0      0.0       8.0       1      1        0
345  02-24-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NNS0059
1             0   NNS0059
2             0   NNS0059
3             0   NNS0059
4             0   NNS0059
..          ...       ...
341           0   NNS0059
342           0   NNS0059
343           0   NNS0059
344           0   NNS0059
345           0   NNS0059

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       3.0       2      2      1.0
1    01-02-2010       1.0      0.0       2.0       2      3      2.0
2    01-02-2011       0.0      0.0       3.0       1      2      1.0
3    01-03-2010       0.0      0.0       3.0       1      2      0.0
4    01-03-2011       1.0      0.0       2.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
471  03-01-2010       0.0      0.0       0.0       1      2      0.0
472  10-21-2010       0.0      0.0       0.0       2      2      4.0
473  12-15-2010       0.0      0.0       0.0       1      2      0.0
474  12-18-2010       0.0      0.0       0.0       1      2      0.0
475  12-31-2010       0.0      0.0       0.0       2      3      0.0

     Disconnect user_name
0           1.0   NOB0181
1           2.0   NOB0181
2           1.0   NOB0181
3           0.0   NOB0181
4           0.0   NOB0181
..          ...       ...
471         0.0   NOB0181
472         4.0   NOB0181
473         0.0   NOB0181
474         0.0   NOB0181
475         0.0   NOB0181

[476 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1        0
1    01-04-2010       3.0      3.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
301  12-27-2010       5.0      1.0       3.0       1      1        0
302  12-28-2010       4.0      0.0       5.0       1      1        0
303  12-29-2010       3.0      0.0       6.0       1      1        0
304  12-30-2010       2.0      0.0       7.0       1      1        0
305  09-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NRD0548
1             0   NRD0548
2             0   NRD0548
3             0   NRD0548
4             0   NRD0548
..          ...       ...
301           0   NRD0548
302           0   NRD0548
303           0   NRD0548
304           0   NRD0548
305           0   NRD0548

[306 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-10-2010       0.0      0.0       0.0       1      1        0
342  05-25-2010       0.0      0.0       0.0       1      1        0
343  10-14-2010       0.0      0.0       0.0       1      1        0
344  12-02-2010       0.0      0.0       0.0       1      1        0
345  12-10-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NRF0137
1             0   NRF0137
2             0   NRF0137
3             0   NRF0137
4             0   NRF0137
..          ...       ...
341           0   NRF0137
342           0   NRF0137
343           0   NRF0137
344           0   NRF0137
345           0   NRF0137

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
317  12-29-2010       3.0      0.0       0.0       1      1        0
318  12-30-2010       2.0      0.0       1.0       1      1        0
319  04-16-2010       0.0      0.0       0.0       1      1        0
320  11-02-2010       0.0      0.0       0.0       1      1        0
321  12-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NRO0768
1             0   NRO0768
2             0   NRO0768
3             0   NRO0768
4             0   NRO0768
..          ...       ...
317           0   NRO0768
318           0   NRO0768
319           0   NRO0768
320           0   NRO0768
321           0   NRO0768

[322 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-06-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-25-2010       0.0      0.0       0.0       1      1        0
342  08-12-2010       0.0      0.0       0.0       1      1        0
343  09-07-2010       0.0      0.0       0.0       1      1        0
344  10-13-2010       0.0      0.0       0.0       1      1        0
345  11-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NSC0597
1             0   NSC0597
2             0   NSC0597
3             0   NSC0597
4             0   NSC0597
..          ...       ...
341           0   NSC0597
342           0   NSC0597
343           0   NSC0597
344           0   NSC0597
345           0   NSC0597

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       6.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011       7.0      2.0       6.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010      10.0      1.0       4.0       1      1        0
342  12-28-2010       4.0      0.0      11.0       1      1        0
343  12-29-2010       8.0      0.0       7.0       1      1        0
344  12-30-2010       4.0      2.0       8.0       1      1        0
345  05-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   NSS0876
1             0   NSS0876
2             0   NSS0876
3             0   NSS0876
4             0   NSS0876
..          ...       ...
341           0   NSS0876
342           0   NSS0876
343           0   NSS0876
344           0   NSS0876
345           0   NSS0876

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      2        0
2    01-05-2010       0.0      0.0       1.0       1      2        0
3    01-05-2011       0.0      0.0       1.0       1      2        0
4    01-06-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  10-12-2010       0.0      0.0       0.0       1      2        0
342  11-04-2010       0.0      0.0       0.0       1      2        0
343  11-12-2010       0.0      0.0       0.0       1      2        0
344  11-19-2010       0.0      0.0       0.0       1      2        0
345  12-02-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   NUL0471
1             0   NUL0471
2             0   NUL0471
3             0   NUL0471
4             0   NUL0471
..          ...       ...
341           0   NUL0471
342           0   NUL0471
343           0   NUL0471
344           0   NUL0471
345           0   NUL0471

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1      1.0
1    01-04-2010       4.0      0.0       5.0       1      1      3.0
2    01-04-2011       7.0      0.0       2.0       1      1      2.0
3    01-05-2010       3.0      0.0       6.0       1      1      2.0
4    01-05-2011       2.0      0.0       7.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
314  12-22-2010       6.0      0.0       3.0       1      1      2.0
315  12-27-2010       5.0      0.0       4.0       1      1      3.0
316  12-28-2010       5.0      0.0       4.0       1      1      4.0
317  12-29-2010       2.0      0.0       7.0       1      1      3.0
318  12-30-2010       3.0      1.0       5.0       1      1      3.0

     Disconnect user_name
0           1.0   NWT0098
1           3.0   NWT0098
2           2.0   NWT0098
3           2.0   NWT0098
4           3.0   NWT0098
..          ...       ...
314         2.0   NWT0098
315         3.0   NWT0098
316         4.0   NWT0098
317         3.0   NWT0098
318         3.0   NWT0098

[319 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       7.0      0.0       8.0     2.0    2.0      9.0
1    01-03-2010       4.0      0.0      11.0     1.0    2.0      8.0
2    01-03-2011       7.0      0.0       8.0     2.0    2.0      9.0
3    01-04-2010       5.0      0.0      10.0     1.0    2.0      9.0
4    01-04-2011       7.0      0.0       8.0     1.0    2.0      9.0
..          ...       ...      ...       ...     ...    ...      ...
430  03-19-2011       0.0      0.0       0.0     1.0    0.0      0.0
431  05-21-2010       0.0      0.0       0.0     1.0    2.0     10.0
432  06-26-2010       0.0      0.0       0.0     1.0    1.0      0.0
433  09-12-2010       0.0      0.0       0.0     1.0    0.0      0.0
434  09-18-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           9.0   OBH0499
1           8.0   OBH0499
2           9.0   OBH0499
3           9.0   OBH0499
4           9.0   OBH0499
..          ...       ...
430         0.0   OBH0499
431        10.0   OBH0499
432         0.0   OBH0499
433         0.0   OBH0499
434         0.0   OBH0499

[435 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-28-2010       4.0      0.0       4.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      1.0       5.0       1      1        0
345  10-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OCB0805
1             0   OCB0805
2             0   OCB0805
3             0   OCB0805
4             0   OCB0805
..          ...       ...
341           0   OCB0805
342           0   OCB0805
343           0   OCB0805
344           0   OCB0805
345           0   OCB0805

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       6.0       2      2      3.0
1    01-04-2010       8.0      0.0       7.0       1      1      3.0
2    01-04-2011       7.0      0.0       9.0       1      2      1.0
3    01-05-2010       7.0      1.0       7.0       1      2      0.0
4    01-05-2011       2.0      1.0      13.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0      11.0       1      2      2.0
342  12-28-2010       2.0      1.0      13.0       1      2      1.0
343  12-29-2010      10.0      0.0       6.0       1      2      3.0
344  12-30-2010      10.0      0.0       6.0       1      2      1.0
345  03-12-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           3.0   OCS0865
1           3.0   OCS0865
2           1.0   OCS0865
3           0.0   OCS0865
4           2.0   OCS0865
..          ...       ...
341         1.0   OCS0865
342         1.0   OCS0865
343         3.0   OCS0865
344         1.0   OCS0865
345         2.0   OCS0865

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      1.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-21-2011       0.0      0.0       0.0       1      1        0
342  04-22-2010       0.0      0.0       0.0       1      1        0
343  06-17-2010       0.0      0.0       0.0       1      1        0
344  06-30-2010       0.0      0.0       0.0       1      1        0
345  07-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OHC0973
1             0   OHC0973
2             0   OHC0973
3             0   OHC0973
4             0   OHC0973
..          ...       ...
341           0   OHC0973
342           0   OHC0973
343           0   OHC0973
344           0   OHC0973
345           0   OHC0973

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       2.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       5.0       1      1        0
342  12-27-2010       2.0      0.0       7.0       1      1        0
343  12-28-2010       0.0      0.0       3.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       2.0      1.0       6.0       1      1        0

     Disconnect user_name
0             0   OJK0233
1             0   OJK0233
2             0   OJK0233
3             0   OJK0233
4             0   OJK0233
..          ...       ...
341           0   OJK0233
342           0   OJK0233
343           0   OJK0233
344           0   OJK0233
345           0   OJK0233

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      0.0       8.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       1.0      0.0       7.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   OKB0439
1             0   OKB0439
2             0   OKB0439
3             0   OKB0439
4             0   OKB0439
..          ...       ...
341           0   OKB0439
342           0   OKB0439
343           0   OKB0439
344           0   OKB0439
345           0   OKB0439

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      1.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       5.0      1.0       3.0       1      1        0
4    01-05-2011       2.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      1.0       4.0       1      1        0
342  12-30-2010       6.0      0.0       3.0       1      1        0
343  05-11-2011       0.0      0.0       0.0       1      1        0
344  05-16-2011       0.0      0.0       0.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OKC0107
1             0   OKC0107
2             0   OKC0107
3             0   OKC0107
4             0   OKC0107
..          ...       ...
341           0   OKC0107
342           0   OKC0107
343           0   OKC0107
344           0   OKC0107
345           0   OKC0107

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-04-2010       4.0      8.0       3.0       1      1        0
1   01-05-2010       6.0      4.0       5.0       1      1        0
2   01-06-2010       3.0      1.0      11.0       1      1        0
3   01-07-2010       0.0     12.0       3.0       1      1        0
4   01-08-2010       4.0      3.0       8.0       1      1        0
..         ...       ...      ...       ...     ...    ...      ...
93  05-14-2010       3.0      2.0       9.0       1      1        0
94  05-17-2010       6.0      3.0       6.0       1      1        0
95  05-18-2010       3.0      4.0       8.0       1      1        0
96  05-19-2010       3.0     11.0       1.0       1      1        0
97  05-20-2010       6.0      4.0       5.0       1      1        0

    Disconnect user_name
0            0   OLB0749
1            0   OLB0749
2            0   OLB0749
3            0   OLB0749
4            0   OLB0749
..         ...       ...
93           0   OLB0749
94           0   OLB0749
95           0   OLB0749
96           0   OLB0749
97           0   OLB0749

[98 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0      12.0       1      1        0
1    01-04-2010       9.0      1.0       5.0       1      1        0
2    01-04-2011       7.0      0.0       8.0       1      1        0
3    01-05-2010       5.0      1.0       7.0       1      1        0
4    01-05-2011       4.0      0.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      1.0       6.0       1      1        0
342  12-28-2010       3.0      1.0      11.0       1      1        0
343  12-29-2010       5.0      0.0      10.0       1      1        0
344  12-30-2010      10.0      0.0       5.0       1      1        0
345  08-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OLF0504
1             0   OLF0504
2             0   OLF0504
3             0   OLF0504
4             0   OLF0504
..          ...       ...
341           0   OLF0504
342           0   OLF0504
343           0   OLF0504
344           0   OLF0504
345           0   OLF0504

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      2      4.0
1    01-04-2010       2.0      1.0       6.0       1      2      0.0
2    01-04-2011       6.0      0.0       3.0       1      2      3.0
3    01-05-2010       2.0      2.0       5.0       1      2      2.0
4    01-05-2011       4.0      0.0       5.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2      2.0
342  12-28-2010       4.0      0.0       5.0       1      1      3.0
343  12-29-2010       4.0      0.0       5.0       1      2      2.0
344  12-30-2010       4.0      0.0       5.0       1      2      3.0
345  04-21-2011       0.0      0.0       0.0       1      2      4.0

     Disconnect user_name
0           4.0   OLW0689
1           0.0   OLW0689
2           3.0   OLW0689
3           2.0   OLW0689
4           2.0   OLW0689
..          ...       ...
341         2.0   OLW0689
342         3.0   OLW0689
343         2.0   OLW0689
344         3.0   OLW0689
345         4.0   OLW0689

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-11-2010       0.0      0.0       0.0       1      1        0
342  06-29-2010       0.0      0.0       0.0       1      1        0
343  08-09-2010       0.0      0.0       0.0       1      1        0
344  11-18-2010       0.0      0.0       0.0       1      1        0
345  12-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OMM0944
1             0   OMM0944
2             0   OMM0944
3             0   OMM0944
4             0   OMM0944
..          ...       ...
341           0   OMM0944
342           0   OMM0944
343           0   OMM0944
344           0   OMM0944
345           0   OMM0944

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       4.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       3.0      2.0       4.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   OMS0101
1             0   OMS0101
2             0   OMS0101
3             0   OMS0101
4             0   OMS0101
..          ...       ...
341           0   OMS0101
342           0   OMS0101
343           0   OMS0101
344           0   OMS0101
345           0   OMS0101

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       5.0      1.0       2.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       3.0      1.0       5.0       1      1        0
343  12-29-2010       1.0      0.0       5.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ONL0276
1             0   ONL0276
2             0   ONL0276
3             0   ONL0276
4             0   ONL0276
..          ...       ...
341           0   ONL0276
342           0   ONL0276
343           0   ONL0276
344           0   ONL0276
345           0   ONL0276

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       1.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       9.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       3.0       1      1        0
342  12-27-2010       2.0      0.0       5.0       1      1        0
343  12-28-2010       4.0      0.0       5.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       5.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   ONW0083
1             0   ONW0083
2             0   ONW0083
3             0   ONW0083
4             0   ONW0083
..          ...       ...
341           0   ONW0083
342           0   ONW0083
343           0   ONW0083
344           0   ONW0083
345           0   ONW0083

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-02-2010       0.0      0.0       0.0       1      1        0
342  03-24-2011       0.0      0.0       0.0       1      1        0
343  04-21-2011       0.0      0.0       0.0       1      1        0
344  07-27-2010       0.0      0.0       0.0       1      1        0
345  12-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OQH0183
1             0   OQH0183
2             0   OQH0183
3             0   OQH0183
4             0   OQH0183
..          ...       ...
341           0   OQH0183
342           0   OQH0183
343           0   OQH0183
344           0   OQH0183
345           0   OQH0183

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  09-15-2010       0.0      0.0       0.0       1      1        0
342  09-20-2010       0.0      0.0       0.0       1      1        0
343  09-28-2010       0.0      0.0       0.0       1      1        0
344  10-12-2010       0.0      0.0       0.0       1      1        0
345  11-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ORB0473
1             0   ORB0473
2             0   ORB0473
3             0   ORB0473
4             0   ORB0473
..          ...       ...
341           0   ORB0473
342           0   ORB0473
343           0   ORB0473
344           0   ORB0473
345           0   ORB0473

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       0.0      0.0       3.0       1      1        0
342  12-27-2010       0.0      0.0       3.0       1      1        0
343  12-28-2010       1.0      0.0       2.0       1      1        0
344  12-29-2010       1.0      0.0       2.0       1      1        0
345  12-30-2010       0.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   ORG0339
1             0   ORG0339
2             0   ORG0339
3             0   ORG0339
4             0   ORG0339
..          ...       ...
341           0   ORG0339
342           0   ORG0339
343           0   ORG0339
344           0   ORG0339
345           0   ORG0339

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       3.0      1.0       4.0       1      1        0
3    01-05-2010       6.0      1.0       2.0       1      1        0
4    01-05-2011       4.0      1.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       6.0       1      1        0
342  12-29-2010       5.0      0.0       4.0       1      1        0
343  12-30-2010       3.0      1.0       5.0       1      1        0
344  02-04-2010       0.0      0.0       0.0       1      1        0
345  03-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ORM0669
1             0   ORM0669
2             0   ORM0669
3             0   ORM0669
4             0   ORM0669
..          ...       ...
341           0   ORM0669
342           0   ORM0669
343           0   ORM0669
344           0   ORM0669
345           0   ORM0669

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      1.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  01-20-2011       0.0      0.0       0.0       1      1        0
345  06-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OSH0655
1             0   OSH0655
2             0   OSH0655
3             0   OSH0655
4             0   OSH0655
..          ...       ...
341           0   OSH0655
342           0   OSH0655
343           0   OSH0655
344           0   OSH0655
345           0   OSH0655

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       2      2        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       7.0      0.0       2.0       1      1        0
3    01-05-2010       6.0      2.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       3.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       4.0      0.0       4.0       1      1        0
345  10-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   OYM0026
1             0   OYM0026
2             0   OYM0026
3             0   OYM0026
4             0   OYM0026
..          ...       ...
341           0   OYM0026
342           0   OYM0026
343           0   OYM0026
344           0   OYM0026
345           0   OYM0026

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       2      3      0.0
1    01-04-2010       0.0      0.0       3.0       2      3      0.0
2    01-04-2011       2.0      1.0       1.0       1      2      0.0
3    01-05-2010       3.0      0.0       0.0       1      2      3.0
4    01-05-2011       0.0      0.0       3.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       3.0      0.0       0.0       1      2      1.0
342  03-25-2010       0.0      0.0       0.0       1      2      0.0
343  05-18-2010       0.0      0.0       0.0       1      1      1.0
344  08-30-2010       0.0      0.0       0.0       1      2      1.0
345  10-28-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   PAD0773
1           0.0   PAD0773
2           0.0   PAD0773
3           3.0   PAD0773
4           0.0   PAD0773
..          ...       ...
341         1.0   PAD0773
342         0.0   PAD0773
343         1.0   PAD0773
344         1.0   PAD0773
345         0.0   PAD0773

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      0.0       5.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       5.0      0.0       6.0       1      1        0
4    01-05-2011       0.0      0.0      11.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       6.0      0.0       5.0       1      1        0
342  12-30-2010       3.0      0.0       8.0       1      1        0
343  02-03-2011       0.0      0.0       0.0       1      1        0
344  02-17-2010       0.0      0.0       0.0       1      1        0
345  11-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PBP0002
1             0   PBP0002
2             0   PBP0002
3             0   PBP0002
4             0   PBP0002
..          ...       ...
341           0   PBP0002
342           0   PBP0002
343           0   PBP0002
344           0   PBP0002
345           0   PBP0002

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2      3.0
1    01-04-2010       0.0      0.0       1.0       1      2      2.0
2    01-04-2011       0.0      0.0       1.0       1      2      2.0
3    01-05-2010       0.0      1.0       0.0       1      2      3.0
4    01-05-2011       0.0      0.0       1.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  07-02-2010       0.0      0.0       0.0       1      2      1.0
342  07-07-2010       0.0      0.0       0.0       1      2      1.0
343  07-09-2010       0.0      0.0       0.0       1      2      3.0
344  08-02-2010       0.0      0.0       0.0       1      1      3.0
345  08-10-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           3.0   PDH0716
1           2.0   PDH0716
2           2.0   PDH0716
3           3.0   PDH0716
4           1.0   PDH0716
..          ...       ...
341         0.0   PDH0716
342         1.0   PDH0716
343         3.0   PDH0716
344         3.0   PDH0716
345         2.0   PDH0716

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       2      3        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       4.0      1.0       4.0       1      2        0
4    01-05-2011       5.0      0.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      0.0       4.0       1      1        0
342  12-29-2010       3.0      1.0       5.0       1      2        0
343  12-30-2010       7.0      0.0       2.0       1      2        0
344  02-16-2010       0.0      0.0       0.0       1      2        0
345  04-29-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   PDW0259
1             0   PDW0259
2             0   PDW0259
3             0   PDW0259
4             0   PDW0259
..          ...       ...
341           0   PDW0259
342           0   PDW0259
343           0   PDW0259
344           0   PDW0259
345           0   PDW0259

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       1      1        0
1    01-04-2010       7.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      1.0       5.0       1      2        0
3    01-05-2010       4.0      0.0       7.0       1      2        0
4    01-05-2011       5.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      1.0       8.0       1      2        0
342  12-28-2010       5.0      0.0       6.0       1      2        0
343  12-29-2010       4.0      2.0       5.0       1      2        0
344  12-30-2010       2.0      2.0       7.0       1      2        0
345  01-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PES0085
1             0   PES0085
2             0   PES0085
3             0   PES0085
4             0   PES0085
..          ...       ...
341           0   PES0085
342           0   PES0085
343           0   PES0085
344           0   PES0085
345           0   PES0085

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      12.0     1.0    1.0        0
1    01-04-2010       8.0      1.0       6.0     1.0    2.0        0
2    01-04-2011      10.0      0.0       6.0     1.0    2.0        0
3    01-05-2010       9.0      0.0       7.0     1.0    2.0        0
4    01-05-2011       9.0      0.0       6.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
349  03-19-2011       0.0      0.0       0.0     1.0    1.0        0
350  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
351  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
352  08-21-2010       0.0      0.0       0.0     1.0    1.0        0
353  11-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   PEV0323
1             0   PEV0323
2             0   PEV0323
3             0   PEV0323
4             0   PEV0323
..          ...       ...
349           0   PEV0323
350           0   PEV0323
351           0   PEV0323
352           0   PEV0323
353           0   PEV0323

[354 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      3.0       4.0       1      1        0
2    01-04-2011       4.0      1.0       6.0       1      1        0
3    01-05-2010       6.0      0.0       5.0       1      1        0
4    01-05-2011       5.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       5.0       1      1        0
342  12-28-2010       2.0      0.0       9.0       1      1        0
343  12-29-2010       8.0      0.0       3.0       1      1        0
344  12-30-2010       6.0      0.0       5.0       1      1        0
345  01-18-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PGC0066
1             0   PGC0066
2             0   PGC0066
3             0   PGC0066
4             0   PGC0066
..          ...       ...
341           0   PGC0066
342           0   PGC0066
343           0   PGC0066
344           0   PGC0066
345           0   PGC0066

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       2.0       1      2        0
1    01-05-2010       1.0      0.0       2.0       1      2        0
2    01-06-2010       1.0      0.0       2.0       1      1        0
3    01-07-2010       0.0      1.0       2.0       1      2        0
4    01-08-2010       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
224  11-22-2010       2.0      0.0       1.0       1      1        0
225  11-23-2010       0.0      0.0       3.0       1      1        0
226  11-24-2010       0.0      1.0       2.0       1      2        0
227  10-05-2010       0.0      0.0       0.0       1      2        0
228  11-18-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PGH0184
1             0   PGH0184
2             0   PGH0184
3             0   PGH0184
4             0   PGH0184
..          ...       ...
224           0   PGH0184
225           0   PGH0184
226           0   PGH0184
227           0   PGH0184
228           0   PGH0184

[229 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       1.0       1      1        0
1    01-04-2010       2.0      0.0       7.0       1      1        0
2    01-04-2011       0.0      0.0       9.0       1      1        0
3    01-05-2010       2.0      1.0       6.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       3.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       5.0      0.0       4.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  05-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PGO0433
1             0   PGO0433
2             0   PGO0433
3             0   PGO0433
4             0   PGO0433
..          ...       ...
341           0   PGO0433
342           0   PGO0433
343           0   PGO0433
344           0   PGO0433
345           0   PGO0433

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0     1.0    1.0        0
1    01-04-2010       2.0      0.0       7.0     1.0    1.0        0
2    01-04-2011       3.0      0.0       6.0     2.0    2.0        0
3    01-05-2010       6.0      1.0       2.0     1.0    1.0        0
4    01-05-2011       2.0      1.0       6.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
350  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
351  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
352  10-02-2010       0.0      0.0       0.0     1.0    1.0        0
353  11-12-2010       0.0      0.0       0.0     2.0    2.0        0
354  11-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   PID0426
1             0   PID0426
2             0   PID0426
3             0   PID0426
4             0   PID0426
..          ...       ...
350           0   PID0426
351           0   PID0426
352           0   PID0426
353           0   PID0426
354           0   PID0426

[355 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       2      3        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       0.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      0.0       3.0       1      2        0
342  01-26-2011       0.0      0.0       0.0       1      2        0
343  05-06-2010       0.0      0.0       0.0       1      2        0
344  07-02-2010       0.0      0.0       0.0       1      2        0
345  08-26-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   PIS0522
1             0   PIS0522
2             0   PIS0522
3             0   PIS0522
4             0   PIS0522
..          ...       ...
341           0   PIS0522
342           0   PIS0522
343           0   PIS0522
344           0   PIS0522
345           0   PIS0522

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      2.0       7.0       1      1        0
1    01-04-2010       2.0      2.0       4.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       3.0      1.0       5.0       1      1        0
343  12-28-2010       3.0      0.0       2.0       1      1        0
344  12-29-2010       0.0      1.0       8.0       1      1        0
345  12-30-2010       7.0      0.0       2.0       1      1        0

     Disconnect user_name
0             0   PKB0281
1             0   PKB0281
2             0   PKB0281
3             0   PKB0281
4             0   PKB0281
..          ...       ...
341           0   PKB0281
342           0   PKB0281
343           0   PKB0281
344           0   PKB0281
345           0   PKB0281

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       1.0      1.0       7.0       1      1        0
3    01-05-2010       4.0      0.0       5.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      1.0       5.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       3.0      0.0       6.0       1      1        0
344  12-30-2010       3.0      0.0       5.0       1      1        0
345  02-07-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PKB0429
1             0   PKB0429
2             0   PKB0429
3             0   PKB0429
4             0   PKB0429
..          ...       ...
341           0   PKB0429
342           0   PKB0429
343           0   PKB0429
344           0   PKB0429
345           0   PKB0429

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-13-2010       0.0      0.0       0.0       1      1        0
342  08-12-2010       0.0      0.0       0.0       1      1        0
343  10-21-2010       0.0      0.0       0.0       1      1        0
344  11-09-2010       0.0      0.0       0.0       1      1        0
345  12-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PLH0715
1             0   PLH0715
2             0   PLH0715
3             0   PLH0715
4             0   PLH0715
..          ...       ...
341           0   PLH0715
342           0   PLH0715
343           0   PLH0715
344           0   PLH0715
345           0   PLH0715

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       7.0       1      1        0
1    01-04-2010      10.0      0.0       5.0       1      1        0
2    01-04-2011       7.0      0.0       8.0       1      1        0
3    01-05-2010       5.0      0.0      10.0       1      1        0
4    01-05-2011       6.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      1.0       6.0       1      1        0
342  12-27-2010       4.0      0.0      11.0       1      1        0
343  12-28-2010       5.0      0.0      10.0       1      1        0
344  12-29-2010      11.0      0.0       4.0       1      1        0
345  12-30-2010       2.0      0.0      13.0       1      1        0

     Disconnect user_name
0             0   PLH0862
1             0   PLH0862
2             0   PLH0862
3             0   PLH0862
4             0   PLH0862
..          ...       ...
341           0   PLH0862
342           0   PLH0862
343           0   PLH0862
344           0   PLH0862
345           0   PLH0862

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1      1.0
1    01-04-2010       1.0      1.0       1.0       1      2      2.0
2    01-04-2011       2.0      0.0       1.0       1      2      3.0
3    01-05-2010       1.0      1.0       1.0       1      2      3.0
4    01-05-2011       1.0      0.0       2.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      2      2.0
342  12-29-2010       0.0      0.0       3.0       1      2      2.0
343  12-30-2010       3.0      0.0       0.0       1      2      3.0
344  05-03-2011       0.0      0.0       0.0       1      2      2.0
345  06-11-2010       0.0      0.0       0.0       1      2      4.0

     Disconnect user_name
0           1.0   PMC0328
1           2.0   PMC0328
2           3.0   PMC0328
3           3.0   PMC0328
4           3.0   PMC0328
..          ...       ...
341         2.0   PMC0328
342         2.0   PMC0328
343         3.0   PMC0328
344         1.0   PMC0328
345         4.0   PMC0328

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0       1      1        0
1    01-04-2010       0.0      0.0       2.0       2      3        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
342  12-28-2010       4.0      0.0       5.0       1      2        0
343  12-29-2010       3.0      1.0       5.0       1      2        0
344  12-30-2010       4.0      1.0       4.0       1      2        0
345  05-14-2011       0.0      0.0       0.0       1      1        0
346  08-25-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   PMJ0564
1             0   PMJ0564
2             0   PMJ0564
3             0   PMJ0564
4             0   PMJ0564
..          ...       ...
342           0   PMJ0564
343           0   PMJ0564
344           0   PMJ0564
345           0   PMJ0564
346           0   PMJ0564

[347 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       2      2      1.0
1    01-04-2010       0.0      0.0       1.0       2      2      2.0
2    01-04-2011       1.0      0.0       0.0       1      2      1.0
3    01-05-2010       1.0      0.0       0.0       1      2      2.0
4    01-05-2011       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  01-11-2010       0.0      0.0       0.0       2      2      1.0
342  01-25-2011       0.0      0.0       0.0       1      1      1.0
343  03-30-2010       0.0      0.0       0.0       1      1      1.0
344  04-14-2010       0.0      0.0       0.0       1      2      1.0
345  08-13-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           1.0   PMV0850
1           2.0   PMV0850
2           1.0   PMV0850
3           2.0   PMV0850
4           0.0   PMV0850
..          ...       ...
341         1.0   PMV0850
342         1.0   PMV0850
343         1.0   PMV0850
344         1.0   PMV0850
345         2.0   PMV0850

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0     1.0    1.0      0.0
1    01-04-2010       2.0      0.0       1.0     1.0    1.0      0.0
2    01-04-2011       2.0      0.0       1.0     1.0    1.0      0.0
3    01-05-2010       1.0      0.0       2.0     1.0    1.0      1.0
4    01-05-2011       2.0      0.0       1.0     1.0    1.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
348  05-14-2011       0.0      0.0       0.0     1.0    0.0      0.0
349  07-03-2010       0.0      0.0       0.0     1.0    1.0      0.0
350  08-18-2010       0.0      0.0       0.0     1.0    1.0      0.0
351  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0
352  12-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   PNH0761
1           0.0   PNH0761
2           0.0   PNH0761
3           1.0   PNH0761
4           2.0   PNH0761
..          ...       ...
348         0.0   PNH0761
349         0.0   PNH0761
350         0.0   PNH0761
351         0.0   PNH0761
352         0.0   PNH0761

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1      2.0
1    01-05-2010       0.0      0.0       1.0       1      1      3.0
2    01-06-2010       0.0      0.0       1.0       1      1      2.0
3    01-07-2010       0.0      0.0       1.0       1      1      3.0
4    01-08-2010       0.0      0.0       1.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
151  03-03-2010       0.0      0.0       0.0       1      1      1.0
152  04-12-2010       0.0      0.0       0.0       1      1      2.0
153  04-21-2010       0.0      0.0       0.0       1      1      2.0
154  06-25-2010       0.0      0.0       0.0       1      1      0.0
155  07-28-2010       0.0      0.0       0.0       1      1      5.0

     Disconnect user_name
0           2.0   PNL0301
1           3.0   PNL0301
2           1.0   PNL0301
3           3.0   PNL0301
4           3.0   PNL0301
..          ...       ...
151         1.0   PNL0301
152         2.0   PNL0301
153         2.0   PNL0301
154         0.0   PNL0301
155         4.0   PNL0301

[156 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       3.0      0.0       0.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       1.0       1      1        0
342  12-30-2010       2.0      0.0       1.0       1      1        0
343  01-26-2011       0.0      0.0       0.0       1      1        0
344  02-23-2011       0.0      0.0       0.0       1      1        0
345  07-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   POB0343
1             0   POB0343
2             0   POB0343
3             0   POB0343
4             0   POB0343
..          ...       ...
341           0   POB0343
342           0   POB0343
343           0   POB0343
344           0   POB0343
345           0   POB0343

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       4.0       1      1      0.0
1    01-04-2010       5.0      0.0       5.0       1      1      0.0
2    01-04-2011       3.0      0.0       6.0       1      1      0.0
3    01-05-2010       5.0      0.0       5.0       1      1      0.0
4    01-05-2011       4.0      0.0       5.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
285  12-27-2010       5.0      0.0       5.0       1      1      0.0
286  12-28-2010       5.0      0.0       5.0       1      1      0.0
287  12-29-2010       4.0      0.0       6.0       1      1      0.0
288  12-30-2010       3.0      1.0       6.0       1      1      0.0
289  03-10-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   PPF0435
1           0.0   PPF0435
2           0.0   PPF0435
3           0.0   PPF0435
4           0.0   PPF0435
..          ...       ...
285         0.0   PPF0435
286         0.0   PPF0435
287         0.0   PPF0435
288         0.0   PPF0435
289         0.0   PPF0435

[290 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      5.0       6.0       1      1        0
1    01-04-2010       5.0      3.0       7.0       1      1        0
2    01-04-2011       5.0      1.0       9.0       1      1        0
3    01-05-2010       4.0      8.0       2.0       1      1        0
4    01-05-2011       4.0      6.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0       1      1        0
342  12-28-2010       5.0      1.0       9.0       1      1        0
343  12-29-2010       3.0      6.0       6.0       1      1        0
344  12-30-2010       5.0      2.0       8.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PRM0740
1             0   PRM0740
2             0   PRM0740
3             0   PRM0740
4             0   PRM0740
..          ...       ...
341           0   PRM0740
342           0   PRM0740
343           0   PRM0740
344           0   PRM0740
345           0   PRM0740

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1      2.0
1    01-05-2010       0.0      0.0       1.0       1      1      2.0
2    01-06-2010       1.0      0.0       0.0       1      1      2.0
3    01-07-2010       0.0      0.0       1.0       1      1      2.0
4    01-08-2010       1.0      0.0       0.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
185  09-29-2010       0.0      0.0       1.0       1      1      6.0
186  09-30-2010       0.0      0.0       1.0       1      1      3.0
187  03-24-2010       0.0      0.0       0.0       1      1      1.0
188  05-21-2010       0.0      0.0       0.0       1      1      1.0
189  08-31-2010       0.0      0.0       0.0       1      1      2.0

     Disconnect user_name
0           2.0   PSF0133
1           2.0   PSF0133
2           2.0   PSF0133
3           2.0   PSF0133
4           2.0   PSF0133
..          ...       ...
185         6.0   PSF0133
186         3.0   PSF0133
187         1.0   PSF0133
188         0.0   PSF0133
189         1.0   PSF0133

[190 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      2        0
2    01-04-2011       6.0      1.0       2.0       1      2        0
3    01-05-2010       4.0      0.0       5.0       1      2        0
4    01-05-2011       3.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       4.0       1      2        0
342  12-27-2010       1.0      3.0       5.0       1      2        0
343  12-28-2010       6.0      0.0       2.0       1      2        0
344  12-29-2010       3.0      0.0       6.0       1      2        0
345  12-30-2010       0.0      0.0       9.0       1      2        0

     Disconnect user_name
0             0   PTH0552
1             0   PTH0552
2             0   PTH0552
3             0   PTH0552
4             0   PTH0552
..          ...       ...
341           0   PTH0552
342           0   PTH0552
343           0   PTH0552
344           0   PTH0552
345           0   PTH0552

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       1.0      0.0       0.0       1      1        0
1    01-03-2011       0.0      0.0       1.0       1      1        0
2    01-04-2010       0.0      0.0       1.0       1      1        0
3    01-04-2011       0.0      0.0       1.0       1      1        0
4    01-05-2010       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
420  09-23-2010       0.0      0.0       0.0       1      1        0
421  09-28-2010       0.0      0.0       0.0       1      1        0
422  10-08-2010       0.0      0.0       0.0       1      1        0
423  11-07-2010       0.0      0.0       0.0       1      1        0
424  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   PTH0830
1             0   PTH0830
2             0   PTH0830
3             0   PTH0830
4             0   PTH0830
..          ...       ...
420           0   PTH0830
421           0   PTH0830
422           0   PTH0830
423           0   PTH0830
424           0   PTH0830

[425 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
300  12-30-2010       3.0      0.0       0.0       1      1        0
301  03-02-2010       0.0      0.0       0.0       1      1        0
302  04-05-2010       0.0      0.0       0.0       1      1        0
303  05-05-2010       0.0      0.0       0.0       1      1        0
304  11-29-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   QCH0110
1             0   QCH0110
2             0   QCH0110
3             0   QCH0110
4             0   QCH0110
..          ...       ...
300           0   QCH0110
301           0   QCH0110
302           0   QCH0110
303           0   QCH0110
304           0   QCH0110

[305 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      0.0       5.0       1      1      3.0
1    01-03-2011       3.0      4.0       3.0       3      3      0.0
2    01-04-2010       4.0      0.0       6.0       2      2      0.0
3    01-04-2011       4.0      1.0       5.0       1      1      2.0
4    01-05-2010       2.0      0.0       6.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
355  12-27-2010       3.0      0.0       7.0       2      2      1.0
356  12-28-2010       3.0      0.0       6.0       1      1      1.0
357  12-29-2010       3.0      0.0       6.0       1      1      0.0
358  12-30-2010       3.0      0.0       7.0       1      1      2.0
359  12-31-2010       4.0      1.0       4.0       2      2      0.0

     Disconnect user_name
0           3.0   QJR0688
1           0.0   QJR0688
2           0.0   QJR0688
3           2.0   QJR0688
4           2.0   QJR0688
..          ...       ...
355         1.0   QJR0688
356         1.0   QJR0688
357         0.0   QJR0688
358         2.0   QJR0688
359         0.0   QJR0688

[360 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       9.0       1      1        0
1    01-04-2010       4.0      1.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       8.0       1      1        0
3    01-05-2010       6.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       4.0       1      1        0
342  12-27-2010       6.0      0.0       5.0       1      1        0
343  12-28-2010       3.0      0.0       8.0       1      1        0
344  12-29-2010       3.0      1.0       7.0       1      1        0
345  12-30-2010       7.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   QNF0205
1             0   QNF0205
2             0   QNF0205
3             0   QNF0205
4             0   QNF0205
..          ...       ...
341           0   QNF0205
342           0   QNF0205
343           0   QNF0205
344           0   QNF0205
345           0   QNF0205

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       7.0       4      4        0
1    01-04-2011       5.0      0.0       4.0       2      2        0
2    01-05-2010       3.0      0.0       7.0       2      2        0
3    01-05-2011       3.0      1.0       7.0       3      3        0
4    01-06-2010       3.0      0.0       8.0       3      3        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      0.0       5.0       5      5        0
342  12-29-2010       4.0      1.0       6.0       3      3        0
343  12-30-2010       3.0      0.0       8.0       4      4        0
344  01-03-2011       0.0      0.0       0.0       6      6        0
345  09-27-2010       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   QNP0216
1             0   QNP0216
2             0   QNP0216
3             0   QNP0216
4             0   QNP0216
..          ...       ...
341           0   QNP0216
342           0   QNP0216
343           0   QNP0216
344           0   QNP0216
345           0   QNP0216

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       5.0      0.0       9.0       1      2      1.0
1    01-04-2010       9.0      1.0       3.0       1      2      1.0
2    01-05-2010       9.0      0.0       5.0       2      3      5.0
3    01-06-2010       7.0      1.0       5.0       1      2      3.0
4    01-07-2010       6.0      0.0       7.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
108  04-30-2010       5.0      0.0       9.0       2      2      2.0
109  05-03-2010      12.0      0.0       2.0       1      2      2.0
110  05-04-2010       4.0      0.0       9.0       2      3      1.0
111  05-05-2010       5.0      0.0       9.0       2      3      2.0
112  05-06-2010       3.0      1.0      10.0       1      2      2.0

     Disconnect user_name
0           1.0   QOS0878
1           1.0   QOS0878
2           5.0   QOS0878
3           3.0   QOS0878
4           3.0   QOS0878
..          ...       ...
108         2.0   QOS0878
109         1.0   QOS0878
110         1.0   QOS0878
111         2.0   QOS0878
112         2.0   QOS0878

[113 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      4.0       1.0       1      1        0
1    01-04-2010       5.0      2.0       8.0       1      1        0
2    01-04-2011       3.0      3.0       9.0       1      1        0
3    01-05-2010       5.0      6.0       2.0       1      1        0
4    01-05-2011       4.0      8.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      4.0       7.0       1      1        0
342  12-27-2010       3.0      8.0       4.0       1      1        0
343  12-28-2010       2.0      8.0       5.0       1      1        0
344  12-29-2010       4.0      2.0       9.0       1      1        0
345  12-30-2010       8.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   QPM0727
1             0   QPM0727
2             0   QPM0727
3             0   QPM0727
4             0   QPM0727
..          ...       ...
341           0   QPM0727
342           0   QPM0727
343           0   QPM0727
344           0   QPM0727
345           0   QPM0727

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      3.0       6.0       1      1        9
1    01-04-2010       4.0     11.0       0.0       1      1        7
2    01-04-2011       3.0      2.0      11.0       1      1        9
3    01-05-2010       6.0      1.0       8.0       1      1        8
4    01-05-2011       2.0      0.0       0.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0     14.0       1.0       1      1        8
342  12-28-2010       6.0      1.0       9.0       1      1        8
343  12-29-2010       6.0      3.0       6.0       1      1        9
344  12-30-2010       3.0      9.0       4.0       1      1        9
345  05-20-2010       0.0      0.0       0.0       1      1        9

     Disconnect user_name
0             9   QRM0739
1             7   QRM0739
2             9   QRM0739
3             8   QRM0739
4             9   QRM0739
..          ...       ...
341           8   QRM0739
342           7   QRM0739
343           9   QRM0739
344           9   QRM0739
345           9   QRM0739

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       3.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       1.0       1      1        0
342  12-29-2010       2.0      0.0       1.0       1      1        0
343  12-30-2010       2.0      0.0       1.0       1      1        0
344  02-18-2010       0.0      0.0       0.0       1      1        0
345  07-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   QSV0778
1             0   QSV0778
2             0   QSV0778
3             0   QSV0778
4             0   QSV0778
..          ...       ...
341           0   QSV0778
342           0   QSV0778
343           0   QSV0778
344           0   QSV0778
345           0   QSV0778

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       2      2      0.0
1    01-05-2010       0.0      0.0       1.0       1      2      0.0
2    01-06-2010       0.0      0.0       1.0       2      2      0.0
3    01-07-2010       0.0      0.0       1.0       1      2      0.0
4    01-08-2010       0.0      0.0       1.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
192  06-23-2010       0.0      0.0       0.0       2      3      0.0
193  07-19-2010       0.0      0.0       0.0       1      2      0.0
194  09-11-2010       0.0      0.0       0.0       1      1      2.0
195  09-13-2010       0.0      0.0       0.0       2      3      1.0
196  09-28-2010       0.0      0.0       0.0       2      3      0.0

     Disconnect user_name
0           0.0   RAB0589
1           0.0   RAB0589
2           0.0   RAB0589
3           0.0   RAB0589
4           0.0   RAB0589
..          ...       ...
192         0.0   RAB0589
193         0.0   RAB0589
194         2.0   RAB0589
195         1.0   RAB0589
196         0.0   RAB0589

[197 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       2.0      2.0       5.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       6.0      0.0       2.0       1      1        0
342  12-30-2010       3.0      0.0       6.0       1      1        0
343  01-28-2011       0.0      0.0       0.0       1      1        0
344  06-04-2010       0.0      0.0       0.0       1      1        0
345  12-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RAG0275
1             0   RAG0275
2             0   RAG0275
3             0   RAG0275
4             0   RAG0275
..          ...       ...
341           0   RAG0275
342           0   RAG0275
343           0   RAG0275
344           0   RAG0275
345           0   RAG0275

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       0.0      0.0       9.0       1      1        0
3    01-05-2010       3.0      1.0       5.0       1      1        0
4    01-05-2011       1.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       3.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  03-15-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RAH0440
1             0   RAH0440
2             0   RAH0440
3             0   RAH0440
4             0   RAH0440
..          ...       ...
341           0   RAH0440
342           0   RAH0440
343           0   RAH0440
344           0   RAH0440
345           0   RAH0440

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2011       1.0      0.0       0.0       1      2        0
1    01-03-2010       0.0      0.0       1.0       1      1        0
2    01-03-2011       0.0      0.0       1.0       1      2        0
3    01-04-2010       1.0      0.0       0.0       1      2        0
4    01-04-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
444  07-08-2010       0.0      0.0       0.0       1      2        0
445  08-03-2010       0.0      0.0       0.0       1      2        0
446  09-07-2010       0.0      0.0       0.0       1      1        0
447  10-04-2010       0.0      0.0       0.0       1      2        0
448  10-16-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   RAM0447
1             0   RAM0447
2             0   RAM0447
3             0   RAM0447
4             0   RAM0447
..          ...       ...
444           0   RAM0447
445           0   RAM0447
446           0   RAM0447
447           0   RAM0447
448           0   RAM0447

[449 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1      2.0
1    01-05-2010       1.0      0.0       0.0       1      1      2.0
2    01-06-2010       0.0      0.0       1.0       1      1      2.0
3    01-07-2010       0.0      0.0       1.0       1      1      1.0
4    01-08-2010       0.0      0.0       1.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
166  05-11-2010       0.0      0.0       0.0       1      1      3.0
167  06-04-2010       0.0      0.0       0.0       1      1      4.0
168  06-07-2010       0.0      0.0       0.0       1      1      2.0
169  08-20-2010       0.0      0.0       0.0       1      1      2.0
170  08-26-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           2.0   RAR0725
1           2.0   RAR0725
2           2.0   RAR0725
3           1.0   RAR0725
4           3.0   RAR0725
..          ...       ...
166         3.0   RAR0725
167         4.0   RAR0725
168         2.0   RAR0725
169         2.0   RAR0725
170         1.0   RAR0725

[171 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      2        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       4.0      0.0       5.0       1      2        0
4    01-05-2011       1.0      3.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2        0
342  12-28-2010       3.0      1.0       5.0       1      1        0
343  12-29-2010       2.0      1.0       6.0       1      2        0
344  12-30-2010       4.0      0.0       5.0       1      2        0
345  05-12-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RAS0432
1             0   RAS0432
2             0   RAS0432
3             0   RAS0432
4             0   RAS0432
..          ...       ...
341           0   RAS0432
342           0   RAS0432
343           0   RAS0432
344           0   RAS0432
345           0   RAS0432

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      0.0       5.0       1      2      2.0
1    01-03-2011       3.0      0.0       6.0       1      1      1.0
2    01-04-2010       6.0      0.0       2.0       1      2      1.0
3    01-04-2011       3.0      1.0       5.0       1      2      3.0
4    01-05-2010       2.0      0.0       7.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
399  02-19-2010       0.0      0.0       0.0       1      2      1.0
400  02-19-2011       0.0      0.0       0.0       1      2      1.0
401  05-27-2010       0.0      0.0       0.0       1      2      0.0
402  07-02-2010       0.0      0.0       0.0       1      1      0.0
403  07-18-2010       0.0      0.0       0.0       1      2      3.0

     Disconnect user_name
0           2.0   RAW0915
1           1.0   RAW0915
2           1.0   RAW0915
3           3.0   RAW0915
4           0.0   RAW0915
..          ...       ...
399         1.0   RAW0915
400         1.0   RAW0915
401         0.0   RAW0915
402         0.0   RAW0915
403         3.0   RAW0915

[404 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0      11.0       1      1        0
1    01-04-2010       8.0      0.0       7.0       1      1        0
2    01-04-2011       1.0      1.0      13.0       1      1        0
3    01-05-2010       7.0      0.0       8.0       1      1        0
4    01-05-2011       6.0      2.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0      11.0       1      1        0
342  12-29-2010       7.0      2.0       6.0       1      1        0
343  12-30-2010       4.0      2.0       9.0       1      1        0
344  04-27-2010       0.0      0.0       0.0       1      1        0
345  06-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RBB0485
1             0   RBB0485
2             0   RBB0485
3             0   RBB0485
4             0   RBB0485
..          ...       ...
341           0   RBB0485
342           0   RBB0485
343           0   RBB0485
344           0   RBB0485
345           0   RBB0485

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0       1      1        0
1    01-04-2010       6.0      1.0       8.0       1      1        0
2    01-04-2011       4.0      0.0      11.0       1      1        0
3    01-05-2010       3.0      1.0      11.0       1      1        0
4    01-05-2011       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       7.0       1      1        0
342  12-27-2010       4.0      0.0      11.0       1      1        0
343  12-28-2010       4.0      0.0      11.0       1      1        0
344  12-29-2010       8.0      1.0       6.0       1      1        0
345  12-30-2010      10.0      0.0       4.0       1      1        0

     Disconnect user_name
0             0   RCC0617
1             0   RCC0617
2             0   RCC0617
3             0   RCC0617
4             0   RCC0617
..          ...       ...
341           0   RCC0617
342           0   RCC0617
343           0   RCC0617
344           0   RCC0617
345           0   RCC0617

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       2.0      1.0       0.0       1      1        0
2    01-04-2011       3.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      1.0       2.0       1      1        0
342  12-29-2010       2.0      0.0       1.0       1      1        0
343  12-30-2010       3.0      0.0       0.0       1      1        0
344  02-09-2011       0.0      0.0       0.0       1      1        0
345  05-05-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RCP0785
1             0   RCP0785
2             0   RCP0785
3             0   RCP0785
4             0   RCP0785
..          ...       ...
341           0   RCP0785
342           0   RCP0785
343           0   RCP0785
344           0   RCP0785
345           0   RCP0785

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      1.0       5.0       1      1        0
3    01-05-2010       6.0      2.0       3.0       1      1        0
4    01-05-2011       4.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      3.0       6.0       1      1        0
342  12-29-2010       4.0      1.0       4.0       1      1        0
343  12-30-2010      10.0      0.0       1.0       1      1        0
344  03-28-2011       0.0      0.0       0.0       1      1        0
345  12-02-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RDM0115
1             0   RDM0115
2             0   RDM0115
3             0   RDM0115
4             0   RDM0115
..          ...       ...
341           0   RDM0115
342           0   RDM0115
343           0   RDM0115
344           0   RDM0115
345           0   RDM0115

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       2.0       1      1        0
1    01-04-2010       3.0      0.0       2.0       1      1        0
2    01-04-2011       4.0      0.0       1.0       1      1        0
3    01-05-2010       3.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      1.0       2.0       1      1        0
342  12-30-2010       2.0      1.0       2.0       1      1        0
343  01-28-2010       0.0      0.0       0.0       1      1        0
344  03-21-2011       0.0      0.0       0.0       1      1        0
345  05-02-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RDM0150
1             0   RDM0150
2             0   RDM0150
3             0   RDM0150
4             0   RDM0150
..          ...       ...
341           0   RDM0150
342           0   RDM0150
343           0   RDM0150
344           0   RDM0150
345           0   RDM0150

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       3.0       1      1      1.0
1    01-04-2010       3.0      0.0       6.0       1      2      1.0
2    01-04-2011       3.0      0.0       6.0       1      2      1.0
3    01-05-2010       4.0      1.0       4.0       1      2      1.0
4    01-05-2011       4.0      0.0       5.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       5.0       1      2      1.0
342  12-28-2010       4.0      0.0       5.0       2      3      3.0
343  12-29-2010       5.0      0.0       4.0       1      2      1.0
344  12-30-2010       4.0      1.0       4.0       1      2      3.0
345  05-12-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           1.0   RDT0424
1           1.0   RDT0424
2           0.0   RDT0424
3           1.0   RDT0424
4           1.0   RDT0424
..          ...       ...
341         1.0   RDT0424
342         3.0   RDT0424
343         1.0   RDT0424
344         3.0   RDT0424
345         1.0   RDT0424

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       2.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       2.0      1.0       1.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       4.0       1      1        0
342  12-28-2010       2.0      1.0       6.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  05-03-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RFP0380
1             0   RFP0380
2             0   RFP0380
3             0   RFP0380
4             0   RFP0380
..          ...       ...
341           0   RFP0380
342           0   RFP0380
343           0   RFP0380
344           0   RFP0380
345           0   RFP0380

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      0.0       4.0       1      2      0.0
1    01-05-2010       3.0      2.0       4.0       1      2      0.0
2    01-06-2010       5.0      0.0       3.0       1      1      0.0
3    01-07-2010       2.0      0.0       7.0       1      2      0.0
4    01-08-2010       3.0      1.0       5.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
217  11-09-2010       5.0      1.0       3.0       1      2      0.0
218  11-10-2010       2.0      1.0       6.0       1      2      0.0
219  11-11-2010       3.0      0.0       6.0       1      2      0.0
220  11-12-2010       3.0      0.0       6.0       1      1      0.0
221  11-15-2010       5.0      0.0       4.0       1      2      0.0

     Disconnect user_name
0           0.0   RGG0064
1           0.0   RGG0064
2           0.0   RGG0064
3           0.0   RGG0064
4           0.0   RGG0064
..          ...       ...
217         0.0   RGG0064
218         0.0   RGG0064
219         0.0   RGG0064
220         0.0   RGG0064
221         0.0   RGG0064

[222 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0     12.0       2.0       1      1        0
1    01-04-2010       4.0      4.0       7.0       1      1        0
2    01-04-2011       5.0      1.0       9.0       1      1        0
3    01-05-2010       6.0      4.0       5.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
276  12-22-2010       4.0      2.0       9.0       1      1        0
277  12-27-2010       7.0      2.0       6.0       1      1        0
278  12-28-2010       4.0      3.0       8.0       1      1        0
279  12-29-2010       6.0      3.0       6.0       1      1        0
280  12-30-2010      11.0      2.0       2.0       1      1        0

     Disconnect user_name
0             0   RGH0728
1             0   RGH0728
2             0   RGH0728
3             0   RGH0728
4             0   RGH0728
..          ...       ...
276           0   RGH0728
277           0   RGH0728
278           0   RGH0728
279           0   RGH0728
280           0   RGH0728

[281 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       2.0     1.0    1.0        0
1    01-04-2010       2.0      1.0       6.0     1.0    1.0        0
2    01-04-2011       7.0      0.0       2.0     1.0    1.0        0
3    01-05-2010       1.0      0.0       8.0     1.0    1.0        0
4    01-05-2011       4.0      0.0       5.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      1.0       3.0     1.0    1.0        0
342  12-28-2010       5.0      1.0       3.0     1.0    1.0        0
343  12-29-2010       3.0      1.0       5.0     1.0    1.0        0
344  12-30-2010       5.0      0.0       4.0     1.0    1.0        0
345  11-29-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   RGN0408
1             0   RGN0408
2             0   RGN0408
3             0   RGN0408
4             0   RGN0408
..          ...       ...
341           0   RGN0408
342           0   RGN0408
343           0   RGN0408
344           0   RGN0408
345           0   RGN0408

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      1.0       1.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      1.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  01-10-2011       0.0      0.0       0.0       1      1        0
343  01-29-2010       0.0      0.0       0.0       1      1        0
344  02-08-2011       0.0      0.0       0.0       1      1        0
345  10-25-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RHC0335
1             0   RHC0335
2             0   RHC0335
3             0   RHC0335
4             0   RHC0335
..          ...       ...
341           0   RHC0335
342           0   RHC0335
343           0   RHC0335
344           0   RHC0335
345           0   RHC0335

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       2.0      1.0       6.0       1      2      2.0
1    01-05-2010       2.0      5.0       2.0       1      2      1.0
2    01-06-2010       2.0      5.0       2.0       2      2      2.0
3    01-07-2010       3.0      3.0       3.0       1      2      3.0
4    01-08-2010       3.0      2.0       4.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
171  09-03-2010       2.0      5.0       2.0       1      2      3.0
172  09-07-2010       5.0      2.0       2.0       2      2      2.0
173  09-08-2010       4.0      0.0       5.0       1      2      0.0
174  09-09-2010       0.0      7.0       2.0       1      2      6.0
175  09-10-2010       1.0      8.0       0.0       1      2      0.0

     Disconnect user_name
0           2.0   RHL0992
1           1.0   RHL0992
2           2.0   RHL0992
3           3.0   RHL0992
4           2.0   RHL0992
..          ...       ...
171         3.0   RHL0992
172         2.0   RHL0992
173         0.0   RHL0992
174         6.0   RHL0992
175         0.0   RHL0992

[176 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0     10.0       1.0     2.0    3.0      3.0
1    01-04-2010       1.0     13.0       1.0     2.0    3.0      3.0
2    01-04-2011       6.0      3.0       6.0     1.0    2.0      2.0
3    01-05-2010       6.0      6.0       3.0     1.0    2.0      2.0
4    01-05-2011       8.0      1.0       6.0     1.0    2.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
349  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
350  07-03-2010       0.0      0.0       0.0     1.0    0.0      0.0
351  11-06-2010       0.0      0.0       0.0     1.0    1.0      0.0
352  11-10-2010       0.0      0.0       0.0     2.0    4.0      4.0
353  11-13-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           3.0   RHO0732
1           3.0   RHO0732
2           2.0   RHO0732
3           2.0   RHO0732
4           0.0   RHO0732
..          ...       ...
349         0.0   RHO0732
350         0.0   RHO0732
351         0.0   RHO0732
352         4.0   RHO0732
353         0.0   RHO0732

[354 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       9.0       1      2        0
1    01-04-2010       6.0      0.0      10.0       1      2        0
2    01-04-2011       8.0      0.0       8.0       1      2        0
3    01-05-2010       9.0      1.0       4.0       1      2        0
4    01-05-2011       5.0      0.0      11.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0      11.0       1      2        0
342  12-28-2010       7.0      0.0       8.0       1      2        0
343  12-29-2010       5.0      0.0      11.0       1      2        0
344  12-30-2010       5.0      0.0      11.0       1      2        0
345  06-11-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   RHP0484
1             0   RHP0484
2             0   RHP0484
3             0   RHP0484
4             0   RHP0484
..          ...       ...
341           0   RHP0484
342           0   RHP0484
343           0   RHP0484
344           0   RHP0484
345           0   RHP0484

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       8.0       1      1        0
1    01-04-2010       8.0      2.0       8.0       1      1        0
2    01-04-2011      11.0      1.0       6.0       1      1        0
3    01-05-2010       6.0      0.0      12.0       1      1        0
4    01-05-2011       8.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0      12.0       1      1        0
342  12-27-2010      12.0      0.0       6.0       1      1        0
343  12-28-2010       8.0      0.0      10.0       1      1        0
344  12-29-2010       7.0      0.0      11.0       1      1        0
345  12-30-2010       4.0      0.0      14.0       1      1        0

     Disconnect user_name
0             0   RHY0079
1             0   RHY0079
2             0   RHY0079
3             0   RHY0079
4             0   RHY0079
..          ...       ...
341           0   RHY0079
342           0   RHY0079
343           0   RHY0079
344           0   RHY0079
345           0   RHY0079

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       1.0       1      1        0
342  12-30-2010       0.0      0.0       3.0       1      1        0
343  04-29-2010       0.0      0.0       0.0       1      1        0
344  05-05-2010       0.0      0.0       0.0       1      1        0
345  05-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RIH0777
1             0   RIH0777
2             0   RIH0777
3             0   RIH0777
4             0   RIH0777
..          ...       ...
341           0   RIH0777
342           0   RIH0777
343           0   RIH0777
344           0   RIH0777
345           0   RIH0777

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       7.0      0.0       2.0       1      1        0
343  12-28-2010       6.0      0.0       3.0       1      1        0
344  12-29-2010       1.0      0.0       8.0       1      1        0
345  12-30-2010       1.0      1.0       7.0       1      1        0

     Disconnect user_name
0             0   RJB0088
1             0   RJB0088
2             0   RJB0088
3             0   RJB0088
4             0   RJB0088
..          ...       ...
341           0   RJB0088
342           0   RJB0088
343           0   RJB0088
344           0   RJB0088
345           0   RJB0088

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       2.0      1.0       6.0       1      1        0
344  12-29-2010       5.0      0.0       4.0       1      1        0
345  12-30-2010       3.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   RJM0381
1             0   RJM0381
2             0   RJM0381
3             0   RJM0381
4             0   RJM0381
..          ...       ...
341           0   RJM0381
342           0   RJM0381
343           0   RJM0381
344           0   RJM0381
345           0   RJM0381

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       9.0      0.0       6.0     1.0    1.0      0.0
1    01-05-2010       6.0      1.0       4.0     1.0    1.0      0.0
2    01-06-2010       8.0      1.0       6.0     1.0    1.0      0.0
3    01-07-2010       4.0      1.0      10.0     1.0    1.0      0.0
4    01-08-2010       8.0      0.0       7.0     1.0    1.0      0.0
..          ...       ...      ...       ...     ...    ...      ...
146  07-30-2010       4.0      1.0       9.0     1.0    1.0      0.0
147  08-02-2010       8.0      0.0       7.0     1.0    1.0      0.0
148  08-03-2010       6.0      1.0       7.0     1.0    1.0      0.0
149  08-04-2010       6.0      1.0       8.0     1.0    1.0      0.0
150  07-10-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           0.0   RKD0604
1           0.0   RKD0604
2           0.0   RKD0604
3           0.0   RKD0604
4           0.0   RKD0604
..          ...       ...
146         0.0   RKD0604
147         0.0   RKD0604
148         0.0   RKD0604
149         0.0   RKD0604
150         0.0   RKD0604

[151 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
330  12-29-2010       6.0      0.0       3.0       1      1        0
331  12-30-2010       1.0      2.0       6.0       1      1        0
332  09-29-2010       0.0      0.0       0.0       1      1        0
333  10-12-2010       0.0      0.0       0.0       1      1        0
334  12-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RKF0164
1             0   RKF0164
2             0   RKF0164
3             0   RKF0164
4             0   RKF0164
..          ...       ...
330           0   RKF0164
331           0   RKF0164
332           0   RKF0164
333           0   RKF0164
334           0   RKF0164

[335 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0     2.0    2.0        0
1    01-04-2010       0.0      0.0       1.0     1.0    1.0        0
2    01-04-2011       0.0      0.0       1.0     1.0    1.0        0
3    01-05-2010       0.0      0.0       1.0     1.0    1.0        0
4    01-05-2011       0.0      0.0       1.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
343  05-03-2010       0.0      0.0       0.0     1.0    1.0        0
344  05-03-2011       0.0      0.0       0.0     1.0    1.0        0
345  05-05-2010       0.0      0.0       0.0     1.0    1.0        0
346  09-08-2010       0.0      0.0       0.0     1.0    1.0        0
347  11-17-2010       0.0      0.0       0.0     1.0    2.0        0

     Disconnect user_name
0             0   RLB0719
1             0   RLB0719
2             0   RLB0719
3             0   RLB0719
4             0   RLB0719
..          ...       ...
343           0   RLB0719
344           0   RLB0719
345           0   RLB0719
346           0   RLB0719
347           0   RLB0719

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       6.0     1.0    1.0      0.0
1    01-04-2010       5.0      0.0      10.0     1.0    2.0      2.0
2    01-04-2011       8.0      0.0       7.0     1.0    2.0      0.0
3    01-05-2010       8.0      0.0       7.0     1.0    2.0      0.0
4    01-05-2011       4.0      1.0       9.0     1.0    2.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
344  12-30-2010       8.0      1.0       6.0     1.0    2.0      2.0
345  03-19-2011       0.0      0.0       0.0     1.0    0.0      0.0
346  04-17-2010       0.0      0.0       0.0     1.0    1.0      0.0
347  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
348  05-13-2011       0.0      0.0       0.0     1.0    2.0      0.0

     Disconnect user_name
0           0.0   RLG0856
1           2.0   RLG0856
2           0.0   RLG0856
3           0.0   RLG0856
4           2.0   RLG0856
..          ...       ...
344         2.0   RLG0856
345         0.0   RLG0856
346         0.0   RLG0856
347         0.0   RLG0856
348         0.0   RLG0856

[349 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       7.0       1      1        0
343  12-29-2010       5.0      0.0       4.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  04-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RMS0266
1             0   RMS0266
2             0   RMS0266
3             0   RMS0266
4             0   RMS0266
..          ...       ...
341           0   RMS0266
342           0   RMS0266
343           0   RMS0266
344           0   RMS0266
345           0   RMS0266

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      1.0       3.0       1      1      1.0
1    01-05-2010       2.0      0.0       7.0       1      1      4.0
2    01-06-2010       4.0      1.0       3.0       1      1      1.0
3    01-07-2010       2.0      0.0       7.0       1      1      2.0
4    01-08-2010       4.0      0.0       5.0       1      1      2.0
..          ...       ...      ...       ...     ...    ...      ...
156  08-16-2010       5.0      0.0       4.0       1      1      3.0
157  08-17-2010       6.0      0.0       3.0       1      1      3.0
158  08-18-2010       4.0      0.0       5.0       1      1      6.0
159  08-19-2010       2.0      0.0       7.0       1      1      2.0
160  05-21-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           1.0   RMW0542
1           4.0   RMW0542
2           1.0   RMW0542
3           2.0   RMW0542
4           2.0   RMW0542
..          ...       ...
156         3.0   RMW0542
157         3.0   RMW0542
158         6.0   RMW0542
159         2.0   RMW0542
160         1.0   RMW0542

[161 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  01-10-2011       0.0      0.0       0.0       1      1        0
343  02-17-2010       0.0      0.0       0.0       1      1        0
344  09-14-2010       0.0      0.0       0.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RNF0765
1             0   RNF0765
2             0   RNF0765
3             0   RNF0765
4             0   RNF0765
..          ...       ...
341           0   RNF0765
342           0   RNF0765
343           0   RNF0765
344           0   RNF0765
345           0   RNF0765

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      1.0       2.0       1      2        0
2    01-04-2011       4.0      0.0       5.0       1      2        0
3    01-05-2010       1.0      0.0       8.0       1      2        0
4    01-05-2011       3.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       0.0      0.0       1.0       1      2        0
342  12-27-2010       3.0      1.0       5.0       1      2        0
343  12-28-2010       2.0      1.0       6.0       1      1        0
344  12-29-2010       5.0      1.0       3.0       1      2        0
345  12-30-2010       2.0      0.0       7.0       1      2        0

     Disconnect user_name
0             0   RNL0695
1             0   RNL0695
2             0   RNL0695
3             0   RNL0695
4             0   RNL0695
..          ...       ...
341           0   RNL0695
342           0   RNL0695
343           0   RNL0695
344           0   RNL0695
345           0   RNL0695

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       4.0       1      1      5.0
1    01-04-2010       5.0      0.0       8.0       1      1      3.0
2    01-04-2011       5.0      1.0       8.0       1      2      4.0
3    01-05-2010       9.0      0.0       5.0       1      2      3.0
4    01-05-2011       6.0      0.0       8.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      10.0      0.0       4.0       1      2      4.0
342  12-27-2010       8.0      0.0       6.0       1      2      2.0
343  12-28-2010       6.0      0.0       8.0       1      2      4.0
344  12-29-2010      10.0      0.0       4.0       1      2      4.0
345  12-30-2010       2.0      1.0      10.0       1      2      2.0

     Disconnect user_name
0           5.0   RNP0211
1           3.0   RNP0211
2           4.0   RNP0211
3           3.0   RNP0211
4           2.0   RNP0211
..          ...       ...
341         4.0   RNP0211
342         1.0   RNP0211
343         4.0   RNP0211
344         4.0   RNP0211
345         2.0   RNP0211

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0     1.0    1.0        0
1    01-04-2010       6.0      0.0       3.0     1.0    1.0        0
2    01-04-2011       4.0      1.0       4.0     1.0    1.0        0
3    01-05-2010       4.0      0.0       5.0     1.0    1.0        0
4    01-05-2011       3.0      0.0       6.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       3.0     1.0    1.0        0
342  12-28-2010       4.0      0.0       5.0     1.0    1.0        0
343  12-29-2010       3.0      0.0       6.0     1.0    1.0        0
344  12-30-2010       6.0      0.0       3.0     1.0    1.0        0
345  03-22-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   ROB0272
1             0   ROB0272
2             0   ROB0272
3             0   ROB0272
4             0   ROB0272
..          ...       ...
341           0   ROB0272
342           0   ROB0272
343           0   ROB0272
344           0   ROB0272
345           0   ROB0272

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       3.0      1.0       5.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      2        0
3    01-05-2010       1.0      0.0       8.0       1      2        0
4    01-05-2011       5.0      0.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2        0
342  12-27-2010       3.0      0.0       6.0       1      2        0
343  12-28-2010       3.0      2.0       3.0       1      1        0
344  12-29-2010       3.0      1.0       5.0       1      2        0
345  12-30-2010       3.0      0.0       6.0       1      2        0

     Disconnect user_name
0             0   RRA0938
1             0   RRA0938
2             0   RRA0938
3             0   RRA0938
4             0   RRA0938
..          ...       ...
341           0   RRA0938
342           0   RRA0938
343           0   RRA0938
344           0   RRA0938
345           0   RRA0938

[346 rows x 9 columns]
aux       str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0   01-02-2010       3.0      0.0       6.0       1      2      3.0
1   01-04-2010       5.0      0.0       4.0       1      2      1.0
2   01-05-2010       5.0      0.0       4.0       1      2      1.0
3   01-06-2010       2.0      0.0       7.0       1      2      2.0
4   01-07-2010       6.0      0.0       3.0       1      2      1.0
..         ...       ...      ...       ...     ...    ...      ...
71  03-27-2010       4.0      1.0       3.0       1      2      0.0
72  03-29-2010       1.0      0.0       8.0       1      2      0.0
73  03-30-2010       3.0      0.0       6.0       1      1      0.0
74  03-31-2010       1.0      2.0       6.0       1      1      2.0
75  04-01-2010       2.0      1.0       6.0       1      2      1.0

    Disconnect user_name
0          3.0   RRC0553
1          1.0   RRC0553
2          0.0   RRC0553
3          2.0   RRC0553
4          1.0   RRC0553
..         ...       ...
71         0.0   RRC0553
72         0.0   RRC0553
73         0.0   RRC0553
74         2.0   RRC0553
75         1.0   RRC0553

[76 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1      1.0
1    01-04-2010       3.0      0.0       6.0       1      1      0.0
2    01-04-2011       4.0      1.0       4.0       1      2      1.0
3    01-05-2010       6.0      0.0       3.0       1      2      1.0
4    01-05-2011       2.0      0.0       7.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       5.0       1      2      0.0
342  12-28-2010       3.0      0.0       6.0       1      2      0.0
343  12-29-2010       4.0      0.0       5.0       1      2      1.0
344  12-30-2010       4.0      0.0       5.0       1      2      0.0
345  02-14-2011       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           1.0   RRP0568
1           0.0   RRP0568
2           1.0   RRP0568
3           1.0   RRP0568
4           0.0   RRP0568
..          ...       ...
341         0.0   RRP0568
342         0.0   RRP0568
343         1.0   RRP0568
344         0.0   RRP0568
345         0.0   RRP0568

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       7.0     1.0    2.0      8.0
1    01-04-2010       3.0      0.0       6.0     2.0    3.0      9.0
2    01-04-2011       3.0      2.0       4.0     1.0    2.0      8.0
3    01-05-2010       4.0      0.0       5.0     1.0    2.0      9.0
4    01-05-2011       2.0      0.0       7.0     3.0    4.0      8.0
..          ...       ...      ...       ...     ...    ...      ...
368  10-02-2010       0.0      0.0       0.0     1.0    1.0      0.0
369  10-16-2010       0.0      0.0       0.0     1.0    1.0      0.0
370  10-30-2010       0.0      0.0       0.0     1.0    0.0      0.0
371  11-06-2010       0.0      0.0       0.0     1.0    1.0      0.0
372  11-21-2010       0.0      0.0       0.0     1.0    0.0      0.0

     Disconnect user_name
0           8.0   RSC0089
1           9.0   RSC0089
2           8.0   RSC0089
3           9.0   RSC0089
4           8.0   RSC0089
..          ...       ...
368         0.0   RSC0089
369         0.0   RSC0089
370         0.0   RSC0089
371         0.0   RSC0089
372         0.0   RSC0089

[373 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       5.0       2      2      2.0
1    01-04-2010       4.0      0.0       5.0       2      3      0.0
2    01-04-2011       6.0      0.0       3.0       1      2      1.0
3    01-05-2010       3.0      0.0       6.0       1      2      2.0
4    01-05-2011       5.0      1.0       3.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       1.0       1      2      3.0
342  12-30-2010       3.0      0.0       5.0       1      2      3.0
343  02-22-2011       0.0      0.0       0.0       1      2      0.0
344  03-22-2010       0.0      0.0       0.0       2      3      3.0
345  09-15-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           2.0   RSM0277
1           0.0   RSM0277
2           1.0   RSM0277
3           2.0   RSM0277
4           0.0   RSM0277
..          ...       ...
341         3.0   RSM0277
342         3.0   RSM0277
343         0.0   RSM0277
344         3.0   RSM0277
345         1.0   RSM0277

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       8.0     1.0    1.0        0
1    01-04-2010       6.0      1.0       7.0     1.0    1.0        0
2    01-04-2011       5.0      1.0       9.0     1.0    2.0        0
3    01-05-2010       5.0      1.0       8.0     1.0    2.0        0
4    01-05-2011       6.0      1.0       8.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
350  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
351  05-14-2011       0.0      0.0       0.0     1.0    1.0        0
352  10-02-2010       0.0      0.0       0.0     1.0    1.0        0
353  11-13-2010       0.0      0.0       0.0     1.0    0.0        0
354  12-04-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   RTO0313
1             0   RTO0313
2             0   RTO0313
3             0   RTO0313
4             0   RTO0313
..          ...       ...
350           0   RTO0313
351           0   RTO0313
352           0   RTO0313
353           0   RTO0313
354           0   RTO0313

[355 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       7.0       1      1      2.0
1    01-04-2010       8.0      0.0       7.0       1      1      2.0
2    01-04-2011       7.0      1.0       6.0       1      2      3.0
3    01-05-2010       9.0      3.0       2.0       1      2      1.0
4    01-05-2011       8.0      0.0       7.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
345  04-17-2010       0.0      0.0       0.0       1      1      0.0
346  07-03-2010       0.0      0.0       0.0       1      1      0.0
347  09-01-2010       0.0      0.0       0.0       1      2      0.0
348  10-02-2010       0.0      0.0       0.0       1      1      0.0
349  10-06-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           2.0   RUM0880
1           2.0   RUM0880
2           3.0   RUM0880
3           1.0   RUM0880
4           2.0   RUM0880
..          ...       ...
345         0.0   RUM0880
346         0.0   RUM0880
347         0.0   RUM0880
348         0.0   RUM0880
349         0.0   RUM0880

[350 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       2.0      0.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       6.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       1.0      2.0       6.0       1      1        0
344  12-29-2010       6.0      0.0       2.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   RVC0232
1             0   RVC0232
2             0   RVC0232
3             0   RVC0232
4             0   RVC0232
..          ...       ...
341           0   RVC0232
342           0   RVC0232
343           0   RVC0232
344           0   RVC0232
345           0   RVC0232

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       8.0       1      2      2.0
1    01-04-2010       1.0      0.0      10.0       1      1      0.0
2    01-04-2011       4.0      0.0       7.0       1      2      2.0
3    01-05-2010       4.0      0.0       7.0       1      2      3.0
4    01-05-2011       4.0      0.0       7.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      1.0       8.0       1      2      2.0
342  12-28-2010       5.0      0.0       6.0       1      1      2.0
343  12-29-2010       9.0      0.0       2.0       1      2      1.0
344  12-30-2010       4.0      0.0       7.0       1      2      1.0
345  04-12-2010       0.0      0.0       0.0       1      1      2.0

     Disconnect user_name
0           2.0   RVF0201
1           0.0   RVF0201
2           2.0   RVF0201
3           3.0   RVF0201
4           1.0   RVF0201
..          ...       ...
341         2.0   RVF0201
342         2.0   RVF0201
343         1.0   RVF0201
344         1.0   RVF0201
345         2.0   RVF0201

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-23-2010       0.0      0.0       0.0       1      1        0
342  07-26-2010       0.0      0.0       0.0       1      1        0
343  08-24-2010       0.0      0.0       0.0       1      1        0
344  09-17-2010       0.0      0.0       0.0       1      1        0
345  10-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RYB0718
1             0   RYB0718
2             0   RYB0718
3             0   RYB0718
4             0   RYB0718
..          ...       ...
341           0   RYB0718
342           0   RYB0718
343           0   RYB0718
344           0   RYB0718
345           0   RYB0718

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       2.0      8.0       5.0       1      2        0
1    01-03-2010       4.0      6.0       5.0       1      2        0
2    01-03-2011       1.0     12.0       2.0       1      1        0
3    01-04-2010       1.0      4.0      10.0       2      2        0
4    01-04-2011       3.0      6.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
475  12-31-2010       4.0      2.0       9.0       2      2        0
476  01-02-2010       0.0      0.0       0.0       1      2        0
477  02-21-2011       0.0      0.0       0.0       1      2        0
478  12-05-2010       0.0      0.0       0.0       1      2        0
479  12-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   RZC0746
1             0   RZC0746
2             0   RZC0746
3             0   RZC0746
4             0   RZC0746
..          ...       ...
475           0   RZC0746
476           0   RZC0746
477           0   RZC0746
478           0   RZC0746
479           0   RZC0746

[480 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       6.0       1      2        9
1    01-04-2010       5.0      0.0       4.0       1      2        9
2    01-04-2011       4.0      2.0       3.0       1      2        8
3    01-05-2010       0.0      1.0       0.0       1      2        9
4    01-05-2011       2.0      1.0       6.0       1      2        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2        8
342  12-27-2010       3.0      3.0       3.0       1      2        9
343  12-28-2010       1.0      6.0       2.0       1      1        9
344  12-29-2010       2.0      6.0       1.0       1      2       10
345  12-30-2010       4.0      1.0       4.0       1      2        9

     Disconnect user_name
0             9   SAA0999
1             9   SAA0999
2             8   SAA0999
3             9   SAA0999
4             9   SAA0999
..          ...       ...
341           8   SAA0999
342           9   SAA0999
343           9   SAA0999
344          10   SAA0999
345           9   SAA0999

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1      0.0
1    01-04-2010       0.0      0.0       3.0       1      2      0.0
2    01-04-2011       0.0      0.0       3.0       1      2      2.0
3    01-05-2010       0.0      0.0       3.0       1      2      1.0
4    01-05-2011       0.0      1.0       2.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  01-29-2010       0.0      0.0       0.0       1      2      0.0
342  02-19-2010       0.0      0.0       0.0       1      2      1.0
343  05-13-2010       0.0      0.0       0.0       1      2      0.0
344  11-01-2010       0.0      0.0       0.0       1      2      1.0
345  12-01-2010       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   SAB0781
1           0.0   SAB0781
2           2.0   SAB0781
3           1.0   SAB0781
4           0.0   SAB0781
..          ...       ...
341         0.0   SAB0781
342         1.0   SAB0781
343         0.0   SAB0781
344         1.0   SAB0781
345         1.0   SAB0781

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-18-2011       0.0      0.0       0.0       1      2        0
342  02-12-2010       0.0      0.0       0.0       1      2        0
343  04-11-2011       0.0      0.0       0.0       1      2        0
344  08-04-2010       0.0      0.0       0.0       1      1        0
345  08-24-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SAC0592
1             0   SAC0592
2             0   SAC0592
3             0   SAC0592
4             0   SAC0592
..          ...       ...
341           0   SAC0592
342           0   SAC0592
343           0   SAC0592
344           0   SAC0592
345           0   SAC0592

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      2.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       2.0      1.0       5.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       7.0       1      1        0
342  12-30-2010       2.0      1.0       6.0       1      1        0
343  01-14-2010       0.0      0.0       0.0       1      1        0
344  03-28-2011       0.0      0.0       0.0       1      1        0
345  07-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SAC0687
1             0   SAC0687
2             0   SAC0687
3             0   SAC0687
4             0   SAC0687
..          ...       ...
341           0   SAC0687
342           0   SAC0687
343           0   SAC0687
344           0   SAC0687
345           0   SAC0687

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-09-2010       0.0      0.0       0.0       1      1        0
342  07-21-2010       0.0      0.0       0.0       1      1        0
343  10-15-2010       0.0      0.0       0.0       1      1        0
344  10-21-2010       0.0      0.0       0.0       1      1        0
345  11-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SAH0599
1             0   SAH0599
2             0   SAH0599
3             0   SAH0599
4             0   SAH0599
..          ...       ...
341           0   SAH0599
342           0   SAH0599
343           0   SAH0599
344           0   SAH0599
345           0   SAH0599

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       5      5        0
1    01-04-2010       4.0      2.0       5.0       4      4        0
2    01-04-2011       4.0      1.0       6.0       2      2        0
3    01-05-2010       6.0      1.0       4.0       5      5        0
4    01-05-2011       0.0      2.0       9.0       6      6        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       6.0       3      3        0
342  12-28-2010       5.0      0.0       6.0       3      3        0
343  12-29-2010       3.0      0.0       8.0       5      5        0
344  12-30-2010       7.0      0.0       3.0       2      2        0
345  02-24-2010       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   SAK0375
1             0   SAK0375
2             0   SAK0375
3             0   SAK0375
4             0   SAK0375
..          ...       ...
341           0   SAK0375
342           0   SAK0375
343           0   SAK0375
344           0   SAK0375
345           0   SAK0375

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       8.0      0.0       7.0       1      1        0
1    01-05-2010      11.0      0.0       4.0       1      1        0
2    01-06-2010       6.0      1.0       8.0       1      1        0
3    01-07-2010       9.0      0.0       6.0       1      1        0
4    01-08-2010       6.0      1.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
141  07-23-2010       6.0      0.0       9.0       1      1        0
142  07-26-2010       8.0      0.0       6.0       1      1        0
143  07-27-2010       5.0      1.0       9.0       1      1        0
144  07-28-2010       2.0      0.0       2.0       1      1        0
145  07-29-2010       7.0      0.0       8.0       1      1        0

     Disconnect user_name
0             0   SAP0867
1             0   SAP0867
2             0   SAP0867
3             0   SAP0867
4             0   SAP0867
..          ...       ...
141           0   SAP0867
142           0   SAP0867
143           0   SAP0867
144           0   SAP0867
145           0   SAP0867

[146 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      7.0       2.0       1      1        0
1    01-04-2010       5.0      1.0       5.0       1      1        0
2    01-04-2011       2.0      9.0       0.0       1      1        0
3    01-05-2010       2.0      0.0       9.0       1      1        0
4    01-05-2011       3.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       6.0       1      1        0
342  12-28-2010       2.0      2.0       7.0       1      1        0
343  12-29-2010       2.0      4.0       5.0       1      1        0
344  12-30-2010       2.0      7.0       2.0       1      1        0
345  08-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SAT0194
1             0   SAT0194
2             0   SAT0194
3             0   SAT0194
4             0   SAT0194
..          ...       ...
341           0   SAT0194
342           0   SAT0194
343           0   SAT0194
344           0   SAT0194
345           0   SAT0194

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       1.0      0.0       2.0       1      1        0
344  04-01-2010       0.0      0.0       0.0       1      1        0
345  10-25-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SBD0913
1             0   SBD0913
2             0   SBD0913
3             0   SBD0913
4             0   SBD0913
..          ...       ...
341           0   SBD0913
342           0   SBD0913
343           0   SBD0913
344           0   SBD0913
345           0   SBD0913

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       5.0       1      2      0.0
1    01-04-2010       6.0      0.0       7.0       1      2      1.0
2    01-04-2011       5.0      0.0       7.0       1      2      0.0
3    01-05-2010       9.0      0.0       4.0       1      2      0.0
4    01-05-2011       7.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
381  12-24-2010       5.0      0.0       8.0       1      2      1.0
382  12-27-2010       3.0      0.0      10.0       1      2      0.0
383  12-28-2010       3.0      1.0       9.0       1      1      0.0
384  12-29-2010       4.0      1.0       8.0       1      2      0.0
385  12-30-2010       9.0      0.0       4.0       1      1      2.0

     Disconnect user_name
0           0.0   SBH0537
1           1.0   SBH0537
2           0.0   SBH0537
3           0.0   SBH0537
4           0.0   SBH0537
..          ...       ...
381         1.0   SBH0537
382         0.0   SBH0537
383         0.0   SBH0537
384         0.0   SBH0537
385         2.0   SBH0537

[386 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0      11.0       2      3        0
1    01-04-2010       2.0      3.0      13.0       1      1        0
2    01-04-2011       8.0      1.0       9.0       1      2        0
3    01-05-2011       6.0      2.0      10.0       1      2        0
4    01-06-2010       6.0      1.0      11.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      1.0      10.0       1      2        0
342  12-28-2010       7.0      0.0      11.0       2      2        0
343  12-29-2010       2.0      0.0       6.0       1      2        0
344  12-30-2010       5.0      1.0      12.0       1      2        0
345  01-05-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SBK0161
1             0   SBK0161
2             0   SBK0161
3             0   SBK0161
4             0   SBK0161
..          ...       ...
341           0   SBK0161
342           0   SBK0161
343           0   SBK0161
344           0   SBK0161
345           0   SBK0161

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       3.0       1      1        0
1    01-04-2010       6.0      0.0       9.0       1      1        0
2    01-04-2011       7.0      1.0       7.0       1      1        0
3    01-05-2010       6.0      0.0       9.0       1      1        0
4    01-05-2011       5.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       7.0       1      1        0
342  12-27-2010      10.0      0.0       5.0       1      1        0
343  12-28-2010       8.0      1.0       6.0       1      1        0
344  12-29-2010       9.0      0.0       6.0       1      1        0
345  12-30-2010       5.0      0.0      10.0       1      1        0

     Disconnect user_name
0             0   SBN0495
1             0   SBN0495
2             0   SBN0495
3             0   SBN0495
4             0   SBN0495
..          ...       ...
341           0   SBN0495
342           0   SBN0495
343           0   SBN0495
344           0   SBN0495
345           0   SBN0495

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       6.0     1.0    1.0      0.0
1    01-04-2010      10.0      0.0       5.0     1.0    1.0      2.0
2    01-04-2011      11.0      1.0       3.0     1.0    1.0      0.0
3    01-05-2010       0.0      1.0       2.0     1.0    1.0      0.0
4    01-05-2011      10.0      0.0       5.0     1.0    1.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
343  12-29-2010       8.0      0.0       7.0     1.0    1.0      3.0
344  12-30-2010       7.0      0.0       7.0     1.0    1.0      1.0
345  02-26-2011       0.0      0.0       0.0     1.0    0.0      0.0
346  03-03-2010       0.0      0.0       0.0     1.0    1.0      1.0
347  05-14-2011       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           0.0   SBN0866
1           2.0   SBN0866
2           0.0   SBN0866
3           0.0   SBN0866
4           2.0   SBN0866
..          ...       ...
343         3.0   SBN0866
344         1.0   SBN0866
345         0.0   SBN0866
346         1.0   SBN0866
347         0.0   SBN0866

[348 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2010       0.0      0.0       1.0       1      1      0.0
1    01-03-2011       1.0      0.0       0.0       1      1      1.0
2    01-04-2010       1.0      0.0       0.0       1      1      1.0
3    01-04-2011       1.0      0.0       0.0       1      1      1.0
4    01-05-2010       1.0      0.0       0.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
444  06-16-2010       0.0      0.0       0.0       1      1      0.0
445  07-01-2010       0.0      0.0       0.0       1      1      1.0
446  08-06-2010       0.0      0.0       0.0       1      1      0.0
447  09-11-2010       0.0      0.0       0.0       1      1      0.0
448  10-29-2010       0.0      0.0       0.0       1      1      0.0

     Disconnect user_name
0           0.0   SBN0971
1           1.0   SBN0971
2           1.0   SBN0971
3           1.0   SBN0971
4           0.0   SBN0971
..          ...       ...
444         0.0   SBN0971
445         1.0   SBN0971
446         0.0   SBN0971
447         0.0   SBN0971
448         0.0   SBN0971

[449 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      0.0       6.0       1      1        0
1    01-04-2010       2.0      0.0       0.0       1      1        0
2    01-04-2011       2.0      1.0      11.0       1      1        0
3    01-05-2010       7.0      0.0       6.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       5.0      0.0       9.0       1      1        0
342  12-30-2010       4.0      1.0       9.0       1      1        0
343  03-23-2010       0.0      0.0       0.0       1      1        0
344  04-12-2010       0.0      0.0       0.0       1      1        0
345  08-31-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SBQ0786
1             0   SBQ0786
2             0   SBQ0786
3             0   SBQ0786
4             0   SBQ0786
..          ...       ...
341           0   SBQ0786
342           0   SBQ0786
343           0   SBQ0786
344           0   SBQ0786
345           0   SBQ0786

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      0.0       2.0       1      1        0
342  12-27-2010       0.0      0.0       3.0       1      1        0
343  12-28-2010       1.0      0.0       2.0       1      1        0
344  12-29-2010       1.0      0.0       2.0       1      1        0
345  12-30-2010       1.0      0.0       2.0       1      1        0

     Disconnect user_name
0             0   SCB0534
1             0   SCB0534
2             0   SCB0534
3             0   SCB0534
4             0   SCB0534
..          ...       ...
341           0   SCB0534
342           0   SCB0534
343           0   SCB0534
344           0   SCB0534
345           0   SCB0534

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      1.0       8.0       1      1        0
1    01-04-2010       5.0      0.0      11.0       1      1        0
2    01-04-2011       1.0      1.0      14.0       1      1        0
3    01-05-2010       4.0      2.0       8.0       1      1        0
4    01-05-2011       9.0      1.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       8.0       1      1        0
342  12-27-2010       8.0      1.0       7.0       1      1        0
343  12-28-2010      10.0      0.0       6.0       1      1        0
344  12-29-2010       5.0      0.0      11.0       1      1        0
345  12-30-2010       8.0      0.0       8.0       1      1        0

     Disconnect user_name
0             0   SCF0608
1             0   SCF0608
2             0   SCF0608
3             0   SCF0608
4             0   SCF0608
..          ...       ...
341           0   SCF0608
342           0   SCF0608
343           0   SCF0608
344           0   SCF0608
345           0   SCF0608

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1      1.0
1    01-04-2010       1.0      0.0       2.0       1      1      1.0
2    01-04-2011       1.0      0.0       2.0       1      1      2.0
3    01-05-2010       1.0      0.0       2.0       1      1      2.0
4    01-05-2011       1.0      1.0       1.0       1      1      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      1.0       2.0       2      2      2.0
342  12-29-2010       2.0      0.0       0.0       1      1      1.0
343  12-30-2010       0.0      0.0       2.0       1      1      1.0
344  02-24-2010       0.0      0.0       0.0       1      1      2.0
345  03-29-2010       0.0      0.0       0.0       2      2      2.0

     Disconnect user_name
0           1.0   SCP0130
1           1.0   SCP0130
2           2.0   SCP0130
3           2.0   SCP0130
4           3.0   SCP0130
..          ...       ...
341         2.0   SCP0130
342         1.0   SCP0130
343         1.0   SCP0130
344         2.0   SCP0130
345         2.0   SCP0130

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       2      2        0
1    01-04-2010       6.0      0.0       3.0       1      2        0
2    01-04-2011       2.0      1.0       6.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       2.0      0.0       7.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      1.0       5.0       1      2        0
342  12-27-2010       4.0      0.0       5.0       1      2        0
343  12-28-2010       2.0      0.0       4.0       2      2        0
344  12-29-2010       3.0      1.0       5.0       1      2        0
345  12-30-2010       4.0      0.0       5.0       1      2        0

     Disconnect user_name
0             0   SDB0106
1             0   SDB0106
2             0   SDB0106
3             0   SDB0106
4             0   SDB0106
..          ...       ...
341           0   SDB0106
342           0   SDB0106
343           0   SDB0106
344           0   SDB0106
345           0   SDB0106

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0       1      1        0
1    01-04-2010       3.0      1.0       7.0       1      1        0
2    01-04-2011       4.0      1.0       6.0       1      1        0
3    01-05-2010       3.0      0.0       8.0       1      1        0
4    01-05-2011       5.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       5.0       1      1        0
342  12-27-2010       4.0      1.0       6.0       1      1        0
343  12-28-2010       7.0      0.0       4.0       1      1        0
344  12-29-2010       4.0      0.0       6.0       1      1        0
345  12-30-2010       8.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   SDF0017
1             0   SDF0017
2             0   SDF0017
3             0   SDF0017
4             0   SDF0017
..          ...       ...
341           0   SDF0017
342           0   SDF0017
343           0   SDF0017
344           0   SDF0017
345           0   SDF0017

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       6.0       1      1        0
1    01-04-2010       6.0      1.0       8.0       1      2        0
2    01-04-2011       4.0      0.0      11.0       1      2        0
3    01-05-2010       6.0      1.0       6.0       1      2        0
4    01-05-2011       6.0      0.0       9.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      2.0       7.0       1      1        0
342  12-29-2010       2.0      1.0      11.0       1      2        0
343  12-30-2010       8.0      0.0       7.0       1      2        0
344  03-07-2011       0.0      0.0       0.0       1      1        0
345  03-09-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SDO0170
1             0   SDO0170
2             0   SDO0170
3             0   SDO0170
4             0   SDO0170
..          ...       ...
341           0   SDO0170
342           0   SDO0170
343           0   SDO0170
344           0   SDO0170
345           0   SDO0170

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0     2.0    2.0        0
1    01-04-2010       1.0      0.0       2.0     2.0    3.0        0
2    01-04-2011       1.0      0.0       0.0     1.0    2.0        0
3    01-05-2010       1.0      0.0       2.0     1.0    2.0        0
4    01-05-2011       1.0      1.0       1.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
345  01-08-2011       0.0      0.0       0.0     1.0    0.0        0
346  02-06-2010       0.0      0.0       0.0     1.0    0.0        0
347  02-26-2011       0.0      0.0       0.0     1.0    1.0        0
348  06-07-2010       0.0      0.0       0.0     2.0    2.0        0
349  11-13-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   SED0886
1             0   SED0886
2             0   SED0886
3             0   SED0886
4             0   SED0886
..          ...       ...
345           0   SED0886
346           0   SED0886
347           0   SED0886
348           0   SED0886
349           0   SED0886

[350 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      1.0       3.0       1      1        0
1    01-05-2010       2.0      0.0       7.0       1      1        0
2    01-06-2010       3.0      1.0       5.0       1      1        0
3    01-07-2010       1.0      0.0       0.0       1      1        0
4    01-08-2010       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
171  09-03-2010       3.0      0.0       6.0       1      1        0
172  09-07-2010       5.0      0.0       4.0       1      1        0
173  09-08-2010       6.0      0.0       3.0       1      1        0
174  09-09-2010       3.0      1.0       5.0       1      1        0
175  09-10-2010       4.0      1.0       4.0       1      1        0

     Disconnect user_name
0             0   SEJ0677
1             0   SEJ0677
2             0   SEJ0677
3             0   SEJ0677
4             0   SEJ0677
..          ...       ...
171           0   SEJ0677
172           0   SEJ0677
173           0   SEJ0677
174           0   SEJ0677
175           0   SEJ0677

[176 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       6.0       1      1        0
2    01-04-2011       5.0      0.0       6.0       1      1        0
3    01-05-2010       4.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       5.0       1      1        0
342  12-28-2010       4.0      2.0       5.0       1      1        0
343  12-29-2010       4.0      0.0       7.0       1      1        0
344  12-30-2010       6.0      0.0       5.0       1      1        0
345  07-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SER0165
1             0   SER0165
2             0   SER0165
3             0   SER0165
4             0   SER0165
..          ...       ...
341           0   SER0165
342           0   SER0165
343           0   SER0165
344           0   SER0165
345           0   SER0165

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      11.0      0.0       4.0       1      2        0
1    01-04-2010       5.0      1.0       9.0       1      2        0
2    01-04-2011      11.0      0.0       4.0       1      2        0
3    01-05-2010       7.0      0.0       8.0       1      2        0
4    01-05-2011       9.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       8.0       1      2        0
342  12-28-2010      11.0      1.0       3.0       1      2        0
343  12-29-2010       3.0      2.0      10.0       1      2        0
344  12-30-2010      10.0      0.0       5.0       1      2        0
345  04-07-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SES0477
1             0   SES0477
2             0   SES0477
3             0   SES0477
4             0   SES0477
..          ...       ...
341           0   SES0477
342           0   SES0477
343           0   SES0477
344           0   SES0477
345           0   SES0477

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       2      3        0
1    01-04-2010       0.0      0.0       1.0       2      3        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       0.0      0.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       0.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-25-2010       0.0      0.0       0.0       1      2        0
342  09-08-2010       0.0      0.0       0.0       1      2        0
343  10-27-2010       0.0      0.0       0.0       2      3        0
344  11-22-2010       0.0      0.0       0.0       1      1        0
345  11-24-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SGB0140
1             0   SGB0140
2             0   SGB0140
3             0   SGB0140
4             0   SGB0140
..          ...       ...
341           0   SGB0140
342           0   SGB0140
343           0   SGB0140
344           0   SGB0140
345           0   SGB0140

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       8.0       1      1        0
1    01-04-2010       8.0      1.0       5.0       1      2        0
2    01-04-2011       8.0      0.0       6.0       1      2        0
3    01-05-2010       9.0      1.0       4.0       1      2        0
4    01-05-2011       2.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       8.0       1      2        0
342  12-27-2010       3.0      1.0       9.0       1      2        0
343  12-28-2010      11.0      0.0       3.0       1      2        0
344  12-29-2010       8.0      1.0       5.0       1      2        0
345  12-30-2010       5.0      1.0       8.0       1      2        0

     Disconnect user_name
0             0   SGG0787
1             0   SGG0787
2             0   SGG0787
3             0   SGG0787
4             0   SGG0787
..          ...       ...
341           0   SGG0787
342           0   SGG0787
343           0   SGG0787
344           0   SGG0787
345           0   SGG0787

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       5.0       1      2      4.0
1    01-04-2010       3.0      1.0       7.0       1      2      2.0
2    01-04-2011       0.0      0.0       9.0       1      2      4.0
3    01-05-2010       3.0      2.0       6.0       1      2      4.0
4    01-05-2011       2.0      1.0       2.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      0.0       5.0       1      2      4.0
342  12-28-2010       4.0      1.0       5.0       1      1      5.0
343  12-29-2010       3.0      0.0       8.0       1      2      4.0
344  12-30-2010       3.0      1.0       7.0       1      2      4.0
345  01-18-2010       0.0      0.0       0.0       1      1      3.0

     Disconnect user_name
0           4.0   SGM0021
1           2.0   SGM0021
2           4.0   SGM0021
3           4.0   SGM0021
4           3.0   SGM0021
..          ...       ...
341         4.0   SGM0021
342         5.0   SGM0021
343         4.0   SGM0021
344         4.0   SGM0021
345         3.0   SGM0021

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      1        0
1    01-04-2010       7.0      0.0       2.0       1      1        0
2    01-04-2011       6.0      1.0       2.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0       3.0       1      1        0
342  12-27-2010       0.0      1.0       8.0       1      1        0
343  12-28-2010       6.0      0.0       3.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   SGS0268
1             0   SGS0268
2             0   SGS0268
3             0   SGS0268
4             0   SGS0268
..          ...       ...
341           0   SGS0268
342           0   SGS0268
343           0   SGS0268
344           0   SGS0268
345           0   SGS0268

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       0.0      0.0       3.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  01-19-2011       0.0      0.0       0.0       1      1        0
345  01-31-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SHR0334
1             0   SHR0334
2             0   SHR0334
3             0   SHR0334
4             0   SHR0334
..          ...       ...
341           0   SHR0334
342           0   SHR0334
343           0   SHR0334
344           0   SHR0334
345           0   SHR0334

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       0.0      0.0       1.0       1      1        0
1    01-04-2011       0.0      0.0       1.0       1      1        0
2    01-05-2010       0.0      0.0       1.0       1      1        0
3    01-05-2011       1.0      0.0       0.0       1      1        0
4    01-06-2010       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  07-29-2010       0.0      0.0       0.0       1      1        0
342  10-11-2010       0.0      0.0       0.0       1      1        0
343  11-24-2010       0.0      0.0       0.0       1      1        0
344  11-30-2010       0.0      0.0       0.0       1      1        0
345  12-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SHW0578
1             0   SHW0578
2             0   SHW0578
3             0   SHW0578
4             0   SHW0578
..          ...       ...
341           0   SHW0578
342           0   SHW0578
343           0   SHW0578
344           0   SHW0578
345           0   SHW0578

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      2.0       7.0       1      1        0
1    01-04-2010       5.0      1.0       8.0       1      1        0
2    01-04-2011       5.0      0.0       8.0       1      1        0
3    01-05-2010       6.0      0.0       8.0       1      1        0
4    01-05-2011       6.0      1.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0      10.0       1      1        0
342  12-28-2010       4.0      2.0       8.0       1      1        0
343  12-29-2010       5.0      1.0       8.0       1      1        0
344  12-30-2010       9.0      0.0       5.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SIJ0661
1             0   SIJ0661
2             0   SIJ0661
3             0   SIJ0661
4             0   SIJ0661
..          ...       ...
341           0   SIJ0661
342           0   SIJ0661
343           0   SIJ0661
344           0   SIJ0661
345           0   SIJ0661

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       2      2        0
1    01-04-2010       2.0      0.0       1.0       2      2        0
2    01-04-2011       3.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      0.0       3.0       1      1        0
342  01-27-2010       0.0      0.0       0.0       2      2        0
343  04-23-2010       0.0      0.0       0.0       1      1        0
344  05-07-2010       0.0      0.0       0.0       1      1        0
345  05-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SJC0333
1             0   SJC0333
2             0   SJC0333
3             0   SJC0333
4             0   SJC0333
..          ...       ...
341           0   SJC0333
342           0   SJC0333
343           0   SJC0333
344           0   SJC0333
345           0   SJC0333

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       8.0       1      1        0
1    01-04-2010       6.0      1.0       3.0       1      1        0
2    01-04-2011       7.0      0.0       3.0       1      1        0
3    01-05-2010       3.0      0.0       7.0       1      1        0
4    01-05-2011       5.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      1.0       3.0       1      1        0
342  12-28-2010       8.0      0.0       2.0       1      1        0
343  12-29-2010       3.0      0.0       7.0       1      1        0
344  12-30-2010       1.0      0.0       9.0       1      1        0
345  05-06-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SJF0094
1             0   SJF0094
2             0   SJF0094
3             0   SJF0094
4             0   SJF0094
..          ...       ...
341           0   SJF0094
342           0   SJF0094
343           0   SJF0094
344           0   SJF0094
345           0   SJF0094

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       5.0       1      2      0.0
1    01-04-2010       1.0      0.0      13.0       2      3      0.0
2    01-04-2011       2.0      0.0       4.0       1      2      1.0
3    01-05-2010       7.0      0.0       7.0       1      2      0.0
4    01-05-2011       6.0      1.0       7.0       2      3      1.0
..          ...       ...      ...       ...     ...    ...      ...
348  12-27-2010       4.0      0.0      10.0       1      2      0.0
349  12-28-2010       7.0      0.0       7.0       1      2      0.0
350  12-29-2010       1.0      0.0      13.0       2      2      0.0
351  12-30-2010       7.0      0.0       7.0       1      2      1.0
352  08-30-2010       0.0      0.0       0.0       1      2      2.0

     Disconnect user_name
0           0.0   SJO0209
1           0.0   SJO0209
2           1.0   SJO0209
3           0.0   SJO0209
4           1.0   SJO0209
..          ...       ...
348         0.0   SJO0209
349         0.0   SJO0209
350         0.0   SJO0209
351         1.0   SJO0209
352         2.0   SJO0209

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      1.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-01-2010       0.0      0.0       0.0       1      1        0
342  02-01-2011       0.0      0.0       0.0       1      1        0
343  03-31-2011       0.0      0.0       0.0       1      1        0
344  08-17-2010       0.0      0.0       0.0       1      1        0
345  09-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SJW0451
1             0   SJW0451
2             0   SJW0451
3             0   SJW0451
4             0   SJW0451
..          ...       ...
341           0   SJW0451
342           0   SJW0451
343           0   SJW0451
344           0   SJW0451
345           0   SJW0451

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      0.0       3.0       1      1        0
342  02-17-2010       0.0      0.0       0.0       1      1        0
343  02-24-2010       0.0      0.0       0.0       1      1        0
344  03-17-2011       0.0      0.0       0.0       1      1        0
345  04-01-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SKG0759
1             0   SKG0759
2             0   SKG0759
3             0   SKG0759
4             0   SKG0759
..          ...       ...
341           0   SKG0759
342           0   SKG0759
343           0   SKG0759
344           0   SKG0759
345           0   SKG0759

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       9.0       1      1        0
1    01-04-2010       6.0      1.0      10.0       1      1        0
2    01-04-2011       4.0      1.0       7.0       1      1        0
3    01-05-2010       3.0      1.0      12.0       1      1        0
4    01-05-2011       7.0      0.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0      13.0       1      1        0
342  12-27-2010       9.0      0.0       9.0       1      1        0
343  12-28-2010      10.0      0.0       8.0       1      1        0
344  12-29-2010       5.0      2.0      11.0       1      1        0
345  12-30-2010       8.0      1.0       9.0       1      1        0

     Disconnect user_name
0             0   SLB0049
1             0   SLB0049
2             0   SLB0049
3             0   SLB0049
4             0   SLB0049
..          ...       ...
341           0   SLB0049
342           0   SLB0049
343           0   SLB0049
344           0   SLB0049
345           0   SLB0049

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       2.0      0.0       1.0       1      1        0
342  12-30-2010       0.0      1.0       2.0       1      1        0
343  01-25-2011       0.0      0.0       0.0       1      1        0
344  03-16-2011       0.0      0.0       0.0       1      1        0
345  05-02-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SLP0762
1             0   SLP0762
2             0   SLP0762
3             0   SLP0762
4             0   SLP0762
..          ...       ...
341           0   SLP0762
342           0   SLP0762
343           0   SLP0762
344           0   SLP0762
345           0   SLP0762

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-05-2010       0.0      0.0       2.0       1      1        0
1    01-06-2010       1.0      0.0       2.0       1      1        0
2    01-07-2010       0.0      0.0       3.0       1      1        0
3    01-08-2010       1.0      0.0       2.0       1      1        0
4    01-11-2010       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
168  09-03-2010       1.0      0.0       2.0       1      1        0
169  09-07-2010       1.0      0.0       2.0       1      1        0
170  01-04-2010       0.0      0.0       0.0       1      1        0
171  03-01-2010       0.0      0.0       0.0       1      1        0
172  08-12-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SLT0907
1             0   SLT0907
2             0   SLT0907
3             0   SLT0907
4             0   SLT0907
..          ...       ...
168           0   SLT0907
169           0   SLT0907
170           0   SLT0907
171           0   SLT0907
172           0   SLT0907

[173 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       1.0      1.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       5.0      0.0       4.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       0.0      0.0       6.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       4.0      1.0       4.0       1      1        0

     Disconnect user_name
0             0   SMB0804
1             0   SMB0804
2             0   SMB0804
3             0   SMB0804
4             0   SMB0804
..          ...       ...
341           0   SMB0804
342           0   SMB0804
343           0   SMB0804
344           0   SMB0804
345           0   SMB0804

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       0.0      0.0       1.0       2      2        0
1    01-02-2010       0.0      0.0       1.0       1      1        0
2    01-02-2011       1.0      0.0       0.0       1      1        0
3    01-03-2010       0.0      0.0       1.0       1      2        0
4    01-03-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
475  06-27-2010       0.0      0.0       0.0       1      2        0
476  07-31-2010       0.0      0.0       0.0       1      1        0
477  08-16-2010       0.0      0.0       0.0       2      2        0
478  09-28-2010       0.0      0.0       0.0       1      2        0
479  12-20-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SMH0291
1             0   SMH0291
2             0   SMH0291
3             0   SMH0291
4             0   SMH0291
..          ...       ...
475           0   SMH0291
476           0   SMH0291
477           0   SMH0291
478           0   SMH0291
479           0   SMH0291

[480 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       1      1        0
1    01-04-2010       2.0      1.0       6.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       2.0      0.0       7.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       5.0       1      1        0
342  12-27-2010       4.0      0.0       5.0       1      1        0
343  12-28-2010       2.0      1.0       6.0       1      1        0
344  12-29-2010       3.0      0.0       6.0       1      1        0
345  12-30-2010       3.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   SMW0084
1             0   SMW0084
2             0   SMW0084
3             0   SMW0084
4             0   SMW0084
..          ...       ...
341           0   SMW0084
342           0   SMW0084
343           0   SMW0084
344           0   SMW0084
345           0   SMW0084

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       3.0       2      2      1.0
1    01-04-2010       5.0      0.0       4.0       1      1      3.0
2    01-04-2011       6.0      0.0       3.0       1      2      0.0
3    01-05-2010       2.0      0.0       7.0       1      2      0.0
4    01-05-2011       4.0      0.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      1.0       4.0       1      2      1.0
342  12-27-2010       2.0      0.0       6.0       1      2      1.0
343  12-28-2010       3.0      0.0       6.0       2      2      2.0
344  12-29-2010       3.0      0.0       6.0       1      2      1.0
345  12-30-2010       3.0      0.0       2.0       1      2      1.0

     Disconnect user_name
0           1.0   SMY0792
1           3.0   SMY0792
2           0.0   SMY0792
3           0.0   SMY0792
4           0.0   SMY0792
..          ...       ...
341         1.0   SMY0792
342         1.0   SMY0792
343         2.0   SMY0792
344         1.0   SMY0792
345         1.0   SMY0792

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1      1.0
1    01-04-2010       0.0      0.0       3.0       1      1      0.0
2    01-04-2011       1.0      0.0       1.0       1      1      0.0
3    01-05-2010       0.0      0.0       3.0       1      1      0.0
4    01-05-2011       0.0      1.0       2.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
295  12-27-2010       0.0      0.0       3.0       1      1      1.0
296  12-28-2010       1.0      1.0       1.0       1      1      0.0
297  12-29-2010       1.0      0.0       2.0       1      1      2.0
298  12-30-2010       2.0      0.0       1.0       1      1      1.0
299  09-17-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           1.0   SNC0187
1           0.0   SNC0187
2           0.0   SNC0187
3           0.0   SNC0187
4           0.0   SNC0187
..          ...       ...
295         1.0   SNC0187
296         0.0   SNC0187
297         2.0   SNC0187
298         1.0   SNC0187
299         1.0   SNC0187

[300 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       1      1        0
1    01-04-2010       4.0      0.0       7.0       1      1        0
2    01-04-2011       6.0      0.0       5.0       1      1        0
3    01-05-2010       1.0      0.0      10.0       1      1        0
4    01-05-2011       2.0      2.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      1.0       2.0       1      1        0
342  12-27-2010       7.0      1.0       3.0       1      1        0
343  12-28-2010       4.0      0.0       7.0       1      1        0
344  12-29-2010       8.0      0.0       3.0       1      1        0
345  12-30-2010       5.0      0.0       6.0       1      1        0

     Disconnect user_name
0             0   SNS0129
1             0   SNS0129
2             0   SNS0129
3             0   SNS0129
4             0   SNS0129
..          ...       ...
341           0   SNS0129
342           0   SNS0129
343           0   SNS0129
344           0   SNS0129
345           0   SNS0129

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      1.0       3.0       4      4        0
1    01-05-2010       3.0      1.0       6.0       4      4        0
2    01-06-2010       4.0      1.0       6.0       2      2        0
3    01-07-2010       3.0      1.0       7.0       4      4        0
4    01-08-2010       4.0      0.0       6.0       4      4        0
..          ...       ...      ...       ...     ...    ...      ...
221  11-15-2010       7.0      0.0       4.0       4      4        0
222  11-16-2010       5.0      1.0       5.0       5      5        0
223  11-17-2010       6.0      1.0       4.0       2      2        0
224  11-18-2010       2.0      1.0       8.0       4      4        0
225  11-19-2010       5.0      0.0       6.0       4      4        0

     Disconnect user_name
0             0   SOB0360
1             0   SOB0360
2             0   SOB0360
3             0   SOB0360
4             0   SOB0360
..          ...       ...
221           0   SOB0360
222           0   SOB0360
223           0   SOB0360
224           0   SOB0360
225           0   SOB0360

[226 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-05-2011       0.0      0.0       0.0       1      1        0
342  04-11-2011       0.0      0.0       0.0       1      1        0
343  05-28-2010       0.0      0.0       0.0       1      1        0
344  10-01-2010       0.0      0.0       0.0       1      1        0
345  11-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SOB0586
1             0   SOB0586
2             0   SOB0586
3             0   SOB0586
4             0   SOB0586
..          ...       ...
341           0   SOB0586
342           0   SOB0586
343           0   SOB0586
344           0   SOB0586
345           0   SOB0586

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       7.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       3.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       7.0      0.0       2.0       1      1        0
342  12-29-2010       5.0      0.0       4.0       1      1        0
343  12-30-2010       5.0      0.0       4.0       1      1        0
344  04-19-2010       0.0      0.0       0.0       1      1        0
345  07-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SOF0808
1             0   SOF0808
2             0   SOF0808
3             0   SOF0808
4             0   SOF0808
..          ...       ...
341           0   SOF0808
342           0   SOF0808
343           0   SOF0808
344           0   SOF0808
345           0   SOF0808

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       2.0      0.0       6.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       2.0      0.0       6.0       1      1        0
342  12-28-2010       3.0      0.0       6.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       4.0      0.0       5.0       1      1        0
345  10-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SOG0411
1             0   SOG0411
2             0   SOG0411
3             0   SOG0411
4             0   SOG0411
..          ...       ...
341           0   SOG0411
342           0   SOG0411
343           0   SOG0411
344           0   SOG0411
345           0   SOG0411

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       6.0     1.0    3.0        0
1    01-04-2010       8.0      1.0       2.0     1.0    2.0        0
2    01-04-2011       3.0      0.0       8.0     2.0    2.0        0
3    01-05-2010       7.0      0.0       4.0     1.0    2.0        0
4    01-05-2011       1.0      1.0       9.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
350  03-13-2010       0.0      0.0       0.0     1.0    1.0        0
351  05-14-2011       0.0      0.0       0.0     1.0    0.0        0
352  05-15-2010       0.0      0.0       0.0     1.0    1.0        0
353  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
354  07-17-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   SPA0141
1             0   SPA0141
2             0   SPA0141
3             0   SPA0141
4             0   SPA0141
..          ...       ...
350           0   SPA0141
351           0   SPA0141
352           0   SPA0141
353           0   SPA0141
354           0   SPA0141

[355 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       9.0     1.0    2.0        0
1    01-04-2010       3.0      0.0       8.0     2.0    2.0        0
2    01-04-2011       3.0      2.0       6.0     1.0    2.0        0
3    01-05-2010       7.0      0.0       4.0     1.0    2.0        0
4    01-05-2011       3.0      0.0       8.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
360  02-19-2011       0.0      0.0       0.0     1.0    1.0        0
361  04-30-2011       0.0      0.0       0.0     1.0    0.0        0
362  10-23-2010       0.0      0.0       0.0     1.0    1.0        0
363  11-27-2010       0.0      0.0       0.0     1.0    1.0        0
364  12-04-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   SRH0155
1             0   SRH0155
2             0   SRH0155
3             0   SRH0155
4             0   SRH0155
..          ...       ...
360           0   SRH0155
361           0   SRH0155
362           0   SRH0155
363           0   SRH0155
364           0   SRH0155

[365 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       1.0      0.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       8.0       1      1        0
342  12-29-2010       1.0      0.0       8.0       1      1        0
343  12-30-2010       2.0      0.0       7.0       1      1        0
344  01-13-2010       0.0      0.0       0.0       1      1        0
345  04-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SRS0231
1             0   SRS0231
2             0   SRS0231
3             0   SRS0231
4             0   SRS0231
..          ...       ...
341           0   SRS0231
342           0   SRS0231
343           0   SRS0231
344           0   SRS0231
345           0   SRS0231

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      2        0
2    01-04-2011       3.0      0.0       5.0       1      2        0
3    01-05-2010       2.0      0.0       7.0       1      2        0
4    01-06-2010       6.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       5.0      0.0       4.0       1      2        0
342  01-05-2011       0.0      0.0       0.0       1      2        0
343  03-16-2011       0.0      0.0       0.0       1      2        0
344  11-09-2010       0.0      0.0       0.0       1      2        0
345  12-15-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SSG0250
1             0   SSG0250
2             0   SSG0250
3             0   SSG0250
4             0   SSG0250
..          ...       ...
341           0   SSG0250
342           0   SSG0250
343           0   SSG0250
344           0   SSG0250
345           0   SSG0250

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      2        0
2    01-04-2011       5.0      0.0       4.0       1      2        0
3    01-05-2010       4.0      0.0       3.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      2        0
342  12-28-2010       2.0      1.0       6.0       2      3        0
343  12-29-2010       2.0      2.0       4.0       1      2        0
344  12-30-2010       3.0      3.0       3.0       1      2        0
345  05-05-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   SSH0799
1             0   SSH0799
2             0   SSH0799
3             0   SSH0799
4             0   SSH0799
..          ...       ...
341           0   SSH0799
342           0   SSH0799
343           0   SSH0799
344           0   SSH0799
345           0   SSH0799

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       3.0      0.0       0.0     1.0    2.0        0
1    01-02-2011       2.0      0.0       1.0     1.0    2.0        0
2    01-03-2010       3.0      0.0       0.0     1.0    2.0        0
3    01-03-2011       0.0      0.0       3.0     1.0    2.0        0
4    01-04-2010       2.0      0.0       1.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
455  05-08-2010       0.0      0.0       0.0     1.0    2.0        0
456  08-16-2010       0.0      0.0       0.0     1.0    2.0        0
457  09-06-2010       0.0      0.0       0.0     1.0    1.0        0
458  09-29-2010       0.0      0.0       0.0     1.0    2.0        0
459  11-20-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   SSJ0784
1             0   SSJ0784
2             0   SSJ0784
3             0   SSJ0784
4             0   SSJ0784
..          ...       ...
455           0   SSJ0784
456           0   SSJ0784
457           0   SSJ0784
458           0   SSJ0784
459           0   SSJ0784

[460 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      0.0       6.0       1      1        0
1    01-05-2010       2.0      0.0       6.0       1      1        0
2    01-06-2010       2.0      0.0       6.0       1      1        0
3    01-07-2010       5.0      0.0       4.0       1      1        0
4    01-08-2010       2.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
191  10-05-2010       4.0      0.0       4.0       1      1        0
192  10-06-2010       5.0      0.0       4.0       1      1        0
193  10-07-2010       4.0      1.0       4.0       1      1        0
194  10-08-2010       2.0      2.0       5.0       1      1        0
195  08-13-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SSR0278
1             0   SSR0278
2             0   SSR0278
3             0   SSR0278
4             0   SSR0278
..          ...       ...
191           0   SSR0278
192           0   SSR0278
193           0   SSR0278
194           0   SSR0278
195           0   SSR0278

[196 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       3.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      1        0
342  12-28-2010       0.0      0.0       3.0       1      1        0
343  12-29-2010       0.0      0.0       3.0       1      1        0
344  12-30-2010       0.0      0.0       3.0       1      1        0
345  04-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SSS0345
1             0   SSS0345
2             0   SSS0345
3             0   SSS0345
4             0   SSS0345
..          ...       ...
341           0   SSS0345
342           0   SSS0345
343           0   SSS0345
344           0   SSS0345
345           0   SSS0345

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       3.0      1.0       4.0       1      1        0
4    01-05-2011       3.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       4.0      0.0       5.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       3.0      1.0       4.0       1      1        0
344  12-29-2010       6.0      0.0       3.0       1      1        0
345  12-30-2010       0.0      0.0       3.0       1      1        0

     Disconnect user_name
0             0   SVL0803
1             0   SVL0803
2             0   SVL0803
3             0   SVL0803
4             0   SVL0803
..          ...       ...
341           0   SVL0803
342           0   SVL0803
343           0   SVL0803
344           0   SVL0803
345           0   SVL0803

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       4.0       1      1        0
1    01-04-2010       5.0      1.0       3.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      2.0       5.0       1      1        0
342  12-27-2010       0.0      0.0       9.0       1      1        0
343  12-28-2010       4.0      1.0       4.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       2.0      1.0       6.0       1      1        0

     Disconnect user_name
0             0   SVL0940
1             0   SVL0940
2             0   SVL0940
3             0   SVL0940
4             0   SVL0940
..          ...       ...
341           0   SVL0940
342           0   SVL0940
343           0   SVL0940
344           0   SVL0940
345           0   SVL0940

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       1      2        0
1    01-04-2010       4.0      2.0       8.0       2      3        0
2    01-04-2011       3.0      0.0      12.0       1      2        0
3    01-05-2010      10.0      0.0       5.0       1      2        0
4    01-05-2011      10.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010      12.0      0.0       3.0       1      2        0
342  12-27-2010       9.0      2.0       4.0       1      2        0
343  12-28-2010       7.0      0.0       8.0       2      3        0
344  12-29-2010       5.0      2.0       8.0       1      2        0
345  12-30-2010       9.0      0.0       6.0       1      2        0

     Disconnect user_name
0             0   SVS0871
1             0   SVS0871
2             0   SVS0871
3             0   SVS0871
4             0   SVS0871
..          ...       ...
341           0   SVS0871
342           0   SVS0871
343           0   SVS0871
344           0   SVS0871
345           0   SVS0871

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       0.0      0.0       3.0       1      1        0
342  12-29-2010       1.0      0.0       0.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  03-14-2011       0.0      0.0       0.0       1      1        0
345  04-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   SXM0895
1             0   SXM0895
2             0   SXM0895
3             0   SXM0895
4             0   SXM0895
..          ...       ...
341           0   SXM0895
342           0   SXM0895
343           0   SXM0895
344           0   SXM0895
345           0   SXM0895

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-25-2010       0.0      0.0       0.0       1      1        0
342  08-05-2010       0.0      0.0       0.0       1      1        0
343  09-17-2010       0.0      0.0       0.0       1      1        0
344  10-26-2010       0.0      0.0       0.0       1      1        0
345  12-21-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TAC0300
1             0   TAC0300
2             0   TAC0300
3             0   TAC0300
4             0   TAC0300
..          ...       ...
341           0   TAC0300
342           0   TAC0300
343           0   TAC0300
344           0   TAC0300
345           0   TAC0300

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       4.0      0.0       4.0       1      2      0.0
1    01-05-2010       4.0      0.0       5.0       1      2      0.0
2    01-06-2010       2.0      0.0       7.0       1      1      0.0
3    01-07-2010       3.0      1.0       5.0       1      2      0.0
4    01-08-2010       3.0      2.0       4.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
221  11-15-2010       4.0      1.0       4.0       1      2      0.0
222  11-16-2010       3.0      1.0       5.0       1      2      0.0
223  11-17-2010       6.0      0.0       3.0       1      2      0.0
224  11-18-2010       2.0      0.0       0.0       1      1      0.0
225  10-23-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           0.0   TAP0551
1           0.0   TAP0551
2           0.0   TAP0551
3           0.0   TAP0551
4           0.0   TAP0551
..          ...       ...
221         0.0   TAP0551
222         0.0   TAP0551
223         0.0   TAP0551
224         0.0   TAP0551
225         1.0   TAP0551

[226 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       0.0      1.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-15-2010       0.0      0.0       0.0       1      1        0
342  05-04-2010       0.0      0.0       0.0       1      1        0
343  07-07-2010       0.0      0.0       0.0       1      1        0
344  08-17-2010       0.0      0.0       0.0       1      1        0
345  10-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TBT0461
1             0   TBT0461
2             0   TBT0461
3             0   TBT0461
4             0   TBT0461
..          ...       ...
341           0   TBT0461
342           0   TBT0461
343           0   TBT0461
344           0   TBT0461
345           0   TBT0461

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       7.0       1      1        0
1    01-04-2010       4.0      1.0       6.0       1      1        0
2    01-04-2011       3.0      1.0       7.0       1      1        0
3    01-05-2010       3.0      0.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       8.0       1      1        0
342  12-27-2010       2.0      1.0       8.0       1      1        0
343  12-28-2010       4.0      0.0       7.0       1      1        0
344  12-29-2010       2.0      0.0       9.0       1      1        0
345  12-30-2010       4.0      0.0       7.0       1      1        0

     Disconnect user_name
0             0   TCD0009
1             0   TCD0009
2             0   TCD0009
3             0   TCD0009
4             0   TCD0009
..          ...       ...
341           0   TCD0009
342           0   TCD0009
343           0   TCD0009
344           0   TCD0009
345           0   TCD0009

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      2        0
1    01-04-2010       0.0      0.0       1.0       1      2        0
2    01-04-2011       0.0      0.0       1.0       1      2        0
3    01-05-2010       1.0      0.0       0.0       1      2        0
4    01-05-2011       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-01-2011       0.0      0.0       0.0       1      2        0
342  05-10-2010       0.0      0.0       0.0       1      2        0
343  07-15-2010       0.0      0.0       0.0       1      2        0
344  08-09-2010       0.0      0.0       0.0       2      3        0
345  11-17-2010       0.0      0.0       0.0       2      2        0

     Disconnect user_name
0             0   TDG0962
1             0   TDG0962
2             0   TDG0962
3             0   TDG0962
4             0   TDG0962
..          ...       ...
341           0   TDG0962
342           0   TDG0962
343           0   TDG0962
344           0   TDG0962
345           0   TDG0962

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      3.0       4.0       1      1        0
1    01-04-2010       2.0      4.0       2.0       1      2        0
2    01-04-2011       1.0      6.0       2.0       1      2        0
3    01-05-2010       2.0      1.0       6.0       1      2        0
4    01-05-2011       6.0      1.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      2.0       2.0       1      2        0
342  12-28-2010       2.0      7.0       0.0       1      2        0
343  12-29-2010       2.0      2.0       5.0       1      2        0
344  12-30-2010       3.0      0.0       6.0       1      2        0
345  07-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   TDJ0998
1             0   TDJ0998
2             0   TDJ0998
3             0   TDJ0998
4             0   TDJ0998
..          ...       ...
341           0   TDJ0998
342           0   TDJ0998
343           0   TDJ0998
344           0   TDJ0998
345           0   TDJ0998

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       5.0      1.0       3.0       1      2      0.0
1    01-03-2010       4.0      1.0       4.0       1      2      1.0
2    01-03-2011       1.0      0.0       8.0       2      2      1.0
3    01-04-2010       3.0      1.0       5.0       1      2      0.0
4    01-04-2011       2.0      0.0       3.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
425  12-30-2010       4.0      2.0       3.0       1      2      0.0
426  12-31-2010       4.0      0.0       5.0       1      2      1.0
427  02-09-2011       0.0      0.0       0.0       2      3      1.0
428  03-14-2010       0.0      0.0       0.0       2      2      0.0
429  09-19-2010       0.0      0.0       0.0       2      2      0.0

     Disconnect user_name
0           0.0   TDS0984
1           1.0   TDS0984
2           1.0   TDS0984
3           0.0   TDS0984
4           1.0   TDS0984
..          ...       ...
425         0.0   TDS0984
426         1.0   TDS0984
427         1.0   TDS0984
428         0.0   TDS0984
429         0.0   TDS0984

[430 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      2        0
2    01-04-2011       6.0      0.0       3.0       1      2        0
3    01-05-2010       5.0      0.0       4.0       1      2        0
4    01-05-2011       3.0      1.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0       2.0       1      2        0
342  12-27-2010       2.0      0.0       7.0       1      2        0
343  12-28-2010       4.0      0.0       5.0       1      2        0
344  12-29-2010       4.0      0.0       5.0       1      2        0
345  12-30-2010       3.0      1.0       5.0       1      2        0

     Disconnect user_name
0             0   TEB0251
1             0   TEB0251
2             0   TEB0251
3             0   TEB0251
4             0   TEB0251
..          ...       ...
341           0   TEB0251
342           0   TEB0251
343           0   TEB0251
344           0   TEB0251
345           0   TEB0251

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      1.0       5.0       1      1        0
1    01-05-2010       3.0      1.0       5.0       1      1        0
2    01-06-2010       2.0      1.0       6.0       1      1        0
3    01-07-2010       5.0      2.0       2.0       1      1        0
4    01-08-2010       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
242  12-17-2010       5.0      0.0       4.0       1      1        0
243  12-20-2010       3.0      0.0       6.0       1      1        0
244  12-21-2010       2.0      2.0       5.0       1      1        0
245  12-22-2010       4.0      1.0       3.0       1      1        0
246  11-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TEM0093
1             0   TEM0093
2             0   TEM0093
3             0   TEM0093
4             0   TEM0093
..          ...       ...
242           0   TEM0093
243           0   TEM0093
244           0   TEM0093
245           0   TEM0093
246           0   TEM0093

[247 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       7.0       1      1        0
1    01-04-2010       6.0      0.0       5.0       1      1        0
2    01-04-2011       2.0      1.0       8.0       1      1        0
3    01-05-2010       2.0      2.0       7.0       1      1        0
4    01-05-2011       7.0      1.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      0.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       9.0       1      1        0
343  12-29-2010       5.0      1.0       5.0       1      1        0
344  12-30-2010       6.0      0.0       5.0       1      1        0
345  04-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TEM0977
1             0   TEM0977
2             0   TEM0977
3             0   TEM0977
4             0   TEM0977
..          ...       ...
341           0   TEM0977
342           0   TEM0977
343           0   TEM0977
344           0   TEM0977
345           0   TEM0977

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       5.0       2      2        0
1    01-04-2010       7.0      0.0       8.0       1      1        0
2    01-04-2011       6.0      1.0       8.0       1      1        0
3    01-05-2010       5.0      1.0       9.0       1      1        0
4    01-05-2011       7.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       8.0      1.0       6.0       1      1        0
342  12-28-2010      10.0      1.0       4.0       2      2        0
343  12-29-2010       6.0      1.0       8.0       1      1        0
344  12-30-2010       5.0      1.0       9.0       1      1        0
345  02-24-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TET0621
1             0   TET0621
2             0   TET0621
3             0   TET0621
4             0   TET0621
..          ...       ...
341           0   TET0621
342           0   TET0621
343           0   TET0621
344           0   TET0621
345           0   TET0621

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      1.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-07-2010       0.0      0.0       0.0       1      1        0
342  07-06-2010       0.0      0.0       0.0       1      1        0
343  09-10-2010       0.0      0.0       0.0       1      1        0
344  09-27-2010       0.0      0.0       0.0       1      1        0
345  10-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   THD0448
1             0   THD0448
2             0   THD0448
3             0   THD0448
4             0   THD0448
..          ...       ...
341           0   THD0448
342           0   THD0448
343           0   THD0448
344           0   THD0448
345           0   THD0448

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      1.0       3.0       1      1      8.0
1    01-04-2010       9.0      0.0       6.0       1      1      8.0
2    01-04-2011       6.0      0.0       9.0       1      1      8.0
3    01-05-2010       8.0      0.0       7.0       1      1      9.0
4    01-05-2011       7.0      0.0       8.0       1      1      8.0
..          ...       ...      ...       ...     ...    ...      ...
342  12-29-2010       8.0      2.0       4.0       1      1      8.0
343  12-30-2010       7.0      1.0       7.0       1      1      6.0
344  04-17-2010       0.0      0.0       0.0       1      1      0.0
345  05-20-2010       0.0      0.0       0.0       1      1      8.0
346  12-17-2010       0.0      0.0       0.0       1      1      7.0

     Disconnect user_name
0           8.0   THR0873
1           8.0   THR0873
2           8.0   THR0873
3           9.0   THR0873
4           8.0   THR0873
..          ...       ...
342         8.0   THR0873
343         6.0   THR0873
344         0.0   THR0873
345         8.0   THR0873
346         7.0   THR0873

[347 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-18-2011       0.0      0.0       0.0       1      1        0
342  04-27-2010       0.0      0.0       0.0       1      1        0
343  04-28-2011       0.0      0.0       0.0       1      1        0
344  05-07-2010       0.0      0.0       0.0       1      1        0
345  07-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TIW0299
1             0   TIW0299
2             0   TIW0299
3             0   TIW0299
4             0   TIW0299
..          ...       ...
341           0   TIW0299
342           0   TIW0299
343           0   TIW0299
344           0   TIW0299
345           0   TIW0299

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-25-2010       0.0      0.0       0.0       1      1        0
342  09-29-2010       0.0      0.0       0.0       1      1        0
343  10-11-2010       0.0      0.0       0.0       1      1        0
344  11-01-2010       0.0      0.0       0.0       1      1        0
345  11-16-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TJB0302
1             0   TJB0302
2             0   TJB0302
3             0   TJB0302
4             0   TJB0302
..          ...       ...
341           0   TJB0302
342           0   TJB0302
343           0   TJB0302
344           0   TJB0302
345           0   TJB0302

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      5.0       2.0       1      1        0
1    01-04-2010       0.0      6.0       3.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       3.0      3.0       3.0       1      1        0
4    01-05-2011       4.0      2.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      3.0       2.0       1      1        0
342  12-29-2010       5.0      1.0       3.0       1      1        0
343  12-30-2010       2.0      3.0       4.0       1      1        0
344  01-07-2011       0.0      0.0       0.0       1      1        0
345  01-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TJD0996
1             0   TJD0996
2             0   TJD0996
3             0   TJD0996
4             0   TJD0996
..          ...       ...
341           0   TJD0996
342           0   TJD0996
343           0   TJD0996
344           0   TJD0996
345           0   TJD0996

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  05-04-2010       0.0      0.0       0.0       1      1        0
342  05-20-2010       0.0      0.0       0.0       1      1        0
343  07-08-2010       0.0      0.0       0.0       1      1        0
344  11-30-2010       0.0      0.0       0.0       1      1        0
345  12-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TJG0582
1             0   TJG0582
2             0   TJG0582
3             0   TJG0582
4             0   TJG0582
..          ...       ...
341           0   TJG0582
342           0   TJG0582
343           0   TJG0582
344           0   TJG0582
345           0   TJG0582

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       0.0      0.0       3.0       1      1        0
342  01-26-2011       0.0      0.0       0.0       1      1        0
343  02-04-2010       0.0      0.0       0.0       1      1        0
344  06-25-2010       0.0      0.0       0.0       1      1        0
345  09-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TLH0648
1             0   TLH0648
2             0   TLH0648
3             0   TLH0648
4             0   TLH0648
..          ...       ...
341           0   TLH0648
342           0   TLH0648
343           0   TLH0648
344           0   TLH0648
345           0   TLH0648

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      2.0       5.0       1      1        0
1    01-04-2010       2.0      6.0       0.0       1      1        0
2    01-04-2011       0.0      2.0       7.0       1      1        0
3    01-05-2010       4.0      2.0       3.0       1      1        0
4    01-05-2011       0.0      9.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       1.0      6.0       1.0       1      1        0
343  12-29-2010       3.0      5.0       1.0       1      1        0
344  12-30-2010       2.0      1.0       6.0       1      1        0
345  11-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TLK0993
1             0   TLK0993
2             0   TLK0993
3             0   TLK0993
4             0   TLK0993
..          ...       ...
341           0   TLK0993
342           0   TLK0993
343           0   TLK0993
344           0   TLK0993
345           0   TLK0993

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       2.0      1.0       6.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      0.0       5.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       7.0       1      1        0
342  12-29-2010       3.0      0.0       6.0       1      1        0
343  12-30-2010       7.0      0.0       2.0       1      1        0
344  02-25-2011       0.0      0.0       0.0       1      1        0
345  12-06-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TLM0797
1             0   TLM0797
2             0   TLM0797
3             0   TLM0797
4             0   TLM0797
..          ...       ...
341           0   TLM0797
342           0   TLM0797
343           0   TLM0797
344           0   TLM0797
345           0   TLM0797

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      2.0       3.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       5.0      0.0       4.0       1      1        0
344  12-29-2010       3.0      1.0       5.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   TMA0069
1             0   TMA0069
2             0   TMA0069
3             0   TMA0069
4             0   TMA0069
..          ...       ...
341           0   TMA0069
342           0   TMA0069
343           0   TMA0069
344           0   TMA0069
345           0   TMA0069

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      1      0.0
1    01-05-2010       0.0      0.0       1.0       1      2      2.0
2    01-06-2010       1.0      0.0       0.0       1      1      1.0
3    01-07-2010       0.0      0.0       1.0       1      2      2.0
4    01-08-2010       0.0      0.0       1.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
235  03-09-2010       0.0      0.0       0.0       2      2      3.0
236  03-23-2010       0.0      0.0       0.0       2      2      3.0
237  08-10-2010       0.0      0.0       0.0       1      2      4.0
238  08-19-2010       0.0      0.0       0.0       1      2      1.0
239  09-22-2010       0.0      0.0       0.0       2      3      2.0

     Disconnect user_name
0           0.0   TNM0961
1           2.0   TNM0961
2           1.0   TNM0961
3           2.0   TNM0961
4           2.0   TNM0961
..          ...       ...
235         3.0   TNM0961
236         3.0   TNM0961
237         4.0   TNM0961
238         1.0   TNM0961
239         2.0   TNM0961

[240 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       4.0       2      3        0
1    01-04-2010       2.0      2.0       6.0       1      2        0
2    01-04-2011       2.0      2.0       7.0       1      2        0
3    01-05-2010       2.0      1.0       7.0       1      2        0
4    01-05-2011       4.0      2.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      6.0       4.0       1      2        0
342  12-30-2010       1.0      5.0       3.0       1      2        0
343  01-26-2011       0.0      0.0       0.0       1      1        0
344  03-17-2011       0.0      0.0       0.0       1      1        0
345  05-02-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   TOR0193
1             0   TOR0193
2             0   TOR0193
3             0   TOR0193
4             0   TOR0193
..          ...       ...
341           0   TOR0193
342           0   TOR0193
343           0   TOR0193
344           0   TOR0193
345           0   TOR0193

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      1.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-12-2010       0.0      0.0       0.0       1      1        0
342  02-16-2011       0.0      0.0       0.0       1      1        0
343  07-30-2010       0.0      0.0       0.0       1      1        0
344  11-01-2010       0.0      0.0       0.0       1      1        0
345  11-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TPH0474
1             0   TPH0474
2             0   TPH0474
3             0   TPH0474
4             0   TPH0474
..          ...       ...
341           0   TPH0474
342           0   TPH0474
343           0   TPH0474
344           0   TPH0474
345           0   TPH0474

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       9.0       1      1        0
1    01-04-2010       6.0      0.0       8.0       1      1        0
2    01-04-2011       9.0      1.0       4.0       1      1        0
3    01-05-2010       7.0      1.0       6.0       1      1        0
4    01-05-2011       6.0      0.0       8.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0      10.0       1      1        0
342  12-28-2010       7.0      1.0       6.0       1      1        0
343  12-29-2010       2.0      0.0      12.0       1      1        0
344  12-30-2010       1.0      0.0      13.0       1      1        0
345  01-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TQS0212
1             0   TQS0212
2             0   TQS0212
3             0   TQS0212
4             0   TQS0212
..          ...       ...
341           0   TQS0212
342           0   TQS0212
343           0   TQS0212
344           0   TQS0212
345           0   TQS0212

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       6.0     1.0    1.0        0
1    01-04-2010       3.0      0.0       6.0     1.0    1.0        0
2    01-04-2011       3.0      4.0       2.0     1.0    1.0        0
3    01-05-2010       1.0      1.0       7.0     1.0    1.0        0
4    01-05-2011       1.0      0.0       8.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      0.0       4.0     1.0    1.0        0
342  12-28-2010       4.0      0.0       5.0     1.0    1.0        0
343  12-29-2010       6.0      0.0       3.0     1.0    1.0        0
344  12-30-2010       4.0      0.0       5.0     1.0    1.0        0
345  04-15-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   TRK0914
1             0   TRK0914
2             0   TRK0914
3             0   TRK0914
4             0   TRK0914
..          ...       ...
341           0   TRK0914
342           0   TRK0914
343           0   TRK0914
344           0   TRK0914
345           0   TRK0914

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       2.0       1      1        0
342  12-28-2010       1.0      0.0       1.0       1      1        0
343  12-29-2010       0.0      0.0       2.0       1      1        0
344  12-30-2010       1.0      0.0       2.0       1      1        0
345  01-12-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TSB0437
1             0   TSB0437
2             0   TSB0437
3             0   TSB0437
4             0   TSB0437
..          ...       ...
341           0   TSB0437
342           0   TSB0437
343           0   TSB0437
344           0   TSB0437
345           0   TSB0437

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      2        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       1.0      1.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       1.0       1      2        0
342  04-08-2011       0.0      0.0       0.0       1      2        0
343  05-06-2010       0.0      0.0       0.0       1      2        0
344  07-08-2010       0.0      0.0       0.0       1      1        0
345  12-16-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   TSG0906
1             0   TSG0906
2             0   TSG0906
3             0   TSG0906
4             0   TSG0906
..          ...       ...
341           0   TSG0906
342           0   TSG0906
343           0   TSG0906
344           0   TSG0906
345           0   TSG0906

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       7.0       6      6        0
1    01-04-2010       5.0      2.0       4.0       5      5        0
2    01-04-2011       9.0      0.0       2.0       6      6        0
3    01-05-2010       4.0      0.0       5.0       4      4        0
4    01-05-2011       3.0      0.0       8.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      0.0       8.0       6      6        0
342  12-28-2010       4.0      1.0       6.0       5      5        0
343  12-29-2010       4.0      1.0       6.0       4      4        0
344  12-30-2010       4.0      1.0       5.0       4      4        0
345  12-02-2010       0.0      0.0       0.0       5      5        0

     Disconnect user_name
0             0   TSM0363
1             0   TSM0363
2             0   TSM0363
3             0   TSM0363
4             0   TSM0363
..          ...       ...
341           0   TSM0363
342           0   TSM0363
343           0   TSM0363
344           0   TSM0363
345           0   TSM0363

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       7.0       1      1        0
1    01-04-2010       4.0      1.0       4.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      1        0
3    01-05-2010       1.0      0.0       8.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       7.0       1      1        0
343  12-29-2010       4.0      0.0       5.0       1      1        0
344  12-30-2010       2.0      0.0       7.0       1      1        0
345  01-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   TSM0927
1             0   TSM0927
2             0   TSM0927
3             0   TSM0927
4             0   TSM0927
..          ...       ...
341           0   TSM0927
342           0   TSM0927
343           0   TSM0927
344           0   TSM0927
345           0   TSM0927

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      2      2.0
1    01-04-2010       8.0      0.0       1.0       1      2      2.0
2    01-04-2011       1.0      1.0       7.0       1      2      1.0
3    01-05-2010       1.0      0.0       8.0       1      2      3.0
4    01-05-2011       3.0      1.0       5.0       1      2      3.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2      1.0
342  12-27-2010       3.0      0.0       6.0       1      2      3.0
343  12-28-2010       1.0      0.0       8.0       1      1      2.0
344  12-29-2010       1.0      2.0       6.0       1      2      2.0
345  12-30-2010       2.0      0.0       7.0       1      2      2.0

     Disconnect user_name
0           2.0   TSR0676
1           2.0   TSR0676
2           1.0   TSR0676
3           3.0   TSR0676
4           3.0   TSR0676
..          ...       ...
341         1.0   TSR0676
342         3.0   TSR0676
343         2.0   TSR0676
344         2.0   TSR0676
345         2.0   TSR0676

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       2.0      1.0       5.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       3.0      2.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       4.0      2.0       2.0       1      1        0
343  12-28-2010       3.0      2.0       4.0       1      1        0
344  12-29-2010       1.0      7.0       1.0       1      1        0
345  12-30-2010       4.0      1.0       4.0       1      1        0

     Disconnect user_name
0             0   TTD1000
1             0   TTD1000
2             0   TTD1000
3             0   TTD1000
4             0   TTD1000
..          ...       ...
341           0   TTD1000
342           0   TTD1000
343           0   TTD1000
344           0   TTD1000
345           0   TTD1000

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       2.0      1.0       0.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       2.0      0.0       1.0       1      1        0
342  12-27-2010       0.0      0.0       3.0       1      1        0
343  12-28-2010       1.0      0.0       2.0       1      1        0
344  12-29-2010       3.0      0.0       0.0       1      1        0
345  12-30-2010       1.0      0.0       2.0       1      1        0

     Disconnect user_name
0             0   TUC0632
1             0   TUC0632
2             0   TUC0632
3             0   TUC0632
4             0   TUC0632
..          ...       ...
341           0   TUC0632
342           0   TUC0632
343           0   TUC0632
344           0   TUC0632
345           0   TUC0632

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      2.0      18.0       2      3        0
1    01-04-2010       9.0      1.0      17.0       1      2        0
2    01-04-2011       6.0      0.0      21.0       1      2        0
3    01-05-2010       6.0      1.0      20.0       1      2        0
4    01-05-2011      14.0      1.0      11.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       6.0      0.0      21.0       1      2        0
342  12-27-2010       2.0      2.0      21.0       1      2        0
343  12-28-2010       4.0      0.0      23.0       1      1        0
344  12-29-2010       8.0      3.0      16.0       1      2        0
345  12-30-2010       6.0      2.0      19.0       1      2        0

     Disconnect user_name
0             0   TVS0006
1             0   TVS0006
2             0   TVS0006
3             0   TVS0006
4             0   TVS0006
..          ...       ...
341           0   TVS0006
342           0   TVS0006
343           0   TVS0006
344           0   TVS0006
345           0   TVS0006

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      12.0      2.0       5.0     2.0    3.0        0
1    01-04-2010       9.0      0.0      10.0     2.0    3.0        0
2    01-04-2011      10.0      0.0       9.0     1.0    2.0        0
3    01-05-2010       6.0      0.0      12.0     2.0    3.0        0
4    01-05-2011       4.0      0.0      15.0     1.0    2.0        0
..          ...       ...      ...       ...     ...    ...      ...
352  07-03-2010       0.0      0.0       0.0     1.0    1.0        0
353  07-17-2010       0.0      0.0       0.0     1.0    0.0        0
354  08-21-2010       0.0      0.0       0.0     1.0    0.0        0
355  10-02-2010       0.0      0.0       0.0     1.0    1.0        0
356  11-13-2010       0.0      0.0       0.0     1.0    0.0        0

     Disconnect user_name
0             0   TVS0050
1             0   TVS0050
2             0   TVS0050
3             0   TVS0050
4             0   TVS0050
..          ...       ...
352           0   TVS0050
353           0   TVS0050
354           0   TVS0050
355           0   TVS0050
356           0   TVS0050

[357 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      1.0       2.0       1      2        0
3    01-05-2010       2.0      0.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  02-18-2011       0.0      0.0       0.0       1      2        0
342  03-31-2010       0.0      0.0       0.0       1      2        0
343  05-28-2010       0.0      0.0       0.0       1      2        0
344  06-09-2010       0.0      0.0       0.0       1      2        0
345  07-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   TYB0779
1             0   TYB0779
2             0   TYB0779
3             0   TYB0779
4             0   TYB0779
..          ...       ...
341           0   TYB0779
342           0   TYB0779
343           0   TYB0779
344           0   TYB0779
345           0   TYB0779

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      2      3.0
1    01-04-2010       1.0      0.0       2.0       1      1      3.0
2    01-04-2011       1.0      0.0       2.0       1      2      3.0
3    01-05-2010       2.0      0.0       1.0       1      2      3.0
4    01-05-2011       0.0      0.0       3.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       2.0      0.0       0.0       1      2      3.0
342  01-07-2011       0.0      0.0       0.0       1      1      2.0
343  08-25-2010       0.0      0.0       0.0       1      2      1.0
344  09-20-2010       0.0      0.0       0.0       1      2      3.0
345  09-27-2010       0.0      0.0       0.0       1      1      3.0

     Disconnect user_name
0           3.0   UAD0771
1           3.0   UAD0771
2           3.0   UAD0771
3           3.0   UAD0771
4           2.0   UAD0771
..          ...       ...
341         3.0   UAD0771
342         2.0   UAD0771
343         1.0   UAD0771
344         3.0   UAD0771
345         3.0   UAD0771

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      1.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-30-2010       1.0      0.0       2.0       1      1        0
342  03-16-2010       0.0      0.0       0.0       1      1        0
343  04-05-2010       0.0      0.0       0.0       1      1        0
344  04-23-2010       0.0      0.0       0.0       1      1        0
345  08-31-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   UBF0645
1             0   UBF0645
2             0   UBF0645
3             0   UBF0645
4             0   UBF0645
..          ...       ...
341           0   UBF0645
342           0   UBF0645
343           0   UBF0645
344           0   UBF0645
345           0   UBF0645

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       0.0      0.0       3.0       1      1        0
3    01-05-2010       1.0      1.0       1.0       1      1        0
4    01-05-2011       2.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
274  12-27-2010       0.0      0.0       3.0       1      1        0
275  12-28-2010       0.0      0.0       3.0       1      1        0
276  12-29-2010       1.0      0.0       2.0       1      1        0
277  12-30-2010       0.0      1.0       2.0       1      1        0
278  10-14-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   UCH0519
1             0   UCH0519
2             0   UCH0519
3             0   UCH0519
4             0   UCH0519
..          ...       ...
274           0   UCH0519
275           0   UCH0519
276           0   UCH0519
277           0   UCH0519
278           0   UCH0519

[279 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       8.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       1.0      0.0       3.0       1      1        0
4    01-05-2011       2.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0       7.0       1      1        0
342  12-27-2010       5.0      0.0       4.0       1      1        0
343  12-28-2010       5.0      1.0       3.0       1      1        0
344  12-29-2010       5.0      0.0       4.0       1      1        0
345  12-30-2010       3.0      1.0       5.0       1      1        0

     Disconnect user_name
0             0   UCS0227
1             0   UCS0227
2             0   UCS0227
3             0   UCS0227
4             0   UCS0227
..          ...       ...
341           0   UCS0227
342           0   UCS0227
343           0   UCS0227
344           0   UCS0227
345           0   UCS0227

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       9.0       2      2        0
1    01-04-2010       4.0      0.0       7.0       2      3        0
2    01-04-2011       5.0      1.0       7.0       1      2        0
3    01-05-2010       4.0      0.0      10.0       1      2        0
4    01-05-2011       6.0      0.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      3.0       8.0       1      2        0
342  12-27-2010       3.0      4.0       7.0       1      2        0
343  12-28-2010       7.0      1.0       6.0       2      3        0
344  12-29-2010       3.0      0.0      11.0       1      2        0
345  12-30-2010       1.0      1.0      12.0       1      2        0

     Disconnect user_name
0             0   UFK0208
1             0   UFK0208
2             0   UFK0208
3             0   UFK0208
4             0   UFK0208
..          ...       ...
341           0   UFK0208
342           0   UFK0208
343           0   UFK0208
344           0   UFK0208
345           0   UFK0208

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0      10.0       6      6        0
1    01-04-2010       2.0      1.0       8.0       6      6        0
2    01-04-2011       2.0      0.0       9.0       4      4        0
3    01-05-2010       4.0      0.0       6.0       2      2        0
4    01-05-2011       1.0      0.0      10.0       5      5        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      1.0      10.0       4      4        0
342  12-27-2010       2.0      0.0       9.0       2      2        0
343  12-28-2010       7.0      0.0       5.0       4      4        0
344  12-29-2010       3.0      0.0       8.0       3      3        0
345  12-30-2010       5.0      0.0       6.0       4      4        0

     Disconnect user_name
0             0   UIR0043
1             0   UIR0043
2             0   UIR0043
3             0   UIR0043
4             0   UIR0043
..          ...       ...
341           0   UIR0043
342           0   UIR0043
343           0   UIR0043
344           0   UIR0043
345           0   UIR0043

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      6.0       4.0       1      1        0
1    01-04-2010       7.0      4.0       3.0       1      1        0
2    01-04-2011       3.0      2.0      10.0       1      1        0
3    01-05-2010       0.0     12.0       3.0       1      1        0
4    01-05-2011       1.0     11.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      5.0       5.0       1      1        0
342  12-28-2010       0.0      6.0       9.0       1      1        0
343  12-29-2010       4.0      7.0       4.0       1      1        0
344  12-30-2010       8.0      1.0       6.0       1      1        0
345  01-26-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   UJC0737
1             0   UJC0737
2             0   UJC0737
3             0   UJC0737
4             0   UJC0737
..          ...       ...
341           0   UJC0737
342           0   UJC0737
343           0   UJC0737
344           0   UJC0737
345           0   UJC0737

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1      1.0
1    01-04-2010       2.0      0.0       7.0       1      1      1.0
2    01-04-2011       7.0      0.0       2.0       1      1      0.0
3    01-05-2010       8.0      0.0       1.0       1      1      0.0
4    01-05-2011       2.0      0.0       6.0       1      1      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      0.0       2.0       1      1      0.0
342  12-27-2010       3.0      1.0       5.0       1      1      1.0
343  12-28-2010       3.0      1.0       5.0       1      1      0.0
344  12-29-2010       3.0      0.0       6.0       1      1      0.0
345  12-30-2010       2.0      1.0       6.0       1      1      0.0

     Disconnect user_name
0           1.0   USH0199
1           1.0   USH0199
2           0.0   USH0199
3           0.0   USH0199
4           0.0   USH0199
..          ...       ...
341         0.0   USH0199
342         1.0   USH0199
343         0.0   USH0199
344         0.0   USH0199
345         0.0   USH0199

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       2      3        0
1    01-04-2010       5.0      0.0       4.0       1      2        0
2    01-04-2011       3.0      1.0       5.0       1      2        0
3    01-05-2010       3.0      0.0       6.0       1      2        0
4    01-05-2011       4.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       3.0      2.0       4.0       1      2        0
342  12-28-2010       6.0      0.0       3.0       1      2        0
343  12-29-2010       3.0      0.0       6.0       1      2        0
344  12-30-2010       4.0      0.0       5.0       1      2        0
345  07-16-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   VAA0087
1             0   VAA0087
2             0   VAA0087
3             0   VAA0087
4             0   VAA0087
..          ...       ...
341           0   VAA0087
342           0   VAA0087
343           0   VAA0087
344           0   VAA0087
345           0   VAA0087

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0     1.0    3.0      3.0
1    01-04-2010       6.0      0.0       3.0     1.0    2.0      2.0
2    01-04-2011       7.0      0.0       1.0     2.0    2.0      2.0
3    01-05-2010       5.0      0.0       4.0     1.0    2.0      0.0
4    01-05-2011       3.0      0.0       6.0     1.0    2.0      1.0
..          ...       ...      ...       ...     ...    ...      ...
346  04-17-2010       0.0      0.0       0.0     1.0    0.0      0.0
347  05-01-2010       0.0      0.0       0.0     1.0    0.0      0.0
348  05-08-2010       0.0      0.0       0.0     1.0    1.0      0.0
349  07-17-2010       0.0      0.0       0.0     1.0    1.0      0.0
350  11-13-2010       0.0      0.0       0.0     1.0    1.0      0.0

     Disconnect user_name
0           3.0   VCC0396
1           2.0   VCC0396
2           2.0   VCC0396
3           0.0   VCC0396
4           1.0   VCC0396
..          ...       ...
346         0.0   VCC0396
347         0.0   VCC0396
348         0.0   VCC0396
349         0.0   VCC0396
350         0.0   VCC0396

[351 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       6.0       1      2        0
1    01-04-2010       3.0      8.0       4.0       1      2        0
2    01-04-2011       3.0      6.0       6.0       1      2        0
3    01-05-2010       5.0      4.0       6.0       1      2        0
4    01-05-2011       7.0      4.0       4.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       7.0      1.0       7.0       1      2        0
342  12-28-2010       5.0      3.0       6.0       1      2        0
343  12-29-2010       5.0      7.0       3.0       1      2        0
344  12-30-2010       8.0      1.0       6.0       1      2        0
345  04-15-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   VCY0751
1             0   VCY0751
2             0   VCY0751
3             0   VCY0751
4             0   VCY0751
..          ...       ...
341           0   VCY0751
342           0   VCY0751
343           0   VCY0751
344           0   VCY0751
345           0   VCY0751

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      0.0       2.0       1      1        0
3    01-05-2010       8.0      0.0       1.0       1      1        0
4    01-05-2011       5.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       4.0       1      1        0
342  12-28-2010       2.0      0.0       7.0       1      1        0
343  12-29-2010       4.0      1.0       3.0       1      1        0
344  12-30-2010       6.0      0.0       3.0       1      1        0
345  10-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   VEB0935
1             0   VEB0935
2             0   VEB0935
3             0   VEB0935
4             0   VEB0935
..          ...       ...
341           0   VEB0935
342           0   VEB0935
343           0   VEB0935
344           0   VEB0935
345           0   VEB0935

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       3.0      1.0       5.0       1      2      0.0
1    01-05-2010       3.0      0.0       6.0       1      2      2.0
2    01-06-2010       3.0      0.0       6.0       2      2      0.0
3    01-07-2010       2.0      3.0       4.0       1      2      0.0
4    01-08-2010       5.0      2.0       2.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
235  12-07-2010       4.0      0.0       5.0       1      2      0.0
236  12-08-2010       4.0      0.0       5.0       2      3      1.0
237  12-09-2010       3.0      1.0       5.0       2      3      0.0
238  12-10-2010       4.0      1.0       4.0       1      2      0.0
239  12-13-2010       0.0      0.0       3.0       2      2      0.0

     Disconnect user_name
0           0.0   VFM0814
1           2.0   VFM0814
2           0.0   VFM0814
3           0.0   VFM0814
4           1.0   VFM0814
..          ...       ...
235         0.0   VFM0814
236         1.0   VFM0814
237         0.0   VFM0814
238         0.0   VFM0814
239         0.0   VFM0814

[240 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      0.0       5.0       1      1        8
1    01-04-2010      12.0      0.0       2.0       1      1        7
2    01-04-2011       7.0      0.0       7.0       1      1        9
3    01-05-2010       6.0      0.0       8.0       1      1        9
4    01-05-2011       8.0      0.0       6.0       1      1        7
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      2.0       7.0       1      1        9
342  12-28-2010       4.0      0.0       9.0       1      1        9
343  12-29-2010       3.0      2.0       9.0       1      1        8
344  12-30-2010       7.0      1.0       6.0       1      1        8
345  05-25-2010       0.0      0.0       0.0       1      1        8

     Disconnect user_name
0             8   VIA0063
1             7   VIA0063
2             9   VIA0063
3             9   VIA0063
4             7   VIA0063
..          ...       ...
341           9   VIA0063
342           9   VIA0063
343           8   VIA0063
344           8   VIA0063
345           8   VIA0063

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      1.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       1.0      0.0       2.0       1      1        0
342  12-29-2010       1.0      0.0       2.0       1      1        0
343  12-30-2010       0.0      0.0       3.0       1      1        0
344  05-11-2011       0.0      0.0       0.0       1      1        0
345  05-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   VLB0647
1             0   VLB0647
2             0   VLB0647
3             0   VLB0647
4             0   VLB0647
..          ...       ...
341           0   VLB0647
342           0   VLB0647
343           0   VLB0647
344           0   VLB0647
345           0   VLB0647

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       7.0       1      1        0
1    01-04-2010       3.0      0.0      11.0       1      1        0
2    01-04-2011       3.0      1.0      10.0       1      1        0
3    01-05-2010       4.0      2.0       7.0       1      1        0
4    01-05-2011       2.0      2.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       7.0       1      1        0
342  12-28-2010       4.0      4.0       6.0       1      1        0
343  12-29-2010       9.0      0.0       5.0       1      1        0
344  12-30-2010       7.0      0.0       7.0       1      1        0
345  09-08-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   VMJ0147
1             0   VMJ0147
2             0   VMJ0147
3             0   VMJ0147
4             0   VMJ0147
..          ...       ...
341           0   VMJ0147
342           0   VMJ0147
343           0   VMJ0147
344           0   VMJ0147
345           0   VMJ0147

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      2      1.0
1    01-04-2010       4.0      1.0       4.0       1      2      1.0
2    01-04-2011       5.0      0.0       4.0       1      2      2.0
3    01-05-2010       5.0      0.0       4.0       1      2      2.0
4    01-05-2011       3.0      0.0       6.0       1      2      4.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       4.0       1      1      2.0
342  12-29-2010       3.0      0.0       6.0       1      2      1.0
343  12-30-2010       1.0      0.0       8.0       1      2      2.0
344  03-25-2011       0.0      0.0       0.0       1      2      2.0
345  09-24-2010       0.0      0.0       0.0       1      2      3.0

     Disconnect user_name
0           1.0   VMJ0546
1           1.0   VMJ0546
2           1.0   VMJ0546
3           2.0   VMJ0546
4           4.0   VMJ0546
..          ...       ...
341         2.0   VMJ0546
342         1.0   VMJ0546
343         2.0   VMJ0546
344         2.0   VMJ0546
345         3.0   VMJ0546

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       2      2      0.0
1    01-04-2010       2.0      1.0       3.0       1      1      2.0
2    01-04-2011       3.0      1.0       4.0       1      2      1.0
3    01-05-2010       1.0      2.0       6.0       1      2      1.0
4    01-05-2011       3.0      0.0       6.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
291  12-28-2010       2.0      0.0       7.0       1      1      0.0
292  12-29-2010       6.0      0.0       3.0       1      2      0.0
293  12-30-2010       2.0      0.0       7.0       1      2      0.0
294  04-28-2010       0.0      0.0       0.0       1      2      0.0
295  10-08-2010       0.0      0.0       0.0       1      2      0.0

     Disconnect user_name
0           0.0   VSA0230
1           2.0   VSA0230
2           1.0   VSA0230
3           1.0   VSA0230
4           0.0   VSA0230
..          ...       ...
291         0.0   VSA0230
292         0.0   VSA0230
293         0.0   VSA0230
294         0.0   VSA0230
295         0.0   VSA0230

[296 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       7.0      0.0       4.0     1.0    1.0      1.0
1    01-05-2010       8.0      1.0       2.0     1.0    1.0      3.0
2    01-06-2010       6.0      0.0       5.0     1.0    1.0      2.0
3    01-07-2010       4.0      0.0       7.0     1.0    1.0      1.0
4    01-08-2010       6.0      0.0       5.0     1.0    1.0      2.0
..          ...       ...      ...       ...     ...    ...      ...
209  10-28-2010       7.0      0.0       4.0     1.0    1.0      2.0
210  10-29-2010       5.0      0.0       6.0     1.0    1.0      6.0
211  11-01-2010       4.0      0.0       7.0     1.0    1.0      2.0
212  11-02-2010       9.0      1.0       1.0     1.0    1.0      1.0
213  11-03-2010       5.0      0.0       6.0     1.0    1.0      2.0

     Disconnect user_name
0           1.0   VSS0154
1           3.0   VSS0154
2           2.0   VSS0154
3           1.0   VSS0154
4           2.0   VSS0154
..          ...       ...
209         2.0   VSS0154
210         6.0   VSS0154
211         2.0   VSS0154
212         1.0   VSS0154
213         2.0   VSS0154

[214 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        8
1    01-04-2010       1.0      0.0       8.0       1      1        9
2    01-04-2011       3.0      0.0       6.0       1      1        7
3    01-05-2010       2.0      0.0       7.0       1      1        9
4    01-05-2011       4.0      1.0       4.0       1      1        9
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      0.0       6.0       1      1        9
342  12-30-2010       2.0      0.0       7.0       1      1        8
343  02-08-2010       0.0      0.0       0.0       1      1        7
344  03-18-2011       0.0      0.0       0.0       1      1        9
345  03-25-2011       0.0      0.0       0.0       1      1        8

     Disconnect user_name
0             8   VTT0385
1             9   VTT0385
2             7   VTT0385
3             9   VTT0385
4             9   VTT0385
..          ...       ...
341           9   VTT0385
342           8   VTT0385
343           6   VTT0385
344           9   VTT0385
345           8   VTT0385

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       2.0      1.0       5.0       1      1        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       5.0      2.0       2.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
249  12-27-2010       4.0      1.0       4.0       1      1        0
250  12-28-2010       3.0      0.0       6.0       1      1        0
251  12-29-2010       2.0      0.0       6.0       1      1        0
252  12-30-2010       4.0      0.0       5.0       1      1        0
253  07-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WAB0143
1             0   WAB0143
2             0   WAB0143
3             0   WAB0143
4             0   WAB0143
..          ...       ...
249           0   WAB0143
250           0   WAB0143
251           0   WAB0143
252           0   WAB0143
253           0   WAB0143

[254 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      0.0       3.0       1      2        0
1    01-04-2010       3.0      0.0       6.0       1      1        0
2    01-04-2011       2.0      1.0       6.0       1      2        0
3    01-05-2010       6.0      0.0       3.0       1      2        0
4    01-05-2011       1.0      0.0       8.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2        0
342  12-27-2010       5.0      0.0       4.0       1      2        0
343  12-28-2010       1.0      0.0       8.0       1      2        0
344  12-29-2010       3.0      0.0       6.0       1      2        0
345  12-30-2010       4.0      0.0       5.0       1      2        0

     Disconnect user_name
0             0   WAS0254
1             0   WAS0254
2             0   WAS0254
3             0   WAS0254
4             0   WAS0254
..          ...       ...
341           0   WAS0254
342           0   WAS0254
343           0   WAS0254
344           0   WAS0254
345           0   WAS0254

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       7.0       2      2      0.0
1    01-04-2010       6.0      1.0       7.0       1      2      2.0
2    01-04-2011       8.0      0.0       6.0       1      2      0.0
3    01-05-2010       6.0      0.0       8.0       1      2      0.0
4    01-05-2011       3.0      0.0      11.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       8.0      0.0       6.0       1      2      1.0
342  12-27-2010       7.0      0.0       6.0       1      2      0.0
343  12-28-2010       2.0      3.0       9.0       1      1      1.0
344  12-29-2010       6.0      1.0       6.0       1      2      0.0
345  12-30-2010       7.0      0.0       7.0       1      2      0.0

     Disconnect user_name
0           0.0   WBC0192
1           2.0   WBC0192
2           0.0   WBC0192
3           0.0   WBC0192
4           0.0   WBC0192
..          ...       ...
341         1.0   WBC0192
342         0.0   WBC0192
343         1.0   WBC0192
344         0.0   WBC0192
345         0.0   WBC0192

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       1      1        0
1    01-04-2010      10.0      2.0       3.0       1      1        0
2    01-04-2011       4.0      0.0      10.0       1      1        0
3    01-05-2010       5.0      1.0       7.0       1      1        0
4    01-05-2011       3.0      0.0      12.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       7.0      0.0       8.0       1      1        0
342  12-29-2010       6.0      1.0       8.0       1      1        0
343  12-30-2010       6.0      1.0       3.0       1      1        0
344  01-26-2010       0.0      0.0       0.0       1      1        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WBC0315
1             0   WBC0315
2             0   WBC0315
3             0   WBC0315
4             0   WBC0315
..          ...       ...
341           0   WBC0315
342           0   WBC0315
343           0   WBC0315
344           0   WBC0315
345           0   WBC0315

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       4.0       3      4      0.0
1    01-04-2010       3.0      1.0       6.0       2      3      0.0
2    01-04-2011       5.0      0.0       5.0       6      7      0.0
3    01-05-2010       1.0      1.0       9.0       2      3      0.0
4    01-05-2011       2.0      0.0       8.0       2      3      0.0
..          ...       ...      ...       ...     ...    ...      ...
303  12-29-2010       6.0      0.0       5.0       4      5      0.0
304  12-30-2010       3.0      0.0       8.0       4      5      0.0
305  02-15-2010       0.0      0.0       0.0       4      5      0.0
306  06-10-2010       0.0      0.0       0.0       6      7      0.0
307  07-20-2010       0.0      0.0       0.0       4      4      0.0

     Disconnect user_name
0           0.0   WDD0366
1           0.0   WDD0366
2           0.0   WDD0366
3           0.0   WDD0366
4           0.0   WDD0366
..          ...       ...
303         0.0   WDD0366
304         0.0   WDD0366
305         0.0   WDD0366
306         0.0   WDD0366
307         0.0   WDD0366

[308 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       6.0      1.0       7.0     1.0    1.0        0
1    01-04-2010       5.0      0.0       5.0     1.0    1.0        0
2    01-04-2011      10.0      1.0       3.0     1.0    1.0        0
3    01-05-2010       8.0      0.0       6.0     1.0    1.0        0
4    01-05-2011       7.0      0.0       7.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
348  02-06-2010       0.0      0.0       0.0     1.0    1.0        0
349  02-20-2010       0.0      0.0       0.0     1.0    0.0        0
350  05-01-2010       0.0      0.0       0.0     1.0    1.0        0
351  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
352  05-14-2011       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   WDO0870
1             0   WDO0870
2             0   WDO0870
3             0   WDO0870
4             0   WDO0870
..          ...       ...
348           0   WDO0870
349           0   WDO0870
350           0   WDO0870
351           0   WDO0870
352           0   WDO0870

[353 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       1.0     2.0    3.0        0
1    01-04-2010       0.0      0.0       1.0     1.0    1.0        0
2    01-04-2011       0.0      0.0       1.0     2.0    1.0        0
3    01-05-2010       0.0      0.0       1.0     1.0    1.0        0
4    01-06-2010       0.0      0.0       1.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
348  07-08-2010       0.0      0.0       0.0     1.0    1.0        0
349  07-19-2010       0.0      0.0       0.0     1.0    1.0        0
350  08-12-2010       0.0      0.0       0.0     2.0    2.0        0
351  09-02-2010       0.0      0.0       0.0     1.0    1.0        0
352  12-15-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   WDV0573
1             0   WDV0573
2             0   WDV0573
3             0   WDV0573
4             0   WDV0573
..          ...       ...
348           0   WDV0573
349           0   WDV0573
350           0   WDV0573
351           0   WDV0573
352           0   WDV0573

[353 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       0.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-08-2011       0.0      0.0       0.0       1      1        0
342  04-30-2010       0.0      0.0       0.0       1      1        0
343  07-20-2010       0.0      0.0       0.0       1      1        0
344  08-11-2010       0.0      0.0       0.0       1      1        0
345  12-27-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WGR0833
1             0   WGR0833
2             0   WGR0833
3             0   WGR0833
4             0   WGR0833
..          ...       ...
341           0   WGR0833
342           0   WGR0833
343           0   WGR0833
344           0   WGR0833
345           0   WGR0833

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      1.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       2.0      0.0       1.0       1      1        0
4    01-05-2011       3.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1        0
342  12-30-2010       2.0      1.0       0.0       1      1        0
343  02-07-2011       0.0      0.0       0.0       1      1        0
344  04-05-2010       0.0      0.0       0.0       1      1        0
345  06-09-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WGS0516
1             0   WGS0516
2             0   WGS0516
3             0   WGS0516
4             0   WGS0516
..          ...       ...
341           0   WGS0516
342           0   WGS0516
343           0   WGS0516
344           0   WGS0516
345           0   WGS0516

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      2        7
1    01-04-2010       5.0      0.0       4.0       1      1        8
2    01-04-2011       4.0      0.0       1.0       1      2        9
3    01-05-2010       2.0      2.0       4.0       1      2        7
4    01-05-2011       4.0      1.0       4.0       1      2        7
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       6.0      1.0       2.0       1      2        9
342  12-28-2010       4.0      0.0       5.0       1      1        9
343  12-29-2010       6.0      0.0       3.0       1      2        7
344  12-30-2010       3.0      2.0       4.0       1      2        6
345  07-19-2010       0.0      0.0       0.0       1      2        8

     Disconnect user_name
0             6   WIF0691
1             8   WIF0691
2             9   WIF0691
3             7   WIF0691
4             7   WIF0691
..          ...       ...
341           9   WIF0691
342           9   WIF0691
343           7   WIF0691
344           6   WIF0691
345           8   WIF0691

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-01-2011       7.0      0.0       2.0       1      2      0.0
1    01-02-2011       3.0      2.0       4.0       1      2      0.0
2    01-03-2010       2.0      0.0       7.0       1      2      1.0
3    01-03-2011       1.0      3.0       5.0       1      2      1.0
4    01-04-2010       4.0      0.0       5.0       1      2      2.0
..          ...       ...      ...       ...     ...    ...      ...
437  12-29-2010       5.0      1.0       3.0       1      1      3.0
438  12-30-2010       3.0      1.0       5.0       1      2      1.0
439  12-31-2010       2.0      1.0       6.0       1      1      1.0
440  01-13-2011       0.0      0.0       0.0       1      2      0.0
441  04-27-2011       0.0      0.0       0.0       1      2      1.0

     Disconnect user_name
0           0.0   WIQ0567
1           0.0   WIQ0567
2           1.0   WIQ0567
3           1.0   WIQ0567
4           2.0   WIQ0567
..          ...       ...
437         3.0   WIQ0567
438         1.0   WIQ0567
439         1.0   WIQ0567
440         0.0   WIQ0567
441         1.0   WIQ0567

[442 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  04-27-2011       0.0      0.0       0.0       1      1        0
342  05-10-2011       0.0      0.0       0.0       1      1        0
343  05-11-2011       0.0      0.0       0.0       1      1        0
344  05-20-2010       0.0      0.0       0.0       1      1        0
345  09-03-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WJD0576
1             0   WJD0576
2             0   WJD0576
3             0   WJD0576
4             0   WJD0576
..          ...       ...
341           0   WJD0576
342           0   WJD0576
343           0   WJD0576
344           0   WJD0576
345           0   WJD0576

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0      12.0     1.0    1.0        0
1    01-04-2010       6.0      0.0      12.0     1.0    1.0        0
2    01-04-2011       6.0      0.0      12.0     1.0    1.0        0
3    01-05-2010       2.0      0.0       4.0     1.0    1.0        0
4    01-05-2011       6.0      1.0      11.0     1.0    1.0        0
..          ...       ...      ...       ...     ...    ...      ...
349  04-17-2010       0.0      0.0       0.0     1.0    1.0        0
350  05-08-2010       0.0      0.0       0.0     1.0    0.0        0
351  07-03-2010       0.0      0.0       0.0     1.0    0.0        0
352  10-02-2010       0.0      0.0       0.0     1.0    0.0        0
353  11-06-2010       0.0      0.0       0.0     1.0    1.0        0

     Disconnect user_name
0             0   WKD0013
1             0   WKD0013
2             0   WKD0013
3             0   WKD0013
4             0   WKD0013
..          ...       ...
349           0   WKD0013
350           0   WKD0013
351           0   WKD0013
352           0   WKD0013
353           0   WKD0013

[354 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       9.0      1.0       6.0       1      1        0
1    01-04-2010       6.0      0.0      11.0       1      1        0
2    01-04-2011       1.0      0.0      17.0       1      1        0
3    01-05-2010       7.0      0.0      10.0       1      1        0
4    01-05-2011       7.0      1.0      10.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010      11.0      0.0       7.0       1      1        0
342  12-28-2010       6.0      0.0      12.0       1      1        0
343  12-29-2010       7.0      2.0       9.0       1      1        0
344  12-30-2010      12.0      0.0       6.0       1      1        0
345  09-07-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WKF0012
1             0   WKF0012
2             0   WKF0012
3             0   WKF0012
4             0   WKF0012
..          ...       ...
341           0   WKF0012
342           0   WKF0012
343           0   WKF0012
344           0   WKF0012
345           0   WKF0012

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       4.0       1      1        0
1    01-04-2010       6.0      1.0       2.0       1      1        0
2    01-04-2011       4.0      1.0       4.0       1      1        0
3    01-05-2010       3.0      0.0       6.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       2.0      0.0       7.0       1      1        0
342  12-29-2010       2.0      1.0       5.0       1      1        0
343  12-30-2010       0.0      0.0       9.0       1      1        0
344  01-19-2010       0.0      0.0       0.0       1      1        0
345  08-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WLV0566
1             0   WLV0566
2             0   WLV0566
3             0   WLV0566
4             0   WLV0566
..          ...       ...
341           0   WLV0566
342           0   WLV0566
343           0   WLV0566
344           0   WLV0566
345           0   WLV0566

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       1.0       1      2        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       2.0      1.0       0.0       1      2        0
3    01-05-2010       0.0      1.0       2.0       1      2        0
4    01-05-2011       0.0      0.0       3.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      0.0       3.0       1      2        0
342  12-30-2010       0.0      0.0       3.0       1      2        0
343  01-12-2010       0.0      0.0       0.0       1      2        0
344  11-04-2010       0.0      0.0       0.0       1      2        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WNB0908
1             0   WNB0908
2             0   WNB0908
3             0   WNB0908
4             0   WNB0908
..          ...       ...
341           0   WNB0908
342           0   WNB0908
343           0   WNB0908
344           0   WNB0908
345           0   WNB0908

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       0.0      0.0       3.0       1      1        0
342  12-30-2010       1.0      0.0       2.0       1      1        0
343  07-15-2010       0.0      0.0       0.0       1      1        0
344  10-08-2010       0.0      0.0       0.0       1      1        0
345  11-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WPE0538
1             0   WPE0538
2             0   WPE0538
3             0   WPE0538
4             0   WPE0538
..          ...       ...
341           0   WPE0538
342           0   WPE0538
343           0   WPE0538
344           0   WPE0538
345           0   WPE0538

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       2.0      0.0       9.0       2      2        0
1    01-02-2011       3.0      0.0       8.0       6      6        0
2    01-03-2011       3.0      0.0       8.0       3      3        0
3    01-04-2010       4.0      2.0       5.0       4      4        0
4    01-04-2011       6.0      0.0       5.0       5      5        0
..          ...       ...      ...       ...     ...    ...      ...
422  12-30-2010       4.0      0.0       6.0       3      3        0
423  01-24-2011       0.0      0.0       0.0       4      4        0
424  03-18-2010       0.0      0.0       0.0       2      2        0
425  04-24-2010       0.0      0.0       0.0       5      5        0
426  10-07-2010       0.0      0.0       0.0       6      6        0

     Disconnect user_name
0             0   WPR0368
1             0   WPR0368
2             0   WPR0368
3             0   WPR0368
4             0   WPR0368
..          ...       ...
422           0   WPR0368
423           0   WPR0368
424           0   WPR0368
425           0   WPR0368
426           0   WPR0368

[427 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       0.0       1      2        0
1    01-05-2010       1.0      0.0       0.0       1      2        0
2    01-06-2010       0.0      0.0       1.0       1      2        0
3    01-07-2010       0.0      0.0       1.0       1      2        0
4    01-08-2010       0.0      0.0       1.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
169  02-17-2010       0.0      0.0       0.0       1      1        0
170  03-22-2010       0.0      0.0       0.0       1      2        0
171  04-09-2010       0.0      0.0       0.0       1      2        0
172  06-28-2010       0.0      0.0       0.0       1      1        0
173  08-26-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   WRM0963
1             0   WRM0963
2             0   WRM0963
3             0   WRM0963
4             0   WRM0963
..          ...       ...
169           0   WRM0963
170           0   WRM0963
171           0   WRM0963
172           0   WRM0963
173           0   WRM0963

[174 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0       5.0       3      3        0
1    01-04-2010       6.0      0.0       4.0       1      1        0
2    01-04-2011       3.0      0.0       7.0       1      1        0
3    01-05-2010       2.0      0.0       8.0       1      1        0
4    01-05-2011       0.0      0.0       9.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       4.0      1.0       5.0       1      1        0
342  12-28-2010       6.0      0.0       4.0       1      1        0
343  12-29-2010       7.0      0.0       3.0       1      1        0
344  12-30-2010       3.0      0.0       6.0       1      1        0
345  02-08-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WSR0241
1             0   WSR0241
2             0   WSR0241
3             0   WSR0241
4             0   WSR0241
..          ...       ...
341           0   WSR0241
342           0   WSR0241
343           0   WSR0241
344           0   WSR0241
345           0   WSR0241

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      1.0       7.0       1      1        0
1    01-04-2010       5.0      0.0       4.0       1      1        0
2    01-04-2011       4.0      0.0       5.0       1      1        0
3    01-05-2010       4.0      1.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       8.0       1      1        0
342  12-28-2010       4.0      1.0       4.0       1      1        0
343  12-29-2010       3.0      1.0       5.0       1      1        0
344  12-30-2010       5.0      0.0       4.0       1      1        0
345  09-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WTF0387
1             0   WTF0387
2             0   WTF0387
3             0   WTF0387
4             0   WTF0387
..          ...       ...
341           0   WTF0387
342           0   WTF0387
343           0   WTF0387
344           0   WTF0387
345           0   WTF0387

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      1.0       4.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       6.0      0.0       3.0       1      1        0
3    01-05-2010       3.0      2.0       4.0       1      1        0
4    01-05-2011       9.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       3.0      1.0       5.0       1      1        0
342  12-29-2010       2.0      2.0       5.0       1      1        0
343  12-30-2010       4.0      0.0       5.0       1      1        0
344  01-07-2011       0.0      0.0       0.0       1      1        0
345  09-23-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WTR0563
1             0   WTR0563
2             0   WTR0563
3             0   WTR0563
4             0   WTR0563
..          ...       ...
341           0   WTR0563
342           0   WTR0563
343           0   WTR0563
344           0   WTR0563
345           0   WTR0563

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       8.0      1.0       4.0       1      1        0
1    01-04-2010       6.0      1.0       7.0       1      1        0
2    01-04-2011       5.0      1.0       8.0       1      1        0
3    01-05-2010       9.0      3.0       2.0       1      1        0
4    01-05-2011       7.0      0.0       7.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      1.0       9.0       1      1        0
342  12-29-2010       3.0      0.0      11.0       1      1        0
343  12-30-2010       4.0      2.0       5.0       1      1        0
344  08-25-2010       0.0      0.0       0.0       1      1        0
345  10-04-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   WVB0539
1             0   WVB0539
2             0   WVB0539
3             0   WVB0539
4             0   WVB0539
..          ...       ...
341           0   WVB0539
342           0   WVB0539
343           0   WVB0539
344           0   WVB0539
345           0   WVB0539

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      0.0      10.0     2.0    2.0      2.0
1    01-04-2010       7.0      0.0       8.0     2.0    2.0      3.0
2    01-04-2011       4.0      0.0      11.0     1.0    1.0      2.0
3    01-05-2010       7.0      1.0       7.0     1.0    1.0      3.0
4    01-05-2011       6.0      2.0       7.0     1.0    1.0      4.0
..          ...       ...      ...       ...     ...    ...      ...
342  12-28-2010       8.0      0.0       7.0     2.0    2.0      2.0
343  12-29-2010       6.0      0.0       9.0     1.0    1.0      1.0
344  12-30-2010       5.0      3.0       7.0     1.0    1.0      1.0
345  01-08-2011       0.0      0.0       0.0     1.0    0.0      0.0
346  04-09-2010       0.0      0.0       0.0     1.0    1.0      3.0

     Disconnect user_name
0           2.0   WXH0872
1           3.0   WXH0872
2           2.0   WXH0872
3           3.0   WXH0872
4           4.0   WXH0872
..          ...       ...
342         2.0   WXH0872
343         1.0   WXH0872
344         1.0   WXH0872
345         0.0   WXH0872
346         3.0   WXH0872

[347 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1      0.0
1    01-04-2010       3.0      0.0       6.0       1      2      0.0
2    01-04-2011       6.0      0.0       3.0       1      2      1.0
3    01-05-2010       3.0      0.0       6.0       1      2      0.0
4    01-05-2011       5.0      1.0       3.0       1      2      0.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      2      1.0
342  12-27-2010       4.0      2.0       3.0       1      2      0.0
343  12-28-2010       5.0      0.0       4.0       1      2      0.0
344  12-29-2010       6.0      0.0       3.0       1      2      0.0
345  12-30-2010       0.0      2.0       7.0       1      2      0.0

     Disconnect user_name
0           0.0   XAA0104
1           0.0   XAA0104
2           1.0   XAA0104
3           0.0   XAA0104
4           0.0   XAA0104
..          ...       ...
341         1.0   XAA0104
342         0.0   XAA0104
343         0.0   XAA0104
344         0.0   XAA0104
345         0.0   XAA0104

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      0.0       6.0       1      1        0
1    01-04-2010       6.0      1.0       2.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       5.0      0.0       4.0       1      1        0
4    01-05-2011       4.0      0.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      0.0       6.0       1      1        0
342  12-30-2010       3.0      0.0       4.0       1      1        0
343  01-14-2011       0.0      0.0       0.0       1      1        0
344  02-16-2011       0.0      0.0       0.0       1      1        0
345  04-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   XBN0229
1             0   XBN0229
2             0   XBN0229
3             0   XBN0229
4             0   XBN0229
..          ...       ...
341           0   XBN0229
342           0   XBN0229
343           0   XBN0229
344           0   XBN0229
345           0   XBN0229

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       1.0      0.0       2.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       3.0      0.0       0.0       1      1        0
342  12-30-2010       2.0      0.0       1.0       1      1        0
343  02-15-2011       0.0      0.0       0.0       1      1        0
344  04-05-2010       0.0      0.0       0.0       1      1        0
345  05-16-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   XHG0902
1             0   XHG0902
2             0   XHG0902
3             0   XHG0902
4             0   XHG0902
..          ...       ...
341           0   XHG0902
342           0   XHG0902
343           0   XHG0902
344           0   XHG0902
345           0   XHG0902

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       5.0      1.0       7.0       1      1      3.0
1    01-05-2010       7.0      0.0       7.0       1      1      3.0
2    01-06-2010       8.0      1.0       6.0       1      1      3.0
3    01-07-2010       3.0      0.0      11.0       1      1      2.0
4    01-08-2010       8.0      0.0       7.0       1      1      1.0
..          ...       ...      ...       ...     ...    ...      ...
190  10-04-2010       5.0      2.0       8.0       1      1      3.0
191  10-05-2010       7.0      0.0       7.0       1      1      2.0
192  10-06-2010       9.0      0.0       6.0       1      1      5.0
193  10-07-2010       7.0      0.0       8.0       1      1      2.0
194  08-10-2010       0.0      0.0       0.0       1      1      1.0

     Disconnect user_name
0           3.0   XHW0498
1           3.0   XHW0498
2           3.0   XHW0498
3           2.0   XHW0498
4           1.0   XHW0498
..          ...       ...
190         3.0   XHW0498
191         2.0   XHW0498
192         5.0   XHW0498
193         2.0   XHW0498
194         1.0   XHW0498

[195 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       0.0      0.0       1.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  03-01-2010       0.0      0.0       0.0       1      1        0
342  03-21-2011       0.0      0.0       0.0       1      1        0
343  05-05-2010       0.0      0.0       0.0       1      1        0
344  09-23-2010       0.0      0.0       0.0       1      1        0
345  10-22-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   XLB0710
1             0   XLB0710
2             0   XLB0710
3             0   XLB0710
4             0   XLB0710
..          ...       ...
341           0   XLB0710
342           0   XLB0710
343           0   XLB0710
344           0   XLB0710
345           0   XLB0710

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1        0
1    01-04-2010       1.0      0.0       2.0       1      2        0
2    01-04-2011       1.0      0.0       2.0       1      2        0
3    01-05-2010       2.0      0.0       1.0       1      2        0
4    01-05-2011       1.0      0.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       0.0      0.0       1.0       1      2        0
342  12-28-2010       1.0      0.0       2.0       1      1        0
343  12-29-2010       1.0      0.0       2.0       1      2        0
344  12-30-2010       2.0      0.0       1.0       1      2        0
345  03-18-2011       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   XRS0633
1             0   XRS0633
2             0   XRS0633
3             0   XRS0633
4             0   XRS0633
..          ...       ...
341           0   XRS0633
342           0   XRS0633
343           0   XRS0633
344           0   XRS0633
345           0   XRS0633

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-04-2010       1.0      0.0       9.0       1      1      1.0
1    01-05-2010       5.0      0.0       5.0       1      2      4.0
2    01-06-2010       5.0      0.0       5.0       1      1      1.0
3    01-07-2010       6.0      0.0       4.0       1      2      2.0
4    01-08-2010       2.0      0.0       8.0       1      2      1.0
..          ...       ...      ...       ...     ...    ...      ...
245  12-21-2010       3.0      0.0       6.0       1      2      2.0
246  12-22-2010       6.0      0.0       4.0       1      2      3.0
247  12-27-2010       5.0      0.0       5.0       1      2      1.0
248  12-28-2010       3.0      1.0       6.0       1      2      1.0
249  12-29-2010       7.0      0.0       3.0       1      2      2.0

     Disconnect user_name
0           1.0   XWD0923
1           4.0   XWD0923
2           1.0   XWD0923
3           2.0   XWD0923
4           1.0   XWD0923
..          ...       ...
245         2.0   XWD0923
246         3.0   XWD0923
247         1.0   XWD0923
248         1.0   XWD0923
249         2.0   XWD0923

[250 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       7.0      0.0       1.0       1      1        0
2    01-04-2011       3.0      1.0       5.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       3.0      0.0       6.0       1      1        0
342  12-27-2010       3.0      1.0       5.0       1      1        0
343  12-28-2010       1.0      0.0       8.0       1      1        0
344  12-29-2010       4.0      0.0       5.0       1      1        0
345  12-30-2010       4.0      0.0       5.0       1      1        0

     Disconnect user_name
0             0   YCE0983
1             0   YCE0983
2             0   YCE0983
3             0   YCE0983
4             0   YCE0983
..          ...       ...
341           0   YCE0983
342           0   YCE0983
343           0   YCE0983
344           0   YCE0983
345           0   YCE0983

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       5.0      1.0       5.0       1      1        0
1    01-04-2010       6.0      1.0       4.0       1      1        0
2    01-04-2011       8.0      0.0       2.0       1      2        0
3    01-05-2010       4.0      0.0       6.0       1      2        0
4    01-05-2011       5.0      0.0       6.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       5.0      1.0       5.0       1      1        0
342  12-29-2010       8.0      1.0       2.0       1      2        0
343  12-30-2010       7.0      0.0       4.0       1      2        0
344  02-09-2011       0.0      0.0       0.0       1      2        0
345  08-30-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   YDN0198
1             0   YDN0198
2             0   YDN0198
3             0   YDN0198
4             0   YDN0198
..          ...       ...
341           0   YDN0198
342           0   YDN0198
343           0   YDN0198
344           0   YDN0198
345           0   YDN0198

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       3.0      1.0       5.0       1      1        0
1    01-04-2010       4.0      2.0       3.0       1      1        0
2    01-04-2011       4.0      0.0       3.0       1      1        0
3    01-05-2010       2.0      1.0       4.0       1      1        0
4    01-05-2011       5.0      0.0       4.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       6.0      1.0       2.0       1      1        0
342  12-29-2010       6.0      0.0       3.0       1      1        0
343  12-30-2010       3.0      3.0       3.0       1      1        0
344  03-28-2011       0.0      0.0       0.0       1      1        0
345  03-30-2011       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   YEV0793
1             0   YEV0793
2             0   YEV0793
3             0   YEV0793
4             0   YEV0793
..          ...       ...
341           0   YEV0793
342           0   YEV0793
343           0   YEV0793
344           0   YEV0793
345           0   YEV0793

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-02-2010       5.0      0.0       6.0       1      1        0
1    01-02-2011       5.0      2.0       4.0       1      2        0
2    01-03-2010       2.0      7.0       2.0       1      2        0
3    01-03-2011       4.0      2.0       4.0       1      2        0
4    01-04-2010       5.0      0.0       5.0       2      2        0
..          ...       ...      ...       ...     ...    ...      ...
347  12-27-2010       6.0      0.0       5.0       2      2        0
348  12-28-2010       1.0      3.0       7.0       1      2        0
349  12-29-2010       4.0      1.0       6.0       1      2        0
350  12-30-2010       1.0      7.0       3.0       1      2        0
351  09-23-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   YIC0195
1             0   YIC0195
2             0   YIC0195
3             0   YIC0195
4             0   YIC0195
..          ...       ...
347           0   YIC0195
348           0   YIC0195
349           0   YIC0195
350           0   YIC0195
351           0   YIC0195

[352 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      2        0
1    01-04-2010       1.0      1.0       1.0       1      2        0
2    01-04-2011       0.0      0.0       3.0       1      2        0
3    01-05-2010       1.0      0.0       2.0       1      2        0
4    01-05-2011       0.0      1.0       2.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-28-2010       0.0      0.0       0.0       1      1        0
342  02-09-2011       0.0      0.0       0.0       1      2        0
343  03-23-2010       0.0      0.0       0.0       2      2        0
344  07-12-2010       0.0      0.0       0.0       1      2        0
345  09-03-2010       0.0      0.0       0.0       1      2        0

     Disconnect user_name
0             0   YJF0532
1             0   YJF0532
2             0   YJF0532
3             0   YJF0532
4             0   YJF0532
..          ...       ...
341           0   YJF0532
342           0   YJF0532
343           0   YJF0532
344           0   YJF0532
345           0   YJF0532

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  01-14-2011       0.0      0.0       0.0       1      1        0
342  04-11-2011       0.0      0.0       0.0       1      1        0
343  05-03-2010       0.0      0.0       0.0       1      1        0
344  09-24-2010       0.0      0.0       0.0       1      1        0
345  11-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   YJV0699
1             0   YJV0699
2             0   YJV0699
3             0   YJV0699
4             0   YJV0699
..          ...       ...
341           0   YJV0699
342           0   YJV0699
343           0   YJV0699
344           0   YJV0699
345           0   YJV0699

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       3.0       1      1        0
1    01-04-2010       0.0      0.0       3.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       1.0      0.0       2.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
256  12-27-2010       0.0      0.0       3.0       1      1        0
257  12-28-2010       0.0      0.0       3.0       1      1        0
258  12-29-2010       2.0      0.0       1.0       1      1        0
259  12-30-2010       1.0      0.0       2.0       1      1        0
260  12-01-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   YWW0660
1             0   YWW0660
2             0   YWW0660
3             0   YWW0660
4             0   YWW0660
..          ...       ...
256           0   YWW0660
257           0   YWW0660
258           0   YWW0660
259           0   YWW0660
260           0   YWW0660

[261 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       0.0      0.0       1.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-20-2010       0.0      0.0       0.0       1      1        0
342  09-16-2010       0.0      0.0       0.0       1      1        0
343  11-24-2010       0.0      0.0       0.0       1      1        0
344  12-07-2010       0.0      0.0       0.0       1      1        0
345  12-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZCF0590
1             0   ZCF0590
2             0   ZCF0590
3             0   ZCF0590
4             0   ZCF0590
..          ...       ...
341           0   ZCF0590
342           0   ZCF0590
343           0   ZCF0590
344           0   ZCF0590
345           0   ZCF0590

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       7.0      0.0       8.0       2      2        0
1    01-04-2010       4.0      1.0      10.0       1      1        0
2    01-04-2011      10.0      0.0       5.0       1      2        0
3    01-05-2010       6.0      0.0       8.0       1      2        0
4    01-05-2011       9.0      0.0       5.0       1      2        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       7.0      1.0       6.0       1      2        0
342  12-27-2010       8.0      0.0       7.0       1      2        0
343  12-28-2010      11.0      1.0       3.0       1      1        0
344  12-29-2010       9.0      0.0       6.0       1      2        0
345  12-30-2010       5.0      0.0      10.0       1      2        0

     Disconnect user_name
0             0   ZDW0859
1             0   ZDW0859
2             0   ZDW0859
3             0   ZDW0859
4             0   ZDW0859
..          ...       ...
341           0   ZDW0859
342           0   ZDW0859
343           0   ZDW0859
344           0   ZDW0859
345           0   ZDW0859

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       0.0       1      1        0
1    01-04-2010       1.0      0.0       0.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  08-19-2010       0.0      0.0       0.0       1      1        0
342  08-26-2010       0.0      0.0       0.0       1      1        0
343  08-30-2010       0.0      0.0       0.0       1      1        0
344  10-12-2010       0.0      0.0       0.0       1      1        0
345  11-17-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZFM0468
1             0   ZFM0468
2             0   ZFM0468
3             0   ZFM0468
4             0   ZFM0468
..          ...       ...
341           0   ZFM0468
342           0   ZFM0468
343           0   ZFM0468
344           0   ZFM0468
345           0   ZFM0468

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011      10.0      0.0       4.0       2      2        0
1    01-04-2010       5.0      0.0      10.0       1      1        0
2    01-04-2011       5.0      0.0      10.0       1      1        0
3    01-05-2010       7.0      0.0       7.0       1      1        0
4    01-05-2011       9.0      1.0       5.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
362  12-28-2010       6.0      0.0       9.0       2      2        0
363  12-29-2010       9.0      1.0       5.0       1      1        0
364  12-30-2010       5.0      0.0      10.0       1      1        0
365  12-31-2010       9.0      0.0       6.0       1      1        0
366  04-20-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZJE0857
1             0   ZJE0857
2             0   ZJE0857
3             0   ZJE0857
4             0   ZJE0857
..          ...       ...
362           0   ZJE0857
363           0   ZJE0857
364           0   ZJE0857
365           0   ZJE0857
366           0   ZJE0857

[367 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       5.0      2.0       2.0       1      1        0
2    01-04-2011       2.0      0.0       7.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-28-2010       4.0      0.0       5.0       1      1        0
342  12-29-2010       3.0      0.0       6.0       1      1        0
343  12-30-2010       3.0      1.0       5.0       1      1        0
344  02-10-2010       0.0      0.0       0.0       1      1        0
345  10-19-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZJS0269
1             0   ZJS0269
2             0   ZJS0269
3             0   ZJS0269
4             0   ZJS0269
..          ...       ...
341           0   ZJS0269
342           0   ZJS0269
343           0   ZJS0269
344           0   ZJS0269
345           0   ZJS0269

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       1.0      0.0       2.0       1      1      8.0
1    01-04-2010       2.0      0.0       1.0       1      1      8.0
2    01-04-2011       0.0      0.0       3.0       1      1      9.0
3    01-05-2010       2.0      0.0       1.0       1      1      8.0
4    01-05-2011       0.0      0.0       3.0       1      1      8.0
..          ...       ...      ...       ...     ...    ...      ...
341  12-29-2010       1.0      0.0       2.0       1      1      9.0
342  12-30-2010       0.0      0.0       3.0       1      1      9.0
343  03-28-2011       0.0      0.0       0.0       1      1      0.0
344  11-10-2010       0.0      0.0       0.0       1      1      0.0
345  12-28-2010       0.0      0.0       0.0       1      1      8.0

     Disconnect user_name
0           8.0   ZKS0899
1           8.0   ZKS0899
2           9.0   ZKS0899
3           8.0   ZKS0899
4           8.0   ZKS0899
..          ...       ...
341         9.0   ZKS0899
342         9.0   ZKS0899
343         0.0   ZKS0899
344         0.0   ZKS0899
345         8.0   ZKS0899

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       4.0      0.0       5.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       0.0      0.0       7.0       1      1        0
4    01-05-2011       6.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       5.0      0.0       3.0       1      1        0
342  12-28-2010       7.0      0.0       2.0       1      1        0
343  12-29-2010       1.0      2.0       6.0       1      1        0
344  12-30-2010       2.0      0.0       7.0       1      1        0
345  09-15-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZMC0284
1             0   ZMC0284
2             0   ZMC0284
3             0   ZMC0284
4             0   ZMC0284
..          ...       ...
341           0   ZMC0284
342           0   ZMC0284
343           0   ZMC0284
344           0   ZMC0284
345           0   ZMC0284

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      1.0       2.0       1      1        0
1    01-04-2010       2.0      0.0       1.0       1      1        0
2    01-04-2011       1.0      0.0       2.0       1      1        0
3    01-05-2010       0.0      0.0       3.0       1      1        0
4    01-05-2011       0.0      0.0       3.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-22-2010       1.0      0.0       2.0       1      1        0
342  12-27-2010       2.0      1.0       0.0       1      1        0
343  12-28-2010       1.0      0.0       2.0       1      1        0
344  12-29-2010       1.0      0.0       2.0       1      1        0
345  12-30-2010       1.0      0.0       2.0       1      1        0

     Disconnect user_name
0             0   ZSB0649
1             0   ZSB0649
2             0   ZSB0649
3             0   ZSB0649
4             0   ZSB0649
..          ...       ...
341           0   ZSB0649
342           0   ZSB0649
343           0   ZSB0649
344           0   ZSB0649
345           0   ZSB0649

[346 rows x 9 columns]
aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       4.0      0.0       5.0       1      1        0
1    01-04-2010       6.0      0.0       3.0       1      1        0
2    01-04-2011       5.0      0.0       4.0       1      1        0
3    01-05-2010       6.0      0.0       3.0       1      1        0
4    01-05-2011       3.0      0.0       6.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  12-27-2010       1.0      0.0       7.0       1      1        0
342  12-28-2010       1.0      0.0       8.0       1      1        0
343  12-29-2010       1.0      0.0       8.0       1      1        0
344  12-30-2010       6.0      1.0       2.0       1      1        0
345  08-11-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZSK0258
1             0   ZSK0258
2             0   ZSK0258
3             0   ZSK0258
4             0   ZSK0258
..          ...       ...
341           0   ZSK0258
342           0   ZSK0258
343           0   ZSK0258
344           0   ZSK0258
345           0   ZSK0258

[346 rows x 9 columns]

aux        str_date  Negative  Neutral  Positive  Logoff  Logon  Connect  \
0    01-03-2011       0.0      0.0       1.0       1      1        0
1    01-04-2010       0.0      0.0       1.0       1      1        0
2    01-04-2011       0.0      0.0       1.0       1      1        0
3    01-05-2010       1.0      0.0       0.0       1      1        0
4    01-05-2011       1.0      0.0       0.0       1      1        0
..          ...       ...      ...       ...     ...    ...      ...
341  06-21-2010       0.0      0.0       0.0       1      1        0
342  07-13-2010       0.0      0.0       0.0       1      1        0
343  08-18-2010       0.0      0.0       0.0       1      1        0
344  09-13-2010       0.0      0.0       0.0       1      1        0
345  09-28-2010       0.0      0.0       0.0       1      1        0

     Disconnect user_name
0             0   ZSL0305
1             0   ZSL0305
2             0   ZSL0305
3             0   ZSL0305
4             0   ZSL0305
..          ...       ...
341           0   ZSL0305
342           0   ZSL0305
343           0   ZSL0305
344           0   ZSL0305
345           0   ZSL0305

[346 rows x 9 columns]

,str_date,Negative,Neutral,Positive,Logoff,Logon,Connect,Disconnect,user_name
229,07-14-2010,8.0,1.0,8.0,1.0,1.0,0.0,0.0,AMD0077
307,11-04-2010,0.0,1.0,1.0,1.0,1.0,0.0,0.0,CCH0182
327,12-03-2010,2.0,1.0,6.0,1.0,1.0,0.0,0.0,RAH0440
290,10-08-2010,2.0,6.0,3.0,1.0,2.0,0.0,0.0,CSP0197
18,01-10-2011,4.0,0.0,6.0,2.0,2.0,0.0,0.0,HAD0246
...,...,...,...,...,...,...,...,...,...
0,01-03-2011,6.0,1.0,7.0,1.0,1.0,0.0,0.0,MAW0166
206,06-11-2010,6.0,2.0,3.0,1.0,2.0,0.0,0.0,YDN0198
78,02-26-2010,5.0,0.0,4.0,1.0,1.0,0.0,0.0,ZJS0269
133,04-08-2010,0.0,1.0,2.0,1.0,2.0,0.0,0.0,CJV0286
342,12-29-2010,4.0,1.0,6.0,1.0,1.0,0.0,0.0,NAF0033

In [6]:
data=pd.read_csv('concatenated_users.csv',index_col=0)
data.head(20)

,str_date,Negative,Neutral,Positive,Logoff,Logon,Connect,Disconnect,user_name
229,07-14-2010,8.0,1.0,8.0,1.0,1.0,0.0,0.0,AMD0077
307,11-04-2010,0.0,1.0,1.0,1.0,1.0,0.0,0.0,CCH0182
327,12-03-2010,2.0,1.0,6.0,1.0,1.0,0.0,0.0,RAH0440
290,10-08-2010,2.0,6.0,3.0,1.0,2.0,0.0,0.0,CSP0197
18,01-10-2011,4.0,0.0,6.0,2.0,2.0,0.0,0.0,HAD0246
245,08-05-2010,4.0,1.0,4.0,1.0,1.0,0.0,0.0,TTD1000
161,03-29-2011,4.0,0.0,6.0,1.0,1.0,1.0,1.0,ESJ0670
87,03-05-2010,1.0,0.0,2.0,1.0,2.0,0.0,0.0,YJF0532
196,05-28-2010,4.0,0.0,5.0,1.0,2.0,9.0,9.0,HRL0540
139,04-12-2010,2.0,2.0,3.0,1.0,1.0,0.0,0.0,RDM0115
281,09-28-2010,1.0,1.0,3.0,3.0,4.0,0.0,0.0,ACV0812
157,04-26-2010,6.0,0.0,8.0,1.0,2.0,0.0,0.0,SDO0170
263,09-01-2010,1.0,0.0,2.0,1.0,2.0,0.0,0.0,WNB0908
271,09-13-2010,1.0,0.0,0.0,1.0,1.0,0.0,0.0,VEB0935
244,08-04-2010,11.0,1.0,4.0,1.0,1.0,3.0,3.0,CAA0612
291,10-11-2010,3.0,0.0,6.0,1.0,1.0,0.0,0.0,HLM0933
249,06-01-2010,1.0,0.0,0.0,1.0,2.0,0.0,0.0,JAJ0849
27,01-21-2010,6.0,0.0,5.0,1.0,1.0,0.0,0.0,RDM0115
216,06-25-2010,5.0,0.0,4.0,1.0,1.0,0.0,0.0,GAF0570
257,08-30-2010,0.0,0.0,3.0,1.0,1.0,0.0,0.0,MFV0897

In [44]:
# plt.figure(figsize=(16,10))
# sns.heatmap(data.corr(),  annot=True, annot_kws={"size": 14})
# sns.set_style('white')
# plt.xticks(fontsize=14)
# plt.yticks(fontsize=14)
# plt.show()

### encoding all users

In [7]:
one_hot=ce.OneHotEncoder()
one_hot.fit(data['user_name'])
y=one_hot.transform(data['user_name'])
y

,user_name_1,user_name_2,user_name_3,user_name_4,user_name_5,user_name_6,user_name_7,user_name_8,user_name_9,user_name_10,...,user_name_989,user_name_990,user_name_991,user_name_992,user_name_993,user_name_994,user_name_995,user_name_996,user_name_997,user_name_998
229,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
327,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
290,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
342,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
print(data['user_name'].unique())
y.columns=data['user_name'].unique()
encoded=pd.concat([data,y],axis=1)
# encoded.to_csv('encoded_users.csv')
y

['AMD0077' 'CCH0182' 'RAH0440' 'CSP0197' 'HAD0246' 'TTD1000' 'ESJ0670'
 'YJF0532' 'HRL0540' 'RDM0115' 'ACV0812' 'SDO0170' 'WNB0908' 'VEB0935'
 'CAA0612' 'HLM0933' 'JAJ0849' 'GAF0570' 'MFV0897' 'SBN0866' 'DOP0562'
 'BLL0929' 'BBH0810' 'HWW0436' 'MKS0204' 'ASS0517' 'FLM0213' 'CKD0680'
 'AHD0848' 'TVS0006' 'ILH0958' 'GOK0238' 'TVS0050' 'SVS0871' 'KJJ0293'
 'LIM0674' 'JML0909' 'HAH0248' 'JMK0099' 'ZKS0899' 'BEH0615' 'ASV0946'
 'AES0827' 'IBS0836' 'JIG0128' 'RSM0277' 'CTR0697' 'ABN0239' 'CPG0322'
 'TSG0906' 'NLO0131' 'MKL0941' 'ZJE0857' 'PLH0862' 'CJK0200' 'MIB0904'
 'DLS0383' 'SAC0687' 'AJR0932' 'WKD0013' 'SLB0049' 'MCJ0324' 'WAS0254'
 'PID0426' 'SMW0084' 'JSA0775' 'GNS0178' 'SBH0537' 'SDB0106' 'NKH0979'
 'SSJ0784' 'NCH0179' 'SBN0495' 'BWH0813' 'WVB0539' 'BWP0202' 'GZC0735'
 'TSR0676' 'BMM0112' 'NRO0768' 'MBW0809' 'ECR0822' 'SVL0940' 'AVM0947'
 'KAC0124' 'CBB0365' 'SNS0129' 'KBL0260' 'NCO0666' 'DIC0988' 'EMB0531'
 'MCF0600' 'ZSB0649' 'FRB0023' 'CRP0456' 'IIW0249' 'ILC0838' 'HIW0536'
 'BEC0505' 'PTH0552' 'SVL0803' 'CCL0068' 'CCC0393' 'FBA0348' 'MSS0001'
 'ACC0042' 'KPP0452' 'SGB0140' 'SCP0130' 'WRM0963' 'NAR0981' 'JCR0921'
 'HSP0290' 'ERH0449' 'AKK0329' 'SJF0094' 'CLS0296' 'MJM0510' 'MCD0125'
 'LHL0309' 'PBP0002' 'AKW0167' 'BAM0636' 'SAB0781' 'MCS0035' 'DHM0937'
 'CCW0524' 'IBB0696' 'GLR0975' 'AIH0675' 'RAB0589' 'RZC0746' 'DGW0752'
 'FKB0163' 'CCW0031' 'MCF0327' 'JRG0207' 'KCO0122' 'MIL0255' 'ALD0529'
 'KVT0028' 'MNR0829' 'LQP0508' 'FWM0707' 'CAM0681' 'HKB0418' 'LHB0967'
 'BJM0111' 'AJR0319' 'QPM0727' 'VCY0751' 'LTS0860' 'AKH0758' 'CAS0507'
 'SSG0250' 'YDN0198' 'DVM0265' 'HKR0628' 'HCL0651' 'MSZ0310' 'BLB0114'
 'MIC0726' 'IYB0918' 'RFP0380' 'FSC0601' 'AOB0019' 'PNH0761' 'EMS0317'
 'OKB0439' 'AJL0462' 'AMW0392' 'IJR0825' 'GCS0571' 'CJV0286' 'CAB0388'
 'MKP0861' 'ARB0834' 'SAT0194' 'GRM0868' 'SCB0534' 'DJS0682' 'BHC0665'
 'OSH0655' 'MNS0224' 'NGO0690' 'PGC0066' 'CRO0027' 'AMR0400' 'NOB0181'
 'RCP0785' 'DBG0261' 'NCE0097' 'AAV0450' 'KKC0683' 'XHG0902' 'HCV0478'
 'MBR0724' 'SBK0161' 'RKD0604' 'DSB0731' 'RKF0164' 'ABC0174' 'AIM0627'
 'LHN0151' 'TJG0582' 'UCS0227' 'ONL0276' 'TET0621' 'NKP0236' 'HDD0806'
 'AAM0658' 'NBC0412' 'BXJ0010' 'AIS0405' 'BAM0611' 'WPE0538' 'IDO0176'
 'NAB0903' 'ATE0869' 'IBB0359' 'HGN0287' 'HBO0413' 'SBN0971' 'EIM0156'
 'EMW0772' 'LOF0311' 'UJC0737' 'KBC0054' 'AIP0394' 'OMM0944' 'JKM0303'
 'SJC0333' 'HDL0748' 'TDS0984' 'RJM0381' 'HPH0075' 'PRM0740' 'LAM0911'
 'CFM0767' 'BRB0355' 'DLM0051' 'OCS0865' 'SCF0608' 'FSB0399' 'DFR0218'
 'TOR0193' 'PSF0133' 'HTF0641' 'AJD0074' 'KQS0415' 'JJH0613' 'CRK0916'
 'LJB0826' 'CKB0482' 'KQC0708' 'LCD0622' 'IBP0883' 'CTW0500' 'JNA0559'
 'LBH0942' 'ABH0663' 'BJP0134' 'DCC0160' 'PDH0716' 'YCE0983' 'CLF0852'
 'DVW0103' 'MDH0686' 'SJO0209' 'SXM0895' 'CNM0800' 'EZH0736' 'IIA0092'
 'KVS0425' 'ESA0642' 'XRS0633' 'NRF0137' 'GHH0288' 'SOG0411' 'BSS0463'
 'BLS0678' 'LFS0071' 'CSL0949' 'YJV0699' 'HDD0789' 'TRK0914' 'FRR0832'
 'APG0307' 'CCM0467' 'BJW0619' 'MHG0244' 'SRS0231' 'WJD0576' 'PKB0429'
 'PMV0850' 'NGC0058' 'AMH0464' 'DDA0476' 'CMB0912' 'ILR0304' 'GTD0116'
 'SMY0792' 'JCC0225' 'AMJ0297' 'RHP0484' 'RAM0447' 'WIF0691' 'NSS0876'
 'WAB0143' 'OHC0973' 'TSM0927' 'JBM0350' 'BAK0964' 'HCS0003' 'JKB0126'
 'SOB0360' 'NMC0486' 'PLH0715' 'WXH0872' 'IKP0472' 'TEB0251' 'LEM0605'
 'ATF0274' 'SLP0762' 'SAH0599' 'ZFM0468' 'ADD0846' 'FEB0306' 'HKF0831'
 'AKC0924' 'JCR0770' 'RUM0880' 'HMW0713' 'RLB0719' 'CLB0774' 'WBC0315'
 'SGG0787' 'PKB0281' 'WLV0566' 'MVB0515' 'CCM0136' 'DMG0358' 'EGK0893'
 'MBJ0312' 'KDT0346' 'RGN0408' 'ECL0930' 'TUC0632' 'JFC0557' 'JJB0127'
 'FHS0837' 'TIW0299' 'MAH0864' 'DGN0480' 'UCH0519' 'AJF0370' 'RAS0432'
 'VSS0154' 'SDF0017' 'IAT0263' 'TEM0977' 'RHC0335' 'JNJ0556' 'NHH0185'
 'IUY0279' 'JTM0223' 'DIW0118' 'MTB0620' 'CJP0952' 'LDM0587' 'ICS0956'
 'ASM0575' 'CNB0900' 'WSR0241' 'AJP0723' 'GHL0460' 'DCH0843' 'HCC0344'
 'SES0477' 'LAF0991' 'EPW0434' 'VTT0385' 'YEV0793' 'LDB0090' 'KKS0119'
 'PIS0522' 'LCC0819' 'BCM0653' 'TLM0797' 'SSH0799' 'ZCF0590' 'TYB0779'
 'EHB0420' 'TCD0009' 'JJH0292' 'KCS0173' 'KBS0874' 'JFC0757' 'SPA0141'
 'JHP0583' 'CJC0494' 'MBG0438' 'BTN0061' 'JXH0493' 'KES0729' 'DIB0081'
 'AJN0607' 'DBS0235' 'HAH0760' 'EFS0882' 'MGS0974' 'NMF0780' 'SJW0451'
 'WIQ0567' 'BDB0453' 'BMG0917' 'KJM0887' 'MLM0950' 'JDB0169' 'FGW0853'
 'UAD0771' 'NNA0610' 'BMS0877' 'BCR0581' 'AOK0844' 'DRR0162' 'RVC0232'
 'POB0343' 'WTR0563' 'JJB0700' 'JCR0172' 'SSS0345' 'ENC0234' 'KLM0639'
 'FXF0957' 'NAH0503' 'HLH0512' 'CEJ0109' 'WDV0573' 'EIP0997' 'DPS0262'
 'SAK0375' 'RJB0088' 'KSH0569' 'JRL0574' 'JOL0024' 'MLD0755' 'TDJ0998'
 'GRC0145' 'FKK0055' 'GQP0743' 'NIH0969' 'RRA0938' 'KCB0815' 'MMB0488'
 'CKH0144' 'GNZ0953' 'ESH0135' 'TNM0961' 'KJW0416' 'CIM0271' 'CGF0337'
 'GDF0704' 'HBB0056' 'DTT0076' 'SEJ0677' 'TJB0302' 'BTL0226' 'JGT0221'
 'MPM0220' 'NSC0597' 'BDI0533' 'BSS0369' 'PAD0773' 'ASS0206' 'CJF0802'
 'HPR0585' 'TDG0962' 'CSH0626' 'KAT0270' 'EHD0584' 'KJA0152' 'BAH0875'
 'KJP0371' 'JMH0543' 'GMF0738' 'JIM0095' 'DJB0159' 'HAC0282' 'DLF0377'
 'MAE0331' 'DMM0623' 'BTL0722' 'FAW0032' 'CMS0454' 'ONW0083' 'SKG0759'
 'IMP0530' 'BSB0990' 'TLH0648' 'LJR0523' 'DBB0384' 'MJB0588' 'CGA0629'
 'ETR0428' 'MJS0890' 'HIA0414' 'PDW0259' 'AJH0175' 'KBG0549' 'RTO0313'
 'CNE0352' 'CAB0614' 'BBS0039' 'CHM0821' 'WDD0366' 'LBF0214' 'HCW0419'
 'MAW0166' 'ANP0555' 'XLB0710' 'CUD0795' 'GTD0898' 'LCB0664' 'IJM0139'
 'NMG0766' 'CXC0336' 'RNL0695' 'AWM0764' 'BYP0070' 'SMH0291' 'FHO0630'
 'KMS0657' 'QRM0739' 'IMG0320' 'BDV0168' 'CAM0102' 'CCR0863' 'PMC0328'
 'JDF0593' 'MKG0711' 'IWM0816' 'XAA0104' 'OLF0504' 'AHG0634' 'FRL0511'
 'KPR0497' 'AHM0410' 'HWH0646' 'BBS0422' 'KRL0062' 'KDS0349' 'GCC0945'
 'HSB0196' 'VMJ0546' 'TSM0363' 'NKH0807' 'AAF0791' 'THD0448' 'MAD0753'
 'TPH0474' 'HGG0240' 'ATP0662' 'CQW0652' 'LLV0602' 'HVB0037' 'OCB0805'
 'AAE0190' 'XWD0923' 'NMS0280' 'CQH0730' 'VLB0647' 'CGB0637' 'ZSK0258'
 'MSG0839' 'GCL0016' 'AMR0318' 'CQH0701' 'GCG0951' 'ILJ0526' 'IJW0851'
 'DBW0483' 'MLL0598' 'PEV0323' 'DEB0782' 'BSA0431' 'CCH0685' 'IAR0694'
 'SAA0999' 'LAP0338' 'QOS0878' 'ORG0339' 'OJK0233' 'MIM0712' 'CTA0020'
 'HCL0113' 'CCM0855' 'JCW0858' 'JKF0465' 'SLT0907' 'CMW0783' 'BMC0547'
 'IIL0513' 'KAL0395' 'RHY0079' 'HJB0742' 'GCR0554' 'CAN0842' 'EIS0041'
 'ELH0960' 'LNS0989' 'CSB0080' 'KNB0022' 'TEM0093' 'TMA0069' 'AIB0948'
 'ADC0391' 'KRM0541' 'KBB0189' 'HPM0986' 'CCA0046' 'HWM0342' 'UBF0645'
 'SBQ0786' 'ARL0034' 'RNF0765' 'AKR0057' 'NJB0243' 'RDT0424' 'CLH0703'
 'BKW0374' 'BTR0403' 'AQD0820' 'KWC0004' 'TBT0461' 'AHC0142' 'JPW0741'
 'WBC0192' 'CAH0936' 'BNG0237' 'NNS0059' 'CBG0398' 'AGB0643' 'MAH0149'
 'USH0199' 'NCK0421' 'ORB0473' 'ZSL0305' 'UIR0043' 'MAS0025' 'RVF0201'
 'OKC0107' 'MMG0943' 'CKP0721' 'HVF0067' 'JLW0053' 'ALB0892' 'CJH0702'
 'GAF0060' 'RDM0150' 'TQS0212' 'AAW0353' 'BTS0011' 'NHE0919' 'LBC0356'
 'RSC0089' 'BHW0458' 'JDC0030' 'GQF0659' 'EMW0105' 'CEL0561' 'HDH0928'
 'ABM0845' 'SOF0808' 'SAP0867' 'JER0404' 'BVC0790' 'NGF0157' 'LQC0479'
 'BVN0514' 'RAR0725' 'IRM0931' 'ASL0378' 'MCT0720' 'ZDW0859' 'JMW0638'
 'MAR0955' 'WPR0368' 'RLG0856' 'JTS0389' 'AMM0014' 'JMC0925' 'WDO0870'
 'JLM0364' 'BAJ0654' 'ROB0272' 'ANT0430' 'GJD0298' 'CLD0894' 'ESH0283'
 'DTP0379' 'DFH0188' 'KPC0073' 'NCK0295' 'KJS0618' 'MHA0798' 'XBN0229'
 'JJM0203' 'HCM0267' 'JSH0330' 'ASG0692' 'NAF0033' 'PMJ0564' 'LPC0492'
 'JOM0750' 'FOB0756' 'RHO0732' 'HGH0595' 'VAA0087' 'DGF0443' 'KTG0091'
 'BJH0811' 'HAV0121' 'CKB0427' 'ASG0048' 'DPM0423' 'KBP0008' 'ENL0100'
 'ECF0828' 'KRL0501' 'LUR0896' 'WTF0387' 'WGR0833' 'MKW0441' 'OBH0499'
 'BRM0995' 'FPC0954' 'WKF0012' 'DMK0257' 'IJM0444' 'YWW0660' 'HKI0171'
 'IMB0481' 'EJW0884' 'SRH0155' 'HDJ0446' 'BIS0247' 'BSH0445' 'EHR0096'
 'KMW0545' 'BMT0528' 'DOL0332' 'CAC0889' 'FDE0117' 'BAL0044' 'PNL0301'
 'GJT0386' 'JGM0934' 'RGG0064' 'ETR0177' 'ICH0294' 'JBD0616' 'NAF0326'
 'NAB0801' 'KRG0158' 'ELT0769' 'HOB0994' 'VSA0230' 'BCB0679' 'SHW0578'
 'LRR0148' 'HRB0351' 'OLW0689' 'ADF0397' 'TAC0300' 'ALH0402' 'MLG0475'
 'KAT0489' 'NMB0972' 'AAN0823' 'MDH0580' 'HJA0018' 'KNW0644' 'LNR0656'
 'PPF0435' 'LRW0970' 'SBD0913' 'LOM0086' 'SED0886' 'SNC0187' 'ORM0669'
 'CBG0490' 'KCF0045' 'OYM0026' 'AJC0840' 'HRD0635' 'MSH0040' 'IEB0153'
 'MHG0733' 'HFB0347' 'PES0085' 'HSG0818' 'OQH0183' 'OMS0101' 'KSP0966'
 'NJC0705' 'AOS0987' 'JAD0609' 'DZC0228' 'MSD0939' 'MLP0668' 'LHB0606'
 'SIJ0661' 'CSJ0340' 'NRD0548' 'CJG0470' 'BJH0354' 'ARB0881' 'DSM0591'
 'AIP0982' 'RMS0266' 'KKW0879' 'JRS0362' 'MDM0625' 'MPT0376' 'NWT0098'
 'IBM0671' 'MSO0222' 'RCC0617' 'MHH0180' 'MVF0594' 'ZJS0269' 'LJJ0905'
 'JCR0289' 'QCH0110' 'MDM0976' 'JZD0888' 'FQA0854' 'IUB0565' 'MYD0978'
 'WGS0516' 'HAM0985' 'ALC0788' 'LJT0817' 'ZMC0284' 'GZB0469' 'KLH0596'
 'JAM0382' 'RMW0542' 'JKJ0698' 'DAL0673' 'IKR0401' 'HRW0550' 'COF0120'
 'CHG0146' 'XHW0498' 'QNF0205' 'THR0873' 'QJR0688' 'KMB0922' 'JRF0835'
 'CEB0210' 'ASD0577' 'MOP0763' 'TSB0437' 'CTR0341' 'HSD0457' 'JCV0245'
 'HXL0968' 'GCS0518' 'ARD0509' 'CIG0052' 'ANM0123' 'TLK0993' 'EGD0409'
 'JCG0316' 'DID0650' 'CIM0926' 'BNR0965' 'DIB0285' 'DRR0242' 'PTH0830'
 'GBM0603' 'VMJ0147' 'KWE0082' 'ABC0253' 'QNP0216' 'PGO0433' 'KNG0672'
 'CFW0264' 'EBC0390' 'DLH0029' 'FIR0920' 'AKF0709' 'CWB0065' 'IJM0776'
 'BBG0325' 'JMD0520' 'QSV0778' 'IRT0491' 'EZT0640' 'RAG0275' 'EDB0714'
 'SGS0268' 'NDM0417' 'AAS0442' 'RGH0728' 'CJM0138' 'TAP0551' 'BRS0734'
 'RAW0915' 'ALD0544' 'RIH0777' 'JAV0361' 'HTH0007' 'JPA0667' 'NBH0256'
 'EGD0132' 'SHR0334' 'ARA0252' 'SMB0804' 'RHL0992' 'CFG0959' 'RYB0718'
 'KJG0910' 'HWY0038' 'AMV0036' 'AAF0535' 'SGM0021' 'FBW0747' 'GKO0078'
 'SAC0592' 'LDG0459' 'FUM0015' 'DAG0558' 'MES0407' 'FMG0527' 'DGM0754'
 'JRH0455' 'NUL0471' 'BER0314' 'AAL0706' 'ELB0847' 'BTW0005' 'GTD0219'
 'CMM0487' 'ESR0693' 'SSR0278' 'MOS0047' 'RNP0211' 'VFM0814' 'BIH0745'
 'RRP0568' 'ASB0796' 'LMF0980' 'DDM0579' 'MAD0496' 'KRV0372' 'PGH0184'
 'VCC0396' 'CJM0521' 'TJD0996' 'YIC0195' 'CYA0506' 'UFK0208' 'COM0321'
 'EWH0191' 'FFC0891' 'RBB0485' 'VIA0063' 'KSP0357' 'MNC0717' 'EHB0824'
 'IHK0841' 'SOB0586' 'MVH0373' 'HDS0367' 'AMH0794' 'CWR0502' 'DKB0631'
 'BQS0525' 'EAH0466' 'SER0165' 'AGB0186' 'CSC0217' 'GCC0744' 'MTT0901'
 'FTM0406' 'HMM0108' 'CRD0624' 'OLB0749' 'JMB0308' 'HJS0072' 'RRC0553'
 'EDA0684' 'LDD0560' 'LPH0572' 'DAR0885']

,AMD0077,CCH0182,RAH0440,CSP0197,HAD0246,TTD1000,ESJ0670,YJF0532,HRL0540,RDM0115,...,HMM0108,CRD0624,OLB0749,JMB0308,HJS0072,RRC0553,EDA0684,LDD0560,LPH0572,DAR0885
229,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
307,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
327,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
290,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
206,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
78,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
133,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
342,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [10]:
encoded

,str_date,Negative,Neutral,Positive,Logoff,Logon,Connect,Disconnect,user_name,AMD0077,...,HMM0108,CRD0624,OLB0749,JMB0308,HJS0072,RRC0553,EDA0684,LDD0560,LPH0572,DAR0885
229,07-14-2010,8.0,1.0,8.0,1.0,1.0,0.0,0.0,AMD0077,1,...,0,0,0,0,0,0,0,0,0,0
307,11-04-2010,0.0,1.0,1.0,1.0,1.0,0.0,0.0,CCH0182,0,...,0,0,0,0,0,0,0,0,0,0
327,12-03-2010,2.0,1.0,6.0,1.0,1.0,0.0,0.0,RAH0440,0,...,0,0,0,0,0,0,0,0,0,0
290,10-08-2010,2.0,6.0,3.0,1.0,2.0,0.0,0.0,CSP0197,0,...,0,0,0,0,0,0,0,0,0,0
18,01-10-2011,4.0,0.0,6.0,2.0,2.0,0.0,0.0,HAD0246,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,01-03-2011,6.0,1.0,7.0,1.0,1.0,0.0,0.0,MAW0166,0,...,0,0,0,0,0,0,0,0,0,0
206,06-11-2010,6.0,2.0,3.0,1.0,2.0,0.0,0.0,YDN0198,0,...,0,0,0,0,0,0,0,0,0,0
78,02-26-2010,5.0,0.0,4.0,1.0,1.0,0.0,0.0,ZJS0269,0,...,0,0,0,0,0,0,0,0,0,0
133,04-08-2010,0.0,1.0,2.0,1.0,2.0,0.0,0.0,CJV0286,0,...,0,0,0,0,0,0,0,0,0,0
342,12-29-2010,4.0,1.0,6.0,1.0,1.0,0.0,0.0,NAF0033,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
encoded=pd.read_csv('encoded_users.csv',nrows=5000,index_col=0)

In [ ]:
# encoded=encoded.drop('user_name',axis=1)
encoded

In [20]:
x=encoded.iloc[:,1:8]
x
y=encoded['AAE0190']
x

     Negative  Neutral  Positive  Logoff  Logon  Connect  Disconnect
229       8.0      1.0       8.0     1.0    1.0      0.0         0.0
307       0.0      1.0       1.0     1.0    1.0      0.0         0.0
327       2.0      1.0       6.0     1.0    1.0      0.0         0.0
290       2.0      6.0       3.0     1.0    2.0      0.0         0.0
18        4.0      0.0       6.0     2.0    2.0      0.0         0.0
..        ...      ...       ...     ...    ...      ...         ...
0         6.0      1.0       7.0     1.0    1.0      0.0         0.0
206       6.0      2.0       3.0     1.0    2.0      0.0         0.0
78        5.0      0.0       4.0     1.0    1.0      0.0         0.0
133       0.0      1.0       2.0     1.0    2.0      0.0         0.0
342       4.0      1.0       6.0     1.0    1.0      0.0         0.0

[329601 rows x 7 columns]

In [21]:
x_train,x_test,y_train,y_test=train_test_split(x, y, test_size=0.3, random_state=42)

In [33]:
# data=data.drop('Disconnect',axis=1)
# y_train.index==100
(y_train.values==1).any() 
# y_train
y_test[y_test.values==1]
x_train

     Negative  Neutral  Positive  Logoff  Logon  Connect
81        8.0      0.0       7.0     1.0    2.0      2.0
82        2.0      0.0       1.0     1.0    1.0      0.0
298       0.0      0.0       3.0     1.0    2.0      0.0
91        0.0      0.0       1.0     1.0    1.0      2.0
18        2.0      0.0       1.0     1.0    1.0      0.0
..        ...      ...       ...     ...    ...      ...
200       5.0      1.0      12.0     1.0    1.0      0.0
268       5.0      1.0       3.0     1.0    1.0      0.0
275       1.0      0.0       2.0     1.0    1.0      0.0
120       1.0      0.0      10.0     4.0    4.0      0.0
82        0.0      8.0       1.0     1.0    1.0      0.0

[3500 rows x 6 columns]

In [45]:
data=pd.read_csv(r'C:\Users\TLS\Desktop\FYDP_updated\LSTM attention\means_threshold.csv')
threshold=[data['neg_neu_pos'][0],data['neg_neu_pos'][0],data['neg_neu_pos'][0],data['log_on_off'][0],data['log_on_off'][0],data['dis_conn'][0],data['dis_conn'][0]]
t=np.array(threshold)
t1=t-1
t2=t+1

In [60]:


class ThresholdHidden(Layer):

    def __init__(self, threshold_values, **kwargs):
        super(ThresholdHidden, self).__init__(**kwargs)
        self.threshold_values = threshold_values

    def call(self, inputs):
        return K.cast(K.greater(inputs, self.threshold_values), K.floatx())

    def get_config(self):
        config = {'threshold_values': self.threshold_values}
        base_config = super(ThresholdHidden, self).get_config()
        return dict(list(base_config.items()) + list(config.items()))

In [62]:
model=Sequential()
# initializer = HeNormal()
model.add(Dense(7,activation = 'relu', input_shape=(7,)))
model.add(ThresholdHidden(threshold_values=t1))
model.add(Dense(14,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [63]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy',metrics =[tf.keras.metrics.Recall(),tf.keras.metrics.Precision(),'accuracy'])

In [64]:
model.fit(x_train, y_train, batch_size=32, epochs = 10)

Epoch 1/10
WARNING:tensorflow:Gradients do not exist for variables ['dense_18/kernel:0', 'dense_18/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['dense_18/kernel:0', 'dense_18/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['dense_18/kernel:0', 'dense_18/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
WARNING:tensorflow:Gradients do not exist for variables ['dense_18/kernel:0', 'dense_18/bias:0'] when minimizing the loss. If you're using `model.compile()`, did you forget to provide a `loss` argument?
7210/7210 [==============================] - 14s 2ms/step - loss: 0.0189 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9987
Epoch 2/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0079 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 3/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0078 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 4/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0078 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 5/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0078 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 6/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0077 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 7/10
7210/7210 [==============================] - 15s 2ms/step - loss: 0.0078 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 8/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0078 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 9/10
7210/7210 [==============================] - 14s 2ms/step - loss: 0.0077 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990
Epoch 10/10
7210/7210 [==============================] - 13s 2ms/step - loss: 0.0077 - recall_6: 0.0000e+00 - precision_6: 0.0000e+00 - accuracy: 0.9990

In [34]:
# plot_model(model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

In [35]:
# model=Sequential()
# initializer = HeNormal()
# model.add(Dense(6,  kernel_initializer=initializer,activation = 'relu', input_shape=(6,)))

In [36]:
# model.add(Dense(12,kernel_initializer=initializer,activation='relu'))

C:\Users\TLS\anaconda3\lib\site-packages\keras\initializers\initializers_v2.py:120: UserWarning: The initializer HeNormal is unseeded and being called multiple times, which will return identical values  each time (even if the initializer is unseeded). Please update your code to provide a seed to the initializer, or avoid using the same initalizer instance more than once.
  warnings.warn(

In [37]:
# model.add(Dense(500,kernel_initializer=initializer,activation='relu'))

# model.add(Dense(300,kernel_initializer=initializer,activation='relu'))

# model.add(Dense(200,kernel_initializer=initializer,activation='relu'))
# model.add(Dense(100,kernel_initializer=initializer,activation='relu'))
# model.add(Dense(50,kernel_initializer=initializer,activation='relu'))
# model.add(Dense(50,kernel_initializer=initializer,activation='relu'))

# model.add(Dense(4,kernel_initializer='uniform',activation='relu'))

In [38]:
# model.add(Dense(1,activation='sigmoid'))

In [39]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', 
              metrics =[tf.keras.metrics.Recall(),tf.keras.metrics.Precision(),'accuracy'])

In [40]:
model.fit(x_train, y_train, batch_size=32, epochs = 100)

Epoch 1/100
110/110 [==============================] - 2s 3ms/step - loss: 1.2040 - recall: 0.6000 - precision: 0.0017 - accuracy: 0.5031
Epoch 2/100
110/110 [==============================] - 0s 2ms/step - loss: 0.1015 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 3/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0451 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 4/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0306 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 5/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0248 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 6/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0220 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 7/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0205 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 8/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0196 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 9/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0189 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 10/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0184 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 11/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0178 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 12/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0174 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 13/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0170 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 14/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0166 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 15/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0162 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 16/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0158 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 17/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0155 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 18/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0152 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 19/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0149 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 20/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0146 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 21/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0144 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 22/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0141 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 23/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0140 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 24/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0136 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 25/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0134 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 26/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0132 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 27/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0130 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 28/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0127 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 29/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0120 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 30/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0118 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 31/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0113 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 32/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0111 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 33/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0110 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 34/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0110 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 35/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0109 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 36/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0106 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 37/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0104 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 38/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0105 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 39/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0103 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 40/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0101 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 41/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0099 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 42/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0100 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 43/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0097 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 44/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0096 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 45/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0094 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 46/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0092 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 47/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0092 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 48/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0091 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 49/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0091 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 50/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0088 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 51/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0087 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 52/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0088 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 53/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0088 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 54/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0088 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 55/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0084 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 56/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0079 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 57/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0082 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 58/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0081 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 59/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0080 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 60/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0079 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 61/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0080 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 62/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0078 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 63/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0078 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 64/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0076 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 65/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0076 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 66/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0073 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 67/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0076 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 68/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0074 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 69/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0075 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 70/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0074 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 71/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0075 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 72/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0071 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 73/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0073 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 74/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0071 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 75/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0074 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 76/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0070 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 77/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0073 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 78/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0067 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 79/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0073 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 80/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0068 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 81/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0068 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 82/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0065 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 83/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0070 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 84/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0069 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 85/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0067 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 86/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0066 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 87/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0067 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 88/100
110/110 [==============================] - 0s 3ms/step - loss: 0.0068 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 89/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0067 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 90/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0065 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 91/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0069 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 92/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0065 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 93/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0066 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 94/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0063 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 95/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0067 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 96/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0060 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 97/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0068 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 98/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0062 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 99/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0064 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986
Epoch 100/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0065 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9986

In [41]:
_,recall,precision, accuracy = model.evaluate(x_test, y_test)
print(' Categorical Accuracy: %.2f' % (accuracy*100))
print(' recall: %.2f' % (recall*100))
print(' Precision: %.2f' % (precision*100))

47/47 [==============================] - 0s 2ms/step - loss: 0.0080 - recall: 0.0000e+00 - precision: 0.0000e+00 - accuracy: 0.9987
 Categorical Accuracy: 99.87
 recall: 0.00
 Precision: 0.00

In [42]:
model.predict([[6.0,0.0,4.0,1.0,2.0,0.0]])

1/1 [==============================] - 0s 147ms/step

array([[0.04067174]], dtype=float32)

In [ ]:
# model=Sequential()
# model.add(Dense(6, kernel_initializer= 'uniform', activation = 'relu', input_dim = 3))

# model.add(Dense(6,kernel_initializer='uniform',activation='relu'))

# model.add(Dense(6,kernel_initializer='uniform',activation='relu'))
# model.add(Dense(5,kernel_initializer='uniform',activation='relu'))
# # model.add(Dense(4,kernel_initializer='uniform',activation='relu'))

# model.add(Dense(7,kernel_initializer='uniform',activation='softmax'))

# model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

# model.fit(X_train, Y_train, epochs = 50)